### ISSUE TITLE
inception_resnet_v2 transfer learning not running on notebook GTX 1070

### ISSUE THREAD

**Issue by 5amuraix** [tensorflow/models#3025] opened 2017-12-19 02:16 UTC
### System information
- **What is the top-level directory of the model you are using**:
**slim**

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
**no**

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
**MS Windows 7**

- **TensorFlow installed from (source or binary)**:
**Binary**

- **TensorFlow version (use command below)**:
**1.4.0 GPU**

- **CUDA/cuDNN version**:
**8.0 / 6.1**

- **GPU model and memory**:
**GeForce GTX 1070 (notebook) 8 GB**

- **Exact command to reproduce**:
python train_image_classifier.py ^
    --train_dir=tf_files/models ^
    --dataset_dir=tf_files/data ^
    --dataset_name=flowers ^
    --dataset_split_name=train ^
    --max_number_of_steps=1000 ^
    --batch_size=32 ^
    --model_name=inception_resnet_v2 ^
    --checkpoint_path=tf_files/models/checkpoints/inception_resnet_v2.ckpt ^
    --checkpoint_exclude_scopes=InceptionResnetV2/Logits,InceptionResnetV2/AuxLogits ^
    --trainable_scopes=InceptionResnetV2/Logits,InceptionResnetV2/AuxLogits

### Describe the problem

Ran the download_and_convert_data.py script successfully to download the flowers example dataset. 
When using the default train_image_classifier.py script with the above arguments the error included in the logs section below occurs.

Adding _--clone_on_cpu=true_  allows the training to run on the CPU (very slowly)

### Source code / logs

WARNING:tensorflow:From train_image_classifier.py:400: create_global_step (from
tensorflow.contrib.framework.python.ops.variables) is deprecated and will be rem
oved in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:From train_image_classifier.py:466: softmax_cross_entropy (fr
om tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be r
emoved after 2016-12-30.
Instructions for updating:
Use tf.losses.softmax_cross_entropy instead. Note that the order of the logits a
nd labels arguments has been changed.
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\tensorflow\c
ontrib\losses\python\losses\loss_ops.py:398: compute_weighted_loss (from tensorf
low.contrib.losses.python.losses.loss_ops) is deprecated and will be removed aft
er 2016-12-30.
Instructions for updating:
Use tf.losses.compute_weighted_loss instead.
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\tensorflow\c
ontrib\losses\python\losses\loss_ops.py:151: add_arg_scope.<locals>.func_with_ar
gs (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and wil
l be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.add_loss instead.
INFO:tensorflow:Summary name /clone_loss is illegal; using clone_loss instead.
INFO:tensorflow:Ignoring --checkpoint_path because a checkpoint already exists i
n tf_files/models
2017-12-19 11:13:32.451682: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports inst
ructions that this TensorFlow binary was not compiled to use: AVX AVX2
2017-12-19 11:13:32.721682: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 wit
h properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 7.60GiB
2017-12-19 11:13:32.723682: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu
\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlo
w device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000
:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from tf_files/models\model.ckpt-64
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framewo
rk.errors_impl.InvalidArgumentError'>, Cannot assign a device for operation 'Inc
eptionResnetV2/Logits/Predictions': Could not satisfy explicit device specificat
ion '/device:GPU:0' because no supported kernel for GPU devices is available.
         [[Node: InceptionResnetV2/Logits/Predictions = Softmax[T=DT_FLOAT, _dev
ice="/device:GPU:0"](InceptionResnetV2/Logits/Logits/BiasAdd)]]

Caused by op 'InceptionResnetV2/Logits/Predictions', defined at:
  File "train_image_classifier.py", line 574, in <module>
    tf.app.run()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\a
pp.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 474, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "D:\Brian\RD\tf\model_test\deployment\model_deploy.py", line 193, in crea
te_clones
    outputs = model_fn(*args, **kwargs)
  File "train_image_classifier.py", line 457, in clone_fn
    logits, end_points = network_fn(images)
  File "D:\Brian\RD\tf\model_test\nets\nets_factory.py", line 135, in network_fn

    return func(images, num_classes, is_training=is_training, **kwargs)
  File "D:\Brian\RD\tf\model_test\nets\inception_resnet_v2.py", line 362, in inc
eption_resnet_v2
    end_points['Predictions'] = tf.nn.softmax(logits, name='Predictions')
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\nn_ops
.py", line 1667, in softmax
    return _softmax(logits, gen_nn_ops._softmax, dim, name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\nn_ops
.py", line 1610, in _softmax
    return compute_op(logits, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_nn
_ops.py", line 4316, in _softmax
    "Softmax", logits=logits, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-
access

InvalidArgumentError (see above for traceback): Cannot assign a device for opera
tion 'InceptionResnetV2/Logits/Predictions': Could not satisfy explicit device s
pecification '/device:GPU:0' because no supported kernel for GPU devices is avai
lable.
         [[Node: InceptionResnetV2/Logits/Predictions = Softmax[T=DT_FLOAT, _dev
ice="/device:GPU:0"](InceptionResnetV2/Logits/Logits/BiasAdd)]]

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1293, in _run_fn
    self._extend_graph()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1354, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a de
vice for operation 'InceptionResnetV2/Logits/Predictions': Could not satisfy exp
licit device specification '/device:GPU:0' because no supported kernel for GPU d
evices is available.
         [[Node: InceptionResnetV2/Logits/Predictions = Softmax[T=DT_FLOAT, _dev
ice="/device:GPU:0"](InceptionResnetV2/Logits/Logits/BiasAdd)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_image_classifier.py", line 574, in <module>
    tf.app.run()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\a
pp.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 570, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\contrib\slim\pyth
on\slim\learning.py", line 742, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "C:\Program Files\Python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\s
upervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\s
upervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\c
oordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "C:\Program Files\Python36\lib\site-packages\six.py", line 693, in rerais
e
    raise value
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\s
upervisor.py", line 953, in managed_session
    start_standard_services=start_standard_services)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\s
upervisor.py", line 708, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\s
ession_manager.py", line 273, in prepare_session
    config=config)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\s
ession_manager.py", line 205, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\s
aver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 889, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a de
vice for operation 'InceptionResnetV2/Logits/Predictions': Could not satisfy exp
licit device specification '/device:GPU:0' because no supported kernel for GPU d
evices is available.
         [[Node: InceptionResnetV2/Logits/Predictions = Softmax[T=DT_FLOAT, _dev
ice="/device:GPU:0"](InceptionResnetV2/Logits/Logits/BiasAdd)]]

Caused by op 'InceptionResnetV2/Logits/Predictions', defined at:
  File "train_image_classifier.py", line 574, in <module>
    tf.app.run()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\a
pp.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 474, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "D:\Brian\RD\tf\model_test\deployment\model_deploy.py", line 193, in crea
te_clones
    outputs = model_fn(*args, **kwargs)
  File "train_image_classifier.py", line 457, in clone_fn
    logits, end_points = network_fn(images)
  File "D:\Brian\RD\tf\model_test\nets\nets_factory.py", line 135, in network_fn

    return func(images, num_classes, is_training=is_training, **kwargs)
  File "D:\Brian\RD\tf\model_test\nets\inception_resnet_v2.py", line 362, in inc
eption_resnet_v2
    end_points['Predictions'] = tf.nn.softmax(logits, name='Predictions')
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\nn_ops
.py", line 1667, in softmax
    return _softmax(logits, gen_nn_ops._softmax, dim, name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\nn_ops
.py", line 1610, in _softmax
    return compute_op(logits, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_nn
_ops.py", line 4316, in _softmax
    "Softmax", logits=logits, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\
ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-
access

InvalidArgumentError (see above for traceback): Cannot assign a device for opera
tion 'InceptionResnetV2/Logits/Predictions': Could not satisfy explicit device s
pecification '/device:GPU:0' because no supported kernel for GPU devices is avai
lable.
         [[Node: InceptionResnetV2/Logits/Predictions = Softmax[T=DT_FLOAT, _dev
ice="/device:GPU:0"](InceptionResnetV2/Logits/Logits/BiasAdd)]]

**Comment by jart** [comment] 2017-12-20 23:00
Thanks for the report. This appears to be a duplicate of #2803. I'm going to escalate the issue further. Please follow that issue.

**Closed by jart** 2017-12-20 23:00 UTC
