### ISSUE TITLE
Cannot run word2vec_basic.py, ERROR ValueError: array must not contain infs or NaNs.

### ISSUE THREAD

**Issue by paratata** [tensorflow/models#1082] opened 2017-02-28 15:01 UTC
## Please let us know which model this issue is about (specify the top-level directory)
model on word2vec basic implementation, on tensorflow and I'm using Jupyter on a mac. Hope this will help close this issue

I tried to run the word2vec_basic.py from this directory without success: Here is the error i get:

ValueError                                Traceback (most recent call last)
<ipython-input-1-db6b364536b9> in <module>()
    248   tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000)
    249   plot_only = 500
--> 250   low_dim_embs = tsne.fit_transform(final_embeddings[:plot_only, :])
    251   labels = [reverse_dictionary[i] for i in xrange(plot_only)]
    252   plot_with_labels(low_dim_embs, labels)

/Users/anaconda/lib/python3.6/site-packages/sklearn/manifold/t_sne.py in fit_transform(self, X, y)
    882             Embedding of the training data in low-dimensional space.
    883         """
--> 884         embedding = self._fit(X)
    885         self.embedding_ = embedding
    886         return self.embedding_

/Users/anaconda/lib/python3.6/site-packages/sklearn/manifold/t_sne.py in _fit(self, X, skip_num_points)
    787                           X_embedded=X_embedded,
    788                           neighbors=neighbors_nn,
--> 789                           skip_num_points=skip_num_points)
    790 
    791     def _tsne(self, P, degrees_of_freedom, n_samples, random_state,

/Users/anaconda/lib/python3.6/site-packages/sklearn/manifold/t_sne.py in _tsne(self, P, degrees_of_freedom, n_samples, random_state, X_embedded, neighbors, skip_num_points)
    845         opt_args['it'] = it + 1
    846         params, kl_divergence, it = _gradient_descent(obj_func, params,
--> 847                                                       **opt_args)
    848         if self.verbose:
    849             print("[t-SNE] KL divergence after %d iterations with early "

/Users/anaconda/lib/python3.6/site-packages/sklearn/manifold/t_sne.py in _gradient_descent(objective, p0, it, n_iter, objective_error, n_iter_check, n_iter_without_progress, momentum, learning_rate, min_gain, min_grad_norm, min_error_diff, verbose, args, kwargs)
    386     for i in range(it, n_iter):
    387         new_error, grad = objective(p, *args, **kwargs)
--> 388         grad_norm = linalg.norm(grad)
    389 
    390         inc = update * grad >= 0.0

/Users/anaconda/lib/python3.6/site-packages/scipy/linalg/misc.py in norm(a, ord, axis, keepdims)
    127     """
    128     # Differs from numpy only in non-finite handling and the use of blas.
--> 129     a = np.asarray_chkfinite(a)
    130 
    131     # Only use optimized norms if axis and keepdims are not specified.

/Users//anaconda/lib/python3.6/site-packages/numpy/lib/function_base.py in asarray_chkfinite(a, dtype, order)
   1213     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
   1214         raise ValueError(
-> 1215             "array must not contain infs or NaNs")
   1216     return a
   1217 

ValueError: array must not contain infs or NaNs

**Comment by tatatodd** [comment] 2017-03-01 05:41
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by paratata** [comment] 2017-03-01 13:31
model on word2vec basic implementation, on tensorflow and I'm using Jupyter on a mac. Hope this will help close this issue

**Comment by tatatodd** [comment] 2017-03-03 19:39
What version of TensorFlow are you using?  What is the git commit hash of the models repository?

**Comment by paratata** [comment] 2017-03-05 12:29
I use TensorFlow 1.0

**Comment by prb12** [comment] 2017-03-06 22:50
Could you please clarify *exactly* what steps are required to reproduce this problem?  (i.e. what command lines did you type) 

It looks to me like you are trying to follow this tutorial: https://www.tensorflow.org/tutorials/word2vec

I gather that you're trying to run `examples/tutorials/word2vec/word2vec_basic.py` (which is part of the `tensorflow/tensorflow` repository), however, I don't understand your comment about "running it from *this* directory", and I don't understand what your are doing with Jupyter.

**Comment by paratata** [comment] 2017-03-06 23:10
@prb12 I meant this github directory, i tried to run word2vec_basic.py and yes I'm trying to follow that tutorial to learn a bit more about tensorflow. 
I used jupyter to run the file and I renamed it to do so, also I ran it using the command python word2vec_basic.py, and I've got the same results. I guess the problem is related to the version of tensorflow I'm using( 1.0). Hope these informations will give you more understanding of the situation, thanks for the help.

**Comment by prb12** [comment] 2017-03-07 22:31
Could you please try running the example not using Jupyter?

**Comment by nb312** [comment] 2017-03-30 10:25
how to run the word2vec_basic.py file just use "python word2vec_basic.py"?.i did this but just wait it for a long time and nothing happened

**Comment by nb312** [comment] 2017-03-30 10:26
what are the things I should prepare

**Comment by YeonjungHong** [comment] 2017-04-21 05:10
The same error occurred on my mac both in PyCharm and Terminal('$ python word2vec_basic.py').
platform: Darwin-15.6.0-x86_64-i386-64bit
python: 3.6.0
numpy: 1.12.1
scipy: 0.19.0
sklearn: 0.18.1

Please help!

**Comment by itsmeolivia** [comment] 2018-02-08 00:41
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by itsmeolivia** 2018-02-08 00:41 UTC
Labels: stat:awaiting response
