### ISSUE TITLE
tensorflow/models/official/keras_application_models/benchmark_main.py

### ISSUE THREAD

**Issue by xueleihan** [tensorflow/models#5103] opened 2018-08-16 02:52 UTC
when running tensorflow/models/official/keras_application_models/benchmark_main.py
when running benchmark_main.py model=inceptionv3
training.py", line 108, in _standardize_input_data
    'Found: ' + str(data)[:200] + '...')
TypeError: Error when checking model input: data should be a Numpy array, or list/dict of Numpy arrays. Found: <RepeatDataset shapes: ((32, 224, 224, 3), (32, 1000)), types:

**Comment by tensorflowbutler** [comment] 2018-08-16 12:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Monekyzoon** [comment] 2018-09-19 11:20
I run the code as readme ：python benchmark_main.py --model resnet50 --eager
tensorflow version is tf1.10
tensorflow installed from pip install 
python version is 2.7
and then error ：Traceback (most recent call last):
  File "benchmark_main.py", line 223, in <module>
    absl_app.run(main)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "benchmark_main.py", line 216, in main
    run_keras_model_benchmark(FLAGS)
  File "benchmark_main.py", line 135, in run_keras_model_benchmark
    validation_steps=int(np.ceil(FLAGS.num_eval_images / FLAGS.batch_size))
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 1348, in fit
    validation_steps=validation_steps)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_eager.py", line 1040, in fit_loop
    do_validation=do_validation)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_eager.py", line 284, in iterator_fit_loop
    model, x, y, sample_weights=sample_weights, training=True)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_eager.py", line 794, in _process_single_batch
    training=training)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_eager.py", line 128, in _model_loss
    outs = model.call(inputs[0])
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/network.py", line 777, in call
    mask=masks)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/keras/engine/network.py", line 948, in _run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 186, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 204, in __call__
    name=self.name)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 981, in conv2d
    name=name, ctx=_ctx)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1014, in conv2d_eager_fallback
    _attr_T, _inputs_T = _execute.args_to_matching_eager([input, filter], _ctx)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/eager/execute.py", line 195, in args_to_matching_eager
    ret = [internal_convert_to_tensor(t, dtype, ctx=ctx) for t in l]
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/tianyukun/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 798, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'int32' for variable of type 'float32'

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by yhliang2018** [comment] 2020-01-29 21:21
Close this as the model doesn't exist in official anymore.

**Closed by yhliang2018** 2020-01-29 21:21 UTC
Labels: stat:awaiting response
