### ISSUE TITLE
Train and Test loss on Tensorboard Losses/TotalLoss

### ISSUE THREAD

**Issue by Kmeliani** [tensorflow/models#4307] opened 2018-05-18 15:45 UTC
------------------------

### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  MacOS High Sierra 10.13.4
- **TensorFlow installed from (source or binary)**:  pip install
- **TensorFlow version (use command below)**: v1.5.0-0-g37aa430d84 1.5.0
- **CUDA/cuDNN version**: I am using CPU
- **CPU model and memory**: 2,2 Ghz Intel Core i7; 16 GB 1600 MHz DDR3

### Describe the problem
Hi !
I wish to display both train and eval losses in Tensorboard Losses/TotalLoss.

I display correctly classification_loss, localization_loss, PascalBoxes_PerformanceByCategory and PascalBoxes_Precision for eval.

How can i achieve that ?

Thank you in advance,

**Comment by tensorflowbutler** [comment] 2018-05-27 03:27
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-09 22:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by harshini-gadige** [comment] 2018-11-09 22:09
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by QuickLearner171998** [comment] 2019-06-03 05:01
> ### System information
> * **What is the top-level directory of the model you are using**: object_detection
> * **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
> * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  MacOS High Sierra 10.13.4
> * **TensorFlow installed from (source or binary)**:  pip install
> * **TensorFlow version (use command below)**: v1.5.0-0-g37aa430d84 1.5.0
> * **CUDA/cuDNN version**: I am using CPU
> * **CPU model and memory**: 2,2 Ghz Intel Core i7; 16 GB 1600 MHz DDR3
> 
> ### Describe the problem
> Hi !
> I wish to display both train and eval losses in Tensorboard Losses/TotalLoss.
> 
> I display correctly classification_loss, localization_loss, PascalBoxes_PerformanceByCategory and PascalBoxes_Precision for eval.
> 
> How can i achieve that ?
> 
> Thank you in advance,

Any updates??

**Comment by tensorflowbutler** [comment] 2020-01-29 23:22
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:45 UTC
Labels: stat:awaiting response
