### ISSUE TITLE
Error in download script - imagenet_lsvrc_2015_synsets.txt: No such file or directory

### ISSUE THREAD

**Issue by pankajkgupta** [tensorflow/models#2478] opened 2017-09-28 18:28 UTC
### System information
- **What is the top-level directory of the model you are using**: research/inception
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:1.3.0
- **Bazel version (if compiling from source)**:0.5.4
- **CUDA/cuDNN version**:7.5/6.0
- **GPU model and memory**:GeForce GTX TITAN X 12GB
- **Exact command to reproduce**:bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}"

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
After setting the DATA_DIR-
root@0047d9668d34:/data/workspace/models/inception# DATA_DIR=/data/imagenet-data

I run the following command-
root@0047d9668d34:/data/workspace/models/inception# bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}"

It asks me imagenet credentials and downloads them fine but soon fails with following error-

bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/download_imagenet.sh: line 105: bazel-bin/inception/download_and_preprocess_imagenet.runfiles/inception/inception/data/imagenet_lsvrc_2015_synsets.txt: No such file or directory

bazel is complaining even though I can list and open the file at that path.

**Comment by tatatodd** [comment] 2017-10-11 07:05
@pankajkgupta I'm not sure which shell you're using, but maybe the problem is that your DATA_DIR isn't exported?  E.g. either try this:
```
$ bazel-bin/inception/download_and_preprocess_imagenet /data/imagenet-data
```
Or this:
```
$ DATA_DIR=/data/imagenet-data bazel-bin/inception/download_and_preprocess_imagenet ${DATA_DIR}
```
Or this:
```
$ export DATA_DIR=/data/imagenet-data
$ bazel-bin/inception/download_and_preprocess_imagenet ${DATA_DIR}
```

**Comment by stecklin** [comment] 2017-12-07 05:06
I am getting the exact same error. 
@pankajkgupta I tried using `bazel-bin/inception/download_and_preprocess_imagenet /data/my-data-dir` as you suggested, the error doesn't change.

**OS:** CentOS 7.3

**Comment by wt-huang** [comment] 2018-10-27 01:19
Closing as this is resolved

**Closed by wt-huang** 2018-10-27 01:19 UTC
Labels: stat:awaiting response
