### ISSUE TITLE
ImportError: No module named image.python.ops

### ISSUE THREAD

**Issue by wuyuzaizai** [tensorflow/models#1698] opened 2017-06-20 13:43 UTC
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/omnisky/models/object_detection/builders/model_builder.py", line 23, in <module>
    from object_detection.builders import matcher_builder
  File "/home/omnisky/models/object_detection/builders/matcher_builder.py", line 19, in <module>
    from object_detection.matchers import bipartite_matcher
  File "/home/omnisky/models/object_detection/matchers/bipartite_matcher.py", line 20, in <module>
    from tensorflow.contrib.image.python.ops import image_ops
ImportError: No module named image.python.ops

**Comment by derekjchow** [comment] 2017-06-20 16:15
@wuyuzaizai  Which version of Tensorflow are you using?

**Comment by vinodkkurmi** [comment] 2017-06-26 14:47
@wuyuzaizai  Have you got the solution of this problem ..i am facing the same problem 
@derekjchow  Is it related to the version of tf???

**Comment by derekjchow** [comment] 2017-06-26 18:06
@vinodkkurmi I suspect so. Could you provide information about your setup?

**Comment by ali01** [comment] 2017-06-30 17:53
Please provide details for how to reproduce this problem.

Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by channingxiao** [comment] 2017-07-02 06:21
I got the exact same error.  The tensorflow I installed was 0.12 using pip install tensorflow-gpu. The problem was solved when reinstall using conda install tensorflow-gpu (which 1.1.1 will be installed).

**Comment by lgallen** [comment] 2017-07-11 20:38
@ali01  Same error here. I installed using the [object detection tutorial installation directions](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md) inside a Conda environment on a Mac OSX 10.12.5. This is with Tensorflow 1.2.1, Python 3.5.3. 

I was able to run the the [object detection tutorial](https://github.com/tensorflow/models/blob/master/object_detection/object_detection_tutorial.ipynb) first but now am getting this error.

The error comes when I run this step:

```
python object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=${PATH_TO_YOUR_PIPELINE_CONFIG} \
    --train_dir=${PATH_TO_TRAIN_DIR}
```

Paths have obviously been modified for my machine in the actual script.

**Comment by derekjchow** [comment] 2017-07-11 21:00
@lgallen I don't think you included the error in your comment. Could you add it?

**Comment by lgallen** [comment] 2017-07-11 22:48
@derekjchow Here it is:
> Traceback (most recent call last):
>   File "object_detection/train.py", line 53, in <module>
>     from object_detection.builders import model_builder
>   File "/Users/d0gk/anaconda/envs/mobilenets/lib/python3.5/site-packages/tensorflow/models/object_detection/builders/model_builder.py", line 23, in <module>
>     from object_detection.builders import matcher_builder
>   File "/Users/d0gk/anaconda/envs/mobilenets/lib/python3.5/site-packages/tensorflow/models/object_detection/builders/matcher_builder.py", line 19, in <module>
>     from object_detection.matchers import bipartite_matcher
>   File "/Users/d0gk/anaconda/envs/mobilenets/lib/python3.5/site-packages/tensorflow/models/object_detection/matchers/bipartite_matcher.py", line 20, in <module>
>     from tensorflow.contrib.image.python.ops import image_ops
> ImportError: No module named image.python.ops

**Comment by rdslater** [comment] 2017-07-13 20:57
it appears that the proper import statement for bipartite_matcher.py line 20 should be:

from tensorflow.python.ops import image_ops

this may or may not solve the entire issue, but searching the repository and browser tensorflow, that is the proper location (I think).

**Comment by lgallen** [comment] 2017-07-14 00:27
@rdslater This fix resolves the specific error message that was reported in this thread. Thank you.

**Comment by YunTuring** [comment] 2017-07-31 09:47
Does this problem solved by someone? I got the same error, as before, I install tensorflow 0.8.0 and cuda 8.0, my python is 2.7.12, when I configure Google's Objection Detection model by using the guildline in website "https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md", and when I almost complete all the steps except the last one－－test the installation.
when I run `python object_detection/builders/model_builder_test.py`, it comes the error same as your guys. Has someone know how to solve the problem? I try to Baidu, Bing (while in china cannot connect google ), no good solutions I got.

**Comment by marekjaszuk** [comment] 2017-08-15 00:24
Tanx a lot. That solved the problem for me.

**Comment by P-a-i-s** [comment] 2018-01-18 06:49
I was running the model_builder_test.py for Object Detection and was facing this error. @rdslater solution helped me solve the "ImportError: No module named image.python.ops" error. Thank you.

**Comment by harshini-gadige** [comment] 2018-09-28 18:12
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-09-28 18:12 UTC
Labels: stat:awaiting response

**Comment by mayuri-kulkarni** [comment] 2022-08-21 12:37
[https://github.com/tensorflow/models/pull/2182] worked for me!
