### ISSUE TITLE
 Default MaxPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by juntawu** [tensorflow/models#7312] opened 2019-07-26 13:24 UTC
### Describe the problem
I run official/resnet/imagenet_main.py with gpu, and it reports:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
	 [[node resnet_model/max_pooling2d/MaxPool (defined at /home/wujunta/anaconda3/envs/tf/lib/python2.7/site-packages/tensorflow_core/python/framework/ops.py:1685) ]]`

What's the problem?

**Comment by tensorflowbutler** [comment] 2019-07-27 12:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yuffon** [comment] 2019-10-29 14:21
Have you resolve this problem?

**Comment by mengdong** [comment] 2019-11-27 09:19
can you check if you install cudnn?
```
ii  libcudnn7                                       7.6.5.32-1+cuda10.0                             amd64        cuDNN runtime libraries
ii  libcudnn7-dev                                   7.6.5.32-1+cuda10.0                             amd64        cuDNN development libraries and headers
```
note that cudnn should match your cuda version, download them here: https://developer.nvidia.com/rdp/cudnn-download

**Comment by ravikyram** [comment] 2020-06-24 13:45
@juntawu 

Is this still an issue?.Please, close this thread if your issue was resolved.Thanks!

**Comment by forest44** [comment] 2020-07-01 09:43
I have the same issue. I have no solution.

**Comment by ravikyram** [comment] 2020-07-01 11:02
@juntawu 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment] 2020-08-08 02:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-08-08 02:21 UTC
Labels: models:research, stat:awaiting response, type:support

**Comment by AnthonyDawson** [comment] 2020-11-03 15:57
Hi

I relise this thread is closed but in the hope that someone can shine the light:

I have a similar issue. Did development, training, etc. on a PC with a GPU tested and ran predictions on there, no problem. Recreated the environment on a laptop with no GPU support using the relevant requirements.txt file and substituting tensorflow GPUs with CPU same predictor code, weight/net that worked on the PC with the GPU and on the laptop I got:

 tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Default MaxPoolingOp only supports NHWC on device type CPU
         [[node sequential/max_pooling2d_1/MaxPool (defined at .\metatrader.py:104) ]] [Op:__inference_predict_function_445]

Did anyone find  solution?
