### ISSUE TITLE
im2txt an error

### ISSUE THREAD

**Issue by burness** [tensorflow/models#480] opened 2016-09-30 17:32 UTC
## Please let us know which model this issue is about (specify the top-level directory)
Hi, when I run the `download_and_preprocess_mscoco.sh`, it get an error:

```
ile "/home/amax/.cache/bazel/_bazel_amax/8f0aff1b79aca7bfbc619652b824e30c/execroot/im2txt/bazel-out/local-fastbuild/bin/im2txt/build_mscoco_data.runfiles/im2txt/im2txt/data/build_mscoco_data.py", line 214, in _to_sequence_example
    encoded_image = f.read()
  File "/home/amax/anaconda2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 102, in read
  File "/home/amax/anaconda2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 72, in _preread_check
  File "/home/amax/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
  File "/home/amax/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
ResourceExhaustedError: /home/amax/burness/git_re/tensorflow/models/im2txt/im2txt/data/mscoco/raw-data/train2014/COCO_train2014_000000107135.jpg
```
My GPU is k20c，Could you help me to solve this problem

**Comment by magicalhobo** [comment] 2016-09-30 18:24
I'm also getting this ResourceExhaustedError using CUDA. I tried varying num_threads, but it didn't help.

**Comment by siavashk** [comment] 2016-09-30 19:13
+1

**Comment by siavashk** [comment] 2016-09-30 21:24
related to tensorflow/tensorflow#4685

**Comment by cshallue** [comment] 2016-09-30 21:48
This is a duplicate of tensorflow/tensorflow#4685

I have a fix pending: see that thread for details and future updates.

**Closed by cshallue** 2016-09-30 21:48 UTC

**Comment by burness** [comment] 2016-10-02 09:54
Thanks @cshallue , I will try

**Comment by jart** [comment] 2016-10-15 04:57
@burness are you using RedHat / CentOS?

**Comment by burness** [comment] 2016-10-18 01:33
@jart  No, I run this model in ubuntu
