### ISSUE TITLE
Slim.learning.train  error when model train too fast

### ISSUE THREAD

**Issue by nguyenvulebinh** [tensorflow/models#1020] opened 2017-02-15 08:11 UTC
I follow step in slim_walkthoungh.ipynb and get error. I gess when train model too fast then elapsed_time equal zero

`Layers
name = deep_regression/fc2/Relu:0, shape = (?, 16)
name = deep_regression/fc1/Relu:0, shape = (?, 32)
name = deep_regression/prediction/BiasAdd:0, shape = (?, 1)

Parameters
name = deep_regression/fc1/weights:0, shape = (1, 32)
name = deep_regression/fc1/biases:0, shape = (32,)
name = deep_regression/fc2/weights:0, shape = (32, 16)
name = deep_regression/fc2/biases:0, shape = (16,)
name = deep_regression/prediction/weights:0, shape = (16, 1)
name = deep_regression/prediction/biases:0, shape = (1,)
WARNING:tensorflow:From D:\ML Learning\python_env\lib\site-packages\tensorflow\python\training\supervisor.py:344 in __init__.: SummaryWriter.__init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Starting Queues.
INFO:tensorflow:Error reported to Coordinator: <class 'ZeroDivisionError'>, float division by zero
INFO:tensorflow:Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "D:/ML Learning/workspace/mnistclass/model.py", line 117, in <module>
    log_every_n_steps=50)
  File "D:\ML Learning\python_env\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 793, in train
    raise
  File "D:\ML Learning\python_env\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\ML Learning\python_env\lib\site-packages\tensorflow\python\training\supervisor.py", line 974, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "D:\ML Learning\python_env\lib\site-packages\tensorflow\python\training\supervisor.py", line 802, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "D:\ML Learning\python_env\lib\site-packages\tensorflow\python\training\coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "D:\ML Learning\python_env\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "D:\ML Learning\python_env\lib\site-packages\tensorflow\python\training\coordinator.py", line 296, in stop_on_exception
    yield
  File "D:\ML Learning\python_env\lib\site-packages\tensorflow\python\training\coordinator.py", line 487, in run
    self.run_loop()
  File "D:\ML Learning\python_env\lib\site-packages\tensorflow\python\training\supervisor.py", line 1044, in run_loop
    steps_per_sec = added_steps / elapsed_time
ZeroDivisionError: float division by zero`

**Comment by aselle** [comment] 2017-02-15 18:13
This is a duplicate of #3172

**Closed by aselle** 2017-02-15 18:13 UTC
