### ISSUE TITLE
Failed to find all Cityscapes modules

### ISSUE THREAD

**Issue by BDMLLang** [tensorflow/models#4644] opened 2018-06-28 08:59 UTC
sh  convert_cityscapes.sh 

Failed to find all Cityscapes modules?

**Comment by tensorflowbutler** [comment] 2018-06-28 19:14
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ChayaBei** [comment] 2018-07-02 02:01
did you solve it? I have the same problem

**Comment by ymodak** [comment] 2018-11-09 22:12
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-12-05 21:58 UTC
Labels: stat:awaiting response
