### ISSUE TITLE
data_augmentation_options

### ISSUE THREAD

**Issue by jpff96** [tensorflow/models#7779] opened 2019-11-10 18:47 UTC
Hi!
I want to apply data augmentation during training but only to a particular class. Is that possible?

**Comment by tensorflowbutler** [comment] 2019-11-11 12:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jpff96** [comment] 2019-11-11 12:23
**Have I written custom code:** yes. I would like to use Tensorflow OpenAPI to create a custom classifier to detect two different classes.
**OS Platform and Distribution** 

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"

**TensorFlow installed from** I am using google Colab
**TensorFlow version** 1.15.0
**CUDA/cuDNN version:** 10.1  
**GPU model and memory:**  NVIDIA-SMI 430.40 
**Exact command to reproduce** I just eval the model and it only detect elements for one class

**Comment by ravikyram** [comment] 2020-06-19 11:38
@jpff96 

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment] 2020-07-14 09:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-14 09:42 UTC
Labels: type:support
