### ISSUE TITLE
KeyError for groundtruth_classes running eval.py

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/models#3179] opened 2018-01-17 14:03 UTC
### System information
- **What is the top-level directory of the model you are using**: ssd_mobilenet_v1 latest
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4.0
- **Bazel version (if compiling from source)**: 0.9.0
- **CUDA/cuDNN version**: 9.0 / 7
- **GPU model and memory**: NVIDIA GTX 1050 4GB (6.1 capability) 
- **Exact command to reproduce**:

i got a pascal-voc based dataset for hands. From that i  successfully created the csv and tfrecord files.
I got around 5000 training images with 10000 labels and around 800 testing images with 2000 labels.
The csv looks like this (so should be alright):
```
filename,width,height,class,xmin,ymin,xmax,ymax
VOC2007_518.jpg,375,500,hand,299,274,333,309
VOC2007_518.jpg,375,500,hand,337,198,376,236
```

My only class is "hand", therefore my label map looks like:
```
item {
  id: 1
  name: 'hand'
}
```
in eval.py i added:
`os.environ['CUDA_VISIBLE_DEVICES'] = '-1'`
to run it on CPU, but deleting this line does not solve the problem

parallel to training (which seems to run successful) i try to run the evaluation job like:
```
python object_detection/eval.py \
--logtostderr \
--pipeline_config_path= /home/gustav/workspace/training_hands/model/ssd_mobilehandsnet.config \
--checkpoint_dir=/home/gustav/workspace/training_hands/model/train \   
--eval_dir=/home/gustav/workspace/training_hands/model/eval
```

and got following error right in the beginning:
```
WARNING:root:image 0 does not have groundtruth difficult flag specified
Traceback (most recent call last):
  File "object_detection/eval.py", line 135, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/eval.py", line 131, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/home/gustav/workspace/tensorflow/models/research/object_detection/evaluator.py", line 210, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/home/gustav/workspace/tensorflow/models/research/object_detection/eval_util.py", line 381, in repeated_checkpoint_run
    save_graph_dir)
  File "/home/gustav/workspace/tensorflow/models/research/object_detection/eval_util.py", line 269, in _run_checkpoint_once
    image_id=batch, groundtruth_dict=result_dict)
  File "/home/gustav/workspace/tensorflow/models/research/object_detection/utils/object_detection_evaluation.py", line 167, in add_single_ground_truth_image_info
    standard_fields.InputDataFields.groundtruth_classes]
KeyError: 'groundtruth_classes'
```

So i printed out the groundtruth_dict which causes the problem, and it looks like this:
```
('groundtruth_dict= ', {'original_image': array([[[[64, 68, 80],
         [66, 70, 82],
         [62, 66, 78],
         ...,
         [12, 16, 15],
         [12, 16, 15],
         [17, 21, 20]],

        [[63, 67, 79],
         [66, 70, 82],
         [61, 65, 77],
         ...,
         [13, 17, 16],
         [13, 17, 16],
         [17, 21, 20]],

        [[62, 66, 78],
         [66, 70, 82],
         [62, 66, 78],
         ...,
         [15, 19, 18],
         [14, 18, 17],
         [18, 22, 21]],

        ...,

        [[97, 83, 82],
         [85, 71, 70],
         [84, 70, 67],
         ...,
         [32, 36, 37],
         [26, 30, 31],
         [27, 31, 32]],

        [[94, 80, 79],
         [86, 72, 71],
         [90, 76, 73],
         ...,
         [30, 34, 35],
         [22, 26, 27],
         [27, 31, 32]],

        [[87, 73, 72],
         [85, 71, 70],
         [97, 83, 80],
         ...,
         [28, 32, 33],
         [18, 22, 23],
         [23, 27, 28]]]], dtype=uint8), 'groundtruth_is_crowd': array([], dtype=bool), 'groundtruth_area': array([], dtype=float32), 'detection_boxes': array([[  3.7222574, 243.85812  , 107.565025 , 424.56796  ],
       [ 11.711642 , 323.64343  , 105.015625 , 500.       ],
       [278.89868  , 458.30972  , 342.8926   , 497.58078  ],
       [  3.8873253,  29.537014 ,  97.22421  , 239.43376  ],
       [ 35.484375 , 428.64963  , 166.29593  , 499.3997   ],
       [252.70572  , 315.68005  , 361.17697  , 437.46945  ],
       [199.74017  , 268.7957   , 218.25183  , 287.99872  ],
       [ 27.835133 , 323.57385  ,  42.138878 , 341.12427  ],
       [262.94836  , 459.0676   , 324.5173   , 497.0951   ],
       [ 30.12121  , 352.18933  ,  42.691647 , 366.9404   ],
       [195.73451  , 346.0745   , 222.67781  , 369.47473  ],
       [182.75648  , 349.4227   , 203.51555  , 368.03787  ],
       [216.14795  , 268.55164  , 239.84476  , 289.22177  ],
       [213.16508  , 347.17734  , 239.56981  , 369.95773  ],
       [196.84222  , 321.86615  , 222.91957  , 343.78122  ],
       [198.60518  , 296.3402   , 221.77362  , 317.35907  ],
       [182.73792  , 323.54163  , 204.73431  , 343.42215  ],
       [212.7839   , 319.90427  , 240.82404  , 343.36578  ],
       [180.62373  , 296.06586  , 200.99411  , 315.83798  ],
       [338.9445   , 348.37943  , 359.15344  , 367.71082  ],
       [234.88895  , 349.16602  , 259.0071   , 370.33292  ],
       [303.46356  , 457.30545  , 364.08194  , 497.49954  ],
       [215.08684  , 240.73073  , 238.43745  , 261.50558  ],
       [145.5085   , 326.44092  , 157.93738  , 338.1567   ],
       [ 83.43828  , 271.63446  ,  98.896355 , 286.15344  ],
       [199.06071  , 241.57281  , 217.82936  , 260.41003  ],
       [140.45529  , 295.98352  , 157.77802  , 310.67267  ],
       [233.60094  , 320.17004  , 260.29773  , 343.26422  ],
       [182.35611  , 269.01178  , 198.91292  , 287.86884  ],
       [181.20068  , 372.96698  , 201.5161   , 393.46417  ],
       [300.68942  , 407.16644  , 359.04584  , 464.96985  ],
       [139.66115  , 444.37216  , 159.07675  , 479.99152  ],
       [ 23.430836 , 397.88272  ,  44.162247 , 422.06415  ],
       [ 21.100252 , 294.047    ,  42.38389  , 314.4236   ],
       [236.31688  , 243.0964   , 258.58383  , 261.66235  ],
       [280.3447   , 407.4605   , 292.8006   , 420.21317  ],
       [299.36264  , 378.95526  , 314.73883  , 393.8552   ],
       [215.91156  , 295.24384  , 241.68756  , 317.32587  ],
       [160.2216   , 293.39374  , 180.43195  , 310.80597  ],
       [104.38906  , 423.31558  , 119.70608  , 449.4095   ],
       [ 28.486263 , 373.89478  ,  45.667873 , 392.93118  ],
       [218.15582  , 216.69876  , 238.20929  , 235.54846  ],
       [ 83.59404  , 397.43365  ,  98.18858  , 419.92328  ],
       [234.9742   , 294.39795  , 259.99747  , 315.69208  ],
       [ 40.300983 , 420.2927   ,  60.01407  , 446.76932  ],
       [ 83.4634   , 300.71408  ,  98.52754  , 313.43674  ],
       [299.78403  , 351.60342  , 317.20264  , 366.65198  ],
       [338.4315   , 373.68985  , 359.32492  , 394.76834  ],
       [166.14731  , 325.57693  , 184.81743  , 340.32037  ],
       [ 44.711205 , 397.67593  ,  61.83229  , 420.33655  ],
       [257.01343  , 350.76517  , 278.36444  , 369.43997  ],
       [158.12172  , 445.21902  , 178.86504  , 480.0696   ],
       [262.4441   , 433.15714  , 275.50058  , 447.81937  ],
       [235.62439  , 269.40042  , 260.34317  , 289.5497   ],
       [216.74083  , 372.85437  , 239.18875  , 395.69507  ],
       [104.77659  , 272.44052  , 120.63016  , 287.7762   ],
       [320.54465  , 352.04922  , 339.21588  , 368.14398  ],
       [335.92252  , 398.19324  , 358.44922  , 421.3909   ],
       [ 58.603916 , 358.8482   ,  70.879425 , 371.98077  ],
       [141.1541   , 271.51678  , 160.22408  , 288.35416  ],
       [165.6901   , 377.2134   , 182.83548  , 393.69647  ],
       [297.67566  , 322.5592   , 319.34927  , 341.68277  ],
       [219.46007  , 191.31029  , 236.61574  , 210.29526  ],
       [261.85358  , 406.24994  , 275.86523  , 420.3969   ],
       [201.52548  , 218.10652  , 218.98857  , 235.7868   ],
       [ 61.601517 , 419.59647  ,  81.58215  , 449.02356  ],
       [259.13358  , 191.19864  , 275.70117  , 210.28836  ],
       [196.6504   , 370.98364  , 219.95567  , 395.11862  ],
       [ 37.326405 , 444.67273  ,  60.239902 , 478.10492  ],
       [ 64.34091  , 272.268    ,  81.0081   , 286.43555  ],
       [239.10269  , 190.63756  , 256.7139   , 209.62975  ],
       [ 84.614586 , 219.65251  , 100.4486   , 234.34676  ],
       [164.96635  , 400.28537  , 179.88608  , 420.6667   ],
       [236.52635  , 449.33408  , 259.5564   , 475.5281   ],
       [276.8998   , 356.08392  , 338.37222  , 413.64206  ],
       [104.9978   , 399.731    , 116.69384  , 418.34628  ],
       [320.3317   , 111.434006 , 338.71234  , 131.7356   ],
       [ 81.85569  , 420.5974   ,  99.61256  , 449.95294  ],
       [237.63846  , 217.76233  , 258.50333  , 235.64027  ],
       [150.84442  , 381.60397  , 163.33492  , 394.88397  ],
       [336.49493  , 293.7339   , 358.86316  , 315.8196   ],
       [316.99408  , 322.72513  , 339.50522  , 341.49857  ],
       [147.58536  , 403.13043  , 160.26057  , 421.39246  ],
       [ 59.55451  , 445.28403  ,  82.34845  , 480.91904  ],
       [124.00205  , 246.3231   , 143.39198  , 263.2262   ],
       [259.49414  , 163.86137  , 276.08868  , 184.64775  ],
       [338.4011   , 107.287674 , 356.83478  , 129.8463   ],
       [ 64.310234 , 398.55325  ,  81.488144 , 421.8755   ],
       [ 81.583664 , 444.8386   , 101.344795 , 482.3399   ],
       [105.01828  , 194.82852  , 119.77269  , 210.081    ],
       [ 36.95982  , 213.85706  ,  63.16913  , 236.14496  ],
       [337.48508  , 322.28442  , 359.05057  , 341.78952  ],
       [ 25.420755 , 164.07928  ,  40.073856 , 183.27313  ],
       [279.17184  , 379.42944  , 294.5789   , 393.39044  ],
       [316.2293   , 295.75665  , 341.90454  , 317.5249   ],
       [104.77272  , 167.66571  , 119.54046  , 183.84103  ],
       [254.92526  , 319.55164  , 280.5428   , 343.57095  ],
       [240.45943  , 163.13182  , 257.80908  , 185.5624   ],
       [ 86.57174  , 194.65358  , 101.57887  , 209.33946  ],
       [201.43233  , 191.00928  , 217.96552  , 209.88242  ]],
      dtype=float32), 'groundtruth_classes': array([1, 1]), 'groundtruth_group_of': array([], dtype=int64), 'detection_classes': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 'groundtruth_boxes': array([[329.     , 185.     , 364.     , 222.     ],
       [228.00002, 142.     , 255.     , 169.     ]], dtype=float32), 'detection_scores': array([0.28857195, 0.27300978, 0.26126269, 0.26062793, 0.2579368 ,
       0.2562737 , 0.25593358, 0.25527725, 0.25475922, 0.25462022,
       0.25362423, 0.25343668, 0.25324154, 0.25309741, 0.25304952,
       0.2525339 , 0.25238705, 0.25216657, 0.25213185, 0.25187644,
       0.25182185, 0.25181577, 0.25178105, 0.25142857, 0.2514179 ,
       0.25129703, 0.2512553 , 0.25114852, 0.25109357, 0.25099254,
       0.25076938, 0.25071684, 0.25066367, 0.25060827, 0.2504932 ,
       0.25044683, 0.25038907, 0.2503281 , 0.25016046, 0.25004968,
       0.25001392, 0.24997473, 0.2499705 , 0.24986933, 0.24985579,
       0.24971655, 0.24966986, 0.24957949, 0.24955411, 0.2495341 ,
       0.24944127, 0.24943528, 0.24927019, 0.24923873, 0.24902871,
       0.24901138, 0.2489826 , 0.248974  , 0.24894503, 0.24888656,
       0.24886039, 0.24881014, 0.24875696, 0.2486437 , 0.248637  ,
       0.24848294, 0.24847926, 0.2484746 , 0.2484148 , 0.2483988 ,
       0.24838823, 0.24836443, 0.24826829, 0.2482202 , 0.24818836,
       0.24814872, 0.24807507, 0.24805978, 0.24801467, 0.24799332,
       0.24793899, 0.24792199, 0.24777597, 0.24773791, 0.2475662 ,
       0.24744678, 0.24743527, 0.24741969, 0.24732958, 0.24732772,
       0.24732672, 0.24732575, 0.24726531, 0.24718814, 0.24705447,
       0.24699058, 0.24694735, 0.24692817, 0.24681918, 0.24681872],
      dtype=float32), 'key': 'VOC2007_348.jpg', 'groundtruth_difficult': array([], dtype=int64)})
('standard_fields.InputDataFields.groundtruth_classes= ', 'groundtruth_classes')
WARNING:root:image 0 does not have groundtruth difficult flag specified
('groundtruth_dict= ', {})
```

Could it be that there is something wrong with the Int / Float formating of my data?

**Comment by aselle** [comment] 2018-01-17 21:29
@tombstone, PTAL. Thanks!

**Comment by julianklumpers** [comment] 2018-02-08 10:51
i have the same warning: WARNING:root:image 0 does not have groundtruth difficult flag specified
but i dont have the traceback error. it just hangs on the warning

**Comment by GustavZ** [comment] 2018-02-19 14:42
@julianklumpers  thats normal, it does not mean its hanging.
evaluation is done in certain interval steps and between those it seems hanging

**Comment by hoshii77** [comment] 2018-03-19 12:17
@julianklumpers  i have the same problem.... have you solved this problem?Thanks

**Comment by vishalgolcha** [comment] 2018-03-31 15:47
facing the same issue can someone provide an update on this ?

**Comment by Orankarl** [comment] 2018-05-23 16:11
Meeting the same error "KeyError: 'groundtruth_classes'"
Have you found the solution?

**Comment by kevin-hxq** [comment] 2018-09-26 04:00
WARNING:root:image 0 does not have groundtruth difficult flag specified.
The problem is in config file ,the "eval_config","num_examples",You should write your real examples numbers.
for example:  the faster_rcnn_resnet101_coco.config, line 122.

**Comment by wt-huang** [comment] 2018-11-17 20:09
Closing as this is resolved, feel free to reopen if problem persists

**Closed by wt-huang** 2018-11-17 20:09 UTC
Labels: stat:awaiting tensorflower, type:bug/performance

**Comment by MaricheloGv** [comment] 2019-09-03 15:33
I have similar problem W0903 10:00:15.551728 13996 object_detection_evaluation.py:304] image b'1125.jpg' does not have groundtruth difficult flag specified
Have you found the solution?
