### ISSUE TITLE
About vggish model. I tried on one of the video posted in the youtube8M Challenge, but the result was different from mediapipe

### ISSUE THREAD

**Issue by yw2278** [tensorflow/models#8066] opened 2020-01-20 03:20 UTC
I tested the mediapipe feature extractor and vggish model on the same video, yet the outcome was quite different, neither of them were passed through quantized part. Did I need to change anything in vggish_params or did I miss something? and I noteiced that if I use Vggish code, the output frames were full-video sized and mediapipe was at max 300, so for Vggish model, just take the first 300 frames?

eg.

result from mediapipe is [0.40838873386383057,-0.6660835146903992,-0.520977258682251,-0.6009337306022644, -0.3703511953353882,-2.109630823135376,0.5200448036193848,1.6607683897018433,0.46320971846580505, -0.3932027816772461]

and result from vggish code is [ 0.83347975, -1.44396414, 1.09875723, -0.21115101, 1.30271451, -2.5692895 , -0.29767793, 0.36399144, 0.27895446, -0.50940639]

**Comment by tensorflowbutler** [comment] 2020-01-21 00:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yw2278** [comment] 2020-01-21 03:23
What is the top-level directory of the model you are using: audioset  VGGish 
Have I written custom code: N/A
OS Platform and Distribution: Ubuntu & Windows10
TensorFlow installed from: The official website.
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by ucas010** [comment] 2020-03-28 07:00
@yw2278 
hi,dear
just want to ask some question, for a poor code man,I'm confused that the vggish just extract every frame 128D features,or no matter how long the audio, the last features are 128D??shape is (128,) or (batch,128)?
could you please help me ?
thx

**Comment by plakal** [comment] 2023-03-16 14:34
Duplicate of #9474

**Closed by plakal** 2023-03-16 14:34 UTC
Labels: type:support, models:research
