### ISSUE TITLE
Object detection memory leak

### ISSUE THREAD

**Issue by YijinLiu** [tensorflow/models#5139] opened 2018-08-20 04:31 UTC
### System information
- **What is the top-level directory of the model you are using**:
research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.10.0
- **Bazel version (if compiling from source)**:
0.15.2
- **CUDA/cuDNN version**:
9.2/7.1.4.18
- **GPU model and memory**:
GTX 960/4G
- **Exact command to reproduce**:
python research/object_detection/model_main.py --alsologtostderr \
    --pipeline_config_path=research/object_detection/samples/configs/ssdlite_mobilenet_v2_coco.config \
    --model_dir=XXX --num_eval_steps=6000

### Describe the problem
There is a slow memory leak, about 600M-1G per hour.
I tried to change some parameters to save memory according to earlier issues. They don't work though.
train_config: {
  batch_size: 24
  batch_queue_capacity: 10
  num_batch_queue_threads: 8
  ...
}
train_input_reader: {
    ....
    num_readers: 10
}
eval_input_reader: {
    num_readers: 1
}

**Comment by bleqdyce** [comment] 2018-08-20 10:27
I've got this problem too when I use estimator-based training.
Haven't meet this while using slim-based training.
I wonder if evaluating while training cause this.

**Comment by wxzs5** [comment] 2018-08-20 12:43
the same problem as me. For my situation, I added a line ```plt.close(fig)``` in object detection source code, then it at least can be trained about 200k steps and not be killed by OOM.you can refer from [this issue](https://github.com/tensorflow/models/issues/3603#issue-305396355) for details.

**Comment by bleqdyce** [comment] 2018-08-20 16:42
@wxzs5 thank you, I'll try this.
btw, training process never got killed in my case. However it would occupy all available memory which make pc extremely slow which include training itself of course.

**Comment by KapoorHitesh** [comment] 2018-08-24 06:33
Any update on this? Even I am facing the exact same issue when I am training a mask rcnn model.

**Comment by bleqdyce** [comment] 2018-08-24 06:50
Still got this issue.
I found that lower frequency of saving checkpoint and evaluate do make leak much slower, and that's all. 
At least, training won't stop during I'm at work.

**Comment by YijinLiu** [comment] 2018-08-25 04:31
Issue [3603](https://github.com/tensorflow/models/issues/3603#issue-305396355) is just part of the problem. I added plt.close(fig) in two places, which only slowed the leak a bit.
I wonder how does Google not bothered by this? (given it has been there for almost half a year!)

**Comment by ldalzovo** [comment] 2018-08-31 08:51
I experience the same problem too.

**Comment by liuchang8am** [comment] 2018-09-05 12:44
Same here. This is probably a bug. Can't locate the leak source though.

**Comment by liuchang8am** [comment] 2018-09-06 03:27
UPDATE:
1. Add plt.close(fig) in visualization_utils.py DO NOT work.
2. Tried eval_interval_secs flag in config, in order to slow down the eval process. Yet it is not implemented. Following https://github.com/tensorflow/models/pull/5144 to implement eval_interval_secs, still, DO NOT work.

Still memory leaking with tf version 1.10.

**Comment by bleqdyce** [comment] 2018-09-06 04:50
> Tried eval_interval_secs flag in config, in order to slow down the eval process. Yet it is not implemented. 
Following #5144 to implement eval_interval_secs, still, DO NOT work.

hi, @liuchang8am . I'm the guy who commit #5144.
It worked in tensorflow r1.9, however they change the way estimator trigger evaluation in 1.10.
See https://github.com/tensorflow/tensorflow/commit/3edb609926f2521c726737fc1efeae1572dc6581#diff-bc4a1638bbcd88997adf5e723b8609c7 for detail.

Simply speaking: 

1. evaluation is triggered after you save a checkpoint.
1. **RunConfig.save_checkpoints_secs** and **RunConfig.save_checkpoints_steps** is now the legitimate way to define the frequency of saving checkpoint.
1. **EvalSpec.throttle_secs** does not define the frequency of  saving checkpoint anymore. However it define the minimum time interval of evaluation. 
1. **EvalSpec.throttle_secs** does override **RunConfig**, which means that evaluation will be skipped if
it is still in the minimum time interval of evaluation.

Here is my workaround

1. To adjust the frequency of saving checkpoint, you can simply add **save_checkpoints_secs** or **save_checkpoints_steps** in this line.
https://github.com/tensorflow/models/blob/7b3046768d2d6ea3f306b6ee7b62c02c9ca128a1/research/object_detection/model_main.py#L55
2. To prevent checkpoint saving to trigger evaluation, follow #5144 and **set eval_interval_secs in config**.
or **simply pass throttle_secs to EvalSpec here**.
https://github.com/tensorflow/models/blob/7b3046768d2d6ea3f306b6ee7b62c02c9ca128a1/research/object_detection/model_lib.py#L609

For example: 

I set RunConfig.save_checkpoints_steps to 5000 and EvalSpec.throttle_secs to 864000 (10 days).
to skipped most evaluation other than first and last time. and I run evaluation on every saved checkpoint after training ends or while training is stopped.

**Comment by bleqdyce** [comment] 2018-09-06 08:33
Hi, @swg209  It does mean to save model-ckpt in model_dir every k step in Tensorflow r1.10.
At least for me =P, check [official doc](https://www.tensorflow.org/api_docs/python/tf/estimator/RunConfig) for more detail.

**Comment by swg209** [comment] 2018-09-06 13:46
@bleqdyce    Thanks for your help.   When I directly  run model_main.py ,your way works.  But when I run legacy/train.py , it doesn't save checkpoint .  Did you meet the same issue?

**Comment by bleqdyce** [comment] 2018-09-06 14:13
legacy/train.py use slim as its tensorflow wrapper. 

If you want to use legacy version, you may want to check out [tf slim](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim). I'm not familiar with slim, but I find out that according to [this](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim#training-loop), you can pass **save_interval_secs** to slim.learning.train in legacy/trainer.py

https://github.com/tensorflow/models/blob/7b3046768d2d6ea3f306b6ee7b62c02c9ca128a1/research/object_detection/legacy/trainer.py#L402

and **save_interval_secs** is to define `How often, in seconds, to save the model to logdir.` . which is writing in [tensorflow/contrib/slim/python/slim/learning.py#L607](https://github.com/tensorflow/tensorflow/blob/973780717983b2ee1f4f52b5ab1f8595e6ba4a05/tensorflow/contrib/slim/python/slim/learning.py#L607)

hope this help but cant guarantee though =P

**Comment by pkulzc** [comment] 2018-09-14 23:52
Sorry for the late response! We removed the usage of "add_cdf_image_summary" in [PR](https://github.com/tensorflow/models/pull/5289), you're encouraged to try again once it gets in.

**Comment by zishanahmed08** [comment] 2018-09-18 08:04
# following

**Comment by zishanahmed08** [comment] 2018-09-24 10:27
Has any body checked now that PR is merged, if the memory leak still exists?

**Comment by YijinLiu** [comment] 2018-09-25 03:29
@zishanahmed08 With tensorflow 1.11.0-rc2 and the latest from models, the memory leak is gone for me.

**Closed** 2018-09-25 03:55 UTC

**Comment by bleqdyce** [comment] 2018-09-25 07:07
@YijinLiu  @zishanahmed08 
I tried agian with the latest tensorflow/model repo in docker using image **tensorflow/tensorflow:1.11.0-rc2-devel-gpu**, still leak (~ 500 MB) every time when evaluation is done.

**Comment by mhtrinh** [comment] 2018-10-05 00:07
Please re-open the issue : it's still there with tf 1.11.0 (from pip install)
I am using ssd_resnet50_v1_fpn : same parameter exept :
- 1 class
- 10 files of 1.8GB of tfrecord

The process go from 13G at start training to 31G after 2h (35100 global_step) on CPU RAM. The GPU RAM do no change.
I throttle the eval to every 1 day (although I still have one eval run after the first checkpoint is saved). So basically there is no eval step during those 2h of training.

**Comment by mhtrinh** [comment] 2018-10-08 22:28
@YijinLiu : I applied your patch and it make the training process crash just after the first checkpoint saving:
```INFO:tensorflow:global_step/sec: 5.43315
INFO:tensorflow:loss = 0.48430496, step = 3040 (1.841 sec)
INFO:tensorflow:global_step/sec: 5.44665
INFO:tensorflow:loss = 0.6008992, step = 3050 (1.836 sec)
INFO:tensorflow:Saving checkpoints for 3060 into models/ssd_resnet50_v1_fpn.wholeCow.20181004.patch/model.ckpt.
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7ff03e1c03c8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7fefb3ee4470>>
Traceback (most recent call last):
[...]
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7fefb863fac8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
./startTraining.sh: line 50:  5651 Aborted                 (core dumped) python3 $tensorflowModel/object_detection/model_main.py --model_dir=$outDir --pipeline_config_path=$config
```
Same error happen if I resume training : it pick up at last checkpoint then train for a while until the first saving checkpoint and crash.

**Comment by mhtrinh** [comment] 2018-10-11 23:42
This issue may be a duplicate of #5296 : the memory leak do not happen with FasterRCNN in my case but only with SSD models.

**Comment by xxllp** [comment] 2018-12-29 07:46
I use fasterRCNN model but get killed !

**Comment by whatlas** [comment] 2019-01-30 02:41
training mobilenetv2-SSD models always get killed because of OOM on my PC, tf 1.9.0 from pip install.
