### ISSUE TITLE
ON syntaxnet test，the error ：Extension 'third_party_gpus_cuda_configure.bzl' has error

### ISSUE THREAD

**Issue by 18222278799** [tensorflow/models#3770] opened 2018-03-27 15:12 UTC
Dear Mr.or Mrs.
After i installed syntaxnet,i want to run the test. i have a error .i only use it with CPU,without GPU. I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this. 

ERROR:/home/zhang/.cache/bazel/_bazel_zhang/..../externel/org_tensorflow/third_party_gpus_cuda_configure.bzl:120:22: The function "set" has been removed in favor of "depset",please use the latter
ERROR:error loading package ' ':Extension 'third_party_gpus_cuda_configure.bzl' has error
ERROR:error loading package ' ':Extension 'third_party_gpus_cuda_configure.bzl' has error

FAILED:Build did not complete successfully
ERROR:counld't start the build. Unable to run tests

i want to know the reson.
thank you very much

**Comment by tensorflowbutler** [comment] 2018-04-25 06:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-09 22:01
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-12-05 21:38 UTC
Labels: stat:awaiting response
