### ISSUE TITLE
ImportError: cannot import name 'fpn_pb2' from 'object_detection.protos'

### ISSUE THREAD

**Issue by CaptainOrigami** [tensorflow/models#9891] opened 2021-04-12 02:03 UTC
I am trying to train a model using tensorflow 1.15 as I need to use the specific version for a project. When I try and run python train.py --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_quantized_300x300_coco.config --logtostderr in my virtual environment using Anaconda, I get this:

2021-04-11 21:49:12.966483: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 36, in <module>
    from object_detection.meta_architectures import context_rcnn_meta_arch
  File "C:\tensorflow1\models\research\object_detection\meta_architectures\context_rcnn_meta_arch.py", line 35, in <module>
    from object_detection.protos import faster_rcnn_pb2
  File "C:\tensorflow1\models\research\object_detection\protos\faster_rcnn_pb2.py", line 21, in <module>
    from object_detection.protos import fpn_pb2 as object__detection_dot_protos_dot_fpn__pb2
ImportError: cannot import name 'fpn_pb2' from 'object_detection.protos' (C:\tensorflow1\models\research\object_detection\protos\__init__.py)

I have been stuck trying to fix this issue for weeks and I have no clue on how to fix this.

**Comment by saikumarchalla** [comment] 2021-04-12 06:11
@CaptainOrigami  Could you please check this [link1](https://stackoverflow.com/questions/64853702/cannot-import-name-fpn-pb2-from-object-detection-protos#:~:text=2%20Answers&text=It%20is%20because%20there%20is,in%20the%20tutorial%20missed%20this.),[link2](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/501) and let us know if that helps.Thanks!

**Comment by CaptainOrigami** [comment] 2021-04-12 09:49
Hey, those helped, but I am getting a new issue when I run the Train.py: 

(tf13) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr -train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_quantized_300x300_coco.config
2021-04-12 05:40:52.785314: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From C:\Users\capta\AppData\Roaming\Python\Python37\site-packages\absl\app.py:251: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W0412 05:40:54.986522  4440 deprecation.py:323] From C:\Users\capta\AppData\Roaming\Python\Python37\site-packages\absl\app.py:251: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\legacy\trainer.py:265: create_global_step (from tf_slim.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W0412 05:40:54.996493  4440 deprecation.py:323] From C:\tensorflow1\models\research\object_detection\legacy\trainer.py:265: create_global_step (from tf_slim.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    tf.app.run()
  File "C:\Users\capta\.conda\envs\tf13\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\capta\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\capta\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\capta\.conda\envs\tf13\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 182, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 58, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 123, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 210, in build
    decoder = decoder_builder.build(input_reader_config)
  File "C:\tensorflow1\models\research\object_detection\builders\decoder_builder.py", line 64, in build
    load_keypoint_depth_features=input_reader_config
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 416, in __init__
    default_value=''),
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 89, in __init__
    label_map_proto_file, use_display_name=False)
  File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py", line 201, in get_label_map_dict
    label_map = load_labelmap(label_map_path_or_proto)
  File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py", line 168, in load_labelmap
    label_map_string = fid.read()
  File "C:\Users\capta\.conda\envs\tf13\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 122, in read
    self._preread_check()
  File "C:\Users\capta\.conda\envs\tf13\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:/tensorflow1/models/research/object_detection/training/labelmap.pbtxt : The system cannot find the file specified.
; No such file or directory

**Comment by saikumarchalla** [comment] 2021-04-14 05:41
@CaptainOrigami  Please make sure you  configure the path correctly and it resolve your query. Please check this [issue](#9870) as well.Thanks!

**Comment by saikumarchalla** [comment] 2021-04-14 06:26
@CaptainOrigami   Closing this issue as of now since the issue is resolved for you and i can see it here #9898.Thanks!

**Closed by saikumarchalla** 2021-04-14 06:26 UTC
Labels: models:research, stat:awaiting response, type:bug
