### ISSUE TITLE
Can i install tensorflow/models package with pip install?

### ISSUE THREAD

**Issue by yunjey** [tensorflow/models#917] opened 2017-01-18 06:59 UTC
tensorflow/models

I installed tensorflow through anaconda, and here I want to include the tensorflow/model.
Can i install tensorflow/models package with pip install?

I want to import the code as shown below.

import nets.inception_resnet_v2

**Comment by asimshankar** [comment] 2017-01-18 16:49
We do not yet, nor do we currently have any plans to, package tensorflow/models in a pip package. You'll have to clone the repository and/or copy-paste the code.

**Comment by tcwalther** [comment] 2017-11-15 10:27
I understand this issue is closed, but wanted to put this back on the radar. I believe that installing pre-trained models is a fair use case, and having the ability to run `pip install tensorflow-models` would be fantastic. Could you elaborate a bit more on the reasons for not considering a pip package for tensorflow/models?

**Comment by ashwinvijayakumar** [comment] 2018-02-21 18:28
21 votes not enough to reopen this issue, or at least provide a close justification?

**Comment by asimshankar** [comment] 2018-02-21 18:34
Apologies, this was closed more than a year ago (before TensorFlow 1.0, i.e., before API stability guarantees from main TensorFlow).

This may be worth revisiting now. 
@karmel - any thoughts?

**Comment by karmel** [comment] 2018-02-21 18:49
We have discussed this, and everyone agrees it is a good idea. Let's leave this open to track for now.

**Comment by viksit** [comment] 2018-04-22 21:31
@asimshankar @karmel it would also be useful to have `official.utils.logs import hooks_helper` and `official.utils.misc import model_helpers` as an installable package as well. There are very few examples out there of using them.

**Comment by bstreit** [comment] 2018-05-11 02:49
The amount of IT work involved in just getting official/wide_deep to run due to the use of official.utils is pretty ridiculous. Please either provide a write-up on how to get working easier or update the packages used within the py files.

**Comment by karmel** [comment] 2018-05-11 17:00
@bstreit -- please see the [Official Models README](https://github.com/tensorflow/models/tree/master/official#tensorflow-official-models) for instructions in setting up the Python path. If you have further issues with that, please open up a new issue, and we can help resolve.

**Comment by hadim** [comment] 2018-07-24 18:51
Could you also create a Pip installable package for the research repository?

**Comment by karmel** [comment] 2018-07-24 20:37
That's an interesting suggestion, but pip installation for /research is not planned. Each model is owned and maintained by the researchers in question, so providing tooling on top of all of those would be exceedingly hard to maintain.

**Comment by hadim** [comment] 2018-07-24 20:55
Actually, I was thinking about the object_detection folder. It would make it more easy and reproducible its usage. We should be able to easily pip install it instead of cloning the whole repository. What do you think?

**Comment by karmel** [comment] 2018-07-24 21:07
That would be under the purview of the researchers-- can you open a separate issue for that?

**Comment by hadim** [comment] 2018-07-24 21:35
Done https://github.com/tensorflow/models/issues/4887.

**Comment by PatrickLittlefield** [comment] 2018-09-10 10:36
Any progress on the pip installable update to object detection or (even better) all of the models?  Eagerly awaiting this.

**Comment by karmel** [comment] 2018-09-14 21:33
For the official models, we have not made any progress-- though if someone wants to pitch in, I'm marking this as Contributions Welcome. For object detection, please see #4887

**Comment by arshdefoamed** [comment] 2018-12-15 07:40
Hello, is there an update on this ?

**Comment by karmel** [comment] 2019-01-08 21:14
There are no current contributors who have picked this up, AFAIK. @lintian06 -- you may also be interested, as pip installation is an oft requested feature.

**Comment by lintian06** [comment] 2019-01-16 05:41
Thank you @karmel! I'll take a look at this. 

A general thought is that we need some sorts of design for different subfolders inside the project, since they may have different configurations and prerequisites.

**Comment by Sri-vatsa** [comment] 2019-03-02 06:46
Would be interested in contributing to making the package pip installable.

**Comment by wqnow** [comment] 2019-05-11 12:30
What a pity for two years waiting...

**Comment by saberkun** [comment] 2019-10-29 04:08
Working in progress. We have an initial package out for official models.

**Comment by saberkun** [comment] 2019-12-18 02:32
We plan to release an light pip package along with TF 2.1 release.

**Comment by AnuragAnalog** [comment] 2019-12-18 13:52
Yes, You can install it
pip install tensorflow          (for python2)
pip3 install tensorflow        (for python3)

**Comment by epignatelli** [comment] 2020-03-18 10:06
Where is the module actually being installed?
`import tensorflow.models` raise an error.

**Comment by chenGitHuber** [comment] 2020-03-18 21:06
> Where is the module actually being installed?
> `import tensorflow.models` raise an error.

Please install the nightly pip first: 
pip install tf-models-nightly

And then import in the following way for example:
from official.nlp.bert import ...

We may make the import easier in the future.

**Comment by saberkun** [comment] 2020-03-19 04:42
Thanks, Chen!

@jaeyounkim Shall we close this issue?

**Comment by jaeyounkim** [comment] 2020-03-19 04:54
Yes, we can close this issue.

**Closed by jaeyounkim** 2020-03-19 04:54 UTC
Labels: stat:contributions welcome, type:build/install, type:feature
