### ISSUE TITLE
[TFlite/Object Detection] TFlite Model outputting the same confidence value for every detected object 

### ISSUE THREAD

**Issue by normandra** [tensorflow/models#5217] opened 2018-08-31 12:07 UTC
### System information
- **What is the top-level directory of the model you are using**:
ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_18

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04

- **TensorFlow installed from (source or binary)**:
source

- **TensorFlow version (use command below)**:
1.8

- **Bazel version (if compiling from source)**:
0.16

- **CUDA/cuDNN version**:
n/a

- **GPU model and memory**:
n/a

- **Exact command to reproduce**:

```
object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path=$CONFIG_FILE \
--trained_checkpoint_prefix=$CHECKPOINT_PATH \
--output_directory=$OUTPUT_DIR \
--add_postprocessing_op=true
```

```
bazel run --config=opt tensorflow/contrib/lite/toco:toco -- \
--input_file=$OUTPUT_DIR/tflite_graph.pb \
--output_file=$OUTPUT_DIR/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops
```

### Describe the problem
Converted Model is outputting correct predictions but the confidence probability for every prediction is 89% (rounded) this value is exactly the same to the last decimal point. This makes it a little bit difficult to work with the outputted results. I've trained a different model with the same dataset (ssdlite_mobilenet_v2) with no such problem. The difference there is that the model is unquantized. Is this a behavior that is expected?

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:44
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:44 UTC
