### ISSUE TITLE
(locally trained) frozen_inference_graph.pb != (pre-trained) frozen_inference_graph.pb

### ISSUE THREAD

**Issue by dsimmo** [tensorflow/models#3874] opened 2018-04-04 14:11 UTC
I am attempting to retrain mobilenet ssd v1 from my own training procedure. My goal is to deploy this on a qualcomm snapdragon chip. The original (pretrained) model that is available from the model zoo can be easily deployed. However, if I retrain the model locally, I have issues with the deployment. I've been analysing the computational graphs using Tensorboard, and I can see that they aren't identical. Is this a bug?

Here is the exported graph for the locally trained model:
https://ibb.co/hBB0ux

Here is the exported graph for the pretrained model:
https://ibb.co/eVv4Mc

**Comment by dsimmo** [comment] 2018-04-05 15:45
I'm not sure what you mean. I don't do any customization of the training procedure. I simply train the Mobilenet ssd v1 using the latest version of the API. 

I've managed to rectify my qualcomm snapdragon deployment problem by using a former branch of the tensorflow/models repo (f7e99c0873c033832529f18e6596a4). After training (using the default training prcedure), this allows me to obtain an exported computational graph that is identical to the one obtained from the model zoo.

**Comment by karmel** [comment] 2018-04-05 15:54
Ah, yes, checkpoints and frozen graphs, for better or for worse, are very sensitive to changes in model definition. If updates have been made to the model, it is possible that the provided frozen graph was not updated to match. 

Tagging @tombstone as FYI, but closing, as it sounds like the issue is resolved. If there are further issues, please (re)open.

**Closed by karmel** 2018-04-05 15:54 UTC
Labels: stat:awaiting response
