### ISSUE TITLE
Object Detection | can not print loss in command line when training

### ISSUE THREAD

**Issue by 1icas** [tensorflow/models#5977] opened 2019-01-02 03:33 UTC
tensorflow version: 1.10.0
des: when i use the object detection program to train the coco dataset. I find that there isn't print any loss information in the command line. Only print the ap information in the command line for val dataset. Is this a problem?

**Comment by jvishnuvardhan** [comment] 2019-01-11 21:15
@1icas Could you provide more details about the issue and provide a code to reproduce the issue to find root-cause of the issue? Thank you

**Comment by jvishnuvardhan** [comment] 2019-06-10 22:03
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-06-10 22:03 UTC
Labels: stat:awaiting response, type:support
