### ISSUE TITLE
model_main.py

### ISSUE THREAD

**Issue by mihuzz** [tensorflow/models#6990] opened 2019-06-10 20:41 UTC
`I've gote problem when start training
sdk) D:\Lesson8\models\research\object_detection>python model_main.py --logtostderr--train_dir=training/--pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
File "model_main.py", line 26, in 
from object_detection import model_lib
File "D:\Lesson8\models\research\object_detection\model_lib.py", line 27, in 
from object_detection import eval_util
File "D:\Lesson8\models\research\object_detection\eval_util.py", line 28, in 
from object_detection.metrics import coco_evaluation
File "D:\Lesson8\models\research\object_detection\metrics\coco_evaluation.py", line 20, in 
from object_detection.metrics import coco_tools
File "D:\Lesson8\models\research\object_detection\metrics\coco_tools.py", line 47, in 
from pycocotools import coco
File "D:\Lesson8\models\research\pycocotools\coco.py", line 55, in 
from . import mask as maskUtils
File "D:\Lesson8\models\research\pycocotools\mask.py", line 3, in 
import pycocotools._mask as _mask
ModuleNotFoundError: No module named 'pycocotools._mask'``

**Comment by tensorflowbutler** [comment] 2019-06-11 12:18
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by renanwille** [comment] 2019-06-12 20:16
Did you follow the steps of https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md ?

**Comment by icmpnorequest** [comment] 2019-06-20 18:03
I followed the [object_detection/g3doc/installation.md](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#coco-api-installation) step by step to install CocoAPI/PythonAPI. 

For the CocoAPI installation, 
- First, I used `make` according to the installation.md, but it says ModuleNotFound Numpy. I indeed installed Numpy before. 
- Then, I tried tried `python3 setup.py build_ext --inplace` to `Make` under cocoapi/PythonAPI, and it doesn't show any errors.

OS: Ubuntu 18.04 LTS
Python Version = 3.6.8 (System Default Version)

However, When I run the command line: 
```
$ python object_detection/model_main.py --pipeline_config_path=pretrained/pipeline.config --model_dir=train --num_train_steps=1000 --sample_1_of_n_eval_examples=1 --alsologtostderr
```
It shows the error again.
```
Traceback (most recent call last):
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/home/yantong/PycharmProjects/PedestrianDetection/object_detection/model_lib.py", line 28, in <module>
    from object_detection import eval_util
  File "/home/yantong/PycharmProjects/PedestrianDetection/object_detection/eval_util.py", line 28, in <module>
    from object_detection.metrics import coco_evaluation
  File "/home/yantong/PycharmProjects/PedestrianDetection/object_detection/metrics/coco_evaluation.py", line 20, in <module>
    from object_detection.metrics import coco_tools
  File "/home/yantong/PycharmProjects/PedestrianDetection/object_detection/metrics/coco_tools.py", line 47, in <module>
    from pycocotools import coco
  File "/home/yantong/PycharmProjects/PedestrianDetection/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/yantong/PycharmProjects/PedestrianDetection/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ModuleNotFoundError: No module named 'pycocotools._mask'
```

Could somebody help me fix this issue? Thanks in advance.

**Comment by ymodak** [comment] 2019-07-20 20:35
Closing this issue since its resolved. Thanks!

**Closed by ymodak** 2019-07-20 20:35 UTC
Labels: models: official, stat:awaiting response
