### ISSUE TITLE
ssdlite_mobilenet_v2_coco android tflite error

### ISSUE THREAD

**Issue by ztwe** [tensorflow/models#5759] opened 2018-11-15 09:03 UTC
tensorflow version: 1.9
model: ssdlite_mobilenet_v2_coco_2018_05_09
tflite_export_tool:  object_detection/export_tflite_ssd_graph.py
tflite-library: 1.10.0/1.9.0

```
Caused by: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model
        at org.tensorflow.lite.NativeInterpreterWrapper.createModelWithBuffer(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:74)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:54)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:114)
```

**Comment by tensorflowbutler** [comment] 2018-11-16 00:18
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by duyanfang123** [comment] 2018-11-16 07:48
/home/luolu/tensorflow-master/tensorflow/lite/toco/BUILD:398:1: Linking of rule '//tensorflow/lite/toco:toco' failed (Exit 1) x86_64-conda_cos6-linux-gnu-cc failed: error executing command /home/luolu/anaconda2/envs/tensorflow/bin/x86_64-conda_cos6-linux-gnu-cc -o bazel-out/k8-fastbuild/bin/tensorflow/lite/toco/toco '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..,-rpath,$ORIGIN/../..' -pthread ... (remaining 8 argument(s) skipped)

pb生成tflite的时候报错，有谁知道原因吗

**Comment by tensorflowbutler** [comment] 2020-01-29 22:59
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:29
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:29 UTC
Labels: stat:awaiting response
