### ISSUE TITLE
Syntaxnet doesn't work with GPU support

### ISSUE THREAD

**Issue by zerodarkzone** [tensorflow/models#3171] opened 2018-01-15 15:31 UTC
### System information
-  OS Platform and Distribution: Linux Ubuntu 16.04
-  Syntaxnet built from source from the master branch
-  Bazel version: 0.5.4
-  CUDA/cuDNN version: 8.0 / 6
-  GPU model and memory: Nvidia GTX 1080TI / 12 GB:

### 
I have been trying to build syntaxnet with gpu support but the tests fail with CUDA_ERROR_OUT_OF_MEMORY. I've already tried all the fixes proposed in the other issues talking about the gpu support

### Source code / logs
[test.log](https://github.com/tensorflow/models/files/1632140/test.log)

**Comment by aselle** [comment] 2018-01-19 22:36
@calberti, could you please take a look?

**Comment by toli-belo** [comment] 2018-12-15 19:01
@zerodarkzone  - looks that another process is already using a large chunk of your GPU memory, run `nvidia-smi` to see the process ID.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:30
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 09:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 09:57 UTC
Labels: stat:awaiting tensorflower, type:support
