### ISSUE TITLE
The problem of  protos/ssd.proto

### ISSUE THREAD

**Issue by SubWayss** [tensorflow/models#4890] opened 2018-07-25 04:49 UTC
when I  protoc the files in protos,I found a question:
`object_detection/protos/ssd.proto:87:3: Expected "required", "optional", or "repeated".`
line 87 in ssd.proto, you should  comment out the line 
`reserved 6;`

**Comment by jackweiwang** [comment] 2018-07-25 13:00
Used protoc 3.0+

**Comment by robieta** [comment] 2018-08-07 22:48
What is the result of `protoc --version`? I ran into this issue with 2.6.1, and it was fixed when I upgraded to 3.6.1.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:15
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ravikyram** [comment] 2020-07-10 09:41
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-10 09:41 UTC
Labels: models:research, type:support
