### ISSUE TITLE
No pipeline.config file produced after train with my own data!

### ISSUE THREAD

**Issue by zychen2016** [tensorflow/models#6311] opened 2019-03-06 13:15 UTC
No pipeline.config file produced after train with my own data!

code
```
python model_main.py --pipeline_config_path=/data2/CZY/data/ssd/models/research/object_detection/ssd_model/ssd_mobilenet_v2_quantized_300x300_coco.config --model_dir=/data2/CZY/data/ssd/models/research/object_detection/ssd_model --num_train_steps=60000 --num_eval_steps=20 --alsologtostderr
```

After training, There model.ckpt file and graph.pbtxt，But no pipeline.config.

Because I want to use export_tflite_ssd_graph.py  to get tflite file.

It need pipeline.config, But No this file was produced.

**Comment by tensorflowbutler** [comment] 2019-03-07 12:19
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zychen2016** [comment] 2019-03-08 02:26
What is the top-level directory of the model you are using  Object_detection_api
Have I written custom code  No
OS Platform and Distribution Ubuntu 16.04
TensorFlow installed from pip install
TensorFlow version 1.10
Bazel version 0.15.0
CUDA/cuDNN version  9.0
GPU model and memory 1080Ti
Exact command to reproduce

**Comment by auslaner** [comment] 2019-03-08 22:35
`model_main.py` isn't meant to produce a pipeline.config file.

I haven't tried this myself but presumably you just need to provide the same pipeline.config file you used to train your model with. That would look something like this:

```bash
python object_detection/export_tflite_ssd_graph \
    --pipeline_config_path /data2/CZY/data/ssd/models/research/object_detection/ssd_model/ssd_mobilenet_v2_quantized_300x300_coco.config \
    --trained_checkpoint_prefix /data2/CZY/data/ssd/models/research/object_detection/ssd_model/model.ckpt-60000 \
    --output_directory path/to/exported_model_directory
```

**Comment by ymodak** [comment] 2019-03-22 21:13
Closing this issue since a workaround is provided. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2019-03-22 21:13 UTC
Labels: models: research, stat:awaiting response

**Comment by 12345k** [comment] 2019-07-23 13:02
Hi @ymodak ,
Can you share the pipeline.config for training in GPU? My custom model is running on CPU not in GPU. Any help will be appreciated

**Comment by zhyj3038** [comment] 2019-07-31 12:14
I met the same problem too!
