### ISSUE TITLE
parameter is not found in .ckpt, when i restore the checkpoint for resnet_V2 fine_tuning training

### ISSUE THREAD

**Issue by Zzmc** [tensorflow/models#2527] opened 2017-10-12 07:45 UTC
Hi,
  when i restore the checkpoint, there is error
`NotFoundError (see above for traceback): Tensor name "resnet_v2_50/block1/unit_1/bottleneck_v2/conv2/biases" not found in checkpoint files ./fine_tuning/resnet_v2_50.ckpt`
what's wrong with that？Could you give me some suggestions?

**Comment by reedwm** [comment] 2017-10-12 17:05
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by qweas120** [comment] 2017-12-11 05:00
This issue also happened to me. It seems that the following biases are missing in the checkpoint of **resnet_v2_50** downloaded from https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models.
'''
resnet_v2_50/block1/unit_1/bottleneck_v2/conv1/biases
resnet_v2_50/block1/unit_1/bottleneck_v2/conv2/biases
resnet_v2_50/block1/unit_2/bottleneck_v2/conv1/biases
resnet_v2_50/block1/unit_2/bottleneck_v2/conv2/biases
resnet_v2_50/block1/unit_3/bottleneck_v2/conv1/biases
resnet_v2_50/block1/unit_3/bottleneck_v2/conv2/biases
resnet_v2_50/block2/unit_1/bottleneck_v2/conv1/biases
resnet_v2_50/block2/unit_1/bottleneck_v2/conv2/biases
resnet_v2_50/block2/unit_2/bottleneck_v2/conv1/biases
resnet_v2_50/block2/unit_2/bottleneck_v2/conv2/biases
resnet_v2_50/block2/unit_3/bottleneck_v2/conv1/biases
resnet_v2_50/block2/unit_3/bottleneck_v2/conv2/biases
resnet_v2_50/block2/unit_4/bottleneck_v2/conv1/biases
resnet_v2_50/block2/unit_4/bottleneck_v2/conv2/biases
resnet_v2_50/block3/unit_1/bottleneck_v2/conv1/biases
resnet_v2_50/block3/unit_1/bottleneck_v2/conv2/biases
resnet_v2_50/block3/unit_2/bottleneck_v2/conv1/biases
resnet_v2_50/block3/unit_2/bottleneck_v2/conv2/biases
resnet_v2_50/block3/unit_3/bottleneck_v2/conv1/biases
resnet_v2_50/block3/unit_3/bottleneck_v2/conv2/biases
resnet_v2_50/block3/unit_4/bottleneck_v2/conv1/biases
resnet_v2_50/block3/unit_4/bottleneck_v2/conv2/biases
resnet_v2_50/block3/unit_5/bottleneck_v2/conv1/biases
resnet_v2_50/block3/unit_5/bottleneck_v2/conv2/biases
resnet_v2_50/block3/unit_6/bottleneck_v2/conv1/biases
resnet_v2_50/block3/unit_6/bottleneck_v2/conv2/biases
resnet_v2_50/block4/unit_1/bottleneck_v2/conv1/biases
resnet_v2_50/block4/unit_1/bottleneck_v2/conv2/biases
resnet_v2_50/block4/unit_2/bottleneck_v2/conv1/biases
resnet_v2_50/block4/unit_2/bottleneck_v2/conv2/biases
resnet_v2_50/block4/unit_3/bottleneck_v2/conv1/biases
resnet_v2_50/block4/unit_3/bottleneck_v2/conv2/biases
'''

**Comment by balconychy** [comment] 2017-12-21 10:36
encount same issue. you need to use proper scope.
`arg_scope = resnet_v2.resnet_arg_scope(weight_decay=self.WEIGHT_REGULIZER_W)
            with slim.arg_scope(arg_scope):
                return resnet_v2.resnet_v2_101(inputs=images,is_training=is_training,num_classes=self.CLASS_NUM)[0]`
ref https://github.com/tensorflow/tensorflow/issues/4249

**Comment by reedwm** [comment] 2017-12-21 18:31
/CC @sguada, can you look into why the biases are missing?

**Comment by daisysnow** [comment] 2018-01-30 08:59
@reedwm hi, I met the same issue, but I solved it by update my tensorflow from v1.1.0 to v1.2.0. 
 I think it is due to the different parameters' name in different version of TF, I use it like this way:

inputs_data = /your/data/
model_path = /your/path/of/checkpoint
with slim.arg_scope(resnet_v2.resnet_arg_scope(is_training=False)):
        resnet_v2.resnet_v2_152(inputs_data, 1001)
variables_to_restore = slim.get_variables_to_restore(include=["resnet_v2_152"])
init_fn = slim.assign_from_checkpoint_fn(model_path, variables_to_restore)
sess = tf.Session()
init_fn(sess)

I wish it helps

**Comment by reedwm** [comment] 2018-01-30 18:29
Thanks for the info @daisysnow. I'm closing this issue since it seems to be resolved, but please reopen if anyone still has this issue on 1.5.

**Closed by reedwm** 2018-01-30 18:29 UTC
Labels: stat:awaiting tensorflower

**Comment by calledbymountains** [comment] 2018-08-06 15:40
This isssue persists in TF 1.7 and TF1.9

**Comment by Cppowboy** [comment] 2018-11-30 16:17
> @reedwm hi, I met the same issue, but I solved it by update my tensorflow from v1.1.0 to v1.2.0.
> I think it is due to the different parameters' name in different version of TF, I use it like this way:
> 
> inputs_data = /your/data/
> model_path = /your/path/of/checkpoint
> with slim.arg_scope(resnet_v2.resnet_arg_scope(is_training=False)):
> resnet_v2.resnet_v2_152(inputs_data, 1001)
> variables_to_restore = slim.get_variables_to_restore(include=["resnet_v2_152"])
> init_fn = slim.assign_from_checkpoint_fn(model_path, variables_to_restore)
> sess = tf.Session()
> init_fn(sess)
> 
> I wish it helps

It works.
This line `with slim.arg_scope(resnet_v2.resnet_arg_scope(is_training=False)):` sets the bias_initializer to None, which won't create bias. The default bias_initializer of layer_lib.conv2d is zero initializer, which will create bias.
