### ISSUE TITLE
Attention OCR Freeze Graph Issue

### ISSUE THREAD

**Issue by kjanjua26** [tensorflow/models#1944] opened 2017-07-13 14:43 UTC
I am unable to find the input and output node names of attention ocr model for freezing the graph. Whatever I write in node name, it says "not in graph". 
Here is the screenshot of the error. 

![screen shot 2017-07-13 at 7 40 43 pm](https://user-images.githubusercontent.com/14023660/28171937-747cd6ca-6803-11e7-9cfc-2be15bbff716.png)

Any help?

**Comment by michaelisard** [comment] 2017-07-13 16:19
Could you give more information on how you created Attention_ocr.pb? It would really help if you filled out the requested information in the issue template. Thanks!

**Comment by kjanjua26** [comment] 2017-07-14 13:52
Sorry for missing out, I am new to this. I created the .pb file using the graph writer. I need to freeze it and for that I need output and input node names. The last and first layer name.

**Comment by michaelisard** [comment] 2017-07-14 17:24
It is difficult for us to figure out what the problem is without more detailed information about what version of the code you are using, etc., and what commands you typed to get you to this point. When you clicked on 'new issue' a template came up with a set of steps for you to follow to fill in that information. If you follow the steps in the template it will be easier for us to help you. Thanks!

**Comment by ahmed-nad** [comment] 2017-07-16 06:53
I was able to solve the problem, but a new one has appeared, i followed the tutorial described in the README file, So i edited the eval.py 
1) Created A place holder tf.placeHolder
2) Passed it model.create_base as input
3) Restored the session file through tf.Saver



![screen shot 2017-07-16 at 11 43 58 am](https://user-images.githubusercontent.com/24569196/28245260-33ad9b82-6a1c-11e7-98e4-3b8353dc627d.png)


The session was restored successfully and i was able to freeze the graph, but then i found out the model was giving the same values for any input i gave it? I am not able to pinpoint the exact problem that what is causing this behaviour

The layer names are
1) Input     : input_layer (Because i defined it myself)
2) Output : AttentionOcr_v1/predicted_chars

**Comment by fistix** [comment] 2017-09-08 09:33
when i do python train.py --checkpoint=model.ckpt-399731
Error:
Traceback (most recent call last):
File "train.py", line 30, in 
import common_flags
File "E:\Workplace\tensorflow\result\models-master\attention_ocr\python\common_flags.py", line 22, in 
import datasets
File "E:\Workplace\tensorflow\result\models-master\attention_ocr\python\datasets_init_.py", line 16, in 
import fsns
ImportError: No module named 'fsns

**Comment by kjanjua26** [comment] 2017-09-09 21:58
Did you clone the whole repository?
There is fsns.py file in the repository which is used during dataset import. Check if you have that in your files.

**Comment by aselle** [comment] 2017-09-20 17:55
@kjanjua26 , did you find any resolution to your problem yet?

**Comment by kjanjua26** [comment] 2017-09-21 07:36
@aselle, Yes, I did find the solution. 
The input layer name had to set, however, the output layer name was: AttentionOcr_v1/predicted_chars.

**Comment by aselle** [comment] 2017-10-03 16:55
I know this is of minimal value right now, but the long term solution to these problems is that we are going to move to SavedModel which declares inputs/outputs explicitly in the model, so you don't have to guess or probe at the names. Since this work is in progress, I am closing this issue. Thank you.

**Closed by aselle** 2017-10-03 16:55 UTC
Labels: type:feature

**Comment by Pro-xiaowen** [comment] 2019-09-06 08:38
> I was able to solve the problem, but a new one has appeared, i followed the tutorial described in the README file, So i edited the eval.py
> 
> 1. Created A place holder tf.placeHolder
> 2. Passed it model.create_base as input
> 3. Restored the session file through tf.Saver
> 
> ![screen shot 2017-07-16 at 11 43 58 am](https://user-images.githubusercontent.com/24569196/28245260-33ad9b82-6a1c-11e7-98e4-3b8353dc627d.png)
> 
> The session was restored successfully and i was able to freeze the graph, but then i found out the model was giving the same values for any input i gave it? I am not able to pinpoint the exact problem that what is causing this behaviour
> 
> The layer names are
> 
> 1. Input     : input_layer (Because i defined it myself)
> 2. Output : AttentionOcr_v1/predicted_chars

hi ahmed-nad, i am new to tensorflow, could you share your eval.py after your editing. 
thanks!
@ahmed-nad

**Comment by VasukiN** [comment] 2020-04-06 17:35
Can you please tell me where to add Input : input_layer (Because i defined it myself) in the AOCR model? Have tried multiple way but couldn't succeed.
