### ISSUE TITLE
Loading Resnet 50 pretrained model gives error

### ISSUE THREAD

**Issue by Sukanya-Kudi** [tensorflow/models#5257] opened 2018-09-06 08:51 UTC
### System information
- **What is the top-level directory of the model you are using**:  https://github.com/tensorflow/models/tree/master/official/resnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **TensorFlow installed from (source or binary)**: anaconda
- **TensorFlow version (use command below)**: 1.8.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

path='path to .pb file'
detection_graph=tf.Graph()
with detection_graph.as_default():
     od_graph_def=tf.GraphDef()
     with tf.gfile.GFile(path,'rb') as fid:
             serialized_graph=fid.read()
             od_graph_def.ParseFromString(serialized_graph)
             tf.import_graph_def(od_graph_def,name='')
sess = tf.Session(graph=detection_graph) 

The whole "20180601_resnet_v2_imagenet_savedmodel.tar" is 90.6 MB, but the pb is just 703KB.
The biggest file is : variables.data-00000-of-00001 of 97.7 MB.

The error thrown is :

---------------------------------------------------------------------------
DecodeError                               Traceback (most recent call last)
<ipython-input-12-23bb7554821d> in <module>()
      6      with tf.gfile.GFile(path,'rb') as fid:
      7              serialized_graph=fid.read()
----> 8              od_graph_def.ParseFromString(serialized_graph)
      9              tf.import_graph_def(od_graph_def,name='')
     10 sess = tf.Session(graph=detection_graph)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\message.py in ParseFromString(self, serialized)
    183     """
    184     self.Clear()
--> 185     self.MergeFromString(serialized)
    186 
    187   def SerializeToString(self, **kwargs):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in MergeFromString(self, serialized)
   1081     length = len(serialized)
   1082     try:
-> 1083       if self._InternalParse(serialized, 0, length) != length:
   1084         # The only reason _InternalParse would return early is if it
   1085         # encountered an end-group tag.

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in InternalParse(self, buffer, pos, end)
   1118         pos = new_pos
   1119       else:
-> 1120         pos = field_decoder(buffer, new_pos, end, self, field_dict)
   1121         if field_desc:
   1122           self._UpdateOneofState(field_desc)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in DecodeField(buffer, pos, end, message, field_dict)
    631         raise _DecodeError('Truncated message.')
    632       # Read sub-message.
--> 633       if value._InternalParse(buffer, pos, new_pos) != new_pos:
    634         # The only reason _InternalParse would return early is if it encountered
    635         # an end-group tag.

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in InternalParse(self, buffer, pos, end)
   1118         pos = new_pos
   1119       else:
-> 1120         pos = field_decoder(buffer, new_pos, end, self, field_dict)
   1121         if field_desc:
   1122           self._UpdateOneofState(field_desc)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in DecodeRepeatedField(buffer, pos, end, message, field_dict)
    610           raise _DecodeError('Truncated message.')
    611         # Read sub-message.
--> 612         if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
    613           # The only reason _InternalParse would return early is if it
    614           # encountered an end-group tag.

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in InternalParse(self, buffer, pos, end)
   1118         pos = new_pos
   1119       else:
-> 1120         pos = field_decoder(buffer, new_pos, end, self, field_dict)
   1121         if field_desc:
   1122           self._UpdateOneofState(field_desc)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in DecodeMap(buffer, pos, end, message, field_dict)
    741       # Read sub-message.
    742       submsg.Clear()
--> 743       if submsg._InternalParse(buffer, pos, new_pos) != new_pos:
    744         # The only reason _InternalParse would return early is if it
    745         # encountered an end-group tag.

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in InternalParse(self, buffer, pos, end)
   1107       if field_decoder is None:
   1108         value_start_pos = new_pos
-> 1109         new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
   1110         if new_pos == -1:
   1111           return pos

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in SkipField(buffer, pos, end, tag_bytes)
    848     # The wire type is always in the first byte since varints are little-endian.
    849     wire_type = ord(tag_bytes[0:1]) & wiretype_mask
--> 850     return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
    851 
    852   return SkipField

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in _SkipGroup(buffer, pos, end)
    797   while 1:
    798     (tag_bytes, pos) = ReadTag(buffer, pos)
--> 799     new_pos = SkipField(buffer, pos, end, tag_bytes)
    800     if new_pos == -1:
    801       return pos

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in SkipField(buffer, pos, end, tag_bytes)
    848     # The wire type is always in the first byte since varints are little-endian.
    849     wire_type = ord(tag_bytes[0:1]) & wiretype_mask
--> 850     return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
    851 
    852   return SkipField

~\AppData\Local\Continuum\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in _SkipFixed32(buffer, pos, end)
    812   pos += 4
    813   if pos > end:
--> 814     raise _DecodeError('Truncated message.')
    815   return pos
    816 

DecodeError: Truncated message.

What is the problem here.
Also is TF-Slim deprecated ? 
Why are there no pretrained models in TF itself.

**Comment by Sukanya-Kudi** [comment] 2018-09-20 10:00
Why is it that the response of the issue is delayed for so long.

**Comment by Drodman93** [comment] 2019-04-08 05:14
I'm also having this issue, anyone know a solution?

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:42 UTC
