### ISSUE TITLE
TypeError: predict() missing 1 required positional argument: 'true_image_shapes'

### ISSUE THREAD

**Issue by mona-abc** [tensorflow/models#3839] opened 2018-04-02 13:50 UTC
When I tried to export  the pb file from the trained model:ckpt files , I met this problem
the code i typed in are 

python object_detection/export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path object_detection/pbfile/faster_rcnn_resnet101_voc07.config \
    --trained_checkpoint_prefix object_detection/ckpt/tiny-yolo-voc-125 \
    --output_directory output_inference_graph.pb

and the errors are 

/home/cmm/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 147, in <module>
    tf.app.run()
  File "/home/cmm/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/export_inference_graph.py", line 143, in main
    FLAGS.output_directory, input_shape)
  File "/home/cmm/models-master/research/object_detection/exporter.py", line 397, in export_inference_graph
    input_shape, optimize_graph, output_collection_name)
  File "/home/cmm/models-master/research/object_detection/exporter.py", line 328, in _export_inference_graph
    output_tensors = detection_model.predict(preprocessed_inputs)
TypeError: predict() missing 1 required positional argument: 'true_image_shapes'
I really don't know the reason and I really want to figure it out , looking forward to your help.

**Comment by qlzh727** [comment] 2018-04-09 00:53
Closing this issue as working as intended. Feel free to reopen it if you still hit any issue.

**Closed by qlzh727** 2018-04-09 00:53 UTC
Labels: stat:awaiting response
