### ISSUE TITLE
SSD prediction

### ISSUE THREAD

**Issue by Sukanya-Kudi** [tensorflow/models#5237] opened 2018-09-04 01:45 UTC
Is there a way to know from which feature map an object is being detected in the SSD architecture.
Can this be done using the Session run on the pre-trained model.
PS: I am using MobileNet_v2 SSD for predictions, and I can also extract the image feature maps during Session Run, but I am interested in visualizing/extracting features  of an object from the feature map that  returns the highest confidence.

**Comment by tensorflowbutler** [comment] 2018-09-04 13:05
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Sukanya-Kudi** [comment] 2018-09-06 05:38
What is the top-level directory of the model you are using: https://github.com/tensorflow/models/tree/master/research/object_detection/models
Have I written custom code: NA
OS Platform and Distribution: Windows 10
TensorFlow installed from: anaconda
TensorFlow version: 1.8.0
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by Sukanya-Kudi** [comment] 2018-09-20 10:00
Why is it that resolution of the issue is being delayed for so long.

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:44
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:44 UTC
