### ISSUE TITLE
protobuf compilation issue in CPP

### ISSUE THREAD

**Issue by puneetsahu** [tensorflow/models#7420] opened 2019-08-09 09:08 UTC
i am getting below error while compiling the example cade. it is showing some issue in .h file.

/usr/local/include/google/protobuf/timestamp.pb.h:232:30: error: expected ‘}’ before end of line
/usr/local/include/google/protobuf/timestamp.pb.h:232:30: error: expected declaration before end of line
In file included from addressbook.pb.h:23:0,
                 from addressbook.pb.cc:4:
/usr/local/include/google/protobuf/io/coded_stream.h: In instantiation of ‘static google::protobuf::uint8* google::protobuf::io::EpsCopyOutputStream::UnsafeVarint(T, google::protobuf::uint8*) [with T = unsigned int; google::protobuf::uint8 = unsigned char]’:
/usr/local/include/google/protobuf/io/coded_stream.h:719:43:   required from here
/usr/local/include/google/protobuf/io/coded_stream.h:900:58: error: ‘static_assert’ was not declared in this scope
                   "Varint serialization must be unsigned");
                                                          ^
/usr/local/include/google/protobuf/io/coded_stream.h: In instantiation of ‘static google::protobuf::uint8* google::protobuf::io::EpsCopyOutputStream::UnsafeVarint(T, google::protobuf::uint8*) [with T = long unsigned int; google::protobuf::uint8 = unsigned char]’:
/usr/local/include/google/protobuf/io/coded_stream.h:1593:57:   required from here
/usr/local/include/google/protobuf/io/coded_stream.h:900:58: error: ‘static_assert’ was not declared in this scope
make: *** [add_person_cpp] Error 1

**Comment by tensorflowbutler** [comment] 2019-08-10 00:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-24 09:54
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-24 09:54 UTC
Labels: stat:awaiting response, type:support
