### ISSUE TITLE
Faster R-CNN change IoU threshold - nothing happens

### ISSUE THREAD

**Issue by HutzelFutzel** [tensorflow/models#4129] opened 2018-04-30 11:09 UTC
Hi, 
when I am changing the IoU threshold of the Faster-RNN network from 0.7 to 0.2 or 0.9, nothing happens to the AP or mAP. They are still exactly the same curves. 
I thought that this is the threshold at which an anchor is labeled positive or negative, isn't it? In my opinion the mAP should increase with a threshold of 0.2 instead of 0.7? Am I doing something wrong?

**Comment by tensorflowbutler** [comment] 2018-04-30 18:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by HutzelFutzel** [comment] 2018-05-02 13:33
I trained a new network with another value for the IoU threshold. The result was exactly the same.

**Comment by qlzh727** [comment] 2018-05-10 15:58
Assign to @jch1, who is one of the owner of object detection model.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:22
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:45 UTC
