### ISSUE TITLE
Detecting+Recognizing Text as an Image

### ISSUE THREAD

**Issue by aejaex** [tensorflow/models#5341] opened 2018-09-20 08:54 UTC
Tensorflow: Version 1.9.0
Python: 2.7.15
OS: Mac OSX High Sierra

I trained a Fast RCNN model using the object detection API to detect specific regions of text in an unstructured document. Basically, our institute receives over 2000 assignments every week, and my goal is to extract "Student Number" or "Student ID" from each of these assignments and save them to database. The position of said region within the document can be absolutely random.

I trained the Fast RCNN-Coco model using about ~200 images to detect "Student Number" within the document, using 1024x1024 input images where "Student Number" had been labeled using LabelImg in the Pascal format and all the xml files converted into tfRecords. I trained for 2000 steps and achieved a loss of lesser than 0.100.

However, my frozen model doesn't detect anything - it fails even on images it was trained on. 

Is this an inherent problem when training a model to detect text as an image? Or is it because documents are not natural images and their features vary from natural(Scene) images? Is this problem not solvable using transfer learning based upon one of the popular, conventional models (Fast RCNN)? If so, how would I go about solving this problem?

**Comment by tensorflowbutler** [comment] 2018-09-20 20:05
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aejaex** [comment] 2018-09-23 08:29
Top level directory: tensorflow/research/object_detection
No custom code written - Only the API used
Config file created for Fast-RCNN Coco: Input image set at 1024 x 1024
Tensorflow installed via pip
Version 1.9.0
No bazel, CUDA used

**Comment by tensorflowbutler** [comment] 2020-01-29 23:10
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:39 UTC
