### ISSUE TITLE
How to train MobileEdgeTPU DeepLab model on custom datasets

### ISSUE THREAD

**Issue by sramirez** [tensorflow/models#8631] opened 2020-06-05 10:43 UTC
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [X] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md#edgetpu-deeplab-models-on-cityscapes

## 2. Describe the issue

TF.__version__ == 1.15

I miss some doc about how to train properly MobileEdgeTPU model. I'm trying to train MobileEdgeTPU model on my own dataset. However, I've been facing several problems. Firstly, I've needed to add add_arg_scope decorator to those layers coming from out of tf.slim scope. Something like that:

```
@add_arg_scope
def expanded_conv(*args, **kwargs):
  return conv_blocks.expanded_conv(*args, **kwargs)
```

Afterwards, I got this error: 

  File "/tensorflow-1.15.2/python3.6/tensorflow_core/contrib/framework/python/ops/variables.py", line 690, in assign_from_checkpoint
    (ckpt_name, str(ckpt_value.shape), str(var.get_shape())))
ValueError: Total size of new array must be unchanged for concat_projection/weights lh_shape: [(1, 1, 512, 256)], rh_shape: [(1, 1, 1280, 256)]

I imagine I missed some parameter configuration here. Launched this command:

`python deeplab/train.py --logtostderr --training_number_of_steps=30000 --train_split="train" --atrous_rates=6 --atrous_rates=12 --atrous_rates=18 --output_stride=16 --train_crop_size="320,320" --train_batch_size=16 --dataset="macro" --tf_initial_checkpoint=X --train_logdir=X --dataset_dir=X --decoder_output_stride='' --aspp_convs_filters=256  --model_variant="mobilenet_edgetpu"`
 
Did I miss something?

**Comment by aquariusjay** [comment] 2020-06-05 22:17
Thanks for bringing up this issue, sramirez.

As mentioned in the [doc](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md), we do not use the ASPP module for mobilenet_edgetpu in the checkpoints. Therefore, you should not use the flags --atrous_rates.

Hope that helps.

Cheers,

**Comment by sramirez** [comment] 2020-06-08 10:54
Ok, thank you @aquariusjay.

After removing this flags:

python deeplab/train.py --logtostderr --training_number_of_steps=30000 --train_split="train" --train_crop_size="320,320" --train_batch_size=16 --dataset="macro" --tf_initial_checkpoint=X --train_logdir=X --dataset_dir=X --decoder_output_stride='' --aspp_convs_filters=256 --model_variant="mobilenet_edgetpu

I got the following error:

  File "/content/models/research/deeplab/utils/train_utils.py", line 221, in get_model_init_fn
    ignore_missing_vars=ignore_missing_vars)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/contrib/framework/python/ops/variables.py", line 690, in assign_from_checkpoint
    (ckpt_name, str(ckpt_value.shape), str(var.get_shape())))
ValueError: Total size of new array must be unchanged for logits/semantic/weights lh_shape: [(1, 1, 256, 19)], rh_shape: [(1, 1, 256, 2)]

I tried with crop_size equal to 256 pixels, but I think no problem there. I will investigate a little further.

**Comment by aquariusjay** [comment] 2020-06-08 19:15
Hi sramirez,

The issue is caused by initializing from the Cityscapes-pretrained checkpoint (which has 19 classes in the last layer).

Could you please try
--initialize_last_layer=false
--last_layers_contain_logits_only=true (false should work too; but some extra modules will be trained from scratch).

Hope that helps.

Cheers,

**Comment by sramirez** [comment] 2020-06-11 14:23
Ok, thanks @aquariusjay

**Comment by kyscg** [comment] 2020-06-18 23:30
Closing this as the issue seems to have been resolved!

**Closed by kyscg** 2020-06-18 23:30 UTC
Labels: models:research, type:docs

**Comment by pranavgundewar** [comment] 2021-02-09 01:01
@sramirez where did you exactly add the @add_arg_scope function?

I am also trying to train MobileEdgeTPU on the custom dataset. Thanks for the help.

**Comment by javierrodenas** [comment] 2021-06-25 09:12
> Hi sramirez,
> 
> The issue is caused by initializing from the Cityscapes-pretrained checkpoint (which has 19 classes in the last layer).
> 
> Could you please try
> --initialize_last_layer=false
> --last_layers_contain_logits_only=true (false should work too; but some extra modules will be trained from scratch).
> 
> Hope that helps.
> 
> Cheers,

It worked for me, 

Thanks
