### ISSUE TITLE
Object detection: PR-Curves in Tensorboard

### ISSUE THREAD

**Issue by blaskowitz100** [tensorflow/models#3081] opened 2017-12-29 14:45 UTC
Hello,
is  it planned to plot PR-Curves as separate summaries in Tensorboard? When not, this would be a nice feature :)

**Comment by bignamehyp** [comment] 2017-12-31 08:49
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by foreverYoungGitHub** [comment] 2018-01-17 15:41
Currently, I'm trying to figure out this problem.

I found that in `./utils/object_detection_evaluation.py` has already calculated the PR value by the `compute_precision_recall` function in `./utils/metrics.py`. 

The detail of how to evaluate the detector is contained in Class`ObjectDetectionEvaluation` and Func`evaluate()`. It returns the pr curve to the interface class `ObjectDetectionEvaluator` Func `evaluate()`. So if you do not need the TP,FP values, Func `evaluate()` can be change like this:

#### `./utils/object_detection_evaluation.py` class `ObjectDetectionEvaluator` Func `evaluate()`
```
  def evaluate(self):
    """Compute evaluation result.

    Returns:
      A dictionary of metrics with the following fields -

      1. summary_metrics:
        'Precision/mAP@<matching_iou_threshold>IOU': mean average precision at
        the specified IOU threshold.

      2. per_category_ap: category specific results with keys of the form
        'PerformanceByCategory/mAP@<matching_iou_threshold>IOU/category'.
    """
    (per_class_ap, mean_ap, precisions_per_class, recalls_per_class, per_class_corloc, mean_corloc) = (
        self._evaluation.evaluate())
    pascal_metrics = {
        self._metric_prefix +
        'Precision/mAP@{}IOU'.format(self._matching_iou_threshold):
            mean_ap
    }
    pr_value = {}
    if self._evaluate_corlocs:
      pascal_metrics[self._metric_prefix + 'Precision/meanCorLoc@{}IOU'.format(
          self._matching_iou_threshold)] = mean_corloc
    category_index = label_map_util.create_category_index(self._categories)
    for idx in range(per_class_ap.size):
      if idx + self._label_id_offset in category_index:
        display_name = (
            self._metric_prefix + 'PerformanceByCategory/AP@{}IOU/{}'.format(
                self._matching_iou_threshold,
                category_index[idx + self._label_id_offset]['name']))
        pascal_metrics[display_name] = per_class_ap[idx]


        # PR curve
        display_name = (
            'PR_curve@{}'.format(category_index[idx + self._label_id_offset]['name']))
        pr_value[display_name] = {'precisions': precisions_per_class[idx], 'recalls': recalls_per_class[idx]}

        # Optionally add CorLoc metrics.classes
        if self._evaluate_corlocs:
          display_name = (
              self._metric_prefix + 'PerformanceByCategory/CorLoc@{}IOU/{}'
              .format(self._matching_iou_threshold,
                      category_index[idx + self._label_id_offset]['name']))
          pascal_metrics[display_name] = per_class_corloc[idx]

    return pascal_metrics, pr_value
```
Notice that the `precisions_per_class` and `recalls_per_class` returns the pr value per class. And we return all the PR_value with in a new object `pr_value`.

Then we change the interface of func `_run_checkpoint_once` and func `repeated_checkpoint_run` in `./eval_util.py` as following:
#### `./eval_util.py` func `_run_checkpoint_once`
```
for evaluator in evaluators:
        #metrics = evaluator.evaluate()
        metrics, pr_value = evaluator.evaluate()
```
....
```
#return (global_step, all_evaluator_metrics)
return (global_step, all_evaluator_metrics, pr_value)
```
 #### `./eval_util.py` func `repeated_checkpoint_run`
```
        # global_step, metrics = _run_checkpoint_once_change(tensor_dict, evaluators,
        #                                             batch_processor,
        #                                             last_evaluated_model_path,
        #                                             variables_to_restore,
        #                                             None, num_batches,
        #                                             master, save_graph,
        #                                             save_graph_dir)
        global_step, metrics, pr_value = _run_checkpoint_once_change(tensor_dict, evaluators,
                                                    batch_processor,
                                                    last_evaluated_model_path,
                                                    variables_to_restore,
                                                    None, num_batches,
                                                    master, save_graph,
                                                    save_graph_dir)
```

Then, add a function `write_metrics()` in file `./eval_util.py` to write the pr_curve.

#### `./eval_util.py` func `write_pr_curve()`
```
def write_pr_curve(pr_value, global_step, summary_dir):
  """Write pr_curve to a summary directory.

  Args:
    pr_value: A dictionary containing pr_value names and values.
    global_step: Global step at which the pr_value are computed.
    summary_dir: Directory to write tensorflow summaries to.
  """
  logging.info('Writing pr_value to tf summary.')
  summary_writer = tf.summary.FileWriter(summary_dir)

  for key in sorted(pr_value):
    summary = summary_lib.pr_curve_raw_data_pb(
      name=key,
      true_positive_counts=pr_value[key]['tp'],
      false_positive_counts=pr_value[key]['fp'],
      true_negative_counts=-np.ones(len(pr_value[key]['tp'])),
      false_negative_counts=-np.ones(len(pr_value[key]['tp'])),
      precision=pr_value[key]['precisions'],
      recall=pr_value[key]['recalls'],
      num_thresholds=len(pr_value[key]['tp'])
      )
    summary_writer.add_summary(summary, global_step)
    logging.info('%s: %f', key, pr_value[key])
  summary_writer.close()
  summary_writer.close()
  logging.info('PR curve written to tf summary.')
```
and use this function in func `repeated_checkpoint_run`
 #### `./eval_util.py` func `repeated_checkpoint_run`
```
write_pr_curve(pr_value, global_step, summary_dir)
```
The re-run the eval.py, you can get some result like this:
![screenshot from 2018-01-17 10-38-07](https://user-images.githubusercontent.com/14891753/35051212-b7564b0e-fb72-11e7-8721-7c1879c6054b.png)

Cheers,

Let me know if there are some bugs.

**Comment by forvd** [comment] 2018-01-18 08:57
Hi,@foreverYoungGitHub. I got an error: NameError: name 'summary_lib' is not defined in ./eval_util.py func write_pr_curve(). Seem like you forgot some of your codes.

**Comment by foreverYoungGitHub** [comment] 2018-01-18 15:18
@forvd,  Yes, you are right, I forget to mention that, it needs to import tensorboard to make the pr curve works fine, which is mentioned in [PR curve](https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/pr_curve).

So, in this case, you need to add `from tensorboard import summary as summary_lib
` in the beginning of `./eval_util.py`.

Besides, the tensorboard should be the newest one to make the pr_curve function work.

If it is necessary, I could make a pull request for this function.

**Comment by zeynali** [comment] 2018-02-22 13:14
Hi ,
i faced with this error : 

INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
Traceback (most recent call last):
  File "eval.py", line 142, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "eval.py", line 138, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/home/mm/models/research/object_detection/evaluator.py", line 240, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/home/mm/models/research/object_detection/eval_util.py", line 448, in repeated_checkpoint_run
    return metrics
UnboundLocalError: local variable 'metrics' referenced before assignment

**Comment by foreverYoungGitHub** [comment] 2018-02-22 23:35
@zeynali, This is caused by the `metrics` is not define first.

If in repeated_checkpoint_run it should be defined as following:

```
global_step, metrics, pr_value = _run_checkpoint_once_change(tensor_dict, evaluators,
                                                    batch_processor,
                                                    last_evaluated_model_path,
                                                    variables_to_restore,
                                                    None, num_batches,
                                                    master, save_graph,
                                                    save_graph_dir)
```

**Comment by zeynali** [comment] 2018-02-23 07:51
again got error

**Comment by tanndx17** [comment] 2018-03-07 12:10
@foreverYoungGitHub I got error in object_detection_evalution.py:
  File "/data/detection/research/object_detection/utils/object_detection_evaluation.py", line 288, in evaluate
    pr_value[display_name] = {'precisions':precisions_per_class[idx],'recalls':recalls_per_class[idx]}

I followed all your changes but I got this error. Did I miss anything?

**Comment by ywpkwon** [comment] 2018-04-30 07:53
@foreverYoungGitHub Thanks for the useful codes.

I have a question in your code
```
    # the pr_curve_raw_data_pb() needs the a ascending precisions array and a descending recalls array
    pr_value[key]['precisions'].sort() 
    pr_value[key]['recalls'][::-1].sort()
```
I think the correct PR curve shouldn't have the artificial sorting. Is it just because `pr_curve_raw_data_pb` requires certain constraint? Why the function has such artificial constraint?

**Comment by austinmw** [comment] 2018-05-23 16:38
@foreverYoungGitHub Hi, after following your instructions I'm getting the error:
 `File "/home/neuro/.local/lib/python3.5/site-packages/tensorflow/models/research/object_detection/eval_util.py", line 65, in write_metrics
    pr_value[key]['precisions'] = np.append(pr_value[key]['precisions'][::gap], pr_value[key]['precisions'][-1])
TypeError: slice indices must be integers or None or have an __index__ method`

Could you please  tell me how to fix this?

**Comment by bsaendig** [comment] 2018-07-18 13:35
Thank you for the instructions but I am getting an error.
Any suggestions?
> WARNING:root:The following classes have no ground truth examples: [12 26 29 30 45 60 66 68 69 71 80 83 89]
/tensorflow-models/research/object_detection/utils/metrics.py:144: RuntimeWarning: invalid value encountered in true_divide
  num_images_correctly_detected_per_class / num_gt_imgs_per_class)
Traceback (most recent call last):
  File "/tensorflow-models/research/object_detection/eval.py", line 136, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/tensorflow-models/research/object_detection/eval.py", line 132, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/tensorflow-models/research/object_detection/evaluator.py", line 212, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/tensorflow-models/research/object_detection/eval_util.py", line 417, in repeated_checkpoint_run
    save_graph_dir)
  File "/tensorflow-models/research/object_detection/eval_util.py", line 309, in _run_checkpoint_once
    metrics, pr_value = evaluator.evaluate()
  File "/tensorflow-models/research/object_detection/utils/object_detection_evaluation.py", line 251, in evaluate
    pr_value[display_name] = {'precisions': precisions_per_class[idx], 'recalls': recalls_per_class[idx]}
IndexError: list index out of range

**Comment by YNVoon** [comment] 2018-08-02 08:54
@bsaendig I faced the same error as well, I have downgraded my numpy to version 1.11.0, and it works fine now.

**Comment by dongsheng20170812** [comment] 2018-09-12 06:03
Hi @foreverYoungGitHub, do you know how could we get the mapped value by tensorboard or coding?

**Comment by anacej** [comment] 2018-10-01 14:58
hi, I'm using Tensorflow object detection new API, I've implemented your code and I don't get any errors. But when I run Tensorboard, I don't get any PR curve data recognized. Is this maybe incompatible with the new API?
thanks

**Comment by anacej** [comment] 2018-10-15 11:50
any suggestions how to do that?

**Comment by alokranjan007** [comment] 2018-11-27 13:33
@foreverYoungGitHub Hello, 
Thank you for sharing your solution. I tried your steps and made necessary changes in the scripts. In fact, I  used the pulled request (git hub) scripts for the evaluation. But the tensorboard is not showing any PR curve tab like the scalar and others. When tried to select from the drop down list then it is saying that "No precision Recall data was found" and do not show the tab what you have shown for the PR curve.

Could you please help me to understand the problem.

Thank you

**Comment by austinmw** [comment] 2019-02-11 19:54
@alokranjan007 I have not tried this in quite a while, but it's possible the posted workaround is incompatible with your version of tensorflow

**Comment by ruksin** [comment] 2019-03-22 08:32
when following the above instructions I got the TP = -1 TN= -1,FP=-1 , AND FN = -1.
whether this is correct?? I don't know much about these as I'm just a beginner.

**Comment by drisyack** [comment] 2019-04-03 10:15
@foreverYoungGitHub Thank you for sharing your solution. I  made necessary changes. the executed without error and tensorboard is appeared. But the tensorboard is not showing any PR curve tab like the scalar and others. When tried to select from the drop down list then it is saying that "No precision Recall data was found" and do not show the tab what you have shown for the PR curve.

Could you please please help me to understand the problem.

Thank you

**Comment by aysark** [comment] 2019-04-09 19:50
Yeah, the PR that @foreverYoungGitHub was not merged and now doesn't work with latest code it seems.

**Comment by austinmw** [comment] 2019-04-10 03:11
Yup I tried it too and couldn't get it to work even after making some obvious fixes.

**Comment by Rakiba291** [comment] 2019-04-26 23:44
> @foreverYoungGitHub Hi, after following your instructions I got the error:
> `File "/home/neuro/.local/lib/python3.5/site-packages/tensorflow/models/research/object_detection/eval_util.py", line 65, in write_metrics pr_value[key]['precisions'] = np.append(pr_value[key]['precisions'][::gap], pr_value[key]['precisions'][-1]) TypeError: slice indices must be integers or None or have an __index__ method`
> 
> it looks like `gap` can be a floating point which causes type error for slice indices. I wrapped int() around gap and can successfully see PR curves in tensorboard. Thanks!
> 
> Any idea how I can additionally get curves for true positive and false negative rates?

@austinmw Hi! can you just share how you got the PR curves in tensorboard?  how did you solve the problem of the one you mentioned? is it   **pr_value[key]['precisions'] = np.append(pr_value[key]['precisions'][::int(gap)], pr_value[key]['precisions'][-1])** ?
I tried to plot by matplotlib in object_detection_evaluation.py after compute.metrics(precision, recall) but I saw no graph plots. I have tried looking for all possible solutions but I could not plot the graphs. So, if you could help to know , would be grateful to you. The tensorflow version I am using in v1.12 with 3.6 python interpreter. Thanks!

**Comment by baronpalacios** [comment] 2019-08-18 17:30
@foreverYoungGitHub hi brot, thank you for given that solution, it worked for me.
In  other hand do you  know how to get Precision-Recall curves  at various IoU thresholds?

**Comment by hanifjunos** [comment] 2019-09-02 10:33
@baronpalacios how did you able to run the eval. I get an issue of:
metrics, pr_value = evaluator.evaluate()
ValueError: too many values to unpack (expected 2)

**Comment by WANGSHUAISWU** [comment] 2019-10-23 09:04
@hanifjunos Hi, I meet the same problem with you. Have you solved it? Could you please give me some advice?

**Comment by hanifjunos** [comment] 2019-10-30 06:54
> @hanifjunos Hi, I meet the same problem with you. Have you solved it? Could you please give me some advice?

I still couldn't solved it.

**Comment by hanifjunos** [comment] 2019-12-25 02:20
@WANGSHUAISWU have u solved this issue?



> @baronpalacios how did you able to run the eval. I get an issue of:
> metrics, pr_value = evaluator.evaluate()
> ValueError: too many values to unpack (expected 2)

**Comment by zychen2016** [comment] 2020-01-13 02:51
Any update?

**Comment by jhonjam** [comment] 2020-04-16 12:54
> @baronpalacios, ¿cómo pudo ejecutar la evaluación? Tengo un problema de:
> metrics, pr_value = evaluator.evaluate ()
> ValueError: demasiados valores para desempaquetar (esperado 2)

hello i have the same problem, you could solve it. Help MEEE

**Comment by BeautyMess** [comment] 2020-05-08 07:17
@hanifjunos @WANGSHUAISWU @jhonjam 
Please check whether you are using COCO metrics in the config file like metrics_set: 'coco_detection_metrics'.
I think the function provided here only supports the pascal metrics.

**Comment by twkim-xiilab** [comment] 2020-05-20 10:08
I want to run this function in model_main.py.
anybody can tell me the process?? then I will be able to customize that.
how can I try like @foreverYoungGitHub ??
otherwise,  somebody can tell me which python file runs that process??
help me please

**Comment by tw0226** [comment] 2020-05-20 10:09
I want to run this function in model_main.py.
anybody can tell me the process?? then I will be able to customize that.
how can I try like @foreverYoungGitHub ??
otherwise, somebody can tell me which python file runs that process??
help me please

**Comment by aguspray001** [comment] 2020-06-04 04:57
> when following the above instructions I got the TP = -1 TN= -1,FP=-1 , AND FN = -1.
> whether this is correct?? I don't know much about these as I'm just a beginner.

do you found the solving?

**Comment by weenkiejinky** [comment] 2020-09-17 10:24
C:\Users\Admin\Anaconda3\envs\tf_gpu\notebook\models\research\object_detection\utils\object_detection_evaluation.py:1195: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
Traceback (most recent call last):
  File "research/object_detection/eval.py", line 142, in <module>
    tf.app.run()
  File "C:\Users\Admin\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\Admin\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "research/object_detection/eval.py", line 138, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\Users\Admin\Anaconda3\envs\tf_gpu\notebook\models\research\object_detection\legacy\evaluator.py", line 296, in evaluate
    eval_export_path=eval_config.export_path)
  File "C:\Users\Admin\Anaconda3\envs\tf_gpu\notebook\models\research\object_detection\eval_util.py", line 536, in repeated_checkpoint_run
    write_metrics(metrics=metrics, pr_value=pr_value, global_step=global_step, summary_dir=summary_dir)
  File "C:\Users\Admin\Anaconda3\envs\tf_gpu\notebook\models\research\object_detection\eval_util.py", line 80, in write_metrics
    logging.info('Writing metrics to tf summary.')
NameError: name 'logging' is not defined


...I followed also the steps but this is the error

**Closed** 2020-09-25 20:41 UTC
Labels: models:research, stalled, stat:awaiting response, type:support

**Comment by diego0718** [comment] 2020-10-10 17:31
Hi all,

    metrics, pr_value = evaluator.evaluate()
ValueError: too many values to unpack (expected 2)

i try to get rid of of this problem. 

  def evaluate(self):
    """Compute evaluation result.

    Returns:
      A dictionary of metrics with the following fields -

      1. summary_metrics:
        'Precision/mAP@<matching_iou_threshold>IOU': mean average precision at
        the specified IOU threshold.

      2. per_category_ap: category specific results with keys of the form
        'PerformanceByCategory/mAP@<matching_iou_threshold>IOU/category'.
    """
    print("Entre a evaluate")
    (per_class_ap, mean_ap, precisions_per_class, recalls_per_class, per_class_corloc, mean_corloc) = (
        self._evaluation.evaluate())
    pascal_metrics = {
        self._metric_prefix +
        'Precision/mAP@{}IOU'.format(self._matching_iou_threshold):
            mean_ap
    }
    pr_value = {}
    if self._evaluate_corlocs:
      pascal_metrics[self._metric_prefix + 'Precision/meanCorLoc@{}IOU'.format(
          self._matching_iou_threshold)] = mean_corloc
    category_index = label_map_util.create_category_index(self._categories)
    for idx in range(per_class_ap.size):
      if idx + self._label_id_offset in category_index:
        display_name = (
            self._metric_prefix + 'PerformanceByCategory/AP@{}IOU/{}'.format(
                self._matching_iou_threshold,
                category_index[idx + self._label_id_offset]['name']))
        pascal_metrics[display_name] = per_class_ap[idx]


        # PR curve
        display_name = (
            'PR_curve@{}'.format(category_index[idx + self._label_id_offset]['name']))
        pr_value[display_name] = {'precisions': precisions_per_class[idx], 'recalls': recalls_per_class[idx]}

        # Optionally add CorLoc metrics.classes
        if self._evaluate_corlocs:
          display_name = (
              self._metric_prefix + 'PerformanceByCategory/CorLoc@{}IOU/{}'
              .format(self._matching_iou_threshold,
                      category_index[idx + self._label_id_offset]['name']))
          pascal_metrics[display_name] = per_class_corloc[idx]

    return pascal_metrics, pr_value

what i am doing wrong?

**Comment by Andres-San** [comment] 2023-06-23 21:40
For anyone struggling with this, please check: 

https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/pr_curve
