### ISSUE TITLE
Tensorflow object detection using Google Satellite

### ISSUE THREAD

**Issue by teffanymae** [tensorflow/models#7622] opened 2019-10-02 18:05 UTC
I am currently working a project entitled Tree Crown Quantification and Delineation through Remote Sensing Technique. So, basically the system can count and identify the tree and it's type.

My question is, is it possible to directly use the Google Map (Satellite Image Link) to test the system?

What I currently did is just take screenshots of the Google map image manually and used it to test the system.

**Comment by tensorflowbutler** [comment] 2019-10-03 12:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-21 15:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-21 15:49 UTC
Labels: stat:awaiting response, type:support
