### ISSUE TITLE
when i export pb file ,encounter error 

### ISSUE THREAD

**Issue by huangqingjun111111** [tensorflow/models#3053] opened 2017-12-25 08:36 UTC
when i want to export pb fie .I encounter an error, the follow is the log.Is there anyone can help me.thanks.
  File "object_detection/export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 129, in run
    _sys.exit(main(argv))
  File "object_detection/export_inference_graph.py", line 115, in main
    FLAGS.output_directory, input_shape)
  File "/home/coolpad/source/models/research/object_detection/exporter.py", line 427, in export_inference_graph
    input_shape, optimize_graph, output_collection_name)
  File "/home/coolpad/source/models/research/object_detection/exporter.py", line 391, in _export_inference_graph
    initializer_nodes='')
  File "/home/coolpad/source/models/research/object_detection/exporter.py", line 72, in freeze_graph_with_def_protos
    optimize_tensor_layout=True)
ValueError: Protocol message RewriterConfig has no "optimize_tensor_layout" field.

**Comment by bignamehyp** [comment] 2017-12-26 06:49
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by bjwimpey** [comment] 2017-12-29 18:56
Last line of huangqingjun111111's log:
'ValueError: Protocol message RewriterConfig has no "optimize_tensor_layout" field.'

Appears to be a duplicate of this issue https://github.com/tensorflow/models/issues/2861

**Comment by dakshvar22** [comment] 2018-01-04 12:00
Change the parameter on line 71 to `layout_optimizer=1` . Made a PR - [#3106](https://github.com/tensorflow/models/pull/3106)

**Comment by Curreno** [comment] 2018-01-11 19:52
This did not work for me, I've tried changing to layout_optimizer=1 on line 71 yet it throws the same error.
I've also tried with the standard value for the parameter with no success. Any tips?

**Comment by ymodak** [comment] 2018-10-31 21:18
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-31 21:18 UTC
Labels: stat:awaiting response
