### ISSUE TITLE
Using syntaxnet

### ISSUE THREAD

**Issue by link-er** [tensorflow/models#549] opened 2016-10-17 08:26 UTC
Hello! 
@calberti, @andorardo, I am trying to run syntaxnet but getting error on exmple command from README:

```
(syntaxnet) linara@linara:~/Documents/models/syntaxnet$ echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh
Traceback (most recent call last):
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/conll2tree.runfiles/__main__/syntaxnet/conll2tree.py", line 21, in <module>
    import tensorflow as tf
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/conll2tree.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/conll2tree.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/conll2tree.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/conll2tree.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/linara/anaconda2/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/conll2tree.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so)
Traceback (most recent call last):
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 23, in <module>
    import tensorflow as tf
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
Traceback (most recent call last):
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/__main__/syntaxnet/parser_eval.py", line 23, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    import tensorflow as tf
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError:     from tensorflow.python import *
/home/linara/anaconda2/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so)  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>

    from tensorflow.python import pywrap_tensorflow
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/linara/anaconda2/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/linara/Documents/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so)
```
Might it be that I have maybe wrong version of GCC? 
I installed everything according to instructions and ran tests, but had 6 failures, but not sure that these errors are connected:

```
//syntaxnet:beam_reader_ops_test                                         FAILED in 0.4s
  /home/linara/.cache/bazel/_bazel_linara/73257c033625ae0d4f393c0cb3d95bf3/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 0.4s
  /home/linara/.cache/bazel/_bazel_linara/73257c033625ae0d4f393c0cb3d95bf3/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 0.5s
  /home/linara/.cache/bazel/_bazel_linara/73257c033625ae0d4f393c0cb3d95bf3/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 0.5s
  /home/linara/.cache/bazel/_bazel_linara/73257c033625ae0d4f393c0cb3d95bf3/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 0.3s
  /home/linara/.cache/bazel/_bazel_linara/73257c033625ae0d4f393c0cb3d95bf3/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 0.5s
  /home/linara/.cache/bazel/_bazel_linara/73257c033625ae0d4f393c0cb3d95bf3/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log
```
According to stackoverflow I should edit my LD_LIBRARY_PATH, but even after adding the lib path the error is still there
Thanks a lot in advance!

**Comment by asimshankar** [comment] 2016-10-18 03:51
Closing this as a duplicate of tensorflow/tensorflow#5017 - that one has more detail.

**Closed by asimshankar** 2016-10-18 03:51 UTC
