### ISSUE TITLE
export savedmodel for AWS sagemaker inference endpoint 

### ISSUE THREAD

**Issue by GL-RuiLa** [tensorflow/models#5675] opened 2018-11-03 00:50 UTC
### System information
- **What is the top-level directory of the model you are using**:
    object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
    No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    Windows 10
- **TensorFlow installed from (source or binary)**:
    source
- **TensorFlow version (use command below)**:
     b'v1.11.0-rc2-4-gc19e29306c' 1.11.0
- **Bazel version (if compiling from source)**:
    
- **CUDA/cuDNN version**:
    cuda 8.0
- **GPU model and memory**:
    GRX 1060 
- **Exact command to reproduce**:
python object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path object_detection/models/model/rfcn_resnet101_pedestrain.config --checkpoint_path object_detection/models/model/train/model.ckpt-573563 --inference_graph_path object_detection/models/model/pedestrain --export_as_saved_model=True
You can collect some of this information using our environment capture script:

### Describe the problem
I want to use od-API to train my model but do data inference on AWS SageMaker. The SM bring your own model platform gave a example of export inference graph from estimator using export_savedmodel() function and generate saved_model which can be used on AWS sagemaker. 
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/tensorflow_iris_byom/tensorflow_BYOM_iris.ipynb

I know od-API doesn't export_savedmodel() function to easily export serving graph but the output generated by above command also has a saved_model folder which has a similar structure. I also followed this thread below 

https://github.com/tensorflow/models/issues/1988

to generate saved_model wieh non-empty variables directory which has exactly same structure as SageMaker required (including variables.data-00000-of-00001 and variables.index files). But the deployment is failed. I am wondering if there is anyone who has experience in tensorflow od-API and AWS sagemaker could help me with that. Thanks.

**Comment by tensorflowbutler** [comment] 2020-01-29 22:59
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:31
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:31 UTC
