### ISSUE TITLE
Nasnet-A medium performance issue

### ISSUE THREAD

**Issue by hetaoaoao** [tensorflow/models#2787] opened 2017-11-14 02:33 UTC
As described in nasnet paper, nasnet medium(7@1920) should has comparable runtime performance with inception-v3 (close params number & FLOPS), but when I try it on single GTX1080Ti, given the 299x299 input, inception-v3 runs at ~40 samples/sec, where nasnet medium runs at ~18 samples/sec.

Here's my config file for nasnet medium
def _medium_imagenet_config(is_training=True):
    drop_path_keep_prob = 1.0 if not is_training else 0.7
    return tf.contrib.training.HParams(
        stem_multiplier=3.0,
        dense_dropout_keep_prob=0.5,
        num_cells=21,
        filter_scaling_rate=2.0,
        num_conv_filters=80,
        drop_path_keep_prob=drop_path_keep_prob,
        use_aux_head=1,
        num_reduction_layers=2,
        data_format='NCHW',
        skip_reduction_layer_input=1,
        total_training_steps=450000,
    )`

Maybe it's due to nasnet complex structure or my medium config is wrong? Possible ways to improve?
Since the nas medium speed/accuracy is really sweet.

**Comment by cy89** [comment] 2017-11-16 01:54
This looks like a duplicate of #2763. If you don't mind, please CC yourself there, and I'll close this issue in favor of that one.

**Comment by hetaoaoao** [comment] 2017-11-16 02:30
@cy89 no, it's not a duplicate actually. My experiments are based on models/research/slim without any code change except that I added the nasnet medium config. I didn't see any performance differences when running on one gpu or more.

My issue is, does nasnet-a medium really beat inception-v3? Therically speaking, they run at comparable cost (4.93B vs 5.72B according to https://arxiv.org/pdf/1707.07012.pdf),  but they behave very different on real machines (v3 runs 2 times faster then nasnet medium). So, I'm wondering if it's possible to make nasnet medium run as fast as inception v3 by improving implementation? Or I just made a big mistake on the medium config file because it's not provided yet in offical repo.

**Comment by cy89** [comment] 2017-11-18 23:29
I don't think this is quite the right forum for a discussion of relative performance of the different models; have you also asked on StackOverflow?

**Comment by hetaoaoao** [comment] 2017-11-26 06:55
Oh, I'll try to do it on StackOverlow. Pls close it ;-)

**Comment by cy89** [comment] 2017-11-28 23:54
Thanks, @hetaoaoao. Good luck!

**Closed by cy89** 2017-11-28 23:54 UTC
Labels: stat:awaiting response

**Comment by michaelmunie** [comment] 2018-01-22 17:15
@hetaoaoao , would you mind adding the link to your stackoverflow question here?

**Comment by muayyad-alsadi** [comment] 2018-01-26 00:37
I add than nasnet mobile is much slower than inception v1 on CPU too.

https://stackoverflow.com/questions/47215223/why-is-nasnet-model-so-slow-using-one-gpu
