### ISSUE TITLE
Perceiver IO: byte-level pretraining

### ISSUE THREAD

**Issue by stefan-it** [tensorflow/models#11050] opened 2023-07-18 18:46 UTC
Hi,

many thanks for providing an additional implementation of Perceiver IO for NLP.

I would like to ask, if you could also provide a configuration/experiment setup that allows to pretrain byte-level Perceiver IO models, as it was proposed in the original paper. This would be a great contribution and would further boot research on token-free models: e.g. CANINE pretraining code is not released, charformer code is kind of experimental, the only token-free model that is possible to pretrain without hassle is ByT5.

Many thanks in advance!

**Comment by laxmareddyp** [comment] 2023-08-28 21:37
Hi @saberkun @Chen-Zhe ,

Could you please check this in your free time.

Thanks

**Comment by saberkun** [comment] 2023-08-28 23:14
We do not reproduce the token free pre-training experiment so we don't have recipe to open source.
Sorry. We also don't know if there is any checkpoint to convert.
We will mark this issue as closed since no additional work is planned for perceiver io modeling features.

**Comment by laxmareddyp** [comment] 2023-08-29 04:50
Thanks @saberkun. Closing this issue as not planned.

**Closed by laxmareddyp** 2023-08-29 04:50 UTC
Labels: stat:awaiting model gardener, type:feature, models:official
