### ISSUE TITLE
TF2 Object Detect API with CenterNet Resnet101 V1 FPN 512x512 

### ISSUE THREAD

**Issue by mm7721** [tensorflow/models#8967] opened 2020-07-25 16:32 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [Y] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [Y] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the bug

Training on a custom dataset using CenterNet Resnet101 V1 FPN 512x512 model has issues.  The checkpoint and pipeline.config were downloaded from the zoo and slightly modified to suit the custom dataset (e.g. number of classes changed).  The outcome depends on the fine_tune_checkpoint_type setting in the pipeline.config file:

fine_tune_checkpoint: "centernet_resnet101_v1_fpn_512x512_coco17_tpu-8/checkpoint/ckpt-0

i. fine_tune_checkpoint_type: "fine_tune"
   -runs successfully

ii. fine_tune_checkpoint_type: "detection"
   -fails with the following error:

File "tf2odapi/models/research/object_detection/meta_architectures/center_net_meta_arch.py", line 2769, in restore_from_objects
    return {'feature_extractor': self._feature_extractor.get_model()}
AttributeError: 'CenterNetResnetV1FpnFeatureExtractor' object has no attribute 'get_model'

iii. fine_tune_checkpoint_type: "classification"
   -gives a long string of warning saying it can't resolve model objects, then stops without giving an error:

...
WARNING:tensorflow:Unresolved object in checkpoint: (root).model._prediction_head_dict.box/offset.0.layer_with_weights-1.kernel
W0725 09:28:17.464377 140311093167936 util.py:143] Unresolved object in checkpoint: (root).model._prediction_head_dict.box/offset.0.layer_with_weights-1.kernel
WARNING:tensorflow:Unresolved object in checkpoint: (root).model._prediction_head_dict.box/offset.0.layer_with_weights-1.bias
W0725 09:28:17.464425 140311093167936 util.py:143] Unresolved object in checkpoint: (root).model._prediction_head_dict.box/offset.0.layer_with_weights-1.bias
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
W0725 09:28:17.464480 140311093167936 util.py:151] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.

## 3. Steps to reproduce

Involves a custom dataset, so it can't be replicated here.

## 4. Expected behavior

Training should run smoothly for all three settings of fine_tune_checkpoint_type.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device name if the issue happens on a mobile device: 
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1, 7.6.5
- GPU model and memory: GE Force RTX 2080 11GB

**Comment by vighneshbirodkar** [comment] 2020-07-28 14:22
This is a duplicate of #8915 . The ResNet feature extractor only supports "classification" type checkpoints. The patch to output a better error message should go out soon. Until we can upload the classification backbones, you can train from scratch or use the hourglass backbone.

**Comment by mm7721** [comment] 2020-07-28 14:36
@vighneshbirodkar, thanks for the explanation.  Before this issue is closed, could you explain what's meant by the three fine tune training types: classification, detection, fine_tune?

**Comment by vighneshbirodkar** [comment] 2020-07-28 14:43
1. classification - The backbone was pre trained on a classification task. Supported by all the ResNet style backbones
2. detection - The backbone was trained on a detection task. Currently supported by Hourglass style backbones.
3 fine_tune - The backbone comes from an existing detection model. In this case you can point to a checkpoint that was created using the OD API training script. It is useful when you want to use a pre-trained OD model and fine tune on a dataset. For this setting you can use any of the checkpoints from TF2 model zoo.

**Comment by mm7721** [comment] 2020-07-28 15:03
Thanks, that's helpful.  Is there any way to tell in advance which category(ies) the TF2 model zoo checkpoints fall under?  It sounds like all of them should work with "fine_tune", some with "detection", and none with "classification" (currently).  Your list above is helpful, but there seem to be some exceptions.  For example, I got efficientdet and mobilenetv2 models to run with "detection" (and I'm assuming they'd also work with "fine_tune").

Also, is there any difference in which parameters are frozen/trained for the three cases?

**Comment by vighneshbirodkar** [comment] 2020-07-28 15:12
My list was only limited to CenterNet. For Centernet we have a patch rolling out soon with better error messages. The most reliable source of truth however, is the `restore_from_objects` method in the meta architecture. I think in all cases with an unsupported checkpoint type, you should see some error.

**Comment by mm7721** [comment] 2020-07-28 15:22
Ok, understood.  Thanks.  And could you answer the final question "is there any difference in which parameters are frozen/trained for the three cases?"  Then we can definitely close this issue :)

**Comment by vighneshbirodkar** [comment] 2020-07-28 15:32
For detection and fine_tune, all except the final prediction layers are restored. The difference is just that dict mapping names to weights is different to support the different kinds of checkpoints we have. For classification, in most cases, the deconv/upsamling part of the network is not restored.

**Comment by vighneshbirodkar** [comment] 2020-07-28 17:16
I also just realized that we have this script that lets you create ResNet based classification checkpoints compatible with CenterNet
https://github.com/tensorflow/models/blob/master/research/object_detection/models/keras_models/convert_keras_models.py

**Comment by mm7721** [comment] 2020-07-29 16:54
Thanks, I'll check it out.

**Closed** 2020-08-03 16:31 UTC
Labels: models:research, type:bug

**Comment by aabbas90** [comment] 2020-08-11 11:55
> This is a duplicate of #8915 . The ResNet feature extractor only supports "classification" type checkpoints. The patch to output a better error message should go out soon. Until we can upload the classification backbones, you can train from scratch or use the hourglass backbone.

I have tried setting  `fine_tune_checkpoint_type: "fine_tune"`, but get the following error:

> ValueError: Sub model fine_tune is not defined for Hourglass.Supported types are ['detection'].
