### ISSUE TITLE
Extra bounding boxes in tensorboard visualisation

### ISSUE THREAD

**Issue by mocialov** [tensorflow/models#9480] opened 2020-11-18 09:06 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ x ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ x ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

## 2. Describe the bug

After evaluating the model, visualisation examples in Tensorboard show many more unnecessary bounding boxes that are not present in the TFRecord file for the ground truth

see:
https://imgur.com/a/vueRKd5

## 3. Steps to reproduce

Generate TFRecord files, train to get a checkpoint, evaluate the checkpoint, look at the image visualisations in tensorboard

## 4. Expected behavior

Expect less bounding boxes

## 5. Additional context

N/A
see https://imgur.com/a/vueRKd5

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device name if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by ravikyram** [comment] 2020-11-18 09:13
@mocialov 

Can you please provide colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by mocialov** [comment] 2020-11-18 09:17
Cannot share the files

**Comment by mocialov** [comment] 2020-11-18 09:32
When I look inside the TFRecord file after it is created, I see at most 2 bounding boxes per image, so I do not think it is a problem with the TFRecord file

```
import tensorflow as tf
import json
from google.protobuf.json_format import MessageToJson
import base64

a_dict = {}

dataset = tf.data.TFRecordDataset("/content/models/research/test.record")
for d in dataset:
    ex = tf.train.Example()
    ex.ParseFromString(d.numpy())
    m = json.loads(MessageToJson(ex))
    if base64.b64decode(m['features']['feature']['image/filename']['bytesList']['value'][0]) not in a_dict:
        a_dict[base64.b64decode(m['features']['feature']['image/filename']['bytesList']['value'][0])] = []
    a_dict[base64.b64decode(m['features']['feature']['image/filename']['bytesList']['value'][0])].append(m['features']['feature']['image/object/bbox/ymin']['floatList']['value'])
    #print(base64.b64decode(m['features']['feature']['image/filename']['bytesList']['value'][0]), m['features']['feature']['image/object/bbox/ymin']['floatList']['value'])

for item in a_dict:
    print (item, a_dict[item])
```

```
b'Overflate_kamera_resized/crack_overflatekamera000214.jpg' [[0.1046875, 0.0703125]]
b'Overflate_kamera_resized/crack_overflatekamera000735.jpg' [[0.128125]]
b'Overflate_kamera_resized/crack_overflatekamera00065.jpg' [[0.465625]]
b'Overflate_kamera_resized/crack_overflatekamera000385.jpg' [[0.075]]
b'Overflate_kamera_resized/crack_overflatekamera000767.jpg' [[0.3140625]]
b'Overflate_kamera_resized/crack_overflatekamera000179.jpg' [[0.0765625]]
b'Overflate_kamera_resized/crack_overflatekamera000645.jpg' [[0.521875]]
b'Overflate_kamera_resized/crack_overflatekamera000844.jpg' [[0.0609375]]
b'Overflate_kamera_resized/crack_overflatekamera000869.jpg' [[0.6234375]]
b'Overflate_kamera_resized/crack_overflatekamera00029.jpg' [[0.3359375]]
b'Overflate_kamera_resized/crack_overflatekamera000272.jpg' [[0.2078125]]
b'Overflate_kamera_resized/crack_overflatekamera000323.jpg' [[0.1390625]]
b'Overflate_kamera_resized/crack_overflatekamera000624.jpg' [[0.04375]]
b'Overflate_kamera_resized/crack_overflatekamera000463.jpg' [[0.3890625]]
b'Overflate_kamera_resized/crack_overflatekamera000274.jpg' [[0.16875]]
b'Overflate_kamera_resized/crack_overflatekamera000804.jpg' [[0.065625]]
b'Overflate_kamera_resized/crack_overflatekamera000121.jpg' [[0.2125]]
b'Overflate_kamera_resized/crack_overflatekamera000156.jpg' [[0.015625]]
b'Overflate_kamera_resized/crack_overflatekamera000142.jpg' [[0.071875]]
b'Overflate_kamera_resized/crack_overflatekamera000378.jpg' [[0.0109375]]
b'Overflate_kamera_resized/crack_overflatekamera000810.jpg' [[0.0359375]]
b'Overflate_kamera_resized/crack_overflatekamera00019.jpg' [[0.484375]]
b'Overflate_kamera_resized/crack_overflatekamera000193.jpg' [[0.0734375]]
b'Overflate_kamera_resized/crack_overflatekamera000446.jpg' [[0.0359375]]
b'Overflate_kamera_resized/crack_overflatekamera000674.jpg' [[0.571875]]
b'Overflate_kamera_resized/crack_overflatekamera000763.jpg' [[0.0234375]]
b'Overflate_kamera_resized/crack_overflatekamera00017.jpg' [[0.1078125]]
b'Overflate_kamera_resized/crack_overflatekamera000704.jpg' [[0.1375]]
b'Overflate_kamera_resized/crack_overflatekamera000431.jpg' [[0.2125]]
b'Overflate_kamera_resized/crack_overflatekamera000250.jpg' [[0.1953125]]
b'Overflate_kamera_resized/crack_overflatekamera000649.jpg' [[0.21875]]
b'Overflate_kamera_resized/crack_overflatekamera000181.jpg' [[0.071875]]
b'Overflate_kamera_resized/crack_overflatekamera00077.jpg' [[0.2671875]]
b'Overflate_kamera_resized/crack_overflatekamera000690.jpg' [[0.5609375]]
b'Overflate_kamera_resized/crack_overflatekamera000943.jpg' [[0.059375]]
b'Overflate_kamera_resized/crack_overflatekamera000183.jpg' [[0.21875]]
b'Overflate_kamera_resized/crack_overflatekamera00081.jpg' [[0.4828125, 0.0953125]]
b'Overflate_kamera_resized/crack_overflatekamera000819.jpg' [[0.0890625]]
b'Overflate_kamera_resized/crack_overflatekamera000755.jpg' [[0.459375]]
b'Overflate_kamera_resized/crack_overflatekamera000245.jpg' [[0.2828125]]
b'Overflate_kamera_resized/crack_overflatekamera0003.jpg' [[0.7375]]
b'Overflate_kamera_resized/crack_overflatekamera00010.jpg' [[0.128125]]
b'Overflate_kamera_resized/crack_overflatekamera000937.jpg' [[0.371875]]
b'Overflate_kamera_resized/crack_overflatekamera00018.jpg' [[0.0734375]]
b'Overflate_kamera_resized/crack_overflatekamera000555.jpg' [[0.0]]
b'Overflate_kamera_resized/crack_overflatekamera000200.jpg' [[0.190625]]
b'Overflate_kamera_resized/crack_overflatekamera000471.jpg' [[0.1015625]]
b'Overflate_kamera_resized/crack_overflatekamera00071.jpg' [[0.4171875]]
b'Overflate_kamera_resized/crack_overflatekamera000756.jpg' [[0.1703125]]
b'Overflate_kamera_resized/crack_overflatekamera000441.jpg' [[0.0828125]]
b'Overflate_kamera_resized/crack_overflatekamera000260.jpg' [[0.0921875]]
b'Overflate_kamera_resized/crack_overflatekamera000367.jpg' [[0.175, 0.1484375]]
b'Overflate_kamera_resized/crack_overflatekamera000946.jpg' [[0.13125]]
b'Overflate_kamera_resized/crack_overflatekamera000257.jpg' [[0.4203125]]
b'Overflate_kamera_resized/crack_overflatekamera000933.jpg' [[0.1609375]]
b'Overflate_kamera_resized/crack_overflatekamera000321.jpg' [[0.0828125, 0.015625]]
b'Overflate_kamera_resized/crack_overflatekamera000468.jpg' [[0.159375]]
b'Overflate_kamera_resized/crack_overflatekamera000871.jpg' [[0.4625]]
b'Overflate_kamera_resized/crack_overflatekamera000333.jpg' [[0.3953125, 0.7046875]]
b'Overflate_kamera_resized/crack_overflatekamera000902.jpg' [[0.0375]]
b'Overflate_kamera_resized/crack_overflatekamera000579.jpg' [[0.21875]]
b'Overflate_kamera_resized/crack_overflatekamera000248.jpg' [[0.0234375]]
b'Overflate_kamera_resized/crack_overflatekamera000896.jpg' [[0.3109375]]
b'Overflate_kamera_resized/crack_overflatekamera000492.jpg' [[0.1109375]]
b'Overflate_kamera_resized/crack_overflatekamera000233.jpg' [[0.3859375]]
b'Overflate_kamera_resized/crack_overflatekamera00035.jpg' [[0.340625]]
b'Overflate_kamera_resized/crack_overflatekamera000212.jpg' [[0.0609375]]
b'Overflate_kamera_resized/crack_overflatekamera00072.jpg' [[0.4875]]
b'Overflate_kamera_resized/crack_overflatekamera0001.jpg' [[0.1578125]]
b'Overflate_kamera_resized/crack_overflatekamera000842.jpg' [[0.071875]]
b'Overflate_kamera_resized/crack_overflatekamera000130.jpg' [[0.503125]]
b'Overflate_kamera_resized/crack_overflatekamera000408.jpg' [[0.0703125]]
b'Overflate_kamera_resized/crack_overflatekamera000377.jpg' [[0.0359375]]
b'Overflate_kamera_resized/crack_overflatekamera000570.jpg' [[0.2015625]]
b'Overflate_kamera_resized/crack_overflatekamera000195.jpg' [[0.040625]]
b'Overflate_kamera_resized/crack_overflatekamera000839.jpg' [[0.0921875]]
b'Overflate_kamera_resized/crack_overflatekamera000478.jpg' [[0.0390625]]
b'Overflate_kamera_resized/crack_overflatekamera000242.jpg' [[0.1765625]]
b'Overflate_kamera_resized/crack_overflatekamera000762.jpg' [[0.01875]]
b'Overflate_kamera_resized/crack_overflatekamera000631.jpg' [[0.28125]]
b'Overflate_kamera_resized/crack_overflatekamera000314.jpg' [[0.2765625]]
b'Overflate_kamera_resized/crack_overflatekamera000776.jpg' [[0.05625]]
b'Overflate_kamera_resized/crack_overflatekamera00011.jpg' [[0.278125]]
b'Overflate_kamera_resized/crack_overflatekamera000727.jpg' [[0.5234375]]
b'Overflate_kamera_resized/crack_overflatekamera000416.jpg' [[0.315625]]
b'Overflate_kamera_resized/crack_overflatekamera00066.jpg' [[0.2671875]]
b'Overflate_kamera_resized/crack_overflatekamera000477.jpg' [[0.33125]]
b'Overflate_kamera_resized/crack_overflatekamera000629.jpg' [[0.353125, 0.2234375]]
b'Overflate_kamera_resized/crack_overflatekamera00039.jpg' [[0.521875]]
b'Overflate_kamera_resized/crack_overflatekamera000681.jpg' [[0.6703125]]
b'Overflate_kamera_resized/crack_overflatekamera000936.jpg' [[0.075]]
b'Overflate_kamera_resized/crack_overflatekamera000825.jpg' [[0.1765625]]
b'Overflate_kamera_resized/crack_overflatekamera000165.jpg' [[0.15625]]
b'Overflate_kamera_resized/crack_overflatekamera000345.jpg' [[0.0578125]]
b'Overflate_kamera_resized/crack_overflatekamera000380.jpg' [[0.0609375]]
b'Overflate_kamera_resized/crack_overflatekamera000171.jpg' [[0.1453125]]
b'Overflate_kamera_resized/crack_overflatekamera000862.jpg' [[0.15625]]
b'Overflate_kamera_resized/crack_overflatekamera000660.jpg' [[0.0671875]]
b'Overflate_kamera_resized/crack_overflatekamera000356.jpg' [[0.428125]]
b'Overflate_kamera_resized/crack_overflatekamera000723.jpg' [[0.0078125]]
b'Overflate_kamera_resized/crack_overflatekamera000218.jpg' [[0.2859375]]
b'Overflate_kamera_resized/crack_overflatekamera000247.jpg' [[0.3203125]]
b'Overflate_kamera_resized/crack_overflatekamera000794.jpg' [[0.21875]]
b'Overflate_kamera_resized/crack_overflatekamera000807.jpg' [[0.1203125]]
b'Overflate_kamera_resized/crack_overflatekamera000207.jpg' [[0.09375]]
b'Overflate_kamera_resized/crack_overflatekamera000300.jpg' [[0.640625]]
b'Overflate_kamera_resized/crack_overflatekamera000683.jpg' [[0.30625]]
b'Overflate_kamera_resized/crack_overflatekamera000659.jpg' [[0.2296875]]
b'Overflate_kamera_resized/crack_overflatekamera000549.jpg' [[0.2625]]
b'Overflate_kamera_resized/crack_overflatekamera000479.jpg' [[0.2234375]]
b'Overflate_kamera_resized/crack_overflatekamera000100.jpg' [[0.35]]
b'Overflate_kamera_resized/crack_overflatekamera000414.jpg' [[0.21875]]
b'Overflate_kamera_resized/crack_overflatekamera000339.jpg' [[0.1796875, 0.465625]]
b'Overflate_kamera_resized/crack_overflatekamera000672.jpg' [[0.15]]
b'Overflate_kamera_resized/crack_overflatekamera000322.jpg' [[0.1453125]]
b'Overflate_kamera_resized/crack_overflatekamera000145.jpg' [[0.2015625]]
b'Overflate_kamera_resized/crack_overflatekamera00069.jpg' [[0.0484375]]
b'Overflate_kamera_resized/crack_overflatekamera000210.jpg' [[0.5078125]]
b'Overflate_kamera_resized/crack_overflatekamera0009.jpg' [[0.646875, 0.303125]]
b'Overflate_kamera_resized/crack_overflatekamera000131.jpg' [[0.6328125]]
b'Overflate_kamera_resized/crack_overflatekamera000351.jpg' [[0.20625]]
b'Overflate_kamera_resized/crack_overflatekamera000303.jpg' [[0.328125, 0.64375, 0.14375]]
b'Overflate_kamera_resized/crack_overflatekamera000386.jpg' [[0.0796875]]
b'Overflate_kamera_resized/crack_overflatekamera00027.jpg' [[0.26875]]
b'Overflate_kamera_resized/crack_overflatekamera000724.jpg' [[0.259375, 0.05]]
b'Overflate_kamera_resized/crack_overflatekamera000853.jpg' [[0.5234375]]
b'Overflate_kamera_resized/crack_overflatekamera000185.jpg' [[0.159375]]
b'Overflate_kamera_resized/crack_overflatekamera000859.jpg' [[0.2515625]]
b'Overflate_kamera_resized/crack_overflatekamera000705.jpg' [[0.0265625]]
b'Overflate_kamera_resized/crack_overflatekamera000458.jpg' [[0.325]]
b'Overflate_kamera_resized/crack_overflatekamera000106.jpg' [[0.515625]]
b'Overflate_kamera_resized/crack_overflatekamera000108.jpg' [[0.1046875]]
b'Overflate_kamera_resized/crack_overflatekamera00052.jpg' [[0.2828125]]
b'Overflate_kamera_resized/crack_overflatekamera000347.jpg' [[0.43125]]
b'Overflate_kamera_resized/crack_overflatekamera000679.jpg' [[0.2921875]]
b'Overflate_kamera_resized/crack_overflatekamera000489.jpg' [[0.015625]]
b'Overflate_kamera_resized/crack_overflatekamera000290.jpg' [[0.05]]
b'Overflate_kamera_resized/crack_overflatekamera000637.jpg' [[0.0203125]]
b'Overflate_kamera_resized/crack_overflatekamera00028.jpg' [[0.54375]]
b'Overflate_kamera_resized/crack_overflatekamera000866.jpg' [[0.1]]
b'Overflate_kamera_resized/crack_overflatekamera00064.jpg' [[0.21875]]
b'Overflate_kamera_resized/crack_overflatekamera000364.jpg' [[0.459375]]
b'Overflate_kamera_resized/crack_overflatekamera00055.jpg' [[0.3078125]]
b'Overflate_kamera_resized/crack_overflatekamera000731.jpg' [[0.23125]]
b'Overflate_kamera_resized/crack_overflatekamera000739.jpg' [[0.3703125]]
b'Overflate_kamera_resized/crack_overflatekamera000299.jpg' [[0.3125]]
b'Overflate_kamera_resized/crack_overflatekamera00047.jpg' [[0.6578125]]
b'Overflate_kamera_resized/crack_overflatekamera000493.jpg' [[0.1859375]]
b'Overflate_kamera_resized/crack_overflatekamera000737.jpg' [[0.4140625]]
b'Overflate_kamera_resized/crack_overflatekamera000426.jpg' [[0.346875]]
b'Overflate_kamera_resized/crack_overflatekamera00079.jpg' [[0.3984375]]
b'Overflate_kamera_resized/crack_overflatekamera000496.jpg' [[0.5359375]]
b'Overflate_kamera_resized/crack_overflatekamera000483.jpg' [[0.0671875]]
b'Overflate_kamera_resized/crack_overflatekamera00033.jpg' [[0.1375]]
b'Overflate_kamera_resized/crack_overflatekamera000667.jpg' [[0.1046875]]
b'Overflate_kamera_resized/crack_overflatekamera000706.jpg' [[0.21875]]
b'Overflate_kamera_resized/crack_overflatekamera000224.jpg' [[0.025]]
b'Overflate_kamera_resized/crack_overflatekamera000840.jpg' [[0.0984375]]
b'Overflate_kamera_resized/crack_overflatekamera000559.jpg' [[0.10625]]
b'Overflate_kamera_resized/crack_overflatekamera00099.jpg' [[0.1203125]]
b'Overflate_kamera_resized/crack_overflatekamera000676.jpg' [[0.0796875]]
b'Overflate_kamera_resized/crack_overflatekamera00070.jpg' [[0.44375]]
b'Overflate_kamera_resized/crack_overflatekamera000868.jpg' [[0.509375]]
b'Overflate_kamera_resized/crack_overflatekamera000278.jpg' [[0.0765625]]
b'Overflate_kamera_resized/crack_overflatekamera000309.jpg' [[0.109375]]
b'Overflate_kamera_resized/crack_overflatekamera000206.jpg' [[0.375]]
b'Overflate_kamera_resized/crack_overflatekamera000239.jpg' [[0.6359375]]
b'Overflate_kamera_resized/crack_overflatekamera000215.jpg' [[0.38125]]
b'Overflate_kamera_resized/crack_overflatekamera000664.jpg' [[0.015625]]
b'Overflate_kamera_resized/crack_overflatekamera000888.jpg' [[0.146875]]
b'Overflate_kamera_resized/crack_overflatekamera000713.jpg' [[0.0328125]]
b'Overflate_kamera_resized/crack_overflatekamera000417.jpg' [[0.2015625]]
b'Overflate_kamera_resized/crack_overflatekamera000944.jpg' [[0.465625]]
b'Overflate_kamera_resized/crack_overflatekamera000695.jpg' [[0.0140625]]
b'Overflate_kamera_resized/crack_overflatekamera000406.jpg' [[0.075]]
b'Overflate_kamera_resized/crack_overflatekamera00024.jpg' [[0.2265625]]
b'Overflate_kamera_resized/crack_overflatekamera000874.jpg' [[0.090625]]
b'Overflate_kamera_resized/crack_overflatekamera000793.jpg' [[0.053125]]
b'Overflate_kamera_resized/crack_overflatekamera000911.jpg' [[0.5375]]
b'Overflate_kamera_resized/crack_overflatekamera000392.jpg' [[0.0734375]]
b'Overflate_kamera_resized/crack_overflatekamera000566.jpg' [[0.2328125]]
b'Overflate_kamera_resized/crack_overflatekamera000768.jpg' [[0.203125]]
b'Overflate_kamera_resized/crack_overflatekamera000653.jpg' [[0.253125]]
b'Overflate_kamera_resized/crack_overflatekamera00059.jpg' [[0.190625]]
b'Overflate_kamera_resized/crack_overflatekamera000329.jpg' [[0.6671875]]
b'Overflate_kamera_resized/crack_overflatekamera000668.jpg' [[0.0515625]]
b'Overflate_kamera_resized/crack_overflatekamera000827.jpg' [[0.21875]]
b'Overflate_kamera_resized/crack_overflatekamera00089.jpg' [[0.146875]]
b'Overflate_kamera_resized/crack_overflatekamera000255.jpg' [[0.2578125]]
b'Overflate_kamera_resized/crack_overflatekamera000613.jpg' [[0.1546875]]
b'Overflate_kamera_resized/crack_overflatekamera000389.jpg' [[0.09375]]
b'Overflate_kamera_resized/crack_overflatekamera000595.jpg' [[0.240625]]
b'Overflate_kamera_resized/crack_overflatekamera000155.jpg' [[0.009375]]
b'Overflate_kamera_resized/crack_overflatekamera000369.jpg' [[0.053125]]
```

**Comment by ilaripih** [comment] 2020-11-18 09:44
I think this is a duplicate of https://github.com/tensorflow/models/issues/9471

**Closed** 2020-11-18 10:22 UTC
Labels: models:research, type:bug
