### ISSUE TITLE
[Syntaxnet] Build errors while following readme on Mac

### ISSUE THREAD

**Issue by place-for-your-ad** [tensorflow/models#4383] opened 2018-05-27 14:37 UTC
- **What is the top-level directory of the model you are using**: models/research/syntaxnet
- **Have I written custom code**: No
- **OS Platform and Distribution**: MacOS High Sierra
- **TensorFlow installed from/version**: I'm installing syntaxnet from source, isn't it bundled with TF of required version?
- **Bazel version**: 0.11.1
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
```
bazel test --linkopt=-headerpad_max_install_names \
    dragnn/... syntaxnet/... util/utf8/...
```

I'm following the https://github.com/tensorflow/models/blob/master/research/syntaxnet/README.md and got the exact versions of the dependencies listed (protobuf 3.3.0 in particular). I've also installed protobuf runtime and system includes (strange that there's nothing about that in readme). All python dependencies live in virtual env and I'm building from an env.

The problem is, that when building, I've got the following error
```
ERROR: /Users/screamer/dev/syntaxnet/models/research/syntaxnet/util/utf8/BUILD:35:1: C++ compilation of rule '//util/utf8:unicodetext_main' failed (Exit 1)
In file included from util/utf8/unicodetext_main.cc:26:
In file included from ./util/utf8/unicodetext.h:25:
In file included from ./syntaxnet/base.h:28:
In file included from external/org_tensorflow/tensorflow/core/lib/core/status.h:23:
bazel-out/darwin-opt/genfiles/external/org_tensorflow/tensorflow/core/lib/core/error_codes.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
bazel-out/darwin-opt/genfiles/external/org_tensorflow/tensorflow/core/lib/core/error_codes.pb.h:13:2: error: incompatible with your Protocol Buffer headers.  Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
bazel-out/darwin-opt/genfiles/external/org_tensorflow/tensorflow/core/lib/core/error_codes.pb.h:14:2: error: your headers.
#error your headers.
 ^
bazel-out/darwin-opt/genfiles/external/org_tensorflow/tensorflow/core/lib/core/error_codes.pb.h:39:46: error: no type named 'FieldMetadata' in namespace 'google::protobuf::internal'
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
bazel-out/darwin-opt/genfiles/external/org_tensorflow/tensorflow/core/lib/core/error_codes.pb.h:40:46: error: no type named 'SerializationTable' in namespace 'google::protobuf::internal'
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
```

With protobuf 3.5.1 it builds fine, but a bunch of test fail:
```
INFO: Build completed, 20 tests FAILED, 118 total actions
//dragnn/components/stateless:stateless_component_test                   PASSED in 0.2s
//dragnn/components/syntaxnet:syntaxnet_component_test                   PASSED in 0.3s
//dragnn/components/syntaxnet:syntaxnet_link_feature_extractor_test      PASSED in 0.3s
//dragnn/components/syntaxnet:syntaxnet_transition_state_test            PASSED in 0.2s
//dragnn/core:beam_test                                                  PASSED in 0.2s
//dragnn/core:compute_session_impl_test                                  PASSED in 0.3s
//dragnn/core:compute_session_pool_test                                  PASSED in 0.2s
//dragnn/core:dragnn_bulk_op_kernels_test                                PASSED in 0.2s
//dragnn/core:dragnn_op_kernels_test                                     PASSED in 0.3s
//dragnn/core:index_translator_test                                      PASSED in 0.2s
//dragnn/core:input_batch_cache_test                                     PASSED in 0.2s
//dragnn/core:resource_container_test                                    PASSED in 0.2s
//dragnn/io:sentence_input_batch_test                                    PASSED in 0.2s
//dragnn/mst:disjoint_set_forest_test                                    PASSED in 0.2s
//dragnn/mst:mst_solver_test                                             PASSED in 0.2s
//dragnn/mst:spanning_tree_iterator_test                                 PASSED in 0.3s
//dragnn/python:composite_optimizer_test                                 PASSED in 9.3s
//dragnn/python:digraph_ops_test                                         PASSED in 5.8s
//dragnn/python:evaluation_test                                          PASSED in 4.9s
//dragnn/python:render_parse_tree_graphviz_test                          PASSED in 5.4s
//dragnn/python:render_spec_with_graphviz_test                           PASSED in 5.4s
//dragnn/python:trainer_lib_test                                         PASSED in 5.3s
//dragnn/python:visualization_test                                       PASSED in 5.1s
//dragnn/tools/benchmarks:beam_benchmark                                 PASSED in 0.2s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0.2s
//syntaxnet:binary_segment_state_test                                    PASSED in 0.2s
//syntaxnet:binary_segment_transitions_test                              PASSED in 0.2s
//syntaxnet:char_ngram_string_extractor_test                             PASSED in 0.2s
//syntaxnet:char_properties_test                                         PASSED in 0.2s
//syntaxnet:char_shift_transitions_test                                  PASSED in 0.2s
//syntaxnet:fml_parser_test                                              PASSED in 0.2s
//syntaxnet:generic_features_test                                        PASSED in 0.2s
//syntaxnet:head_label_transitions_test                                  PASSED in 0.3s
//syntaxnet:head_transitions_test                                        PASSED in 0.2s
//syntaxnet:label_transitions_test                                       PASSED in 0.2s
//syntaxnet:morphology_label_set_test                                    PASSED in 0.2s
//syntaxnet:once_transitions_test                                        PASSED in 0.2s
//syntaxnet:parser_features_test                                         PASSED in 0.2s
//syntaxnet:registry_test                                                PASSED in 0.2s
//syntaxnet:registry_test_with_duplicate                                 PASSED in 0.2s
//syntaxnet:segmenter_utils_test                                         PASSED in 0.2s
//syntaxnet:sentence_features_test                                       PASSED in 0.2s
//syntaxnet:shared_store_test                                            PASSED in 0.2s
//syntaxnet:tagger_transitions_test                                      PASSED in 0.2s
//syntaxnet:term_frequency_map_test                                      PASSED in 0.2s
//syntaxnet:whole_sentence_features_test                                 PASSED in 0.2s
//syntaxnet/util:check_test                                              PASSED in 4.6s
//syntaxnet/util:registry_test                                           PASSED in 4.6s
//syntaxnet/util:resources_test                                          PASSED in 4.5s
//util/utf8:unicodetext_unittest                                         PASSED in 0.2s
//dragnn/python:biaffine_units_test                                      FAILED in 4.6s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/biaffine_units_test/test.log
//dragnn/python:bulk_component_test                                      FAILED in 4.7s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/bulk_component_test/test.log
//dragnn/python:component_test                                           FAILED in 4.7s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/component_test/test.log
//dragnn/python:dragnn_model_saver_lib_test                              FAILED in 5.0s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/dragnn_model_saver_lib_test/test.log
//dragnn/python:lexicon_test                                             FAILED in 4.8s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/lexicon_test/test.log
//dragnn/python:mst_ops_test                                             FAILED in 4.7s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/mst_ops_test/test.log
//dragnn/python:mst_units_test                                           FAILED in 4.8s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/mst_units_test/test.log
//dragnn/python:network_units_test                                       FAILED in 5.2s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/network_units_test/test.log
//dragnn/python:runtime_support_test                                     FAILED in 5.1s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/runtime_support_test/test.log
//dragnn/python:sentence_io_test                                         FAILED in 5.2s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/sentence_io_test/test.log
//dragnn/python:spec_builder_test                                        FAILED in 5.2s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/spec_builder_test/test.log
//dragnn/python:transformer_units_test                                   FAILED in 5.1s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/transformer_units_test/test.log
//dragnn/tools:model_trainer_test                                        FAILED in 3.7s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/tools/model_trainer_test/test.log
//syntaxnet:beam_reader_ops_test                                         FAILED in 4.4s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 4.4s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 4.4s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 4.3s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 4.4s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 3.9s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/syntaxnet/text_formats_test/test.log
//dragnn/python:graph_builder_test                                       FAILED in 5 out of 5 in 4.9s
  Stats over 5 runs: max = 4.9s, min = 1.9s, avg = 2.6s, dev = 1.2s
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/graph_builder_test/shard_4_of_5/test.log
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/graph_builder_test/shard_1_of_5/test.log
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/graph_builder_test/shard_2_of_5/test.log
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/graph_builder_test/shard_5_of_5/test.log
  /private/var/tmp/_bazel_screamer/18e2c8b2c8dff4a4063d43a04ecb656f/execroot/__main__/bazel-out/darwin-opt/testlogs/dragnn/python/graph_builder_test/shard_3_of_5/test.log

Executed 70 out of 70 tests: 50 tests pass and 20 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```
Each of the test logs have the same contents:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
python(5945,0x7fff8df61380) malloc: *** error for object 0x10c7af7a0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

I will appreciate any help and will be happy to provide any additional information, if necessary.

**Comment by tensorflowbutler** [comment] 2018-05-28 00:40
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by colloidal-isotope** [comment] 2018-05-28 12:20
@tensorflowbutler, @robieta  updated

**Comment by tensorflowbutler** [comment] 2020-01-29 23:21
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ravikyram** [comment] 2020-07-10 10:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-10 10:13 UTC
Labels: models:research, type:support
