### ISSUE TITLE
Can't use tf.contrib.slim

### ISSUE THREAD

**Issue by ZH-Lee** [tensorflow/models#6872] opened 2019-05-24 00:55 UTC
I want to use MobileNet model, but i got this error : 
`ImportError: cannot import name 'monitoring'`, 
and i can't pip3 install monitoring package.  My tensorflow (1.13), Macbook Pro. So, what's wrong and how to fix it ?

**Comment by tensorflowbutler** [comment] 2019-05-25 00:25
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ZH-Lee** [comment] 2019-05-27 01:13
Thanks. I've solved this problem by installing a lower version of tensorlow.

**Comment by ymodak** [comment] 2019-05-30 19:06
Just a quick heads up staring TF 2.X tf.contrib has been deprecated. Please take a look at these [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0-alpha0) to know more. Closing this issue since it has been resolved. Thanks!

**Closed by ymodak** 2019-05-30 19:06 UTC
Labels: models: research
