### ISSUE TITLE
Object Detection : Cannot run eval.py locally . It gives warnings for TF 1.3 

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2387] opened 2017-09-14 09:52 UTC
I am using tensorflow 1.3 . 
My training script run well locally . But evaluation is not showing the results or printing the results . 
Here's the tensorboard Visualization 
![image](https://user-images.githubusercontent.com/16892570/30423380-3b8b5474-9975-11e7-92bc-5db7e90ef2c1.png)

Then this gives this directory 
![image](https://user-images.githubusercontent.com/16892570/30423468-76e47bc2-9975-11e7-8b58-ba38a03bbc31.png)

**Comment by xiaoyi201406** [comment] 2017-09-14 15:37
Do you switch the location of the tensorboard log  from the train log to the eval log?

**Comment by shamanez** [comment] 2017-09-15 03:25
yes. Problem is when I run the eval.py it's not printing any  evaluation results as it does in the cloud API. Only thing appears in the terminal is this . It's not running 

![image](https://user-images.githubusercontent.com/16892570/30465238-8096feea-9a08-11e7-8191-91b04e5ca39f.png)

**Comment by shamanez** [comment] 2017-09-15 05:27
This keep going nothing get evaluated . 

![image](https://user-images.githubusercontent.com/16892570/30467737-8629e172-9a19-11e7-9efc-45d2facebc47.png)

**Comment by reedwm** [comment] 2017-09-15 21:57
/CC @derekjchow do you know what the issue is?

**Comment by yimintsai** [comment] 2017-09-18 08:02
Encounter the same problem using TF1.3.

**Comment by shreyas0906** [comment] 2018-01-21 07:00
Can someone please explain how to run the evalutation from scratch? For now, all I am trying to do is 
python eval.py --logtostderr --checkpoint_dir=data/model.ckpt-5575 --eval_dir=eval_model/ --pipeline_config_path=data/object-detect.pbtxt 

and the object-detect.pbtxt contains

item {
    id: 1 
    name: 'ball'	
}


Can someone please let me know how to do this.?

**Comment by zeynali** [comment] 2018-02-23 09:48
@shamanez , did you can train Faster_rcnn_res101 ? my system 1080 , 16G ram ,
https://github.com/tensorflow/models/issues/3408

**Comment by tensorflowbutler** [comment] 2020-01-29 23:33
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 09:51
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 09:51 UTC
Labels: stat:awaiting tensorflower

**Comment by ibrahim1611** [comment] 2020-02-21 03:02
hi I am getting this error while run eval.py  please help

AssertionError: `checkpoint_dir` is missing
