### ISSUE TITLE
Running export_inference_graph.py gives TypeError: x and y must have the same dtype, got tf.float32 != tf.int32

### ISSUE THREAD

**Issue by uzu22** [tensorflow/models#2774] opened 2017-11-11 20:36 UTC
Running the following commands in cmd

    python export_inference_graph.py \ --input_type image_tensor \ --pipeline_config_path training/ssd_mobilenet_v1_pets.config \ --trained_checkpoint_prefix training/model.ckpt-2453 \ --output_directory heart_graph

Results with an error:

    Traceback (most recent call last):
      File "export_inference_graph.py", line 119, in <module>
        tf.app.run()
      File "C:\Users\<Name>\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
        _sys.exit(main(_sys.argv[:1] + flags_passthrough))
      File "export_inference_graph.py", line 115, in main
        FLAGS.output_directory, input_shape)
      File "C:\Users\<Name>\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\models\research\object_detection\exporter.py", line 427, in export_inference_graph
        input_shape, optimize_graph, output_collection_name)
      File "C:\Users\<Name>\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\models\research\object_detection\exporter.py", line 353, in _export_inference_graph
        postprocessed_tensors = detection_model.postprocess(output_tensors)
      File "C:\Users\<Name>\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\models\research\object_detection\meta_architectures\ssd_meta_arch.py", line 405, in postprocess
        class_predictions_without_background)
      File "C:\Users\<Name>\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\models\research\object_detection\builders\post_processing_builder.py", line 94, in score_converter_fn
        scaled_logits = tf.divide(logits, logit_scale, name='scale_logits')
      File "C:\Users\<Name>\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\math_ops.py", line 309, in divide
        return DivideDelegateWithName(x, name) / y
      File "C:\Users\<Name>\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\math_ops.py", line 294, in __truediv__
        return _truediv_python3(self.x, y, self.name)
      File "C:\Users\<Name>\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\math_ops.py", line 981, in _truediv_python3
        (x_dtype, y_dtype))
    TypeError: x and y must have the same dtype, got tf.float32 != tf.int32

Where is the problem and how to solve this?

**Comment by temiklis** [comment] 2017-11-13 06:09
install tensorflow version 1.4

**Comment by depauwjimmy** [comment] 2017-11-13 15:26
Hello,
I have exactly the same problem but i have 1.4.0 installed already.
Any other possible cause for this error?

**Comment by hoou** [comment] 2017-11-14 08:28
I am having exactly the same error. I am putting down my system information. Hope it helps and you guys figure it out soon, good luck.

### System information
- **What is the top-level directory of the model you are using**:
object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.4.0
- **CUDA/cuDNN version**:
CUDA 8.0, cuDNN 6.0
- **GPU model and memory**:
NVIDIA GeForce GTX 1050 Ti 4GB
- **Exact command to reproduce**:
python -m object_detection\export_inference_graph --pipeline_config_path=config\faster_rcnn-traffic_udacity_real.config --trained_checkpoint_prefix=data\real_training_data\model.ckpt-10000 --output_directory=frozen_real\

### Describe the problem
If i run that command above, it gives me TypeError. Look at log.

### Source code / logs
Traceback (most recent call last):
  File "E:\Anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\export_inference_graph.py", line 119, in <module>
    with gfile.GFile(FLAGS.output_file, 'wb') as f:
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\export_inference_graph.py", line 115, in main
    shape=[FLAGS.batch_size, image_size,
  File "E:\Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\models\research\object_detection\exporter.py", line 427, in export_inference_graph
    input_shape, optimize_graph, output_collection_name)
  File "E:\Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\models\research\object_detection\exporter.py", line 353, in _export_inference_graph
    postprocessed_tensors = detection_model.postprocess(output_tensors)
  File "E:\Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 859, in postprocess
    mask_predictions=mask_predictions)
  File "E:\Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 1200, in _postprocess_box_classifier
    class_predictions_with_background_batch))
  File "E:\Anaconda3\envs\tensorflow\Lib\site-packages\tensorflow\models\research\object_detection\builders\post_processing_builder.py", line 94, in score_converter_fn
    scaled_logits = tf.divide(logits, logit_scale, name='scale_logits')
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 309, in divide
    return DivideDelegateWithName(x, name) / y
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 294, in __truediv__
    return _truediv_python3(self.x, y, self.name)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 981, in _truediv_python3
    (x_dtype, y_dtype))
TypeError: x and y must have the same dtype, got tf.float32 != tf.int32

**Comment by mpeniak** [comment] 2017-11-14 09:44
I have the same issue when trying to freeze embedded_ssd_mobilenet_v1. Previously I would get this:

https://github.com/tensorflow/models/issues/2777

but after reverting to previous version of that file I get the error specified in this thread.

Any ideas what to do and how to freeze this model?

**Comment by temiklis** [comment] 2017-11-14 12:19
google cloud requires a version 1.2, but I can't do export_graph on this version. On version 1.4 everything is fine, but the cloud does not perceive the model as it needs version 1.2. I'm having the same error as users above. Will notify if I find a solution.

**Comment by ypasichnyk** [comment] 2017-11-15 08:44
I get very similar error while running the following command:

python.app object_detection/eval.py --logtostderr --pipeline_config_path=object_detection/data/faster_rcnn_resnet101_pets.config --checkpoint_dir=object_detection/models/sigs_faster_rcnn_resnet101_pets/train --eval_dir=object_detection/models/sigs_faster_rcnn_resnet101_pets/eval

INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Scale of 0 disables regularizer.
Traceback (most recent call last):
  File "object_detection/eval.py", line 130, in <module>
    tf.app.run()
  File ".../tensorflow-anaconda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/eval.py", line 126, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File ".../tensorflow/models/research/object_detection/evaluator.py", line 142, in evaluate
    ignore_groundtruth=eval_config.ignore_groundtruth)
  File ".../tensorflow/models/research/object_detection/evaluator.py", line 61, in _extract_prediction_tensors
    **detections = model.postprocess(prediction_dict)
  File ".../tensorflow/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 859, in postprocess
    mask_predictions=mask_predictions)
  File ".../tensorflow/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1200, in _postprocess_box_classifier
    class_predictions_with_background_batch))
  File ".../tensorflow/models/research/object_detection/builders/post_processing_builder.py", line 94, in score_converter_fn
    scaled_logits = tf.divide(logits, logit_scale, name='scale_logits')
  File ".../tensorflow-anaconda/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 309, in divide
    return DivideDelegateWithName(x, name) / y
  File ".../tensorflow-anaconda/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 294, in __truediv__
    return _truediv_python3(self.x, y, self.name)
  File ".../tensorflow-anaconda/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 981, in _truediv_python3
    (x_dtype, y_dtype))
TypeError: x and y must have the same dtype, got tf.float32 != tf.int32**

I highlighted in bold the part of the stack trace that is exactly the same.

**Comment by cosmicpowercr** [comment] 2017-11-15 09:46
I solve this problem. This  is a small bug about TypeError ,we can do as follow:
In the file:post_processing_builder.py, I change the codes as follow:
def _score_converter_fn_with_logit_scale(tf_score_converter_fn, logit_scale):
  """Create a function to scale logits then apply a Tensorflow function."""
  def score_converter_fn(logits):
    cr = logit_scale
    cr = tf.constant([[cr]],tf.float32)
    print(logit_scale)
    print(logits)
    scaled_logits = tf.divide(logits, cr, name='scale_logits') #change logit_scale
    return tf_score_converter_fn(scaled_logits, name='convert_scores')
  score_converter_fn.__name__ = '%s_with_logit_scale' % (
      tf_score_converter_fn.__name__)
  return score_converter_fn

**Comment by depauwjimmy** [comment] 2017-11-15 10:17
I tried your suggestion but i receive: 
AttributeError: 'function' object has no attribute 'name'

I am using python 2.7 which maybe is why it does not work?

**Comment by hoou** [comment] 2017-11-15 10:26
@depauwjimmy 
**LONG STORY:**
look what code he actually changed/added in comparison with old code, don't just simply copy his text, github is not interpreting his text as python code, so for example github changed "\_\_name__" to "name" but with bold font....

**SHORT STORY:**
just replace "score_converter_fn.name" with "score_converter_fn.\_\_name__" and "tf_score_converter_fn.name" with "tf_score_converter_fn.\_\_name__"

**Comment by hoou** [comment] 2017-11-15 10:35
@cosmicpowercr thanks, it is working now!

**Comment by offbye** [comment] 2017-12-22 03:13
@cosmicpowercr  it works !

**Comment by scalable** [comment] 2018-01-01 15:49
@cosmicpowercr very promising, but after changing post_processing_builder.py, do I need to do an "install" step to make the change take effect? Thanks.

**Comment by cosmicpowercr** [comment] 2018-01-01 16:07
@scalable No,you would like to just change the code as above.

**Comment by ShegnkaiWu** [comment] 2018-01-16 03:38
It works! That's great!

**Comment by raingo** [comment] 2018-01-30 18:35
Just had this error. What helped me is just to upgrade `protobuf`, and recompile the `*.proto` files.

My guess is that if the `protoc` is older than the python `google.protobuf`, the `logit_scale` is mistakenly parsed into `integer`. I think upgrading protobuf is a better solution than patching the python function, because there could be hidden problems.

**Comment by wt-huang** [comment] 2018-11-02 02:18
Closing as this is resolved

**Closed by wt-huang** 2018-11-02 02:18 UTC
Labels: stat:awaiting tensorflower
