### ISSUE TITLE
How do I change anchor box type?

### ISSUE THREAD

**Issue by 89douner** [tensorflow/models#5473] opened 2018-10-11 07:02 UTC
System information
What is the top-level directory of the model you are using: /home/user
Have I written custom code: No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.10.1
Bazel version (if compiling from source): I don't use it
CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
GPU model and memory: Geforce GTX 1070
Exact command to reproduce: No

#############################################################################
[Question]
I wanna change the shape of anchor box by adjusting the size and aspect ratio.
I knew there is anchor box information in [configure](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_nas_coco.config) .

Q1.  Can I just change the values of scales and aspect ration in configure file and then train ?

`first_stage_anchor_generator {
      grid_anchor_generator {
        scales: [0.25, 0.5, 1.0, 2.0]
        aspect_ratios: [0.5, 1.0, 2.0]
        height_stride: 16
        width_stride: 16
      }`

Q2. Does aspect ration 0.5 means height(1)/width(2) ratio?
Q3. What is height stride? (If you don't know this question, you can skip!)

You can refer below
https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_nas_coco.config

**Comment by netanel-s** [comment] 2018-10-11 08:57
1) Yes.
2) Yes.
3) It means the difference, in pixels of the original image, between consequent anchors in the given axis.

**Comment by netanel-s** [comment] 2018-10-11 11:15
Take a specific anchor parameters, e.g. scale=1 and aspect ratio=1. Now put it on the original image in the top left corner. The anchor will then slide over the image both horizontally and vertically. The width stride is what is the difference in pixels between the first above-mentioned anchor to the next one on the right in the same row, while the height stride is what is the difference in pixels between the first anchor to the next one under it on the same column.

**Comment by 89douner** [comment] 2018-10-11 11:59
Clearly, understand! Thanks a lot!

**Comment by qlzh727** [comment] 2018-11-07 17:11
Thanks @netanel-s  for answering the question, assume the issue is resolved, closing the issue now.

**Closed by qlzh727** 2018-11-07 17:11 UTC

**Comment by ZengyuanYu** [comment] 2018-12-03 08:02
> System information
> What is the top-level directory of the model you are using: /home/user
> Have I written custom code: No
> OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
> TensorFlow installed from (source or binary): source
> TensorFlow version (use command below): 1.10.1
> Bazel version (if compiling from source): I don't use it
> CUDA/cuDNN version: CUDA 9.0 / cuDNN: 7.1
> GPU model and memory: Geforce GTX 1070
> Exact command to reproduce: No
> 
> #############################################################################
> [Question]
> I wanna change the shape of anchor box by adjusting the size and aspect ratio.
> I knew there is anchor box information in [configure](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_nas_coco.config) .
> 
> Q1. Can I just change the values of scales and aspect ration in configure file and then train ?
> 
> `first_stage_anchor_generator { grid_anchor_generator { scales: [0.25, 0.5, 1.0, 2.0] aspect_ratios: [0.5, 1.0, 2.0] height_stride: 16 width_stride: 16 }`
> 
> Q2. Does aspect ration 0.5 means height(1)/width(2) ratio?
> Q3. What is height stride? (If you don't know this question, you can skip!)
> 
> You can refer below
> https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_nas_coco.config



> Thanks for your answer! but, could you explain the answer to the third question in detail?

When I see this question, I will ask the another. I want to change Anchor scale, ratios or nums on my own data, please how to generate anchor? What is the basis? Thank you~
