### ISSUE TITLE
GPU is detected but training starts on the CPU

### ISSUE THREAD

**Issue by VanitarNordic** [tensorflow/models#3366] opened 2018-02-12 08:02 UTC
Hi,

I have installed the tensorflow-gpu 1.5 or 1.6.rc0 in accompany with Cuda-9.0 and CuDNN-7.0.5
When I start training using `train.py`, it detects the GPU, but it starts the training on the CPU and CPU load is 100%. The GPU memory gets filled and its core clocks increases but it does not show any consistent load on the cores.

```
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2018-02-12 11:23:48.533753: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1308] Adding visible gpu devices: 0
2018-02-12 11:23:57.838951: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:989] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4742 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
```

**Comment by VanitarNordic** [comment] 2018-02-12 08:53
![pr](https://user-images.githubusercontent.com/18719591/36089124-801990ce-0fef-11e8-83d6-22a694a87903.png)

**Comment by monomon** [comment] 2018-02-12 09:13
Seems like the GPU *is* being used. How are you loading your input data? Could be that that part works intensively on the CPU.

**Comment by VanitarNordic** [comment] 2018-02-12 09:20
I just followed the procedure. I have created `train.record` and `val.record` and it accompanies with a config file, a `label_map.pbtxt` and a pretrained weights. 
Then I run training in the console.  as you see it detects the GPU, but the load goes to CPU.

 I don't know it is related or not, but I trained till 800 steps but the loss plays around 2 and 3.

**Comment by cy89** [comment] 2018-02-12 18:22
@VanitarNordic are you convinced that this is a bug, and not just some sort of configuration thing? 
Would you please fill out the usual platform/configuration/reproducibility part of the standard report? 


Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by VanitarNordic** [comment] 2018-02-12 18:55
@cy89 

It might be a bug, because I have tested many things and I followed a standard procedures. During my google search I saw some other people had also reported something like this. if you feel it is necessary, I'll find where it was.

**Platform:** Windows10-x64
**CUDA:** Cuda-9.0 and CuDNN-7.0.5 - GTX 1060 6G GPU
**Tested by these Tensorflow versions:** 1.5 and 1.6-rc0 (both shows a similar behavior). Installed through pip (`pip install tensorflow-gpu`)

Training command: (it starts training but with this behavior)

`python train.py --logtostderr --train_dir=results/train \ --peline_config_path=weight/ssd_inception_v2_coco.config`

**Comment by VanitarNordic** [comment] 2018-02-12 22:24
in this issue some users have encountered the same problem: https://github.com/tensorflow/tensorflow/issues/12388#issuecomment-365081928

**Comment by adriancar** [comment] 2018-02-13 00:46
I'm getting similar behaviour to what @VanitarNordic describes:
Platform: Windows7-x64
CUDA: Cuda-9.0.176.1 and CuDNN-7.0.5 - GTX 1060 6G GPU
Tested by these Tensorflow versions: 1.5, Installed through pip `pip install tensorflow-gpu` as per official tensorflow install instructions for anaconda. 

When I run mnist_test.py from https://www.tensorflow.org/tutorials/layers i get cpu under heavy load, no change in gpu load, and when I run `nvidia-smi` it detects the gpu, but no processes are visible.

**Comment by adriancar** [comment] 2018-02-13 01:06
Augh, it seemed to be a driver issue for me: I uninstalled, re-downloaded, and re-installed my gpu drivers, restarted my computer, and it seems to be working fine now!

**Comment by VanitarNordic** [comment] 2018-02-13 08:08
@adriancar 

Make sure that it is working and test its operation by the open-hardware-monitor software, because I have done these steps many times but still it does not work. The load is on the CPU.

**Comment by adriancar** [comment] 2018-02-13 08:24
@VanitarNordic

After reinstalling the driver, when executing training, hardware monitor shows my GPU gets pegged at 100%, while CPU sits at ~25%.

**Comment by VanitarNordic** [comment] 2018-02-13 08:27
@adriancar 

I'm using the latest driver and I had cleaned everything before. Are you using the last commit?

**Comment by adriancar** [comment] 2018-02-13 08:38
I used a fresh tensorflow install on a fresh anaconda env. I fetched it using the instructions on tensorflow website - version 1.5.0.

**Comment by VanitarNordic** [comment] 2018-02-13 08:44
@adriancar 

No, what I mean from the latest commit, is the tensorflow detection API repository. when have you downloaded and used the latest repository?

**Comment by adriancar** [comment] 2018-02-13 20:58
I used the MNIST CNN tutorial to test if the GPU was being used: https://www.tensorflow.org/tutorials/layers

**Comment by CarltonSemple** [comment] 2018-02-14 04:39
It seems like the published tensorflow-gpu wheel has been a problem for Windows users for a while now: https://github.com/tensorflow/models/issues/1942#issuecomment-316023323
Unfortunately I have not been able to successfully compile it for myself, as there are compilation errors
https://github.com/tensorflow/tensorflow/issues/16138

**Comment by civilman628** [comment] 2018-02-14 18:48
I just clean install the latest driver for Titan Xp 390.77 on Windows 7, but training still use CPU but not GPU.

**Comment by VanitarNordic** [comment] 2018-02-14 19:02
@civilman628 

Yes, by the evidences it is a bug.

**Comment by CarltonSemple** [comment] 2018-02-14 23:40
@VanitarNordic this should probably be moved https://github.com/tensorflow/tensorflow, no?

**Comment by VanitarNordic** [comment] 2018-02-15 00:02
@CarltonSemple 

I don't know because that might happen with the object detection API only. let the @cy89 decide about it.

**Comment by CarltonSemple** [comment] 2018-02-15 00:55
I've had it happen with other things.

**Comment by cy89** [comment] 2018-02-15 01:23
@VanitarNordic @CarltonSemple I'm not seeing in the comment stream whether you think this problem is all computations not using the GPU, or whether it's just ssd_inception_v2_coco. 

I.e., @VanitarNordic if you run @adriancar 's tutorial MNIST example, do things work as expected?

**Comment by VanitarNordic** [comment] 2018-02-15 07:51
@cy89 
The computations use the GPU inefficiently (something like blinking) and pushe the constant 100% load on the CPU.

**Comment by rhys-saldanha** [comment] 2018-02-21 17:05
Tensorflow fills my GPU RAM then does all the work on the CPU... runs slower than if I force using just the CPU, what's going on here?

**Comment by VanitarNordic** [comment] 2018-02-21 18:42
@rhys-saldanha 

You are not alone. I hope they fix the bug as soon as possible

**Comment by ParinithShekar** [comment] 2018-02-24 17:12
@VanitarNordic I am experiencing the same behavior. I am trying to use TensorFlow's object detection API. 
**Platform**: Ubuntu 16.04 64-bit
**CUDA**: Cuda-9.0.176.1 and CuDNN-7.0.5 - GTX 1060 6GB GPU
**Tensorflow version**: 1.5.0. Installed through pip (_pip install tensorflow-gpu_ also tried _tensorflow-gpu==1.5.0_)
Specifically, I am running SSD mobilenet using a webcam and  I can see CPU load spike to 100% while GPU utilization is at 2-5% while temp is upto 58-60C and all of the available GPU memory is used.
I am getting close to 0.5FPS which is not logical at all, considering TF is detecting my GPU.
Hope this gets resolved soon.

**Comment by VanitarNordic** [comment] 2018-02-24 17:16
@ParinithShekar 

Hi. Yes you are not alone. at least 3 people reported it under this issue. I hope @cy89  consider it as soon as possible.

**Comment by pianas** [comment] 2018-02-25 15:13
Any news on this? I have the same problem with tensorflow 1.6.0rc1, keras 2.1.4 and cuda 9.0 (on both Linux and Windows, single-GPU and multi-GPU).

**Comment by wildpig22** [comment] 2018-03-09 12:26
I have a similar symptom:

While training with SSD Mobilenet(with ssd_mobilenet_v1_coco_2017_11_17 and research\object_detection\train.py), the GPU is not fully loaded, instead it jumps from 0~60% forming a "comb" shaped pattern in GPU-Z

However while trying the cifar-10 training example(tutorials\image\cifar10\cifar10_train.py), GPU usage keeps a solid/constant 90%

I then did some more experiments.

Changing image_resizer to 100*100(from original value of 300*300) in ssd_mobilenet_v1_coco.config yields a solid/constant gpu usage

Increasing or decreasing batch_size in the same config file changes nothing, still a "comb" shaped pattern

Since in all cases the same installation of tensorflow-gpu 1.6.0 are used, maybe there is some problem within the object detection api?

**Comment by VanitarNordic** [comment] 2018-03-09 12:45
@cy89 

You don't want to consider this?

**Comment by hbb21st** [comment] 2018-03-25 16:07
Why my problem still exist. I tried all ways mentioned above, and seemed load in gpu successfully, but...
totalMemory: 3.95GiB freeMemory: 3.91GiB
2018-03-25 11:59:22.538312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1227] Device peer to peer matrix
2018-03-25 11:59:22.538353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1233] DMA: 0 1 
2018-03-25 11:59:22.538360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 0:   Y N 
2018-03-25 11:59:22.538364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 1:   N Y 
2018-03-25 11:59:22.538374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0, 1
2018-03-25 11:59:23.892312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1616 MB memory) -> physical GPU (device: 0, name: Quadro K2200, pci bus id: 0000:03:00.0, compute capability: 5.0)
2018-03-25 11:59:23.913047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 1616 MB memory) -> physical GPU (device: 1, name: Quadro K2200, pci bus id: 0000:04:00.0, compute capability: 5.0)
2018-03-25 11:59:24.786177: E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2018-03-25 11:59:24.787125: E tensorflow/stream_executor/cuda/cuda_dnn.cc:393] possibly insufficient driver version: 384.81.0
2018-03-25 11:59:24.787164: F tensorflow/core/kernels/conv_ops.cc:717] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by sheucm** [comment] 2018-06-19 07:50
I have the same issue on tensorflow-gpu 1.8 with the same graphic card GTX 1060.

When runing train.py with ssd_mobilenet_v1 config, gpu loaded almost maximum memory (almost 6GB), but gpu is not using. 

Sometimes it went to 90% usage, but most of the time, it showed 0%.

While cpu usage was always 100%.

**Comment by nitinpapadkar** [comment] 2018-06-29 17:35
Guys, 
Is anyone got solution for this problem?
I am facing the same problem with TF 1.8 with cuda 9.0 and CUDNN  7.1
I am trying to train dynamic RNN model . With CPU Epoch duration is 2718.3 Seconds, however with GPU the same model takes 7344.9 Seconds. 
My System Configuration is as below:
Lptop: Microsoft surface book Pro2
RAM: 8GB
GPU: NVIDIA GForce GTX  965 M
CPU: Intel I7 6600 U Quad core

**Comment by Sri06006** [comment] 2018-07-02 07:48
I'm also facing the same problem. 
I have installed tensorflow-gpu 1.8, validated installation and uses gpu, but the python code, it says using tensforflow as backend, but still CPU memory is 100% and not using GPU .


Have you guys found the  solution ?

**Comment by VanitarNordic** [comment] 2018-07-02 08:19
I have opened this issue from a long time ago and introduce bugs for free but they don't consider

**Comment by Sri06006** [comment] 2018-07-02 11:52
Well issue is resolved for me. Here is what I did.
1. Check the current device 
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
Output : Show CPU
2. run "pip list"
3. there might be several versions of tensorflow installed
4. Uninstall others except the tensorflow-gpu
5. Run "pip install --ignore-installed --upgrade tensorflow-gpu"
6. Run 
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
output: Should show GPU.

**Comment by VanitarNordic** [comment] 2018-07-02 12:15
@Sri06006 

that's a basic consideration for installing GPU related packages that majority of us has correctly installed them and it already shows GPU

**Comment by nitinpapadkar** [comment] 2018-07-02 20:09
For me , the problem is not with GPU utilization. I can see the GPU  utilization is there but the training takes more time when I am using GPU. It is more faster on CPU

**Comment by kcobrien** [comment] 2018-07-05 10:56
I have also come across this (frustrating) issue.. using GTX 1080 ti and can detect GPU no problem in tensorflow. Have reinstalled drivers several times but still no joy.

Last week when I ran it on the CPU only version it ran perfectly fine for me (albeit slowly), but now the CPU usage flies up to 100% before the whole PC freezes even before the training queues start. A part of me is quite relieved to see that it's not juts me its happening to and that it very well could be a bug. Hopefully there is a fix available soon.

**Comment by notbrian** [comment] 2018-07-12 15:04
Same issue is happening to me on Tensorflow-GPU 1.9.0. Lots of CPU usage but only around 2.5% GPU usage.

**Comment by kcobrien** [comment] 2018-07-12 15:11
I got it working by using the following SSD_mobilenet at https://github.com/tensorflow/models/blob/master/object_detection/samples/configs/ssd_mobilenet_v1_pets.config


Also found at:
https://pythonprogramming.net/training-custom-objects-tensorflow-object-detection-api-tutorial/

Hope it helps someone! :)

**Comment by nitinpapadkar** [comment] 2018-07-13 18:13
@kcobrien : 
Can you please explain a bit , how did you made the training faster with GPU.
The link "https://github.com/tensorflow/models/blob/master/object_detection/samples/configs/ssd_mobilenet_v1_pets.config" is not working for me.

**Comment by kcobrien** [comment] 2018-07-17 09:23
@nitinpapadkar Try to get the ssd_mobilenet from this link instead:
 https://pythonprogramming.net/training-custom-objects-tensorflow-object-detection-api-tutorial/

I am using tensorflow 1.8 and CUDA 9.0 and I made sure to test that my GPU is responsive in tensorflow.

Also worth noting that when my model is training my CPU usage stays between 70-99% (I assume because I am loading images into the model) but it is clearly using my GPU to train and the PC no longer freezes.

I am not sure if there is still a bug with tensorflow 1.8 and cuda 9.0 but it seems that perhaps its more to do with model versions being used? I could be wrong though. Worth training with the model at the link above and seeing if that makes any difference :)

**Comment by nitinpapadkar** [comment] 2018-07-25 21:32
thanks @kcobrien . however it still not solve my problem. Checking now with more complex model

**Comment by Aigul95** [comment] 2018-10-29 08:14
> I have a similar symptom:
> 
> While training with SSD Mobilenet(with ssd_mobilenet_v1_coco_2017_11_17 and research\object_detection\train.py), the GPU is not fully loaded, instead it jumps from 0~60% forming a "comb" shaped pattern in GPU-Z
> 
> However while trying the cifar-10 training example(tutorials\image\cifar10\cifar10_train.py), GPU usage keeps a solid/constant 90%
> 
> I then did some more experiments.
> 
> Changing image_resizer to 100_100(from original value of 300_300) in ssd_mobilenet_v1_coco.config yields a solid/constant gpu usage
> 
> Increasing or decreasing batch_size in the same config file changes nothing, still a "comb" shaped pattern
> 
> Since in all cases the same installation of tensorflow-gpu 1.6.0 are used, maybe there is some problem within the object detection api?

I have the same problem. Do you solve it?

**Comment by Aigul95** [comment] 2018-10-29 08:18
@wildpig22
I have the same problem. Do you solve it?

**Comment by Aigul95** [comment] 2018-10-29 08:20
@wildpig22
@sheucm
I have the same problem. Do you solve it?

**Comment by Prakash19921206** [comment] 2018-11-18 08:12
Duplicate issue! 
i found an older issue [here ](https://github.com/tensorflow/models/issues/1942)
can we close this and continue the conversation there?

**Comment by VanitarNordic** [comment] 2018-11-18 08:31
@Prakash19921206 

There is no solution for this weird problem in your mentioned thread either. Therefore it makes no difference.

**Comment by Prakash19921206** [comment] 2018-11-19 09:34
I installed Ubuntu 18.04. its training there much faster!

**Comment by JoelTsui** [comment] 2019-01-16 08:02
same issue...

**Comment by CharlesCCC** [comment] 2019-03-21 17:02
Well, I felt a little bit relieved as I'm not the only one out there getting this problem/issue/bug(?) 
First of all here is my specs:

```
Windows 10 
Tensorflow-GPU (Only installed version -- through virtual venv) version 1.12 
CUDA/CUDNN 9.0 
i7-6700
GTX1070 
```
behavior:
```
scenario #1 
when training pet_detector with ssd_mobilenet_v2, GPU usage constant above 90% , CPU usage around 30% 

scenario #2 
when training pet_detector with ssd_inception_v2 GPU usage is jump between 0% ~ 90%, CPU usage constant around 90%

```
Read through all the previous reply and some of the reference issue as well, here are some of my thoughts: 

Originally I thought @wildpig22 was right about the assumption with the `image_resizer` because that might take quite some CPU power, but two of the scenarios I have both have `image_resizer` set as 300 x 300  but I agreed him with `Increasing or decreasing batch_size in the same config file changes nothing.` 

I found one [stackoverflow ](https://stackoverflow.com/a/46146814/3233111)answers seems make sense on the behavior i'm seeing, but not sure if that was the real cause

**Comment by sehargul-123** [comment] 2019-12-03 08:38
i have installed tensorflow-gpu==1.14
cuda=10.0
cudnn=7.5
deepspeech-gpu 0.5.1
but when i am training my own model its being done CPU not on GPU kindly help

**Comment by yerzhik** [comment] 2019-12-20 06:41
running inference on ObjectDetction using tiny yolo. It uses 81 MB of GPU, and something like 2 % of gpu utilization. But all 12 cores are loaded constantly on 70%. Why this is still a problem for ~one year?

**Comment by NasimSulaiman** [comment] 2020-01-20 08:40
@sehargul-123 have you solved the issue?! I am having the same issue here.

**Comment by Ndron** [comment] 2020-02-04 12:07
Now its 2020 problem dont solved
When i try to train ssd_mobilenet_v1  no gpu utilization training on cpu
When I use pretrained model - inference on GPU

**Comment by NasimSulaiman** [comment] 2020-02-04 12:12
Uninstall and install again, It will work. While installing check the compatibility between tensorflow version,cuda, cudnn and nvidia driver

**Comment by sehargul-123** [comment] 2020-02-07 05:08
I have solved this issue by reinstalling cuda 10.0

________________________________

**Comment by abuzahid** [comment] 2020-03-04 10:28
The solution is :
1. Firstly check if your GPU is working by installing pytorch and running this "torch.cuda.is_available()"
2. If that works then use the previous version of CUDA. Such as now the latest version is 10.2 so use 10.1 because the latest version sometimes is not stable completely.

**Comment by rlfrmsdh** [comment] 2020-04-02 07:56
I solved this issue by below procedures.
1. By mistake, I installed tensorflow module and tensorflow-gpu module together. So I erased the tensorflow module and tensorflow-gpu module and numpy altogether.  After that considering the dependency issue, I installed tensorflow-gpu == 1.13.1  Numpy == 1.16.0
2. After that I checked the graphic driver version and upgrade the latest version.
3. Reinstall the cuda , cudnn. 
And it works!

[SPEC]
Nvidia Geforce GTX 1080 
Driver version 442.19
Cuda - 10.0
cudnn  - 7.6.5

I hope it helps!

**Comment by ravikyram** [comment] 2020-07-10 12:25
@VanitarNordic 

Is this still an issue?
Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-08-12 07:35
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-08-12 07:35 UTC
Labels: stat:awaiting response, type:support

**Comment by shehroz010** [comment] 2020-10-26 16:39
I am having the same issue. This all started when I installed the TF Object Detection API. Now even if I create a new environment with TF-GPU only, it still runs on CPU instead of GPU.  This whole TF OD thing messed up everything in my system.  If anyone finds anything please help.

**Comment by 3d-illusions** [comment] 2020-12-21 00:47
same problem on a 1070

**Comment by shehroz010** [comment] 2020-12-21 08:22
> 
> 
> same problem on a 1070. Installed in anaconda prompt:
> 
> conda create -n tf-gpu tensorflow-gpu
> conda activate tf-gpu

@3d-illusions I solved it by installing the conda package of tf-gpu(not the pip one) after cleaning all the previous envs(deleting anconda and its whole file system and then reinstalling it). Installing conda version of TF-GPU installs cuda 10.1 and cudnn by default. Install corrssponding tensorflow version with respect to tf-gpu too, as TF OD API installs TF module too. I have 1060 and now works properly on my system. M using Win 10 as OS

**Comment by 3d-illusions** [comment] 2020-12-21 18:58
@shehroz010 

deleted everything and did the below (still not working)

open anaconda
create new environment
in the channels section change dropdown to non installed
search for tensor
select tensorflow-gpu and apply

still not recognising the gpu.  You mentioned install corresponding tensorflow version with respect to tf-gpu.  does this mean that I need to select tensorflow (without -gpu) and apply that afterwards? Sorry, tensorflow noob.  Any chance of a step by step suitable for a moron :D

**Comment by shehroz010** [comment] 2020-12-21 19:23
@3d-illusions 1st I uninstalled the anaconda through control panel and they removed the remaining files of anaconda by searching all the files and deleting it manually as I wanted no trace of anaconda in my system. After reinstalling it, I opened anaconda command prompt  and used this command 
`conda install -c anaconda tensorflow-gpu`
 This installs the TF x.x.x version. You can check the list of modules intalled using command 
`conda list` 
After that I installed the exact version of TF from pip
`pip install tensorflow==x.x.x`
Then I installed the TF OD API.
NOTE: If you are installing TF-GPU through conda instead of pip, then you don't need to install cudatoolkit and cudnn separately by downloading them from nividia's website as conda version of TF-GPU comes with cudatoolkit 10.1 and cudnn bundled.

**Comment by shehroz010** [comment] 2020-12-21 19:28
@3d-illusions 
One quick question, when did this problem started ? I mean was it working before ? In my case, it started when I installed the TF Object Detection API, before that everything was working fine for me.

**Comment by 3d-illusions** [comment] 2020-12-24 01:50
everyone having this problem.  Here's the solution:

https://www.youtube.com/watch?v=PnK1jO2kXOQ

I think the only step I was missing was the registration at the end.

**Comment by shehroz010** [comment] 2020-12-24 03:40
@3d-illusions good to know that now it's working for you. Even I had so much trouble while I faced this issue. I had everything working fine untill I installed the TF Object Detection API. It messed up my envs. Installing package from conda hub is the best way to handle it instead of pip. Anyway, goodluck for your future work

**Comment by bhaskatripathi** [comment] 2021-10-09 11:26
Check if Tensorflow GPU version is installed. If you have Tensorflow CPU then uninstall it and use the GPU version.

```
import tensorflow as tf 

if tf.test.gpu_device_name(): 
    print('Default GPU Device:{}'.format(tf.test.gpu_device_name()))
    print("It should print Default GPU Device: /device:GPU:0")
else:
    print("Please install GPU version of TF")
```
