### ISSUE TITLE
CudnnLSTM is incompatible with the 1.5.0 Tensorflow version

### ISSUE THREAD

**Issue by tastyminerals** [tensorflow/models#3382] opened 2018-02-14 16:38 UTC
Please update [recurrent PTB model](https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py). 

`CudnnLSTM` throws 
```
TypeError: __init__() got an unexpected keyword argument 'input_size'
```
as well as 
```
AttributeError: 'CudnnLSTM' object has no attribute 'params_size'
```

**Comment by cy89** [comment] 2018-02-15 00:03
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by tastyminerals** [comment] 2018-02-15 13:32
### System information
- **Have I written custom code**: [PTB model](https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py) from official RNN tutorial (using custom data and hyperparams slightly modified)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux 4.14.16-1 Manjaro
- **TensorFlow installed from**: pip
- **TensorFlow version**: 1.5.0
- **Python version**: 3.6 
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: NVIDIA GTX 1070 Mobile (8GB, driver 384.111)
- **Exact command to reproduce**: just running the training file `main.py` with default FLAG params

**Comment by zplizzi** [comment] 2018-07-06 03:11
I see this issue also in TF 1.8.0 from pip, exactly as described.

**Comment by Subsack** [comment] 2018-08-01 17:04
This is still a problem in 1.9.

Have I written custom code: No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro Version 10.0.17134 Build 17134
TensorFlow installed from: pip
TensorFlow version: 1.9.0
Python version: 3.6
Bazel version (if compiling from source): -
GCC/Compiler version (if compiling from source): -
CUDA/cuDNN version: 9.0
GPU model and memory: Asus GeForce GTX 1080 Strix Gaming Advanced
Exact command to reproduce: python ptb_word_lm.py --data_path simple-examples/data --rnn_mode=cudnn from the demo/tutorial under tutorials\rnn\ptb

**Comment by wt-huang** [comment] 2018-11-01 14:45
Closing as the PR fixes this issue

**Closed by wt-huang** 2018-11-01 14:45 UTC
