### ISSUE TITLE
Can update the ptb-word-lm to tf1.5+ please?

### ISSUE THREAD

**Issue by shiningliang** [tensorflow/models#3742] opened 2018-03-25 14:47 UTC
### Version
- TensorFlow 1.6
- CUDA 9
- cuDNN 7
### Description
I have some trouble in using new API of cudnn_rnn. And the ptb-word-lm model that the cudnn_rnn is used is based on tf <=1.4. There are little codes for new API on github and stackoverflow.
So can anyone update the ptb-word-lm to tf1.5+ please?

**Comment by tensorflowbutler** [comment] 2018-04-25 06:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-10-31 21:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-10-31 21:16 UTC
Labels: stat:awaiting response
