### ISSUE TITLE
NasNet models not loading the checkpoint files due a bad magic number

### ISSUE THREAD

**Issue by jorgemf** [tensorflow/models#2953] opened 2017-12-04 12:40 UTC
TensorFlow 1.4 with cuda support.

Download the nasnet model from the web into CHECKPOINT_PATH and create the directories DATASET_DIR and TRAIN_DIR, then:
```
python download_and_convert_data.py --dataset_name=flowers --dataset_dir=${DATASET_DIR}
python train_image_classifier.py \
 --train_dir=${TRAIN_DIR} \
 --dataset_dir=${DATASET_DIR} \
 --dataset_name=flowers \
 --dataset_split_name=train \
 --model_name=nasnet_large \
 --checkpoint_path=${CHECKPOINT_PATH}/checkpoint \
 --clone_on_cpu=True \
 --moving_average_decay=0.999 \
 --checkpoint_exclude_scopes=aux_7/aux_logits/FC,final_layer/FC \
 --trainable_scopes=".*/aux_logits/FC,final_layer/FC"
```
The error:
```
2017-12-04 13:36:45.190260: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Unable to open table file /experiments/checkpoints/nasnet_v1_2017_10_04/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.DataLossError'>, Unable to open table file /checkpoints/nasnet_v1_2017_10_04/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```
It also happens with the mobile net

**Comment by reedwm** [comment] 2017-12-05 00:18
@sguada, do you know what the issue is?

**Comment by jorgemf** [comment] 2017-12-05 01:41
@reedwm In other code I have, it seems to work with the nightly build. So probably an issue with 1.4. Feel free to close it

**Comment by reedwm** [comment] 2017-12-05 01:59
Closing, feel free to repoen if you determine the issue is still on nightly.

**Closed by reedwm** 2017-12-05 01:59 UTC
Labels: stat:awaiting tensorflower

**Comment by Tauranis** [comment] 2018-01-18 18:21
I've tested on my machine with TF 1.4 with all networks and checkpoints available [here](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models)

Nasnet and mobilenet were the only ones which crashed with this error.

**Comment by Tauranis** [comment] 2018-01-18 21:20
Thanks @jorgemf . I'll check

**Comment by Benzzzxxx** [comment] 2018-10-05 03:05
checkpoint_exclude_scopes=aux_7/aux_logits/FC,final_layer/FC     How to find the layer name and to set correctly ? In nasnet.py file, I only find the "final_layer"and don't know where is the " aux7 " layer. Tank you for your answer.
