### ISSUE TITLE
pixel_domain_adaptation Research Folder Update

### ISSUE THREAD

**Issue by gcscoding** [tensorflow/models#3183] opened 2018-01-17 21:55 UTC
### System information
- **What is the top-level directory of the model you are using**: Domain_Adaptation
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mint Linux
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.4
- **Bazel version (if compiling from source)**: 
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
Code in models/research/domain_adaptation/pixel_domain_adaptation/ does not appear to have been updated after the research folder transition was made. Is it possible to update these files to match new directory differences? I keep reaching roadblocks when trying to run through the instructions provided because of directory errors. Program unable to find the correct folders needed to run.

**Comment by aselle** [comment] 2018-01-21 01:03
@nealwu, this seems to be the case, when I try to run bazel build research/domain_adaption/pxiel_domain_adaptation. Could you PTAL?

**Comment by nealwu** [comment] 2018-01-22 21:37
Re-assigning to the [code owners](https://github.com/tensorflow/models/blob/master/CODEOWNERS) for domain_adaptation: @bousmalis and @dmrd

**Comment by tensorflowbutler** [comment] 2020-01-29 23:30
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 09:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 09:57 UTC
Labels: type:build/install
