### ISSUE TITLE
Textsum error: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by abslamp** [tensorflow/models#4036] opened 2018-04-20 01:29 UTC
--------------------
### System information
- **What is the top-level directory of the model you are using**: Textsum
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7
- **Bazel version (if compiling from source)**: 0.12.0(binary)
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: seq2seq_attention --mode=train --article_key=article --abstract_key=abstract --data_path=D:/TS/data/training-* --vocab_path=D:/TS/data/vocab --log_root=D:/TS/textsum/log_root --train_dir=D:/TS/textsum/log_root/train

### Source code / logs
Simply used the toy data provided with Textsum and renamed it to training-0. The example training code (changed dir to use in cmd) caused many of this error:

Exception in thread Thread-xxx:
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "\\?\C:\Users\xxx\AppData\Local\Temp\Bazel.runfiles_0br8l4_4\runfiles\__main__\textsum\batch_reader.py", line 139, in _FillInputQueue
    data.ToSentences(article, include_token=False)]
  File "\\?\C:\Users\xxx\AppData\Local\Temp\Bazel.runfiles_0br8l4_4\runfiles\__main__\textsum\data.py", line 215, in ToSentences
    return [s for s in s_gen]
  File "\\?\C:\Users\xxx\AppData\Local\Temp\Bazel.runfiles_0br8l4_4\runfiles\__main__\textsum\data.py", line 215, in <listcomp>
    return [s for s in s_gen]
  File "\\?\C:\Users\xxx\AppData\Local\Temp\Bazel.runfiles_0br8l4_4\runfiles\__main__\textsum\data.py", line 189, in SnippetGen
    start_p = text.index(start_tok, cur)
**TypeError: a bytes-like object is required, not 'str'**

**Comment by wei-yuan** [comment] 2018-05-01 07:43
@yhliang2018  Same error here, have you figured out yet?

**Comment by yhliang2018** [comment] 2018-05-01 16:47
@k-w-w Do you have any idea on this issue? Feel free to add people to this thread if they can help.

**Comment by k-w-w** [comment] 2018-05-01 18:02
It looks like this issue appears when using python 3 (error does not appear with python 2).

A quick fix would be to decode the bytes in `_GetExFeatureText(self, ex, key)` in `batch_reader.py`:
```
return ex.features.feature[key].bytes_list.value[0].decode('utf-8')
```
I'll submit a PR with this change if the code runs to completion without error.

**Comment by ersinyar** [comment] 2018-05-09 14:30
@k-w-w That trick does not work for me. I still have the same problem. Have you found a way to solve this issue?

**Comment by k-w-w** [comment] 2018-05-09 17:54
@ersinyar Are you getting the same error? Also are you running with python 3?

**Comment by ersinyar** [comment] 2018-05-10 06:46
I am getting a similar error. I was following the post given in [https://eilianyu.wordpress.com/2016/10/17/text-summarization-using-sequence-to-sequence-model-in-tensorflow-and-gpu-computing/](url). When I try to convert from text to binary before training as explained in the post, I get an error stating that

```TypeError: "b'AFP'" has type str, but expected one of: bytes

I run on Python 3 and latest Tensorflow. The post I follow uses TF 0.9.0. First, I thought that latest version of TF might be problematic and I tried different versions. But, I kept getting the same error.

**Comment by k-w-w** [comment] 2018-05-10 19:08
@ersinyar The code was most likely intended to run with Python 2, so if that is available to you I would recommend using Py2 instead of applying the fixes. Dealing with differing string encoding can be pretty messy. If you must use Py3, applying the changes in [this commit](https://github.com/tensorflow/models/commit/9f58c3dda7f2f832f3c7b64985be1326bc5efc22) should work.

**Comment by Hexa4C** [comment] 2018-12-28 08:45
> It looks like this issue appears when using python 3 (error does not appear with python 2).
> 
> A quick fix would be to decode the bytes in `_GetExFeatureText(self, ex, key)` in `batch_reader.py`:
> 
> ```
> return ex.features.feature[key].bytes_list.value[0].decode('utf-8')
> ```
> I'll submit a PR with this change if the code runs to completion without error.

I got the same error using python3. And this WORKS for me! 
Thank you!

**Comment by EricZhang90** [comment] 2019-06-28 18:40
I am getting the same error:
`/models-master/research/object_detection/utils/label_map_util.py", line 138, in load_labelmap
    label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'`

**Comment by Anatolist** [comment] 2019-11-28 12:45
**System information**
****What is the top-level directory of the model you are using**: Object_Detection
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** No
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**Ubuntu 18
**TensorFlow installed from (source or binary):** binary
**TensorFlow version (use command below):** 2.0
Bazel version (if compiling from source): 
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: python3 legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

I 've configured my model, and when I run this command I get the error:
 TypeError: a bytes-like object is required, not 'str'
Could you give me more explanations to fix my problem? Thank U

**Comment by yhliang2018** [comment] 2020-01-29 21:11
You may follow the changes in [this commit](https://github.com/tensorflow/models/commit/9f58c3dda7f2f832f3c7b64985be1326bc5efc22) to fix this. Close this bug for now.

**Closed by yhliang2018** 2020-01-29 21:11 UTC
Labels: stat:awaiting owner
