### ISSUE TITLE
Unable to train model!! All these errors show up

### ISSUE THREAD

**Issue by marufm1** [tensorflow/models#5073] opened 2018-08-12 22:48 UTC
(tensorflow1) D:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From C:\Users\BATMAN\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From D:\tensorflow1\models\research\object_detection\legacy\trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\BATMAN\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "C:\Users\BATMAN\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "D:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 290, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "D:\tensorflow1\models\research\slim\deployment\model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "D:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 203, in _create_losses
    prediction_dict = detection_model.predict(images, true_image_shapes)
  File "D:\tensorflow1\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 680, in predict
    self._anchors.get(), image_shape, true_image_shapes))
  File "D:\tensorflow1\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 767, in _predict_second_stage
    anchors, image_shape_2d, true_image_shapes)
  File "D:\tensorflow1\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 1234, in _postprocess_rpn
    clip_window=clip_window)
  File "D:\tensorflow1\models\research\object_detection\core\post_processing.py", line 402, in batch_multiclass_non_max_suppression
    parallel_iterations=parallel_iterations)
  File "D:\tensorflow1\models\research\object_detection\utils\shape_utils.py", line 228, in static_or_dynamic_map_fn
    return tf.map_fn(fn, elems, dtype, parallel_iterations, back_prop)
  File "C:\Users\BATMAN\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 409, in map_fn
    swap_memory=swap_memory)
  File "C:\Users\BATMAN\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2934, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\Users\BATMAN\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2720, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\Users\BATMAN\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2662, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "C:\Users\BATMAN\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 399, in compute
    packed_fn_values = fn(packed_values)
  File "D:\tensorflow1\models\research\object_detection\core\post_processing.py", line 378, in _single_image_nms_fn
    additional_fields=per_image_additional_fields)
  File "D:\tensorflow1\models\research\object_detection\core\post_processing.py", line 150, in multiclass_non_max_suppression
    score_threshold=score_thresh)
TypeError: non_max_suppression() got an unexpected keyword argument 'score_threshold'

**Comment by Manish-rai21bit** [comment] 2018-08-14 05:07
I had this error but after I updated to tensorflow 1.9, I don't get this error.

**Comment by JamesMsuya** [comment] 2018-08-15 15:14
I have tensorflow 1.16 but stil got same issues. What might be workaround for that

**Comment by karmel** [comment] 2018-08-19 15:42
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/models/issues/new). Please provide all the information it asks. Thank you.

**Comment by harshini-gadige** [comment] 2018-11-20 23:32
Closing as this is in "awaiting response" status for more than a week.  Please add comments if any, we will reopen it. Thanks !
This should not be a problem with the latest tensorflow version. Please try and post comments if any.

**Closed by harshini-gadige** 2018-11-20 23:32 UTC
Labels: stat:awaiting response
