### ISSUE TITLE
TypeError: TF_SessionRun_wrapper: expected all values in input dict to be ndarray

### ISSUE THREAD

**Issue by 757227488** [tensorflow/models#6270] opened 2019-02-26 10:02 UTC
* **### **OS Platform and Distribution** ### 👍 
  **win10**
* **TensorFlow installed from (source or binary)**:
  Anaconda3
* **TensorFlow version (use command below)**:
  1.13.0-rcl
* **Python version (use command below)**:
  3.7.1

### Source code:

import tensorflow as tf;
a= tf.add(2,4)
b=tf.multiply(a,5)
sess=tf.Session()
dict={a:100}
sess.run(b,feed_dict=dict)
sess.close()

### log:
Traceback (most recent call last):
  File "D:/python/test/sessionTest.py", line 6, in <module>
    sess.run(b,feed_dict=dict)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
TypeError: TF_SessionRun_wrapper: expected all values in input dict to be ndarray

**Comment by tensorflowbutler** [comment] 2019-02-27 00:17
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yugushihuang** [comment] 2019-02-28 22:42
Follow.. I have face the exactly same issue

**Comment by atercaelum** [comment] 2019-02-28 23:25
I have the same issue. I'm running Visual Code.

Btw, @757227488  i ran into issue using python 3.7 and tensor flow. i read tensorflow is not supporting python 3.7


Here is my info:

* **### **OS Platform and Distribution** ### 
  **win10**
* **TensorFlow installed from (binary)**:
  Anaconda3
* **TensorFlow version ()**:
  1.13.0-rcl
* **Python version ()**:
  3.6.8

i ran example from rasa after i already build a model:

from rasa_nlu.model import Metadata, Interpreter
import json

def pprint(o):
 # small helper to make dict dumps a bit prettier
    print(json.dumps(o, indent=2))

interpreter = Interpreter.load('./models/current/nlu')
pprint(interpreter.parse(u"Hello"))

I might be missing a lib because it worked fine when i ran in the windows power shell.

**Comment by atercaelum** [comment] 2019-03-01 00:22
after installing rasa_core i saw that it installed many other libs and uninstalled and installed tensorflow, it's current version is 1.13.1. i now don't have this error.

**Comment by Azizimj** [comment] 2019-04-13 20:37
Same issue. Tried 
```
conda update conda
conda update anaconda
```
did not work.
I got this error after running
```
pip install -U tensorflow
```

**Comment by mrevow** [comment] 2019-04-13 22:33
I ran into the same issue. I don't think it is directly an issue with tf [see](https://github.com/tensorflow/tensorflow/issues/25729#issuecomment-473003935) In my case I had not changed anything in tf but installed some other packages which reinstalled amongst other things numpy. The following fixed the issue for me

pip uninstall numpy  # Keep repeating till all version of numpy are uninstalled
pip install numpy

**Comment by akmishra-nitr** [comment] 2019-05-07 17:55
@mrevow Thank you! I was facing a similar problem while running TF based script for image processing. Re-installing the version of numpy solved it for me. 

Windows 7 | Installed from Anaconda 3 | TF version: 1.13.1 | Python version: 3.6.3

**Comment by ymodak** [comment] 2019-06-07 23:22
Closing this issue since its resolved. Feel free to reopen if still have any further questions. Thanks !

**Closed by ymodak** 2019-06-07 23:22 UTC
Labels: stat:awaiting response, type:support

**Comment by MarcosDana** [comment] 2020-05-20 15:15
> I ran into the same issue. I don't think it is directly an issue with tf [see](https://github.com/tensorflow/tensorflow/issues/25729#issuecomment-473003935) In my case I had not changed anything in tf but installed some other packages which reinstalled amongst other things numpy. The following fixed the issue for me
> 
> pip uninstall numpy # Keep repeating till all version of numpy are uninstalled
> pip install numpy

U have saved me!
