### ISSUE TITLE
object_detection eval prefetch_queue size hardcoded to 500

### ISSUE THREAD

**Issue by pimpke** [tensorflow/models#4202] opened 2018-05-08 10:46 UTC
Why is object_detection eval prefetch_queue size always set to 500 and not taken from eval_input_reader part of the config file?
https://github.com/tensorflow/models/blob/master/research/object_detection/evaluator.py#L71

**Comment by tensorflowbutler** [comment] 2018-05-10 01:30
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bitfort** [comment] 2018-05-18 16:04
Adding someone who can help.

**Comment by harshini-gadige** [comment] 2018-11-09 21:50
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-11-09 21:50 UTC
Labels: stat:awaiting owner
