### ISSUE TITLE
Running SyntaxNet in any sort of IDE

### ISSUE THREAD

**Issue by k1trd** [tensorflow/models#1783] opened 2017-06-27 19:05 UTC
Hi,
I post my question week ago in stack-overflow but nobody answered so I decide to ask it here , maybe finally somebody can help me  
I am working on SyntaxNet and syntactic parsing in English language with NN, I installed SyntaxNet on two different Ubuntu servers, one with GPU  and the other one without GPU, I successfully run SyntaxNet on both  machine and compared the performance also I changed the system in a way  that it is processing my data with my desire parameters and desired output format. (I wrote a program around the SytaxNet to control its parameters and etc). also I can fully control the pipeline of the SyntaxNet by using scriptfile that people suggest in other posts as well.

Now I need to change some part of the code of SyntaxNet and I need to  trace it step by step (having a program in debugging mode) so is there anyway that I can load a SytaxNet in any IDE like pycharm (and it is working) so I can trace it.

It is highly appreciated any sort of help that you can offer.

@calberti @andorardo

**Comment by ruipiresc-work** [comment] 2017-06-29 09:33
i need the same think

**Comment by aselle** [comment] 2017-07-06 17:13
I suspect it is possible, but it will require some programming script work. PyCharm may require you to use a specific version of Python, but if you can install tensorflow there, you should be able to run TensorFlow there too and thus syntaxnet.

However, this really is more amenable to StackOverflow, and if nobody has done it there, it is less likely anyone in this forum will know. Marking as community support. Good luck!

**Comment by k1trd** [comment] 2017-07-06 20:48
@aselle I am not really in mandate to use pycharm. ( i used pycharm for other tensorflow project before) but any sort of solution (IDE, terminal, etc ) that helps me to apply some changes in syntaxnet code directly would be really beneficial for me, 

PS.   adding couple lines and then compile the whole syntaxnet with bazel again not really works for me I need a way that I can trace my code when i insert it inside syntaxnet code

**Comment by adrinjalali** [comment] 2017-08-03 17:05
@aselle can you run any of [the examples](https://github.com/tensorflow/models/blob/master/syntaxnet/examples/dragnn)? Or the the default [parser](https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/parser_eval.py)? I suspect you might also reach this error or similar: https://github.com/tensorflow/models/issues/1826

**Comment by ymodak** [comment] 2018-10-31 20:57
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Closed by ymodak** 2018-10-31 20:58 UTC
Labels: stat:community support, type:support
