### ISSUE TITLE
ptb_word_lm.py no longer working for multi-gpu with tf 1.11

### ISSUE THREAD

**Issue by pcgreat** [tensorflow/models#5403] opened 2018-09-30 04:30 UTC
when running with multi-gpu, ptb_word_lm.py will throw an exception when OptimizeGraph(). I tried from tf 1.8-1.11, and this bug can be reproduced from all versions.

```
Traceback (most recent call last):
  File "ptb_word_lm.py", line 527, in <module>
    tf.app.run()
  File "/home/chao/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "ptb_word_lm.py", line 498, in main
    util.auto_parallel(metagraph, m)
  File "/home/chao/Project/models/tutorials/rnn/ptb/util.py", line 96, in auto_parallel
    optimized_graph = tf_optimizer.OptimizeGraph(rewriter_config, metagraph)
  File "/home/chao/anaconda3/lib/python3.6/site-packages/tensorflow/python/grappler/tf_optimizer.py", line 39, in OptimizeGraph
    verbose, graph_id, status)
  File "/home/chao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Non-existent input AutoParallel-Replica-0/AutoParallel-Div-Const for node AutoParallel-Replica-0/AutoParallel-Div-AutoParallel-Replica-0/Train/Model/GradientDescent/update_Model/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/bias/ApplyGradientDescent
```

### System information
- **What is the top-level directory of the model you are using**: tutorials
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.11.0-0-gc19e29306c 1.11.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**: GTX 1080 Ti 11G
- **Exact command to reproduce**:  python ptb_word_lm.py --data_path=$HOME/ProjData/ptb/ --model=small --num_gpus 3

**Comment by tsungruihon** [comment] 2018-11-01 02:15
the same problem as yours.

**Comment by JiabinYang** [comment] 2019-02-15 03:48
the same problem as yours with tf 1.12

**Comment by tensorflowbutler** [comment] 2020-01-29 23:09
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:39 UTC
