### ISSUE TITLE
Rewrite models/tutorials/image/cifar10_estimator to remove deprecated methods

### ISSUE THREAD

**Issue by KevinLucidyne** [tensorflow/models#4921] opened 2018-07-27 17:48 UTC
What is the top-level directory of the model you are using: models/tutorials/image/cifar10_estimator
Have I written custom code; No.
OS Platform and Distribution: Ubuntu 17.10
TensorFlow installed from: N/A
TensorFlow version: 1.9 (master branch)
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: See https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10_estimator

The master branch version of models/tutorials/image/cifar10_estimator/cifar10_main.py is using deprecated functions.  Please rewrite because this is the most advanced example posted for using multiple GPUs.

When you run this program you get the warnings

```
WARNING:tensorflow:From pslinknet.py:397: Experiment.__init__ (from tensorflow.contrib.learn.python.learn.experiment) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.estimator.train_and_evaluate. You will also have to convert to a tf.estimator.Estimator.
WARNING:tensorflow:From /home/gradescan/miniconda3/envs/untitled/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:279: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.

```

**Comment by KevinLucidyne** [comment] 2018-07-30 21:15
Done.

**Comment by diego898** [comment] 2019-03-26 14:58
In the spirit of this issue, while this tutorial be rewritten for tensorflow 2.0?

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ravikyram** [comment] 2020-07-10 09:22
@KevinLucidyne 
Is this still an issue?
Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-08-12 07:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-08-12 07:32 UTC
Labels: stat:awaiting response, type:support
