### ISSUE TITLE
TensorRT links for the models are not working

### ISSUE THREAD

**Issue by ds2268** [tensorflow/models#4422] opened 2018-06-01 13:49 UTC
### System information
- **What is the top-level directory of the model you are using**: research/tensorrt
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: centOS 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4.1
- **Bazel version (if compiling from source)** N/A:
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: Tesla K80
- **Exact command to reproduce**: N/A

### Describe the problem
The links provided for the Resnet models are not working: Permission denied.

Anonymous caller does not have storage.objects.get access to download.tensorflow.org/models/official/resnetv1_imagenet_savedmodel.tar.gz.

**Comment by HonoluluHenk** [comment] 2019-01-04 11:33
Probably a duplicate of  #4422

**Comment by yongwww** [comment] 2019-06-13 23:37
I met the same issue

**Comment by tensorflowbutler** [comment] 2020-01-29 23:21
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:44 UTC
