### ISSUE TITLE
I have a license plate detection project, how can I crop the image after the detection object?

### ISSUE THREAD

**Issue by cecepnrhya** [tensorflow/models#7949] opened 2019-12-16 03:06 UTC
![image](https://user-images.githubusercontent.com/46098300/70876282-95400d80-1feb-11ea-83ea-ba1e90ada596.png)

how to add the code?

# Import packages
import os
import cv2
import numpy as np
import tensorflow as tf
import sys
from PIL import Image

# This is needed since the notebook is stored in the object_detection folder.
sys.path.append("..")

# Import utilites
from utils import label_map_util
from utils import visualization_utils as vis_util

# Name of the directory containing the object detection module we're using
MODEL_NAME = 'plate'
IMAGE_NAME = 'test1.jpg'

# Grab path to current working directory
CWD_PATH = os.getcwd()

# Path to frozen detection graph .pb file, which contains the model that is used
# for object detection.
PATH_TO_CKPT = os.path.join(CWD_PATH,MODEL_NAME,'frozen_inference_graph.pb')

# Path to label map file
PATH_TO_LABELS = os.path.join(CWD_PATH,'training','labelmap.pbtxt')

# Path to image
PATH_TO_IMAGE = os.path.join(CWD_PATH,IMAGE_NAME)

# Number of classes the object detector can identify
NUM_CLASSES = 1

# Load the label map.
# Label maps map indices to category names, so that when our convolution
# network predicts `5`, we know that this corresponds to `king`.
# Here we use internal utility functions, but anything that returns a
# dictionary mapping integers to appropriate string labels would be fine
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

# Load the Tensorflow model into memory.
detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')

    sess = tf.Session(graph=detection_graph)

# Define input and output tensors (i.e. data) for the object detection classifier

# Input tensor is the image
image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')

# Output tensors are the detection boxes, scores, and classes
# Each box represents a part of the image where a particular object was detected
detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')

# Each score represents level of confidence for each of the objects.
# The score is shown on the result image, together with the class label.
detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')

# Number of objects detected
num_detections = detection_graph.get_tensor_by_name('num_detections:0')

# Load image using OpenCV and
# expand image dimensions to have shape: [1, None, None, 3]
# i.e. a single-column array, where each item in the column has the pixel RGB value
image = cv2.imread(PATH_TO_IMAGE)
image_expanded = np.expand_dims(image, axis=0)

# Perform the actual detection by running the model with the image as input
(boxes, scores, classes, num) = sess.run(
    [detection_boxes, detection_scores, detection_classes, num_detections],
    feed_dict={image_tensor: image_expanded})

# Draw the results of the detection (aka 'visulaize the results')

vis_util.visualize_boxes_and_labels_on_image_array(
    image,
    np.squeeze(boxes),
    np.squeeze(classes).astype(np.int32),
    np.squeeze(scores),
    category_index,
    use_normalized_coordinates=True,
    line_thickness=8,
    min_score_thresh=0.60)

print(test1.jpg)

     
# All the results have been drawn on image. Now display the image.
cv2.imshow("object detector", image)

# Press any key to close the image
cv2.waitKey(0)

# Clean up
cv2.destroyAllWindows()

**Comment by tensorflowbutler** [comment] 2019-12-17 00:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cecepnrhya** [comment] 2019-12-17 04:04
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

OS Platform Raspbian buster

TensorFlow version-1.15.0
Raspberry Pi4 2 gb

**Comment by KamalChhirang** [comment] 2019-12-28 14:05
Something like this:

 (boxes, scores, classes, num) =  sess.run([detection_boxes, detection_scores, detection_classes, num_detections],feed_dict={image_tensor: expended_image})


left = int(np.floor(boxes[0][j][1]*img.size[0]))
top = int(np.floor(boxes[0][j][0]*img.size[1]))
right = int(np.floor(boxes[0][j][3]*img.size[0]))
bottom = int(np.floor(boxes[0][j][2]*img.size[1]))           


 img = img.crop((left, top, right, bottom))

Boxes is a 3 dimensional array. First dimension is for image. For example boxes[0] for first image prediction, boxes[1] for second image prediction. 

Second dimension is for different objects inside a single image. Third dimension is for top, left, bottom, right.

**Comment by ravikyram** [comment] 2020-06-15 12:27
@cecepnrhya 

Is this still an issue?. Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-07-14 09:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-14 09:24 UTC
Labels: stat:awaiting response, type:support
