### ISSUE TITLE
attention_ocr: train run too long time

### ISSUE THREAD

**Issue by congyingTech** [tensorflow/models#6771] opened 2019-05-13 01:34 UTC
I use python train.py --checkpoint=model.ckpt-399731 to train the model, but two days passed, the model has not been trained completely, I want to know why? 
who can give me some useful advice? 
thanks a lot

**Comment by tensorflowbutler** [comment] 2019-05-14 00:20
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2020-03-18 21:15
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ravikyram** [comment] 2020-06-25 07:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by xavigibert** [comment] 2020-06-25 17:54
I'll updated the readme to include --max_number_of_steps=50000 in the fine-tuning examples. The default value for this flag is 10 million, which takes forever and it defeats the purpose of fine-tuning, since the initial weights are completely forgotten after so many iterations.
Thank you for reporting this issue.

**Closed** 2020-09-18 16:17 UTC
Labels: stalled, stat:awaiting response, type:support
