### ISSUE TITLE
Build fail with error 'google/protobuf/stubs/common.h' file not found

### ISSUE THREAD

**Issue by coreych** [tensorflow/models#1116] opened 2017-03-05 15:12 UTC
https://github.com/tensorflow/models/tree/master/syntaxnet
 
The following command threw an error on Mac OS X during build. 

bazel test --linkopt=-headerpad_max_install_names 
syntaxnet/... util/utf8/...

ERROR: /private/var/tmp/_bazel_coreychong/12e1cac900a5b57469553695a912bfcb/external/org_tensorflow/tensorflow/contrib/ffmpeg/BUILD:36:1: C++ compilation of rule '@org_tensorflow//tensorflow/contrib/ffmpeg:encode_audio_op_cc' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 47 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/org_tensorflow/tensorflow/contrib/ffmpeg/encode_audio_op.cc:18:
In file included from external/org_tensorflow/tensorflow/contrib/ffmpeg/ffmpeg_lib.h:22:
In file included from external/org_tensorflow/tensorflow/core/lib/core/status.h:22:
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/core/lib/core/error_codes.pb.h:9:10: fatal error: 'google/protobuf/stubs/common.h' file not found
#include <google/protobuf/stubs/common.h>
         ^
1 error generated.
INFO: Elapsed time: 7.281s, Critical Path: 4.35s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:binary_segment_state_test                                 NO STATUS
//syntaxnet:binary_segment_transitions_test                           NO STATUS
//syntaxnet:char_properties_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:morphology_label_set_test                                 NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:segmenter_utils_test                                      NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 17 tests: 1 fails to build and 16 were skipped.

Protobuf version ==3.0.0b2 followed setup instructions and Bazel version 0.4.3.
Anyone encountered this error before?

**Comment by bakarov** [comment] 2017-03-06 06:51
Problem with `common.h` can be fixed by installing protobuf-dev package, e.g. for Ubuntu:

`sudo apt-get install libprotobuf-dev protobuf-compiler`

But that I'm getting an error:

```
fatal error: google/protobuf/arena.h: No such file or directory compilation terminated.

```

People [say](https://github.com/BVLC/caffe/issues/4988) that it can be caused by the outdated version of protobuf, but I have the latest version 3.0.0b2.

**Comment by prb12** [comment] 2017-03-06 21:14
@calberti I was assuming this was a generic TF installation problem, but then noticed you have detailed instructions in your README.md including how to install protobuf.  Is it possible these are now out of date?

**Comment by coreych** [comment] 2017-03-07 00:18
It worked! Executed 16 out of 17 tests: 17 tests pass.

Instead of following setup instructions using pip and version 3.0.0b2.
All i did was 
> brew install protobuf

In home-brew, protobuf==3.2.0

Not sure if I should remove the previous 3.0.0b2 installed using pip?

**Comment by ankanch** [comment] 2017-09-13 09:59
I have the same issue, 
Build FAILED.

"D:\caffe2\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\caffe2\build\caffe2\Caffe2_CPU.vcxproj" (default target) (3) ->
"D:\caffe2\build\caffe2\proto\Caffe2_PROTO.vcxproj" (default target) (4) ->
(ClCompile target) ->
  D:\caffe2\build\caffe2/proto/prof_dag.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.h': N
o such file or directory (compiling source file D:\caffe2\build\caffe2\proto\prof_dag.pb.cc) [D:\caffe2\build\caffe2\proto\Caffe2
_PROTO.vcxproj]
  D:\caffe2\build\caffe2/proto/caffe2_legacy.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.
h': No such file or directory (compiling source file D:\caffe2\build\caffe2\proto\caffe2_legacy.pb.cc) [D:\caffe2\build\caffe2\pr
oto\Caffe2_PROTO.vcxproj]
  D:\caffe2\build\caffe2/proto/predictor_consts.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/comm
on.h': No such file or directory (compiling source file D:\caffe2\build\caffe2\proto\predictor_consts.pb.cc) [D:\caffe2\build\caf
fe2\proto\Caffe2_PROTO.vcxproj]
  D:\caffe2\build\caffe2/proto/hsm.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.h': No suc
h file or directory (compiling source file D:\caffe2\build\caffe2\proto\hsm.pb.cc) [D:\caffe2\build\caffe2\proto\Caffe2_PROTO.vcx
proj]
  D:\caffe2\build\caffe2/proto/caffe2.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.h': No
such file or directory (compiling source file D:\caffe2\build\caffe2\proto\caffe2.pb.cc) [D:\caffe2\build\caffe2\proto\Caffe2_PRO
TO.vcxproj]
  D:\caffe2\build\caffe2/proto/metanet.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.h': No
 such file or directory (compiling source file D:\caffe2\build\caffe2\proto\metanet.pb.cc) [D:\caffe2\build\caffe2\proto\Caffe2_P
ROTO.vcxproj]


"D:\caffe2\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\caffe2\build\caffe2\Caffe2_CPU.vcxproj" (default target) (3) ->
"D:\caffe2\build\caffe\proto\Caffe_PROTO.vcxproj" (default target) (5) ->
  D:\caffe2\build\caffe/proto/caffe.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.h': No su
ch file or directory [D:\caffe2\build\caffe\proto\Caffe_PROTO.vcxproj]

    0 Warning(s)
    7 Error(s)

**Comment by OLGKAD** [comment] 2017-10-19 07:52
@bakarov, I'm having exactly the same problem. I would highly appreciate it, if you could share with us how you resolved it.

**Comment by mmazloum** [comment] 2018-01-17 00:07
same here with protobuf 3.5.1 on XCode for a basic C++ project. The compiler asks to turn angles into quotes but this turns out to spread further similar errors on all protobuf other includes

**Comment by itsmeolivia** [comment] 2018-02-08 01:03
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by mmazloum** [comment] 2018-02-08 10:33
@itsmeolivia I added a comment on this issue because I had the same problem but it's not related to tensorflow directly.

The issue is that the XCode IDE (Mac OS users only) won't link with the protocolbuffer library, so any header file like the ones suggested above ( 'google/protobuf/stubs/common.h') included in a XCode project won't compile.

Feel free to ask if you need more info.

**Comment by karmel** [comment] 2018-02-22 19:45
It sounds like this is an XCode/protobuf issue. This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Closed by karmel** 2018-02-22 19:45 UTC
