### ISSUE TITLE
DELF: extract_boxes.py, Check failed: NDIMs == dims() (2 vs. 3)

### ISSUE THREAD

**Issue by lanma901106** [tensorflow/models#6750] opened 2019-05-10 09:45 UTC
when I run the command below:
'''
python extract_boxes.py \
  --detector_path parameters/d2r_frcnn_20190411 \
  --detector_thresh 0.8 \
  --list_images_path list_images_detector.txt \
  --output_dir data/oxford5k_boxes \
  --output_viz_dir data/oxford5k_boxes_viz
'''
I meet the problem below when I use python3.6 and tensorflow=1.9:
"Check failed: NDIMS == dims() (2 vs. 3) Asking for tensor 2 dimensions from a tensor of 3 dimensions"

**Comment by tensorflowbutler** [comment] 2019-05-11 00:22
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by houguanqun** [comment] 2019-06-06 12:04
I have the same trouble, expecting your reply~

**Comment by lanma901106** [comment] 2019-06-10 09:35
I found it caused by the tensorflow version, you can try tensorflow==1.12.

**Comment by houguanqun** [comment] 2019-06-13 07:49
Thanks, what is your keras version?

**Comment by ymodak** [comment] 2019-07-17 04:36
Closing this issue since it's resolved. Thanks!

**Closed by ymodak** 2019-07-17 04:36 UTC
Labels: models: research
