### ISSUE TITLE
change YAMNet for micro，We're having trouble

### ISSUE THREAD

**Issue by xpdrycry** [tensorflow/models#9693] opened 2021-02-01 04:02 UTC
# Prerequisites
 tensorflow version : 2.4.0
code:
import tensorflow as tf
saved_model_dir = 'yamnet'
# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir) # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
output:
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): RFFT,ComplexAbs.
how to solve this trouble?
when we try to change to micro modul.cc
code:
def representative_dataset():
    for _ in range(100):
      data = np.random.rand(1, 244, 244, 3)
      yield [data.astype(np.float32)]
import tensorflow as tf
saved_model_dir = 'yamnet'
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()

output:
ConverterError: See console for info.
2021-02-01 12:00:03.073291: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-02-01 12:00:03.074291: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-02-01 12:00:05.674291: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2021-02-01 12:00:05.674291: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
2021-02-01 12:00:05.827291: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-02-01 12:00:05.838291: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x532130 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-01 12:00:05.838291: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-02-01 12:00:05.839291: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-02-01 12:00:05.840291: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-01 12:00:05.843291: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: n28liuljie
2021-02-01 12:00:05.844291: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: n28liuljie
loc(fused["yamnet_frames/tf_op_layer_RFFT/RFFT@__inference___call___23647", "StatefulPartitionedCall/yamnet_frames/tf_op_layer_RFFT/RFFT"]): error: 'tf.RFFT' op is neither a custom op nor a flex op
loc(fused["yamnet_frames/tf_op_layer_ComplexAbs/ComplexAbs@__inference___call___23647", "StatefulPartitionedCall/yamnet_frames/tf_op_layer_ComplexAbs/ComplexAbs"]): error: 'tf.ComplexAbs' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): RFFT,ComplexAbs.
Traceback (most recent call last):
  File "c:\users\administrator.1-pc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator.1-pc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.1-PC\AppData\Local\Programs\Python\Python38\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator.1-pc\appdata\local\programs\python\python38\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\administrator.1-pc\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\administrator.1-pc\appdata\local\programs\python\python38\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "c:\users\administrator.1-pc\appdata\local\programs\python\python38\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "c:\users\administrator.1-pc\appdata\local\programs\python\python38\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 50, in execute
    output_str = _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc(fused["yamnet_frames/tf_op_layer_RFFT/RFFT@__inference___call___23647", "StatefulPartitionedCall/yamnet_frames/tf_op_layer_RFFT/RFFT"]): 'tf.RFFT' op is neither a custom op nor a flex op
<unknown>:0: error: loc(fused["yamnet_frames/tf_op_layer_ComplexAbs/ComplexAbs@__inference___call___23647", "StatefulPartitionedCall/yamnet_frames/tf_op_layer_ComplexAbs/ComplexAbs"]): 'tf.ComplexAbs' op is neither a custom op nor a flex op
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): RFFT,ComplexAbs.

how to solve this problem?
thanks

**Comment by ravikyram** [comment] 2021-02-01 08:28
@xpdrycry 

Please, share colab link or simple standalone code with proper indentation and with supporting files(model files) to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by xpdrycry** [comment] 2021-02-07 06:30
tensorflow provide 3 type yamnet for computer , js , lite,but not for microprocessor,can you provide yamnet model for microprocees?

**Comment by dpwe** [comment] 2021-02-08 14:35
Duplicate of #9713

**Closed by dpwe** 2021-02-08 14:35 UTC
Labels: models:research, type:support
