### ISSUE TITLE
Skip-Thought Vectors: Alternative Data Source to expand vocabulary

### ISSUE THREAD

**Issue by sxhmilyoyo** [tensorflow/models#4553] opened 2018-06-15 18:54 UTC
### System information
- **What is the top-level directory of the model you are using**: N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**:  N/A
- **Bazel version (if compiling from source)**:  N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**:N/A
- **Exact command to reproduce**:N/A

### Describe the problem
For the vocabulary expansion in Skip-Thought Vectors, could I use the [GloVe word2vec for Twitter](https://nlp.stanford.edu/projects/glove/)? Since I want to build Skip-Thought Vectors for Tweets.
Thanks.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
N/A

**Comment by tensorflowbutler** [comment] 2018-06-16 06:36
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2020-01-29 23:19
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ravikyram** [comment] 2020-07-10 10:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-10 10:02 UTC
Labels: stat:awaiting response, type:support
