### ISSUE TITLE
detection_graph.get_tensor_by_name('detection_classes:0') is a numpy.ndarray that is filled by default with "1", which conflicts with the first item in your labelmap.pbtxt

### ISSUE THREAD

**Issue by isademigod** [tensorflow/models#7518] opened 2019-08-29 21:49 UTC
example output of detection_graph.get_tensor_by_name:

```
[[73.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
<class 'numpy.ndarray'>
```

if 73 is a car, and 1 is a person, how do I know if this is 1 car and 89 people, or any other arbitrary number of your first entry in labelmap. This makes calling functions based on what is detected impossible; for example:

```
        for i in classes.tolist():
            print(self.category_index[classes[i]]['name'])
```

I could just ignore everything after the last number greater than 1, but that's a band-aid solution.

could anyone suggest a viable workaround? something like 

```
detected = []
classlist = classes.tolist()
for i in range(self.num_detections):
     detected.append(classlist[i])
     
```
and then:
```
for i in detected:
            print(self.category_index[detected[i]]['name'])
```

**Comment by tensorflowbutler** [comment] 2019-08-30 12:11
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-22 11:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-22 11:27 UTC
Labels: models:research, stat:awaiting response, type:support
