### ISSUE TITLE
tar: Exiting with failure status due to previous errors

### ISSUE THREAD

**Issue by wzhen1996** [tensorflow/models#2100] opened 2017-08-02 19:42 UTC
I have uncompressed the validation set of imagenet successfully, but when it comes to the training set it appears like the following:

Uncompressing individual train tar-balls in the training data.
Processing: n01440764
tar: Skipping to next header 
tar: Exiting with failure status due to previous errors

**Comment by shivaniag** [comment] 2017-08-02 20:45
Could you please provide more details on this, e.g. code snippet and dataset link.

**Comment by wzhen1996** [comment] 2017-08-03 14:35
I'm trying to download the imagenet dataset following the instructions in inception directory.

**Comment by rohan100jain** [comment] 2017-08-14 14:41
Could you provide the exact commands you issued so that we can try and reproduce?

**Comment by davidparks21** [comment] 2017-10-16 18:32
I've downloaded imagenet twice now and am getting the same thing, download from image-net.org via:

`wget -c http://www.image-net.org/archive/stanford/fall11_whole.tar`

**Comment by ymodak** [comment] 2018-10-31 21:19
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-31 21:19 UTC
Labels: stat:awaiting response

**Comment by davidparks21** [comment] 2018-11-01 00:08
A followup note on this issue, after contacting the team at stanford they've added an MD5 hash of the download so you can now validate the download. I had numerous corrupt downloads, but finally got a good download that I was able to vaidate against their MD5 hash successfully.
