### ISSUE TITLE
Distributed training resnet with parameter_server strategy

### ISSUE THREAD

**Issue by wxjcn** [tensorflow/models#7988] opened 2019-12-27 00:57 UTC
### System information
- **What is the top-level directory of the model you are using**:/official/vision/image_classification
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:2.0.0
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:N/A
- **Exact command to reproduce**:

### Describe the problem
I am running distributed tensorflow training and when I tried to adopt the parameter server strategy I found there is no ps configure.

### Source code / logs
error information
```
Traceback (most recent call last):
  File "resnet_imagenet_main.py", line 276, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "resnet_imagenet_main.py", line 269, in main
    stats = run(flags.FLAGS)
  File "resnet_imagenet_main.py", line 93, in run
    tpu_address=flags_obj.tpu)
  File "/models-master/official/utils/misc/distribution_utils.py", line 154, in get_distribution_strategy
    return tf.distribute.experimental.ParameterServerStrategy()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/parameter_server_strategy.py", line 115, in __init__
    self, cluster_resolver=cluster_resolver)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/parameter_server_strategy.py", line 145, in __init__
    parameter_device=parameter_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/parameter_server_strategy.py", line 156, in _initialize_strategy
    self._initialize_multi_worker(cluster_resolver)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/parameter_server_strategy.py", line 221, in _initialize_multi_worker
    raise ValueError("The cluster spec needs to have `ps` jobs.")
ValueError: The cluster spec needs to have `ps` jobs.
```
the code in /official/utils/misc/distribution_utils.py :
```
elif worker_hosts:
    workers = worker_hosts.split(',')
    num_workers = len(workers)
    if num_workers > 1 and task_index < 0:
      raise ValueError('Must specify task_index when number of workers > 1')
    task_index = 0 if num_workers == 1 else task_index
    os.environ['TF_CONFIG'] = json.dumps({
        'cluster': {
            'worker': workers
        },
        'task': {'type': 'worker', 'index': task_index}
    })
```

**Comment by allenwang28** [comment] 2020-06-22 21:46
Hi,

Sorry for the delayed response. Since the bug was created we deprecated the model in question (resnet_imagenet_main.py) and replaced it with a [new trainer](https://github.com/tensorflow/models/blob/master/official/vision/image_classification/classifier_trainer.py).

The `ps` issue should be resolved: https://github.com/tensorflow/models/blob/master/official/utils/misc/distribution_utils.py#L153-L154

For now I'll close this bug. Please feel free to re-open it if this is reproduced.

**Closed by allenwang28** 2020-06-22 21:46 UTC
Labels: models:official, type:support
