### ISSUE TITLE
model_main.py freezes on execution

### ISSUE THREAD

**Issue by aanagn** [tensorflow/models#5432] opened 2018-10-03 11:53 UTC
When I try to run model_main.py, it generates the following errors, and then freezes.
https://pastebin.com/0f8mvDWS

------------------------

### System information
- **What is the top-level directory of the model you are using**:
- ** this is the output of ls -R **: https://pastebin.com/6yDdX3tM
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18.04LTS
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
v1.11.0-0-gc19e29306c 1.11.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
Cuda compilation tools, release 9.0, V9.0.176
cuDNN 7.2.1
- **GPU model and memory**:
03:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
04:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
RAM 64GB
- **Exact command to reproduce**:
python3 model_main.py --logtostderr --train_dir=/home/tanasi/Documents/models/research/object_detection/training/ --pipeline_config_path=/home/tanasi/Documents/models/research/object_detection/training/ssd_mobilenet_v1_pets.config 

Thanks in advance!

**Comment by flamato** [comment] 2018-10-05 14:21
I'm facing the same freeze using ubuntu 18.04, tf 1.9, cuda 9.0 and cudnn 7.1.2
An idea ?

**Comment by varun19299** [comment] 2018-10-06 16:16
Are there any scalars written to tensorboard?

**Comment by aanagn** [comment] 2018-10-08 07:55
@varun19299 I don't know, I was just trying to run a custom object detection following tutorials.

**Comment by dori-reichmann** [comment] 2018-10-22 14:33
It doesn't freezes it's a bug with logging to stdout.

**Comment by AlanNaoto** [comment] 2018-11-09 17:08
> It doesn't freezes it's a bug with logging to stdout.
> add:
> tf.logging.set_verbosity(tf.logging.INFO)
> to: 'model_main.py' (after the imports)

Thanks! Worked like a charm :)

**Comment by rringham** [comment] 2019-03-22 20:29
> It doesn't freezes it's a bug with logging to stdout.
> add:
> tf.logging.set_verbosity(tf.logging.INFO)
> to: 'model_main.py' (after the imports)

This is still broken.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:07
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:37 UTC
