### ISSUE TITLE
Feature Request: mask_ssd_mobilenet 

### ISSUE THREAD

**Issue by GustavZ** [tensorflow/models#3516] opened 2018-03-05 09:20 UTC
Is there already an implementation of a mask ssd network somewhere out there in the depth of the world wide web?
If not (i did not find one yet), why? Is anybody currently working on this by any chance?
Are there any well known incompatibilities i am currently not aware of?
The point is, mask rcnn is nice, but way too slow for mobile usage. So i really would like a ssd version of that.

With that being said, i will start working on this and i would really appreciate any help!

**Comment by tensorflowbutler** [comment] 2018-04-25 06:55
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-10-31 21:15
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-10-31 21:15 UTC
Labels: stat:awaiting response
