### ISSUE TITLE
tf.image.per_image_whitening error

### ISSUE THREAD

**Issue by bucktoothsir** [tensorflow/models#693] opened 2016-11-28 12:38 UTC
File "tensorflow/models/slim/preprocessing/cifarnet_preproces.py", line 70, in preprocess_for_train
    return tf.image.per_image_whitening(distorted_image)
AttributeError: 'module' object has no attribute 'per_image_whitening'

**Comment by poxvoculi** [comment] 2016-11-28 20:54
Please include the information requested in the new issue template.

**Comment by bucktoothsir** [comment] 2016-11-29 03:02
@poxvoculi I am sorry, where could I find the new issue template?

**Comment by poxvoculi** [comment] 2016-11-29 16:35
When you select the "New Issue" button the text box created should be filled with a template describing information that should be included to help diagnose the problem.  However, I see now that when this button is selected from within "tensorflow/models" (as this page is), that template is different and not very informative.  Try clicking moving to the "tensorflow/tensorflow/issues" directory and clicking "New Issue" to see a more full template.  Basically, I don't know what versions of software you're using and how you're trying to invoke a the program: I don't have a reproducible example.

**Comment by michaelisard** [comment] 2016-12-06 17:08
Closing due to lack of activity.

**Closed by michaelisard** 2016-12-06 17:08 UTC
Labels: awaiting response

**Comment by golmschenk** [comment] 2016-12-11 01:09
For anyone else who has this problem, `per_image_whitening` was replaced by `per_image_standardization` in v0.12.
