### ISSUE TITLE
tensorflow object_detection API trouble google.protobuf.text_format.ParseError: 158:3 : Message type "object_detection.protos.TrainConfig" has no field named "load_all_detection_checkpoint_vars".

### ISSUE THREAD

**Issue by wanglidog** [tensorflow/models#5451] opened 2018-10-07 15:27 UTC
When I was using train.py , I got this error. How to solve? 

google.protobuf.text_format.ParseError: 158:3 : Message type "object_detection.protos.TrainConfig" has no field named "load_all_detection_checkpoint_vars".

**Comment by netanel-s** [comment] 2018-10-07 15:34
Try recompiling the protobuf files:
```
# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.
```

**Comment by MariusMez** [comment] 2018-11-05 15:43
Googling this error, I'm here. Had the same error message and solved it by deleting the line where load_all_detection_checkpoint_vars = true appear in my pipeline config file. Seem's I were using an old version of pipeline config example.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:07
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:37 UTC

**Comment by basedrhys** [comment] 2020-03-30 02:25
Just for any future finders of this problem, I had accidentally deleted a `}` in my config file. Make sure the pipeline config file is properly written.

**Comment by jacoverster** [comment] 2021-12-03 07:15
Same error on my side, I had an extra " in the config file. Agree with @basedrhys.
