### ISSUE TITLE
Problem in "regularizers.py"

### ISSUE THREAD

**Issue by AmitSoli** [tensorflow/models#2957] opened 2017-12-04 17:23 UTC
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**: ('v1.4.0-rc1-11-g130a514', '1.4.0')
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: scripts/script_test_pretrained_models.sh

### Describe the problem
When trying to run the cognitive_mapping_and_planning/scripts/script_test_pretrained_models.sh, I get the error "ValueError('scale cannot be an integer: %s' % (scale,))" from the file tensorflow/contrib/layers/python/layers/regularizers.py.
This does not allow me to test the pretrained models.
I tried to track this issue and came to a conclusion that it might happen because of incorrect use of default parameters to function "l2_regularizer". However, I find it hard to believe that it is an error in the code and I do not know how to solve it.
When I tried forcing values instead of the one currently implemented, I got a bunch of other errors that showed me I am not in the right direction

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

Traceback (most recent call last):
  File "scripts/script_nav_agent_release.py", line 253, in <module>
    app.run()
  File "/home/amitx2/venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "scripts/script_nav_agent_release.py", line 89, in main
    _launcher(FLAGS.config_name, FLAGS.logdir)
  File "scripts/script_nav_agent_release.py", line 99, in _launcher
    _test(args)
  File "scripts/script_nav_agent_release.py", line 195, in _test
    summary_mode=args.control.test_mode)
  File "/run/user/1001/gvfs/smb-share:server=132.68.147.228,share=anpl/anp-dl-project/research/cognitive_mapping_and_planning/tfcode/cmp.py", line 285, in setup_to_run
    num_maps=len(task_params.map_crop_sizes))
  File "/run/user/1001/gvfs/smb-share:server=132.68.147.228,share=anpl/anp-dl-project/research/cognitive_mapping_and_planning/tfcode/cmp.py", line 196, in get_map_from_images
    mapper_arch.encoder, freeze_conv, wt_decay, is_training)
  File "/run/user/1001/gvfs/smb-share:server=132.68.147.228,share=anpl/anp-dl-project/research/cognitive_mapping_and_planning/tfcode/nav_utils.py", line 102, in get_repr_from_image
    with slim.arg_scope(resnet_v2.resnet_utils.resnet_arg_scope(resnet_is_training)):
  File "/home/amitx2/venv/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 257, in resnet_arg_scope
    weights_regularizer=regularizers.l2_regularizer(weight_decay),
  File "/home/amitx2/venv/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/regularizers.py", line 92, in l2_regularizer
    raise ValueError('scale cannot be an integer: %s' % (scale,))
ValueError: scale cannot be an integer: False

**Comment by reedwm** [comment] 2017-12-04 18:35
/CC @s-gupta, can you take a look?

**Comment by AmitSoli** [comment] 2017-12-07 16:30
Hi @reedwm, thanks for tagging @s-gupta .
I still can't figure out a solution that doesn't cause other issues when I apply it.

By the way, I was trying to find which TensorFlow version you were using but couldn't.  Could it be related to the version?

**Comment by reedwm** [comment] 2017-12-07 19:11
@AmitSoli unfortunately, I don't know anything about the model or have ever run it so I cannot comment.

/CC @jcdavidson can you also take a look or ping @s-gupta?

**Comment by trihuynh88** [comment] 2018-02-19 22:36
I am having the same problem. Were we able to fix this problem? @s-gupta

**Comment by DrifterFun** [comment] 2018-02-27 03:23
I meet the same problem. Have you solved the problem or could you give me some advice? @AmitSoli

**Comment by kuanting** [comment] 2018-03-07 18:02
I hit the same problem. Is there any solution yet?

**Comment by DrifterFun** [comment] 2018-03-08 05:15
@kuanting I try tensorflow from 1.3-1.7. However I find it is no use. This problem may not related to version of tensorflow.

**Comment by youkenhou** [comment] 2018-04-11 05:46
Hi guys, @AmitSoli @DrifterFun @trihuynh88 @kuanting . I ran into the same error as well several days ago.  I added ```float()``` in front of ```weight_decay``` in the file ```local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py```, referring to [here](https://github.com/tensorflow/models/pull/1707/files) and it seemed to be solved. I've not met any further error which is due to this change so far. Hope this will help you guys.

**Comment by wt-huang** [comment] 2018-10-20 01:57
Closing as the issue is resolved

**Closed by wt-huang** 2018-10-20 01:57 UTC
