### ISSUE TITLE
Inception v1 missing 5x5 Convolutions

### ISSUE THREAD

**Issue by JoshVarty** [tensorflow/models#2545] opened 2017-10-17 19:07 UTC
According to [Going Deeper with Convolutions](https://arxiv.org/pdf/1409.4842v1.pdf) the original inception modules had the following structure: 
![image](https://user-images.githubusercontent.com/1249087/31683804-ea24827c-b34b-11e7-9934-eaf4fc80234a.png)

However, while reviewing `models/research/slim/nets/inception_v1.py` I noticed that the inception modules were missing 5x5 convolutions and instead had an extra 3x3 convolution in `Branch_2`:
https://github.com/tensorflow/models/blob/6263692bf175b0e9160faa5614d5bdb1b237c878/research/slim/nets/inception_v1.py#L84-L97

Would you like me to submit a PR to correct this? If so, how would you like to handle the pre-trained networks that you have available for download?

/cc @nealwu @sguada

**Comment by nealwu** [comment] 2017-10-17 19:50
@derekjchow can you take a look? Looks like the model needs a fix, which means we'll want to retrain a new checkpoint.

**Comment by JoshVarty** [comment] 2017-10-17 21:41
Also there are a few other things I've noticed that might be mistakes or things I'm misunderstanding.

1. There are no LocalResponseNorm layers as indicated in the paper. 

![image](https://user-images.githubusercontent.com/1249087/31690584-26e15af4-b361-11e7-90e8-f7688c890068.png)

2. I'm not sure if the 1x1 Convolution at the front of the network is using the correct weights. However, the paper is missing the 1x1 Convolution from its weight table, so it's hard to say.

![image](https://user-images.githubusercontent.com/1249087/31690769-b191465a-b361-11e7-8c47-6a6277370461.png)

The images (in both the paper and code) are indicated to be of size `224x224`. 

| type | Output Size| Note|
| ------------- | ------------- | ------------- |
| Input      | 224x224x3  |
| Conv 7x7  | 112x112x64|
| Max Pool  | 56x56x64|
| Conv 1x1  | 56x56x64 | I think this is unnecessary since there is no dimensionality reduction
| Conv 3x3  | 56x56x192|

The code for these layers is available here: 
https://github.com/tensorflow/models/blob/6263692bf175b0e9160faa5614d5bdb1b237c878/research/slim/nets/inception_v1.py#L62-L71

**Comment by tensorflowbutler** [comment] 2020-01-29 23:32
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 09:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 09:52 UTC
