### ISSUE TITLE
400: Invalid request: https://raw.githubusercontent.com/tensorflow/models/master/inception/inception/data/

### ISSUE THREAD

**Issue by alifejon** [tensorflow/models#2432] opened 2017-09-22 00:19 UTC
When I am running note "Apply Pre-trained Inception V1 model to Images." in  slim_walkthrough.ipynb, I found invalid request error.

In https://github.com/tensorflow/models/blob/master/research/slim/datasets/imagenet.py#L86-L87, 
the base_url should be:
```
base_url = 'https://raw.githubusercontent.com/tensorflow/models/master/research/inception/inception/data/'
```

**Comment by asimshankar** [comment] 2017-10-04 07:36
@shlens @vincentvanhoucke - mind taking a look?

**Comment by shlens** [comment] 2017-10-04 14:02
This link should be updated to the slim/ repository. Code fixes welcome.

**Comment by wt-huang** [comment] 2018-10-20 02:02
Closing as the issue is resolved

**Closed by wt-huang** 2018-10-20 02:02 UTC
Labels: type:build/install
