### ISSUE TITLE
object_detection model zoo, can't download faster_rcnn_nas

### ISSUE THREAD

**Issue by luoxiaobatman** [tensorflow/models#2655] opened 2017-10-31 06:25 UTC
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to download.tensorflow.org/models/object_detection/faster_rcnn_nas_17_10_2017.tar.gz.
</Details>
</Error>

**Comment by aicentral** [comment] 2017-10-31 14:29
Same here I got:
Anonymous users does not have storage.objects.get access to download.tensorflow.org/models/object_detection/faster_rcnn_nas_17_10_2017.tar.gz.

**Comment by tombstone** [comment] 2017-10-31 16:06
duplicate of #2660

**Closed** 2017-10-31 16:06 UTC
