### ISSUE TITLE
SyntaxNet installation ：  TypeError: zeros_initializer() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by Iris6713** [tensorflow/models#930] opened 2017-01-20 03:07 UTC
SyntaxNet：master     bazel: 0.4.3
FAIL: //syntaxnet:beam_reader_ops_test 
FAIL: //syntaxnet:parser_trainer_test
FAIL: //syntaxnet:graph_builder_test
FAIL: //syntaxnet:reader_ops_test 
test.log:
TypeError: zeros_initializer() takes at most 1 argument (2 given)

Could someone tell me where I need to change?
Thank you in advance

**Comment by Gyunstorys** [comment] 2017-01-20 08:58
I have the same problem. 
:(

**Comment by asimshankar** [comment] 2017-01-20 18:14
Apologies for the trouble here. Unfortunately, the models in tensorflow/model are community maintained and not always up to date. This particular one seems like a duplicate of #902 - since there are a few things that need to be done to get syntaxnet working. 

@calberti : Could you take a look?

Contributions welcome!

**Closed by asimshankar** 2017-01-20 18:14 UTC
