### ISSUE TITLE
Data preprocess for Movinet trained on K600 and K400

### ISSUE THREAD

**Issue by Wangbk-dl** [tensorflow/models#11086] opened 2023-09-15 09:03 UTC
I'm curious about the data pre-process when training the Movinet on Kinetics600. Could you please help me with that?
 I've tried to finetune the checkpoint that you provided, but the result seems upset, and the final acc is much lower than I expected.
I guess that it results from the simple data pre-process that I defined by myself. Now, I didn't do anything special, the value of the pixels range from 0 to 1. Looking forward to your reply!

**Comment by laxmareddyp** [comment] 2024-02-02 18:07
Closing this as it is duplicate of [#11089](https://github.com/tensorflow/models/issues/11089)

**Closed by laxmareddyp** 2024-02-02 18:07 UTC
Labels: type:support, models:official
