### ISSUE TITLE
Tensorrt compilation issue

### ISSUE THREAD

**Issue by deepkshikha** [tensorflow/models#5080] opened 2018-08-13 13:51 UTC
Below is the last few lines when I run tensorrt.py with all parameters

Running INT8 graph
2018-08-13 13:42:29.249291: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 4
2018-08-13 13:42:30.004405: I tensorflow/contrib/tensorrt/convert/convert_graph.cc:419] MULTIPLE tensorrt candidate conversion: 2
2018-08-13 13:42:30.022164: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:3090] Max batch size= 128 max workspace size= 24292802
2018-08-13 13:42:30.022202: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:3104] finished op preparation
2018-08-13 13:42:30.022227: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:3112] OK
2018-08-13 13:42:30.022236: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:3113] finished op building
2018-08-13 13:42:30.198919: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:3090] Max batch size= 128 max workspace size= 2123190784
2018-08-13 13:42:30.199123: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:3104] finished op preparation
2018-08-13 13:42:30.199394: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:3112] OK
2018-08-13 13:42:30.199408: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:3113] finished op building
INFO:tensorflow:Starting execution
2018-08-13 13:42:34.610332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1, 2, 3
2018-08-13 13:42:34.610409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-13 13:42:34.610421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1 2 3
2018-08-13 13:42:34.610430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N Y Y Y
2018-08-13 13:42:34.610436: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   Y N Y Y
2018-08-13 13:42:34.610443: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 2:   Y Y N Y
2018-08-13 13:42:34.610449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 3:   Y Y Y N
2018-08-13 13:42:34.611918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 16248 MB memory) -> physical GPU (device: 0, name: Tesla V100-DGXS-32GB, pci bus id: 0000:07:00.0, compute capability: 7.0)
2018-08-13 13:42:34.612048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 16249 MB memory) -> physical GPU (device: 1, name: Tesla V100-DGXS-32GB, pci bus id: 0000:08:00.0, compute capability: 7.0)
2018-08-13 13:42:34.612138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 16249 MB memory) -> physical GPU (device: 2, name: Tesla V100-DGXS-32GB, pci bus id: 0000:0e:00.0, compute capability: 7.0)
2018-08-13 13:42:34.612221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 16249 MB memory) -> physical GPU (device: 3, name: Tesla V100-DGXS-32GB, pci bus id: 0000:0f:00.0, compute capability: 7.0)
INFO:tensorflow:Starting Warmup cycle
Segmentation fault (core dumped)

I am using Tesla V100

and 

Cuda compilation tools, release 9.0, V9.0.176
Tensorflow version : 1.8

Please suggest

**Comment by deepkshikha** [comment] 2018-08-15 13:25
I am using Tensorflow 18:07-py3 container
CUDA version =9.2
GPU = Volta 100=4
No custom code

**Comment by tensorflowbutler** [comment] 2020-01-29 23:14
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ravikyram** [comment] 2020-07-10 09:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-10 09:03 UTC
Labels: type:support
