### ISSUE TITLE
1 Channel / grey images for object detection

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [tensorflow/models#7785] opened 2019-11-11 17:55 UTC
### Describe the problem

I have been working on object detection for some time, all the models that I have seen use RGB only as input (well if we do not have 3 channels we copy data from one color/dimension to other). Do we have any deep learning models where we can only feed 1 channel as input to the model, like the face/eye detectors (LBPHFaceRecognizer) in open CV. Basically looking for deep neural networks that are simple and computational less demanding, when we have only 1 channel from sources like - thermal images, infrared cameras, TOF cameras, radars, etc.

**Comment by tensorflowbutler** [comment] 2019-11-12 12:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-19 09:53
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-19 09:53 UTC
Labels: models:research, stat:awaiting response, type:support
