### ISSUE TITLE
module 'tensorflow.python.platform.flags' has no attribute 'DEFINE_list'

### ISSUE THREAD

**Issue by yuyijie1995** [tensorflow/models#3662] opened 2018-03-20 11:42 UTC
what do I lack of?

**Comment by tensorflowbutler** [comment] 2018-04-25 06:57
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment] 2018-11-21 21:11
Closing this issue due to lack of information to work with. Please create a new issue describing your problem or update this issue with new information and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-11-21 21:11 UTC
Labels: stat:awaiting response
