### ISSUE TITLE
ERROR: Attempted to map inputs that were not found in graph_def: [dropout_rate:0, input:0]

### ISSUE THREAD

**Issue by amrha** [tensorflow/models#8202] opened 2020-02-26 16:03 UTC
when o try running this model using the frozen graph i get this error:
Attempted to map inputs that were not found in graph_def: [dropout_rate:0, input:0]
this error was asked about on stackoverflow but no answers were given :
https://stackoverflow.com/questions/47447782/tensorflow-import-gives-attempted-to-map-inputs-that-were-not-found-in-graph-de
i'm running code i got from here :
https://leimao.github.io/blog/Save-Load-Inference-From-TF-Frozen-Graph/

**Comment by tensorflowbutler** [comment] 2020-02-27 16:11
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-15 11:40
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-15 11:40 UTC
Labels: stat:awaiting response
