### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /content/train/cells_label_map.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by haivamsieee** [tensorflow/models#8976] opened 2020-07-27 18:14 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by haivamsieee** [comment] 2020-07-27 18:14
i was getting error
tensorflow.python.framework.errors_impl.NotFoundError: /content/train/cells_label_map.pbtxt; No such file or directory

**Comment by haivamsieee** [comment] 2020-07-27 18:15
how to solve this

**Comment by ravikyram** [comment] 2020-07-28 03:42
@haivamsieee 

I think this issue is duplicate of #8975 .Please, close this issue and we can track the issue in #8975.Thanks!

**Comment by ravikyram** [comment] 2020-09-10 06:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-09-10 06:46 UTC
Labels: stat:awaiting response, type:support
