### ISSUE TITLE
Cannot build icp.so

### ISSUE THREAD

**Issue by Kayee6** [tensorflow/models#5168] opened 2018-08-22 23:04 UTC
Background of my problem:
```
What is the top-level directory of the model you are using: vid2depth
Have I written custom code: NO
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: binary
TensorFlow version:('v1.5.0-0-g37aa430d84', '1.5.0')
Bazel version:0.16.1
CUDA/cuDNN version: CUDA 9.0 and CUDNN 6.0 or 7.0.x (cannot remember..)
GPU model and memory: 1080
Exact command to reproduce: bazel build ops:pcl_demo
```
I installed Bazel as the official site recommended, and run the command as above. And here is the error:

```
ERROR: /home/kj/.cache/bazel/_bazel_kj/6133cd459ec400cb06d5eb6c3cd88b0e/external/com_github_pointcloudlibrary_pcl/BUILD.bazel:329:1: no such package '@boost//': Error downloading [https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz] to /home/kj/.cache/bazel/_bazel_kj/6133cd459ec400cb06d5eb6c3cd88b0e/external/boost/boost_1_66_0.tar.gz: GET returned 403 Forbidden and referenced by '@com_github_pointcloudlibrary_pcl//:registration'
ERROR: Analysis of target '//ops:pcl_demo' failed; build aborted: no such package '@boost//': Error downloading [https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz] to /home/kj/.cache/bazel/_bazel_kj/6133cd459ec400cb06d5eb6c3cd88b0e/external/boost/boost_1_66_0.tar.gz: GET returned 403 Forbidden
INFO: Elapsed time: 14.759s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
I am not familiar with the system, and I checked similar problems posted. But it seems not match to my problem. Some errors happen when I run `bazel build ops:icp_op.so` as well:
```
/home/kj/.cache/bazel/_bazel_kj/6133cd459ec400cb06d5eb6c3cd88b0e/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 0.173s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I can see someone said he already built the `icp.so` successfully, but now I cannot even get the `.so` file. Please help!

**Comment by toodef** [comment] 2018-11-19 08:43
Hope this help to anyone while waiting for patch.
[icp_op.zip](https://github.com/tensorflow/models/files/2594393/icp_op.zip)

There is 4 files: builded Icp_op.so, modifyed icp_op_kernel.cc and icp_op.py and CMakeLists.txt

For build this file u need to:
```
sudo apt install libpcl-dev
sudo apt install libeigen3-dev
cd models/research/vid2depth/ops
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
mv libicp_op.so ../Icp_op.so
```

**Comment by bharat-robotics** [comment] 2019-06-23 22:20
@Kayee6  were you able to actually train the icp loss? I can import the op but getting segmentation fault during the training?

**Comment by ymxlzgy** [comment] 2019-08-01 13:24
@toodef @bharat-robotics How you guys compile ops with cmake？Why do I got a lot of errors from tensorflow?
``/home/ymxl/anaconda3/envs/flownet3d_env/lib/python3.5/site-packages/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:476:58: error: expected template-name before ‘<’ token
 struct scalar_product_op<QInt32, double> : binary_op_base<QInt32, double> {
                                                          ^
/home/ymxl/anaconda3/envs/flownet3d_env/lib/python3.5/site-packages/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:476:58: error: expected ‘{’ before ‘<’ token
/home/ymxl/anaconda3/envs/flownet3d_env/lib/python3.5/site-packages/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:476:58: error: expected unqualified-id before ‘<’ token
``

**Comment by tensorflowbutler** [comment] 2020-01-29 23:14
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by joshi-bharat** [comment] 2020-01-31 20:00
@tensorflowbutler I was able to solve that later. Thanks anyways

**Comment by amahendrakar** [comment] 2020-02-07 10:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 10:13 UTC
