### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection'

### ISSUE THREAD

**Issue by JakeMalis** [tensorflow/models#10113] opened 2021-07-06 17:06 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using
https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb

## 2. Describe the bug

`ModuleNotFoundError: No module named 'object_detection'` error is thrown due to an error in the installation of the object detection api.

## 3. Steps to reproduce

Just run the file in Google Colab.

## 4. Expected behavior

The object detection api should be installed which would allow the rest of the code to work properly.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

Google Colab GPU

`v1.12.1-59375-ga5317d67e6c 2.6.0-rc0`

**Comment by 007rohitSaini** [comment] 2021-07-07 17:54
pip install tensorflow-object-detection-api

**Comment by JakeMalis** [comment] 2021-07-08 01:12
> pip install tensorflow-object-detection-api

Thanks for the tip, but the tutorial says that it should install as the code is shown in the repository, which it doesn't. I know I could install it with pip but it would be easier for newbies to learn if the provided code wasn't broken.

**Comment by saikumarchalla** [comment] 2021-07-08 15:38
@JakeMalis Please update the cells with the below code  and it will work. Thanks!
```
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.
cp object_detection/packages/tf2/setup.py .
python -m pip install .

```

**Comment by JakeMalis** [comment] 2021-07-08 17:03
I did in the attached Pull Request

**Comment by saikumarchalla** [comment] 2021-07-20 13:31
@JakeMalis  If the issue is resolved for you Please go ahead and close the issue . We can track the bug in PR seperately.Thanks!

**Closed** 2021-07-20 13:34 UTC
Labels: models:research:odapi, stat:awaiting response, type:bug

**Comment by utkarsh125** [comment] 2022-04-25 18:08
If you are on Anaconda notebook just install the setup.py file after follow the steps mentioned by _**@saikumarchalla**_ upto where you use protobuf and then manually copy the setup.py file from `object_detection/tf2/` and paste it under `models/research`

now all you have to do it run it using `python -m pip install .`

**Comment by mahi01agarwal** [comment] 2023-10-08 14:04
It still doesn't work , I already have setup.py file in models/research  but i get the error "ModuleNotFoundError: No module named 'object_detection'" .

**Comment by utkarsh125** [comment] 2023-10-08 18:50
Make sure you use the exact versions of the required toolkits and frameworks as mentioned in the tutorial as TensorFlow GPU is not longer used since December 2022...

**Comment by mahi01agarwal** [comment] 2023-10-09 05:10
### The error faced by me is :
Traceback (most recent call last):
  File "/content/drive/MyDrive/TFOD_face/models/research/object_detection/model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
ModuleNotFoundError: No module named 'object_detection'

**Comment by Kushal3603** [comment] 2024-08-11 09:17
Did you find a solution to it? I'm facing the same issue.
