### ISSUE TITLE
Inconsistent formatting style

### ISSUE THREAD

**Issue by wsascha** [tensorflow/models#8248] opened 2020-03-05 14:00 UTC
**Documentation URL(s) with the issue:**
E.g.
-  [vision/detection/main.py](https://github.com/tensorflow/models/blob/master/official/vision/detection/main.py)
-  [vision/detection/dataloader/input_reader.py](https://github.com/tensorflow/models/blob/master/official/vision/detection/dataloader/input_reader.py)

**Description of the issue (what needs to be changed):**
I'd like to commit a couple of changes to the `vision/detection` framework but I noticed that the formatting is not consistent to the [Google Python Style Guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md).
I tried the `pep8` and `google` style in `yapf`.

Apart from that I propose to add e.g. a `.style.yapf` file to the `official` directory that everyone can use with a code formatter.

I can do that but first like to get an opinion about it.

**Comment by saberkun** [comment] 2020-03-07 00:30
Hi @wsascha ,
We have internal pylint system and sorry, I don't know how to port that and apply to github.
Of course we can get the lint/formatting back through comments here or sometime we will patch the pr to fix it.
What's the inconsistency you saw?
If you have changes, you may send us a draft PR first as we may need to judge if we can accept it.

**Comment by wsascha** [comment] 2020-03-09 11:45
Hey, @saberkun,
thanks for the quick reply.

> We have internal pylint system

Do you have well-defined linter settings? What style do you use? - I assumed the "official" google style but may be wrong (see below).

> Of course we can get the lint/formatting back through comments here or sometime we will patch the pr to fix it.

I filed a PR ( #8263 ) that applies the google style to all `.py` files located in `models/official`.
However, if you use a different style or custom spec I can update the files with that spec if you make it public.

> What's the inconsistency you saw?

Hard to say as I don't know your spec (Probably the term _consistent_ is a bit misleading here).
I meant that it's not communicated publicly.

**Comment by wsascha** [comment] 2020-03-09 11:46
It's also possible to put that formatting task into CI.
I can do that if you like.

**Comment by saberkun** [comment] 2020-03-09 21:38
Thanks. I saw the changes are mostly come from indentations? We use two spaces rather than tap. I will do some research to find how other TF repos apply this.

**Comment by wsascha** [comment] 2020-03-09 21:57
`yapf` defines different styles [here](https://github.com/google/yapf/blob/master/yapf/yapflib/style.py#L365).
But it's also possible to slightly modify it and add it to the style file.

**Comment by wsascha** [comment] 2020-03-24 13:04
Any news on a formal description of the formatting style for `tensorflow/models/official`?

**Comment by laxmareddyp** [comment] 2022-11-09 21:05
Hi @wsascha,

This issue is duplicate of [8262](https://github.com/tensorflow/models/pull/8262) and [8263](https://github.com/tensorflow/models/pull/8263) and i can see those 2 issues were closed already.
Please let us know still you would like to have discussions here.
Thanks

**Comment by wsascha** [comment] 2022-11-13 11:58
Hey @laxmareddyp, I can't tell if the problem still persists as this issue wasn't mentioned by another PR that actually made it into the main branch. So if you can live with / don't care about inconsistencies, you can close this as I don't use this repo anymore.

**Comment by laxmareddyp** [comment] 2022-11-14 15:48
Hi @saberkun,

 Could you please suggest here to keep open or close this issue as user doesn't use this repo anymore.

Thanks.

**Comment by laxmareddyp** [comment] 2022-11-14 17:48
Hi @saberkun,

Thanks for the quick response and will document it from my side.

Closing this as completed.

Thanks.

**Closed by laxmareddyp** 2022-11-14 17:48 UTC
Labels: type:docs, models:official
