### ISSUE TITLE
Run Object delection train.py ERROR

### ISSUE THREAD

**Issue by SourcePowered** [tensorflow/models#2424] opened 2017-09-21 03:39 UTC
```
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    tf.app.run()
  File "E:\Development_Software\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 145, in main
    model_config, train_config, input_config = get_configs_from_multiple_files()
  File "train.py", line 127, in get_configs_from_multiple_files
    text_format.Merge(f.read(), train_config)
  File "E:\Development_Software\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 118, in read
    self._preread_check()
  File "E:\Development_Software\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "E:\Development_Software\Python\Python36\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "E:\Development_Software\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open:  : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
```

On Windows 10, Python 3.6.2, Tensorflow 1.3.

I have spent 11 days trying to study it, but I can't solve it at all. I checked all kinds of coding problems and couldn't find any clue.

Please help me, I'm hopeless now. Thank you

**Comment by SourcePowered** [comment] 2017-09-21 03:42
Doesn't it completely support the Windows platform? Or do not support Unicode's system at all? I have no any idea about this.

**Comment by benvanik** [comment] 2017-09-28 18:22
I have had trouble with the tensorflow gfile reader on Windows and paths that contain unicode characters. Unfortunately I think this is a known issue in tf's file handling code. I think it was fixed here, but haven't built tf from head to confirm: https://github.com/tensorflow/tensorflow/pull/11562

**Comment by tatatodd** [comment] 2017-10-11 04:59
@SourcePowered Can you either try @benvanik 's suggestion, or perhaps try a file with only ASCII characters to confirm the root problem?

**Comment by kaaier** [comment] 2018-12-14 13:04
Hello, I want to ask if you have solved the problem

**Comment by kaaier** [comment] 2018-12-14 13:05
I am very worry, do you solve it???????????????????????????/label_map PBTXT: ϵ ͳ \ udcd5 Ҳ \ udcbb \ udcb5 \ udcbd ָ \ udcb6 \ udca8 \ udcb5 \ udcc4 · \ udcbe \ udcb6 \ udca1 \ udca3

**Comment by tensorflowbutler** [comment] 2020-01-29 23:33
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 09:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 09:52 UTC
Labels: stat:awaiting response
