### ISSUE TITLE
VGGish feature with YouTube-8M starter code: 'video_id' is required but could not be found

### ISSUE THREAD

**Issue by patriceguyot** [tensorflow/models#5345] opened 2018-09-20 13:18 UTC
@plakal 
@dpwe 

Dear authors,

As suggested in the documentation, I would like to use the VGGish feature extractor with another model, which is the "Starter code for working with the YouTube-8M dataset".

I use vggish_inference_demo.py to create an embedding from an arbitrary audio input. When I try to run the inference function from YouTube-8M, I obtain the error: Context feature 'video_id' is required but could not be found.

It seems that this two codes (VGGish feature extraction and YouTube-8M starter code) are designed to work together. 
Maybe I am missing something here, but I am wondering if there is a simple way to bypass this issue, or if I have to modify the code (in order to add a video_id field to the embedding, or to bypass the reading of this field in YouTube-8M).

Thanks by advance for any answer or comment.

**Comment by plakal** [comment] 2018-09-20 17:17
@samihaija 

This is a duplicate of https://github.com/tensorflow/models/issues/5286.

The workaround is to replace id with video_id in readers.py in the YT-8M code base.

The real fix is to change the YT-8M code base to allow reading older datasets. We don't plan on updating the legacy VGGish embeddings (since we are planning on replacing them anyway). Perhaps you can bring this issue up on the YT-8M users list https://groups.google.com/forum/#!forum/youtube8m-users (and perhaps ask them to enable issue tracking on YT-8M as well)

**Closed by plakal** 2018-09-20 17:17 UTC

**Comment by patriceguyot** [comment] 2018-09-24 09:13
@plakal 

Thanks for your quick answer. However, my post concerns another issue (and I have already solved the problem you mentioned).

I am trying now to use YT-8M with VGGish feature extractor (that differs from Audioset features). This VGGish feature extractor outputs an embedding that does not seems to contains any 'video_id' or 'id' field.

Is there a simple way to output an inference from this embedding with the YT-8M code?

Thanks.
