### ISSUE TITLE
SSD MobileNet v2 320x320 has input of 300x300

### ISSUE THREAD

**Issue by ChristianMartin868** [tensorflow/models#9945] opened 2021-04-25 09:07 UTC
I converted the SSD MobileNet v2 320x320 to a quantized Tensorflow Lite Model with representative dataset. The shape must 300x300. So I think in the repository the name of the SSD MobileNet v2 320x320 must be changed to SSD MobileNet v2 300x300

**Comment by saikumarchalla** [comment] 2021-04-27 09:57
@ChristianMartin868  Could you please let us know where you have converted the SSD MobileNet model?. Thanks!

**Comment by ChristianMartin868** [comment] 2021-05-02 15:50
@saikumarchalla I used the Model as TFLite Model in Android Studio Witz the Object Detection Example Project. By Input Shape it works only with 300.
The SSD Mobilenet v2 FPNLite 320x320 works correctly with Input of 320 by the conversion to TFLite Model an in Android Studio.

**Comment by ChristianMartin868** [comment] 2021-05-02 15:54
@saikumarchalla If I used in Android Studio Input of 320 for the SSD Mobilenet v2 320x320 I get Bytebuffer error. With Input of 300 it works. The SSD Mobilenet v2 FPN Lite 320x320 works without errors with Input of 320 in Android Studio.

**Comment by saikumarchalla** [comment] 2021-05-03 12:24
@ChristianMartin868   Yes, you are correct and the shape has been set to 300*300 instead of 320*320 in the config file. To make it work with 320 *320 images , we need to edit the below code from config file.

```
image_resizer { 
  fixed_shape_resizer {
  height: 300
   width: 300
  }
```




https://github.com/tensorflow/models/blob/master/research/object_detection/configs/tf2/ssd_mobilenet_v2_320x320_coco17_tpu-8.config

**Comment by ChristianMartin868** [comment] 2021-05-04 15:13
@saikumarchalla Ok, the problem  is the config file. I didn‘t think about that.

**Comment by saikumarchalla** [comment] 2021-05-05 11:57
@ChristianMartin868  Closing the issue since the issue is resolved now. Please feel free to reopen the issue if you need help further. Thanks!

**Closed by saikumarchalla** 2021-05-05 11:57 UTC
Labels: models:research, stat:awaiting response, type:bug
