### ISSUE TITLE
help

### ISSUE THREAD

**Issue by manav-singh** [tensorflow/models#10846] opened 2022-12-02 08:48 UTC
TypeError Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14208/2792951555.py in
----> 1 config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

~\anaconda3\lib\site-packages\object_detection\utils\config_util.py in get_configs_from_pipeline_file(pipeline_config_path, config_override)
98 text_format.Merge(config_override, pipeline_config)
99 return create_configs_from_pipeline_proto(pipeline_config)
--> 100
101 def create_configs_from_pipeline_proto(pipeline_config):
102 """Creates a configs dictionary from pipeline_pb2.TrainEvalPipelineConfig.

~\anaconda3\lib\site-packages\object_detection\utils\config_util.py in create_configs_from_pipeline_proto(pipeline_config)
122 configs["eval_input_config"] = configs["eval_input_configs"][0]
123 if pipeline_config.HasField("graph_rewriter"):
--> 124 configs["graph_rewriter_config"] = pipeline_config.graph_rewriter
125
126 return configs

TypeError: 'InputReader' object is not subscriptable

facing this issue, please help...

**Comment by laxmareddyp** [comment] 2022-12-02 18:31
Hi @manav-singh ,

It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.


In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Closed** 2022-12-16 19:49 UTC
Labels: stat:awaiting response, type:support, stalled
