### ISSUE TITLE
About the performance of the compress network

### ISSUE THREAD

**Issue by onlyyouxgl** [tensorflow/models#604] opened 2016-11-01 14:06 UTC
I try to run this code(https://github.com/tensorflow/models/tree/master/compression) on my images database. There are 1338 images, png format, 300~500kb and image-size 512x384 in my database. The results after runing compression code, I got 1338*16 images, corresponding to 16 kinds of compressing levels. I found that the compressing results did not show the great compression performance. For example, one image, 316.1kb , 16 kinds of compression versions , 249.2kb, 270.3kb, 272.0kb, 270.6kb, 271.7kb, 273.2kb, 273.5kb, 275.6kb, 277.7kb, 280kb, 281.8kb, 283.3kb, 285.3kb, 287.3kb, 288.0kb, 288.8kb; high compressing level does not have the smallest space. I can not understand it. Can you explain this case? Thanks

**Comment by aselle** [comment] 2016-11-01 18:16
@nickj-google, may be able to provide more insight. A few suggestions...
1. Can you reproduce the example image compression results in the README?
2. What does your image look like?

**Comment by nickj-google** [comment] 2016-11-01 20:08
Do you have any example input images / npz files you can share?
[two_example_codes.zip](https://github.com/tensorflow/models/files/564945/two_example_codes.zip)

For the example in the repo, it is a 1024x768 image. I've included the results of running to iteration 15 (2 bits per pixel) and running to iteration 0 (1/8 bits per pixel). The binary codes produced should be nominally 196,608 bytes and 12,228 bytes respectively.

Because the numpy arrays are packed and zipped, they're actually a little smaller than this at 194,382 bytes and 10,318 bytes respectively. It's possible on average it will vary, but these codes should be no more than 49 kB for your case.

**Comment by onlyyouxgl** [comment] 2016-11-02 07:06
Of course. I chosed two images in my database. You can download from this link to check it.(I am sorry for this trouble, i met the problem, 'we dont support that file type', when i uploaded this file, zip type.)
[https://github.com/onlyyouxgl/test_example/](url)

**Comment by nickj-google** [comment] 2016-11-02 15:47
I think I may see the confusion. The sizes mentioned above appear to be for the decoded images and not the file representation in the *.npz code file. 

Due to some of the artifacts the network creates in the resulting image, it's probable that PNG may not be able to compress them as efficiently or even in decreasing order. As you've seen in your examples, PNG is less capable of compressing low bitrate images as efficiently as our network represents them. 

So for compression performance we can measure the speeds of the encoder/decoder portions of the network and the resulting filesizes of the codes, but that doesn't hold for the file sizes of the visualization container we choose. Does that make sense?

**Comment by onlyyouxgl** [comment] 2016-11-03 01:44
OK, understood. Thanks for your answer. appreciate your reply greatly.

**Comment by aselle** [comment] 2016-11-03 17:50
Closing this issue for now. We will reopen it if further information becomes available. Thanks.

**Closed by aselle** 2016-11-03 17:50 UTC
Labels: type:support
