### ISSUE TITLE
Failing 6 SyntaxNet tests

### ISSUE THREAD

**Issue by BayBenj** [tensorflow/models#285] opened 2016-07-23 20:52 UTC
I am stuck trying to get Parsey McParseface to work. It may be because I fail half the tests after I try to build it. After installing everything, I run this initial SyntaxNet build/test:

bazel test --linkopt=-headerpad_max_install_names \
    syntaxnet/... util/utf8/...

I pass 6 of the tests and fail the other 6. This is what I see: 
<img width="1042" alt="tests" src="https://cloud.githubusercontent.com/assets/17600555/17080199/8d0be092-50e3-11e6-9396-71e7de4e3bb7.png">

When I later try to parse text with Parsey McParseface with this command:

echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh

After a long traceback it gives this message:

ImportError: No module named _pywrap_tensorflow

<img width="1263" alt="traceback" src="https://cloud.githubusercontent.com/assets/17600555/17080238/d58aaef6-50e4-11e6-996a-a5b7a1e9d3df.png">

Any suggestions on what I'm doing wrong? These are my specs:
I am using Mac OS X.
My Python version is 2.7.11.
I am using bazel version 0.2.2b.
Numpy, asciitree, protobuf 3.0.0b2, and swig are all installed.

**Comment by concretevitamin** [comment] 2016-07-25 04:22
Duplicate of #284.  Please redirect discussion there.

**Closed by concretevitamin** 2016-07-25 04:22 UTC
