### ISSUE TITLE
How to use trained RNN QuickDraw model to make predictions/inference ?

### ISSUE THREAD

**Issue by shubhank008** [tensorflow/models#6919] opened 2019-05-29 23:37 UTC
I tried asking about it on stackoverflow but could not get any replies and had been trying my hands at using Estimator.predict but still couldn't figure it out.  

I have trained the RNN QuickDraw model following https://www.tensorflow.org/tutorials/sequences/recurrent_quickdraw#loss_predictions_and_optimizer and using the following train_model  
https://github.com/tensorflow/models/blob/master/tutorials/rnn/quickdraw/train_model.py

What I cannot grasp is, once I have the checkpoints and all, how do I make predictions using my own drawing images (.png/.jpg files) or do proper inference.

**Comment by tensorflowbutler** [comment] 2019-05-30 12:23
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by shubhank008** [comment] 2019-05-30 16:08
What is the top-level directory of the model you are using
> ./quickdraw

Have I written custom code
> No 

OS Platform and Distribution
> Linux, Ubuntu 14

TensorFlow installed from
> pip3

TensorFlow version
> v1.4~

Bazel version
> No 

CUDA/cuDNN version> No 
> 10.0

GPU model and memory
> K80 12GB

Exact command to reproduce
> N/A

**Comment by lukaszkaiser** [comment] 2019-06-19 22:06
I don't know this code, please do not assign to me.

**Comment by tensorflowbutler** [comment] 2020-03-18 21:16
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-05-08 20:55 UTC
Labels: models:official, type:support
