### ISSUE TITLE
AttributeError: 'module' object has no attribute 'load_op_library'

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/models#67] opened 2016-05-12 23:25 UTC
After build `syntaxnet`, running the demo.sh I've got

```shell
macbookproloreto:syntaxnet admin$ echo 'Bob brought the pizza to Alice.' | syntaxnet/demo.sh
Traceback (most recent call last):
  File "/Volumes/MacHDD2/Developmemt/AI/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/parser_eval.py", line 28, in <module>
    from syntaxnet import graph_builder
  File "/Volumes/MacHDD2/Developmemt/AI/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/graph_builder.py", line 20, in <module>
    import syntaxnet.load_parser_ops
  File "/Volumes/MacHDD2/Developmemt/AI/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/load_parser_ops.py", line 21, in <module>
    tf.load_op_library(
AttributeError: 'module' object has no attribute 'load_op_library'
Traceback (most recent call last):
  File "/Volumes/MacHDD2/Developmemt/AI/models/syntaxnet/bazel-bin/syntaxnet/conll2tree.runfiles/syntaxnet/conll2tree.py", line 22, in <module>
    import syntaxnet.load_parser_ops
  File "/Volumes/MacHDD2/Developmemt/AI/models/syntaxnet/bazel-bin/syntaxnet/conll2tree.runfiles/syntaxnet/load_parser_ops.py", line 21, in <module>
    tf.load_op_library(
AttributeError: 'module' object has no attribute 'load_op_library'
Traceback (most recent call last):
  File "/Volumes/MacHDD2/Developmemt/AI/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/parser_eval.py", line 28, in <module>
    from syntaxnet import graph_builder
  File "/Volumes/MacHDD2/Developmemt/AI/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/graph_builder.py", line 20, in <module>
    import syntaxnet.load_parser_ops
  File "/Volumes/MacHDD2/Developmemt/AI/models/syntaxnet/bazel-bin/syntaxnet/parser_eval.runfiles/syntaxnet/load_parser_ops.py", line 21, in <module>
    tf.load_op_library(
AttributeError: 'module' object has no attribute 'load_op_library'
```

Some tests failed during the build

```shell
FAIL: //syntaxnet:lexicon_builder_test (see /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log).
FAIL: //syntaxnet:graph_builder_test (see /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log).
FAIL: //syntaxnet:reader_ops_test (see /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log).
FAIL: //syntaxnet:beam_reader_ops_test (see /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log).
FAIL: //syntaxnet:text_formats_test (see /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log).
FAIL: //syntaxnet:parser_trainer_test (see /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log).
INFO: Elapsed time: 2115,987s, Critical Path: 1370,47s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0,3s
//syntaxnet:parser_features_test                                         PASSED in 0,2s
//syntaxnet:sentence_features_test                                       PASSED in 0,4s
//syntaxnet:shared_store_test                                            PASSED in 5,2s
//syntaxnet:tagger_transitions_test                                      PASSED in 0,4s
//util/utf8:unicodetext_unittest                                         PASSED in 0,1s
//syntaxnet:beam_reader_ops_test                                         FAILED in 1,1s
  /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 3,1s
  /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 3,1s
  /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 1,2s
  /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 3,0s
  /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 1,2s
  /private/var/tmp/_bazel_admin/7de5e8ad26205d6f3b147001f8f93014/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log
```

**Comment by KeSyren** [comment] 2016-05-18 23:03
I have the same problem.

**Comment by mrry** [comment] 2016-05-18 23:04
Have you got an old version of TensorFlow (earlier than 0.8) installed on your machine?

**Comment by loretoparisi** [comment] 2016-05-19 10:52
@mrry so I have installed the '0.8' through pip:

 `sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0-py2-none-any.whl`

**Comment by mrry** [comment] 2016-05-19 14:13
Can you print the results of `import tensorflow as tf; print tf.__version__; print dir(tf)`?

**Comment by loretoparisi** [comment] 2016-05-20 13:53
@mrry uhm it seems to be an `tensorflow` install problem I have tried from source again:

```shell
git clone --recurse-submodules https://github.com/tensorflow/tensorflow
cd tensorflow
./configure
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
pip install /tmp/tensorflow_pkg/tensorflow-0.8.0-py2-none-any.whl
bazel build -c opt //tensorflow/cc:tutorials_example_trainer
```

after some hourse I have got

```shell
INFO: From Linking tensorflow/cc/ops/image_ops_gen_cc [for host]:
clang: warning: argument unused during compilation: '-pthread'
INFO: From Compiling tensorflow/core/kernels/mirror_pad_op.cc:
In file included from tensorflow/core/kernels/mirror_pad_op.cc:20:
In file included from ./tensorflow/core/kernels/mirror_pad_op.h:19:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from external/eigen_archive/eigen-eigen-a5e9085a94e8/unsupported/Eigen/CXX11/Tensor:57:
In file included from external/eigen_archive/eigen-eigen-a5e9085a94e8/unsupported/Eigen/CXX11/ThreadPool:53:
external/eigen_archive/eigen-eigen-a5e9085a94e8/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:183:10: warning: private field 'pad_' is not used [-Wunused-private-field]
    char pad_[128];
         ^
1 warning generated.
INFO: From Linking tensorflow/cc/tutorials_example_trainer:
clang: warning: argument unused during compilation: '-pthread'
Target //tensorflow/cc:tutorials_example_trainer up-to-date:
  bazel-bin/tensorflow/cc/tutorials_example_trainer
INFO: Elapsed time: 1300,997s, Critical Path: 1297,02s
```

but no way to import in python:

```python
>>> import tensorflow 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflo
```

**Comment by mrry** [comment] 2016-05-20 19:42
Are you running `python` from inside the `tensorflow/` source directory? That would explain the `ImportError`.

**Comment by loretoparisi** [comment] 2016-05-23 08:23
@mrry ok I guess the error seems to be `protobuf`

Runnig within the `tensorflow/ ` root folder I get the error before - you were right, but running from the source directory I get this error, that I think it's the problem:

```shell
macbookproloreto:tensorflow admin$ cd tensorflow/
macbookproloreto:tensorflow admin$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 55, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Library/Python/2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
>>>
```

**Comment by slavpetrov** [comment] 2016-06-02 15:11
Were you able to resolve this or are you still having trouble? I am going to close the issue but feel free to reopen if the problem is not resolved.

**Closed by slavpetrov** 2016-06-02 15:11 UTC
