### ISSUE TITLE
OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile

### ISSUE THREAD

**Issue by swy0915** [tensorflow/models#7510] opened 2019-08-29 05:57 UTC
in saver.py file :
_SHARDED_SUFFIX = "_temp_%s/part" % uuid.uuid4().hex

in os win10: my code run error:
OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: Failed to create a NewWriteableFile

because in win10 '\' is path 

i think the code change is better?
_SHARDED_SUFFIX_temp = "_temp_%s" % uuid.uuid4().hex
 _SHARDED_SUFFIX = os.path.join(_SHARDED_SUFFIX_temp, 'part')

**Comment by tensorflowbutler** [comment] 2019-08-30 00:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-22 11:44
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-22 11:44 UTC
Labels: stat:awaiting response, type:support
