### ISSUE TITLE
Checkpoint Error with Object Detection on Google Cloud ML Engine

### ISSUE THREAD

**Issue by clovers1254** [tensorflow/models#5704] opened 2018-11-06 17:24 UTC
Today, I trying to use Object Detection Library for my project, but when I use Google Cloud ML to train my models, it have an error about checkpoint.

![image](https://user-images.githubusercontent.com/9329079/48081733-4be79100-e223-11e8-9155-4b72df97e115.png)
 
I have try many way but no one can work, please help me as soon as you can.
Thanks.

------------------------

### System information
- **What is the top-level directory of the model you are using**: 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **Exact command to reproduce**:  gcloud ml-engine jobs submit training object_detection_`date +%m_%d_%Y_%H_%M_%S` \
    --runtime-version 1.9 \
    --job-dir=gs://veye2019-ml/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,/tmp/pycocotools/pycocotools-2.0.tar.gz \
    --module-name object_detection.model_main \
    --region us-central1 \
    --config ~/train.yaml \
	--python-version 3.5 \
    -- \
    --pipeline_config_path=gs://veye2019-ml/data/pipeline.config \

**Comment by tensorflowbutler** [comment] 2018-11-07 12:17
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by GDunne96** [comment] 2018-11-13 18:06
Hi @tensorflowbutler @robieta, has there been any update on this issue. I'm currently encountering the same problem with the checkpoint file when running my training job using Google Cloud Machine Learning.

<img width="1169" alt="screen shot 2018-11-13 at 17 45 48" src="https://user-images.githubusercontent.com/22687826/48432964-cf4a3a80-e76d-11e8-8685-589c72a481b0.png">

### System information
- **What is the top-level directory of the model you are using**: models/research/object-detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS High Sierra
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023 1.9.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
gcloud ml-engine jobs submit training object_detection_`date +%s` \
    --runtime-version 1.9 --python-version 3.5 \
    --job-dir=gs://csc3032-fyp/initial-wd-mobilenet/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,cocoapi/pycocotools-2.0.tar.gz \
    --module-name object_detection.model_main \
    --region us-east1 \
    --config ~/cloud.yaml \
    -- \
    --train_dir=gs://csc3032-fyp/initial-wd-mobilenet/train \
    --pipeline_config_path=gs://csc3032-fyp/initial-wd-mobilenet/data/ssd_mobilenet_v1_coco.config

Thanks

**Comment by MirkoArnold1** [comment] 2018-11-19 10:37
Duplicate of #5754

**Comment by ymodak** [comment] 2019-02-06 21:47
> Duplicate of #5754
Closing this issue since a solution is provided in the mentioned duplicate issue. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2019-02-06 21:47 UTC
Labels: models: research, stat:awaiting response
