### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.compat.v2' has no attribute '__internal__'

### ISSUE THREAD

**Issue by Prithvi0167** [tensorflow/models#10025] opened 2021-05-27 10:58 UTC
![image](https://user-images.githubusercontent.com/43097533/119814912-95df1200-bf08-11eb-9a18-fcedd7aa05fb.png)

**Comment by antonazaides** [comment] 2021-05-31 09:41
Hi, any news about this issue?

**Comment by shayozes** [comment] 2021-05-31 10:09
This is happening to me too when I'm using tensorflow 1.x, any help?

**Comment by ZillaRU** [comment] 2021-06-02 03:11
I got the same eror with Keras2.2.4 and tensorflow 2.0.0

**Comment by ZillaRU** [comment] 2021-06-02 03:11
I got the same eror with Keras2.2.4 and tensorflow 2.0.0.

**Comment by saberkun** [comment] 2021-06-05 21:05
The __internal__ thing is something very recent. I feel it means some of the code or package is requiring TF 2.5.
@qlzh727 made the changes. Please contact @qlzh727

**Comment by qlzh727** [comment] 2021-06-07 18:26
The tf.__internal__ is added in tf 2.5. Please update your tf version to the latest. Also, please check what's the version of keras (or keras-nightly) package you are using.

**Comment by abbesmoe** [comment] 2021-07-02 15:12
have same exact issue.

**Comment by qlzh727** [comment] 2021-07-07 18:10
Looking from the stack trace above, it seems that your PIP env has an old keras 2.1.6 installed. When we split keras code from tensorflow/python/keras to it new repository in keras-team/keras, we reuse the existing keras PIP package name, and now it is a dependency for tensorflow. The error above is because the old keras package get picked up. Please try uninstall keras 2.1.6 (or any old keras package, and only have the latest keras-nightly in the repository).

**Comment by jvishnuvardhan** [comment] 2021-07-16 00:09
@Prithvi0167 Looks like this was resolved with @qlzh727 suggestion. I could not reproduce the issue. [Here](https://colab.research.google.com/gist/jvishnuvardhan/2872d92fb6f6413c45568e22f0a4e1a3/untitled.ipynb) is a gist for reference.

If it is still an issue, please share a standalone code to reproduce the issue. Thanks!

**Closed** 2021-07-30 01:38 UTC
Labels: stalled, stat:awaiting response, type:support
