### ISSUE TITLE
For how may epoch dose open image model on faster rcnn is trained?

### ISSUE THREAD

**Issue by nareshmungpara** [tensorflow/models#5804] opened 2018-11-22 12:05 UTC
For how many steps does `faster_rcnn_inception_resnet_v2_atrous_oid` model is trained ?

I am trying to retrain it with open image data set for 600 classes and after around 1 lack steps i tried to test it using `object_detection_tutorial.ipynb` with that 2 images of dog and beach but there is no object detected.

So is this expected behaviour or there is some other issue?

**Comment by tensorflowbutler** [comment] 2018-11-23 00:15
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2020-01-29 22:59
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:29
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:29 UTC
Labels: stat:awaiting response
