### ISSUE TITLE
 multi GPU train using object dection API

### ISSUE THREAD

**Issue by hongfangyu** [tensorflow/models#4316] opened 2018-05-20 02:49 UTC
there are four GPUs in my computer, I use models/research/object_detection/train.py to fine-tuning faster_rcnn on my own dataset, but only one GPU works.
This is the output of nvidia-smi:only one GPU works and its power is 80W, ohters are less than 20W which explain they do not work.How can I train with multi GPUs? or it does not suppert.
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:02:00.0      On |                  N/A |
| 36%   78C    P2    80W / 250W |  11664MiB / 12199MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:03:00.0     Off |                  N/A |
| 22%   53C    P8    18W / 250W |  11604MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:82:00.0     Off |                  N/A |
| 22%   38C    P8    15W / 250W |  11604MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:83:00.0     Off |                  N/A |
| 22%   43C    P8    16W / 250W |  11602MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by a819721810** [comment] 2018-05-20 03:41
![image](https://user-images.githubusercontent.com/10041362/40275491-ac8ca4fa-5c22-11e8-8a17-49a3d13e7d4c.png)

https://github.com/tensorflow/models/issues/1972
and you should close this issue,because it is not a bug or feature.

**Comment by hongfangyu** [comment] 2018-05-21 12:56
I set "--num_clones=4 --ps_tasks=1" in train.py and set batch_size = 4 in faster_rcnn_resnet101_voc07.config. as for one step in train process, it is a little slowly than if I set "--num_clones=1 --ps_tasks=0" and set batch_size = 1. I know the former way train 4 pictures in one step, it is faster in fact. The output of 'nvidia-smi' indicates that four GPUs are all working.
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.59                 Driver Version: 390.59                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:02:00.0  On |                  N/A |
| 59%   84C    P2   140W / 250W |  11724MiB / 12204MiB |     77%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:03:00.0 Off |                  N/A |
| 56%   85C    P2   141W / 250W |  11706MiB / 12212MiB |     69%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 00000000:82:00.0 Off |                  N/A |
| 48%   82C    P2   173W / 250W |  11706MiB / 12212MiB |     70%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 00000000:83:00.0 Off |                  N/A |
| 50%   83C    P2   152W / 250W |  11706MiB / 12212MiB |     71%      Default |
+-------------------------------+----------------------+----------------------+
     this is not important. but unfortunately, the curve of loss function becomes concussion and divergence. This is not what I what. So I finally choose the way of only using one GPU.
    At the same time, I notice this in train.py(line131~137):

  # Parameters for a single worker.
  ps_tasks = 0
  worker_replicas = 1
  worker_job_name = 'lonely_worker'
  task = 0
  is_chief = True
  master = ''

it seems that they force or suggest  you to choose the way of using one GPU.

**Comment by hongfangyu** [comment] 2018-05-21 13:08
when I use 4 GPUs in Darknet, one GPU runs one step which means GPU0 runs step i, GPU1 runs step i+1, GPU2 runs step i+2 and GPU3 runs step i+3. but here when using 4 GPUs,  the four GPUs run the same step and one GPU run one batch. I do not know why!

**Closed** 2018-05-22 03:52 UTC

**Comment by hongfangyu** [comment] 2018-05-22 12:17
Thank you! @a819721810

**Comment by spk921** [comment] 2018-07-13 21:17
@hongfangyu  I can't run multiple-gpu with faster_rcnn_resnet101_pets.config. Have you tried with faster RCNN? Could you share your command script?

I got following error message: 

Traceback (most recent call last):
File "object_detection/train.py", line 183, in 
tf.app.run()
File "/home/sangpilk/pyenv/py27/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
_sys.exit(main(argv))
File "object_detection/train.py", line 179, in main
graph_hook_fn=graph_rewriter_fn)
File "/home/sangpilk/git/dash_net/research/object_detection/trainer.py", line 287, in train
clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
File "/home/sangpilk/git/dash_net/research/slim/deployment/model_deploy.py", line 193, in create_clones
outputs = model_fn(*args, **kwargs)
File "/home/sangpilk/git/dash_net/research/object_detection/trainer.py", line 179, in _create_losses
train_config.use_multiclass_scores)
ValueError: need more than 0 values to unpack
