### ISSUE TITLE
Please i need good detailled help for mask rcnn training

### ISSUE THREAD

**Issue by GhislainAdon** [tensorflow/models#6294] opened 2019-03-02 14:30 UTC
I want a script to create tf_record.py for rcnn mask training. Please need help

**Comment by tensorflowbutler** [comment] 2019-03-03 12:16
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rootkitchao** [comment] 2019-03-03 17:52
Have you tried create_coco_tf_record.py(https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_coco_tf_record.py)?

**Comment by GhislainAdon** [comment] 2019-03-04 12:39
i am using object detection api as models at this link https://github.com/tensorflow/models/tree/master/research/object_detection
My OS platform is Ubuntu 16.04 LTS 
I used tensorflow CPU installed from pip 
tensorflow version is  1.9

**Comment by GhislainAdon** [comment] 2019-03-04 13:39
**System information**

    What is the top-level directory of the model you are using: model/research/object_detection
    **Have I written custom code **: No
    OS Platform and Distribution : Linux Ubuntu 16.04
    TensorFlow installed from (source or binary): source
    TensorFlow version (use command below): 1.9.0
    Bazel version (if compiling from source): N/A
    CUDA/cuDNN version: N/A
    GPU model and memory: No GPU
    Exact command to reproduce:

**Describe the problem**

### I want to learn object detection with mask . 
First i use labelme to annotate my dataset .Then i convert json file generaed in PNG mask.
I use this script below to create TFrecord file :
`#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 26 10:57:09 2018

@author: shirhe-lyh
"""

"""Convert raw dataset to TFRecord for object_detection.

Please note that this tool only applies to labelme's annotations(json file).

Example usage:
    python3 create_tf_record.py \
        --images_dir=your absolute path to read images.
        --annotations_json_dir=your path to annotaion json files.
        --label_map_path=your path to label_map.pbtxt
        --output_path=your path to write .record.
"""

import cv2
import glob
import hashlib
import io
import json
import numpy as np
import os
import PIL.Image
import tensorflow as tf
from object_detection.utils import label_map_util
#import read_pbtxt_file

flags = tf.app.flags

flags.DEFINE_string('images_dir', default='D:/Mask_RCNN-master/train_data/pic',help='')
flags.DEFINE_string('annotations_json_dir', 'D:/Mask_RCNN-master/train_data/json',
                   help='')
flags.DEFINE_string('label_map_path',default='C:/Users/18301/Desktop/data.pbtxt',help='')
flags.DEFINE_string('output_path', default='C:/Users/18301/Desktop/train.record', help='')

FLAGS = flags.FLAGS


def int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def int64_list_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))


def bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def bytes_list_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))


def float_list_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))


def create_tf_example(annotation_dict, label_map_dict=None):
    """Converts image and annotations to a tf.Example proto.

    Args:
        annotation_dict: A dictionary containing the following keys:
            ['height', 'width', 'filename', 'sha256_key', 'encoded_jpg',
             'format', 'xmins', 'xmaxs', 'ymins', 'ymaxs', 'masks',
             'class_names'].
        label_map_dict: A dictionary maping class_names to indices.

    Returns:
        example: The converted tf.Example.

    Raises:
        ValueError: If label_map_dict is None or is not containing a class_name.
    """
    if annotation_dict is None:
        return None
    if label_map_dict is None:
        raise ValueError('`label_map_dict` is None')

    height = annotation_dict.get('height', None)
    width = annotation_dict.get('width', None)
    filename = annotation_dict.get('filename', None)
    sha256_key = annotation_dict.get('sha256_key', None)
    encoded_jpg = annotation_dict.get('encoded_jpg', None)
    image_format = annotation_dict.get('format', None)
    xmins = annotation_dict.get('xmins', None)
    xmaxs = annotation_dict.get('xmaxs', None)
    ymins = annotation_dict.get('ymins', None)
    ymaxs = annotation_dict.get('ymaxs', None)
    masks = annotation_dict.get('masks', None)
    class_names = annotation_dict.get('class_names', None)

    labels = []
    for class_name in class_names:
        label = label_map_dict.get(class_name, None)
        if label is None:
            raise ValueError('`label_map_dict` is not containing {}.'.format(
                class_name))
        labels.append(label)

    encoded_masks = []
    for mask in masks:
        pil_image = PIL.Image.fromarray(mask.astype(np.uint8))
        output_io = io.BytesIO()
        pil_image.save(output_io, format='PNG')
        encoded_masks.append(output_io.getvalue())

    feature_dict = {
        'image/height': int64_feature(height),
        'image/width': int64_feature(width),
        'image/filename': bytes_feature(filename.encode('utf8')),
        'image/source_id': bytes_feature(filename.encode('utf8')),
        'image/key/sha256': bytes_feature(sha256_key.encode('utf8')),
        'image/encoded': bytes_feature(encoded_jpg),
        'image/format': bytes_feature(image_format.encode('utf8')),
        'image/object/bbox/xmin': float_list_feature(xmins),
        'image/object/bbox/xmax': float_list_feature(xmaxs),
        'image/object/bbox/ymin': float_list_feature(ymins),
        'image/object/bbox/ymax': float_list_feature(ymaxs),
        'image/object/mask': bytes_list_feature(encoded_masks),
        'image/object/class/label': int64_list_feature(labels)}
    example = tf.train.Example(features=tf.train.Features(
        feature=feature_dict))
    return example


def _get_annotation_dict(images_dir, annotation_json_path):
    """Get boundingboxes and masks.

    Args:
        images_dir: Path to images directory.
        annotation_json_path: Path to annotated json file corresponding to
            the image. The json file annotated by labelme with keys:
                ['lineColor', 'imageData', 'fillColor', 'imagePath', 'shapes',
                 'flags'].

    Returns:
        annotation_dict: A dictionary containing the following keys:
            ['height', 'width', 'filename', 'sha256_key', 'encoded_jpg',
             'format', 'xmins', 'xmaxs', 'ymins', 'ymaxs', 'masks',
             'class_names'].
#
#    Raises:
#        ValueError: If images_dir or annotation_json_path is not exist.
    """
    #    if not os.path.exists(images_dir):
    #        raise ValueError('`images_dir` is not exist.')
    #
    #    if not os.path.exists(annotation_json_path):
    #        raise ValueError('`annotation_json_path` is not exist.')

    if (not os.path.exists(images_dir) or
            not os.path.exists(annotation_json_path)):
        return None

    with open(annotation_json_path, 'r') as f:
        json_text = json.load(f)
    shapes = json_text.get('shapes', None)
    if shapes is None:
        return None
    image_relative_path = json_text.get('imagePath', None)
    if image_relative_path is None:
        return None
    image_name = image_relative_path.split('/')[-1]
    image_path = os.path.join(images_dir, image_name)
    image_format = image_name.split('.')[-1].replace('jpg', 'jpeg')
    if not os.path.exists(image_path):
        return None

    with tf.gfile.GFile(image_path, 'rb') as fid:
        encoded_jpg = fid.read()
    image = cv2.imread(image_path)
    height = image.shape[0]
    width = image.shape[1]
    key = hashlib.sha256(encoded_jpg).hexdigest()

    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    masks = []
    class_names = []
    hole_polygons = []
    for mark in shapes:
        class_name = mark.get('label')
        class_names.append(class_name)
        polygon = mark.get('points')
        polygon = np.array(polygon)
        if class_name == 'hole':
            hole_polygons.append(polygon)
        else:
            mask = np.zeros(image.shape[:2])
            cv2.fillPoly(mask, [polygon], 1)
            masks.append(mask)

            # Boundingbox
            x = polygon[:, 0]
            y = polygon[:, 1]
            xmin = np.min(x)
            xmax = np.max(x)
            ymin = np.min(y)
            ymax = np.max(y)
            xmins.append(float(xmin) / width)
            xmaxs.append(float(xmax) / width)
            ymins.append(float(ymin) / height)
            ymaxs.append(float(ymax) / height)
    # Remove holes in mask
    for mask in masks:
        mask = cv2.fillPoly(mask, hole_polygons, 0)

    annotation_dict = {'height': height,
                       'width': width,
                       'filename': image_name,
                       'sha256_key': key,
                       'encoded_jpg': encoded_jpg,
                       'format': image_format,
                       'xmins': xmins,
                       'xmaxs': xmaxs,
                       'ymins': ymins,
                       'ymaxs': ymaxs,
                       'masks': masks,
                       'class_names': class_names}
    return annotation_dict


def main(_):
    if not os.path.exists(FLAGS.images_dir):
        raise ValueError('`images_dir` is not exist.')
    if not os.path.exists(FLAGS.annotations_json_dir):
        raise ValueError('`annotations_json_dir` is not exist.')
    if not os.path.exists(FLAGS.label_map_path):
        raise ValueError('`label_map_path` is not exist.')

    #label_map = read_pbtxt_file.get_label_map_dict(FLAGS.label_map_path)
    label_map = label_map_util.get_label_map_dict(FLAGS.label_map_path)

    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)

    num_annotations_skiped = 0
    annotations_json_path = os.path.join(FLAGS.annotations_json_dir, '*.json')
    for i, annotation_file in enumerate(glob.glob(annotations_json_path)):
        if i % 100 == 0:
            print('On image %d', i)

        annotation_dict = _get_annotation_dict(
            FLAGS.images_dir, annotation_file)
        if annotation_dict is None:
            num_annotations_skiped += 1
            continue
        tf_example = create_tf_example(annotation_dict, label_map)
        writer.write(tf_example.SerializeToString())

    print('Successfully created TFRecord to {}.'.format(FLAGS.output_path))


if __name__ == '__main__':
    tf.app.run()`

### i used this command to generate my tfrecord  :

`python3 create_tf_record_json.py --images_dir=image_mask --annotations_json_dir=image_mask --label_map_path=cacao_mask.pbtxt --output_path=/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/data/train_mask.record`

### this is the content of my file cacao_mask.pbtxt : 

`item {
  name: "cacao_sain"
  id: 1
  display_name: "Cacao en bon etat"
}

item {
  name: "cacao_infecte"
  id: 2
  display_name: "cacao infecte"
}

item {
  name: "gonflement_tige"
  id: 3
  display_name: "Gonflement de la tige"
}

item {
  name: "__ignore__"
  id: 4
  display_name: ""
}
`
### this is file generated by labelme class_name.txt : 

`__ignore__
_background_

cacao_sain
cacao_infecte
gonflement_tige`

I selected this pre-trained model for training mask_rcnn_resnet50_atrous_coco_2018_01_28 

### when i execute this command for training : 

`python3 legacy/train.py --train_dir=training_mask/ --pipeline_config_path=mask_rcnn_resnet50_atrous_coco_2018_01_28/pipeline.config`

i get these errors : 
`Traceback (most recent call last):
  File "legacy/train.py", line 184, in <module>
    tf.app.run()
  File "/home/fabienne/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/fabienne/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "legacy/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/legacy/trainer.py", line 290, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/legacy/trainer.py", line 205, in _create_losses
    losses_dict = detection_model.loss(prediction_dict, true_image_shapes)
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1670, in loss
    groundtruth_masks_list,
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1916, in _loss_box_classifier
    raise ValueError('Groundtruth instance masks not provided. '
ValueError: Groundtruth instance masks not provided. Please configure input reader.`

### Excuse me if i make a mistake in these line below i am french speaker . I need help for solving . what is wrong ???

**Comment by GhislainAdon** [comment] 2019-03-04 13:40
**System information**

    What is the top-level directory of the model you are using: model/research/object_detection
    **Have I written custom code **: No
    OS Platform and Distribution : Linux Ubuntu 16.04
    TensorFlow installed from (source or binary): source
    TensorFlow version (use command below): 1.9.0
    Bazel version (if compiling from source): N/A
    CUDA/cuDNN version: N/A
    GPU model and memory: No GPU
    Exact command to reproduce:

**Describe the problem**

### I want to learn object detection with mask . 
First i use labelme to annotate my dataset .Then i convert json file generaed in PNG mask.
I use this script below to create TFrecord file :
`#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 26 10:57:09 2018

@author: shirhe-lyh
"""

"""Convert raw dataset to TFRecord for object_detection.

Please note that this tool only applies to labelme's annotations(json file).

Example usage:
    python3 create_tf_record.py \
        --images_dir=your absolute path to read images.
        --annotations_json_dir=your path to annotaion json files.
        --label_map_path=your path to label_map.pbtxt
        --output_path=your path to write .record.
"""

import cv2
import glob
import hashlib
import io
import json
import numpy as np
import os
import PIL.Image
import tensorflow as tf
from object_detection.utils import label_map_util
#import read_pbtxt_file

flags = tf.app.flags

flags.DEFINE_string('images_dir', default='D:/Mask_RCNN-master/train_data/pic',help='')
flags.DEFINE_string('annotations_json_dir', 'D:/Mask_RCNN-master/train_data/json',
                   help='')
flags.DEFINE_string('label_map_path',default='C:/Users/18301/Desktop/data.pbtxt',help='')
flags.DEFINE_string('output_path', default='C:/Users/18301/Desktop/train.record', help='')

FLAGS = flags.FLAGS


def int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def int64_list_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))


def bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def bytes_list_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=value))


def float_list_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))


def create_tf_example(annotation_dict, label_map_dict=None):
    """Converts image and annotations to a tf.Example proto.

    Args:
        annotation_dict: A dictionary containing the following keys:
            ['height', 'width', 'filename', 'sha256_key', 'encoded_jpg',
             'format', 'xmins', 'xmaxs', 'ymins', 'ymaxs', 'masks',
             'class_names'].
        label_map_dict: A dictionary maping class_names to indices.

    Returns:
        example: The converted tf.Example.

    Raises:
        ValueError: If label_map_dict is None or is not containing a class_name.
    """
    if annotation_dict is None:
        return None
    if label_map_dict is None:
        raise ValueError('`label_map_dict` is None')

    height = annotation_dict.get('height', None)
    width = annotation_dict.get('width', None)
    filename = annotation_dict.get('filename', None)
    sha256_key = annotation_dict.get('sha256_key', None)
    encoded_jpg = annotation_dict.get('encoded_jpg', None)
    image_format = annotation_dict.get('format', None)
    xmins = annotation_dict.get('xmins', None)
    xmaxs = annotation_dict.get('xmaxs', None)
    ymins = annotation_dict.get('ymins', None)
    ymaxs = annotation_dict.get('ymaxs', None)
    masks = annotation_dict.get('masks', None)
    class_names = annotation_dict.get('class_names', None)

    labels = []
    for class_name in class_names:
        label = label_map_dict.get(class_name, None)
        if label is None:
            raise ValueError('`label_map_dict` is not containing {}.'.format(
                class_name))
        labels.append(label)

    encoded_masks = []
    for mask in masks:
        pil_image = PIL.Image.fromarray(mask.astype(np.uint8))
        output_io = io.BytesIO()
        pil_image.save(output_io, format='PNG')
        encoded_masks.append(output_io.getvalue())

    feature_dict = {
        'image/height': int64_feature(height),
        'image/width': int64_feature(width),
        'image/filename': bytes_feature(filename.encode('utf8')),
        'image/source_id': bytes_feature(filename.encode('utf8')),
        'image/key/sha256': bytes_feature(sha256_key.encode('utf8')),
        'image/encoded': bytes_feature(encoded_jpg),
        'image/format': bytes_feature(image_format.encode('utf8')),
        'image/object/bbox/xmin': float_list_feature(xmins),
        'image/object/bbox/xmax': float_list_feature(xmaxs),
        'image/object/bbox/ymin': float_list_feature(ymins),
        'image/object/bbox/ymax': float_list_feature(ymaxs),
        'image/object/mask': bytes_list_feature(encoded_masks),
        'image/object/class/label': int64_list_feature(labels)}
    example = tf.train.Example(features=tf.train.Features(
        feature=feature_dict))
    return example


def _get_annotation_dict(images_dir, annotation_json_path):
    """Get boundingboxes and masks.

    Args:
        images_dir: Path to images directory.
        annotation_json_path: Path to annotated json file corresponding to
            the image. The json file annotated by labelme with keys:
                ['lineColor', 'imageData', 'fillColor', 'imagePath', 'shapes',
                 'flags'].

    Returns:
        annotation_dict: A dictionary containing the following keys:
            ['height', 'width', 'filename', 'sha256_key', 'encoded_jpg',
             'format', 'xmins', 'xmaxs', 'ymins', 'ymaxs', 'masks',
             'class_names'].
#
#    Raises:
#        ValueError: If images_dir or annotation_json_path is not exist.
    """
    #    if not os.path.exists(images_dir):
    #        raise ValueError('`images_dir` is not exist.')
    #
    #    if not os.path.exists(annotation_json_path):
    #        raise ValueError('`annotation_json_path` is not exist.')

    if (not os.path.exists(images_dir) or
            not os.path.exists(annotation_json_path)):
        return None

    with open(annotation_json_path, 'r') as f:
        json_text = json.load(f)
    shapes = json_text.get('shapes', None)
    if shapes is None:
        return None
    image_relative_path = json_text.get('imagePath', None)
    if image_relative_path is None:
        return None
    image_name = image_relative_path.split('/')[-1]
    image_path = os.path.join(images_dir, image_name)
    image_format = image_name.split('.')[-1].replace('jpg', 'jpeg')
    if not os.path.exists(image_path):
        return None

    with tf.gfile.GFile(image_path, 'rb') as fid:
        encoded_jpg = fid.read()
    image = cv2.imread(image_path)
    height = image.shape[0]
    width = image.shape[1]
    key = hashlib.sha256(encoded_jpg).hexdigest()

    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    masks = []
    class_names = []
    hole_polygons = []
    for mark in shapes:
        class_name = mark.get('label')
        class_names.append(class_name)
        polygon = mark.get('points')
        polygon = np.array(polygon)
        if class_name == 'hole':
            hole_polygons.append(polygon)
        else:
            mask = np.zeros(image.shape[:2])
            cv2.fillPoly(mask, [polygon], 1)
            masks.append(mask)

            # Boundingbox
            x = polygon[:, 0]
            y = polygon[:, 1]
            xmin = np.min(x)
            xmax = np.max(x)
            ymin = np.min(y)
            ymax = np.max(y)
            xmins.append(float(xmin) / width)
            xmaxs.append(float(xmax) / width)
            ymins.append(float(ymin) / height)
            ymaxs.append(float(ymax) / height)
    # Remove holes in mask
    for mask in masks:
        mask = cv2.fillPoly(mask, hole_polygons, 0)

    annotation_dict = {'height': height,
                       'width': width,
                       'filename': image_name,
                       'sha256_key': key,
                       'encoded_jpg': encoded_jpg,
                       'format': image_format,
                       'xmins': xmins,
                       'xmaxs': xmaxs,
                       'ymins': ymins,
                       'ymaxs': ymaxs,
                       'masks': masks,
                       'class_names': class_names}
    return annotation_dict


def main(_):
    if not os.path.exists(FLAGS.images_dir):
        raise ValueError('`images_dir` is not exist.')
    if not os.path.exists(FLAGS.annotations_json_dir):
        raise ValueError('`annotations_json_dir` is not exist.')
    if not os.path.exists(FLAGS.label_map_path):
        raise ValueError('`label_map_path` is not exist.')

    #label_map = read_pbtxt_file.get_label_map_dict(FLAGS.label_map_path)
    label_map = label_map_util.get_label_map_dict(FLAGS.label_map_path)

    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)

    num_annotations_skiped = 0
    annotations_json_path = os.path.join(FLAGS.annotations_json_dir, '*.json')
    for i, annotation_file in enumerate(glob.glob(annotations_json_path)):
        if i % 100 == 0:
            print('On image %d', i)

        annotation_dict = _get_annotation_dict(
            FLAGS.images_dir, annotation_file)
        if annotation_dict is None:
            num_annotations_skiped += 1
            continue
        tf_example = create_tf_example(annotation_dict, label_map)
        writer.write(tf_example.SerializeToString())

    print('Successfully created TFRecord to {}.'.format(FLAGS.output_path))


if __name__ == '__main__':
    tf.app.run()`

### i used this command to generate my tfrecord  :

`python3 create_tf_record_json.py --images_dir=image_mask --annotations_json_dir=image_mask --label_map_path=cacao_mask.pbtxt --output_path=/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/data/train_mask.record`

### this is the content of my file cacao_mask.pbtxt : 

`item {
  name: "cacao_sain"
  id: 1
  display_name: "Cacao en bon etat"
}

item {
  name: "cacao_infecte"
  id: 2
  display_name: "cacao infecte"
}

item {
  name: "gonflement_tige"
  id: 3
  display_name: "Gonflement de la tige"
}

item {
  name: "__ignore__"
  id: 4
  display_name: ""
}
`
### this is file generated by labelme class_name.txt : 

`__ignore__
_background_

cacao_sain
cacao_infecte
gonflement_tige`

I selected this pre-trained model for training mask_rcnn_resnet50_atrous_coco_2018_01_28 

### when i execute this command for training : 

`python3 legacy/train.py --train_dir=training_mask/ --pipeline_config_path=mask_rcnn_resnet50_atrous_coco_2018_01_28/pipeline.config`

i get these errors : 
`Traceback (most recent call last):
  File "legacy/train.py", line 184, in <module>
    tf.app.run()
  File "/home/fabienne/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/fabienne/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "legacy/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/legacy/trainer.py", line 290, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/legacy/trainer.py", line 205, in _create_losses
    losses_dict = detection_model.loss(prediction_dict, true_image_shapes)
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1670, in loss
    groundtruth_masks_list,
  File "/home/fabienne/Bureau/SAUVEGARDE/models-master/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1916, in _loss_box_classifier
    raise ValueError('Groundtruth instance masks not provided. '
ValueError: Groundtruth instance masks not provided. Please configure input reader.`

### Excuse me if i make a mistake in these line below i am french speaker . I need help for solving . what is wrong ?

**Comment by GhislainAdon** [comment] 2019-03-04 13:48
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

What is the top-level directory of the model you are using: model/research/object_detection
**Have I written custom code **: No
OS Platform and Distribution : Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): 1.9.0
Bazel version (if compiling from source): N/A
CUDA/cuDNN version: N/A
GPU model and memory: No GPU
Exact command to reproduce:

**Comment by GhislainAdon** [comment] 2019-03-04 13:59
i forget i specify in pipeline.config that i have 4 class it correct ??? without background??

**Comment by wyxsky** [comment] 2019-03-06 05:55
Faced the same error, "Groundtruth instance masks not provided. Please configure input reader."

with MSCOCO dataset.

**Comment by wyxsky** [comment] 2019-03-06 07:57
Problem solved. we should use the latest model config file rather that the config file in downloaded tar.gz.

the correct config path:https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/mask_rcnn_inception_resnet_v2_atrous_coco.config

**Comment by GhislainAdon** [comment] 2019-03-06 20:46
thank my friend i will test your solution

**Comment by ymodak** [comment] 2019-05-31 22:11
Closing this issue since its resolved. Feel free to reopen if have any further questions. Thanks!

**Closed by ymodak** 2019-05-31 22:11 UTC

**Comment by royshil** [comment] 2020-01-17 15:37
The crux of the matter is  adding
```
  load_instance_masks: true
  mask_type: PNG_MASKS
```
to `eval_input_reader` and `train_input_reader`

**Comment by GhislainAdon** [comment] 2020-01-17 23:02
whre

> Le nœud du problème consiste à ajouter
> 
> ```
>   load_instance_masks: true
>   mask_type: PNG_MASKS
> ```
> 
> à `eval_input_reader`et`train_input_reader`

where ?? in which file ?? please

**Comment by RenauxLouis** [comment] 2020-02-18 14:28
He means in the `pipeline.config` file
