### ISSUE TITLE
KeyError: 'IteratorGetDevice' when using official pre-trained resnet model

### ISSUE THREAD

**Issue by JoelTsui** [tensorflow/models#4978] opened 2018-08-02 07:18 UTC
I use this code to import pre-trained model.

```
sess = tf.Session()
saver = tf.train.import_meta_graph("path/to/model/model.ckpt-62500.meta")
saver.restore(sess,"path/to/model/model.ckpt-62500")
```

but when i import it, it raise 

`KeyError: 'IteratorGetDevice'`
 
and there are more key error when proceed.

some one asked the same question in this issue:https://github.com/tensorflow/tensorflow/issues/21024,
it said "fixed after updated to tensorflow 1.9", but it does not work for me.

Does anyone else coming up with this error? 
or am i writing code wrong?

**Comment by tensorflowbutler** [comment] 2018-08-02 19:26
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by TheKeyLimePie** [comment] 2018-08-03 12:27
Let me say you that you're not alone with this issue. I've noticed the same error recently. I'm trying to use an official pretrained model (https://github.com/tensorflow/models/tree/master/official/resnet, ResNet-50 v2 on ImageNet) for further segmentation training purposes and get the same error.
```python
tf.reset_default_graph()
config = tf.ConfigProto()
config.gpu_options.allow_growth = True

with tf.Session(config = config) as sess:
        sess.run(tf.global_variables_initializer())
        saver = tf.train.import_meta_graph('./pretrained/imagenet-resnet50/model.ckpt-258931.meta', clear_devices = True)
        saver.restore(sess, tf.train.latest_checkpoint('./pretrained/imagenet-resnet50/'))
```
There's no difference in running `tf.train.import_meta_graph()` without the `clear_devices` flag regarding the printed error messages.

---
OS Platform: Windows 10 Education 1803
Tensorflow: Installed from pip (using Anaconda)
Tensorflow version: 1.9.0
CUDA version: 9.0.176
cuDNN version: 7.1
GPU: NVIDIA GTX 1070, 8 GB
Command to reproduce: see above

**Comment by qlzh727** [comment] 2018-08-06 18:47
Adding @mrry. I can also repo this my instance with latest TF nightly. Not sure why "IteratorGetDevice" is not available in the registed ops. Does it have anything to do with https://github.com/tensorflow/tensorflow/pull/18624?

**Comment by mrry** [comment] 2018-08-06 18:53
It looks like the saved `MetaGraphDef` has some ops from `tf.contrib` in it, which haven't been loaded when you call `tf.train.import_meta_graph()`.

Can you try adding the following statement before calling `tf.train.import_meta_graph()`?

```python
_ = tf.contrib  # Force the `tf.contrib` kernels to be loaded.
```

**Comment by TheKeyLimePie** [comment] 2018-08-06 19:06
I added your suggested line of code just after `sess.run(tf.global_variables_initializer())` but it didn't solve the error.

**Comment by mrry** [comment] 2018-08-06 20:08
Can you try adding it before the `with tf.Session(...):` line?

(Also, I don't think `sess.run(tf.global_variables_initializer())` is doing anything, since the graph is empty at that point, so there are no variables, global or otherwise, to initialize.)

**Comment by TheKeyLimePie** [comment] 2018-08-06 20:44
Unfortunately, this didn't do the trick either and lead to the same error message. Calling a sub module like `_ = tf.contrib.nn`, on the other hand, revealed a new error message:

> NotFoundError: Op type not registered 'NcclAllReduce' in binary running on [PC-NAME]. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by mrry** [comment] 2018-08-06 21:45
Aha, thanks: now that you mention it, I realize that you need to reference a submodule of `tf.contrib` to trick the lazy module loader into running.

The `NcclAllReduce` op looks like it uses *even lazier* loading...

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/nccl/python/ops/nccl_ops.py#L267-L274

It looks like you might need another call to get this to run, e.g.

```python
from tensorflow.contrib.nccl.python.ops import nccl_ops
nccl_ops._maybe_load_nccl_ops_so()
```

(Clearly it's a bug that you should have to do so much work to load a pretrained model. I'm not sure how this model was generated, but perhaps there is a way to generate it without the input pipeline and NCCL ops?)

**Comment by JoelTsui** [comment] 2018-08-07 06:17
@mrry Unfortunately, even with all code above, new error message occurred.

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef missing attr 'output_types' from Op<name=FunctionBufferingResource; signature=string_arg:string, target_device:string -> resource:resource; attr=shared_name:string; attr=container:string; attr=f:func; attr=buffer_size:int; attr=output_types:list(type); is_stateful=true>; NodeDef: {{node FunctionBufferingResource}} = FunctionBufferingResource[_output_shapes=[<unknown>], buffer_size=1, container="", f=_prefetch_fn_0CSL7hFXlzE[], shared_name="", _device="/device:GPU:0"](IteratorToStringHandle, IteratorGetDevice)

During handling of the above exception, another exception occurred:

ValueError: NodeDef missing attr 'output_types' from Op<name=FunctionBufferingResource; signature=string_arg:string, target_device:string -> resource:resource; attr=shared_name:string; attr=container:string; attr=f:func; attr=buffer_size:int; attr=output_types:list(type); is_stateful=true>; NodeDef: {{node FunctionBufferingResource}} = FunctionBufferingResource[_output_shapes=[<unknown>], buffer_size=1, container="", f=_prefetch_fn_0CSL7hFXlzE[], shared_name="", _device="/device:GPU:0"](IteratorToStringHandle, IteratorGetDevice)

```

I am not sure if it is because i used macos cpu version of tensorflow. Later i will try tensorflow-gpu under ubuntu

**Comment by mrry** [comment] 2018-08-07 14:53
This error reflects a mismatch between the version of TensorFlow used to save the model, and the version in which you're importing it. The attr mentioned in the error message was added in https://github.com/tensorflow/tensorflow/commit/6d1beebffd216c5cb2eda8a8ba3a59d605ed8fe1. 

It seems clear that the model uses ops from `tf.contrib`, and there is no guarantee that `tf.contrib` ops will be compatible across versions. In particular, their signature may change, or they may be deleted and/or replaced with a different op. This suggests two workarounds:

* Ensure that you're using the same version of TensorFlow for both saving and loading the model.
* Ensure that the model you save has no `tf.contrib` ops in it. The `Estimator.export_savedmodel()` API may be useful here, because it can avoid inserting the input pipeline and optimizer ops, which seem to be what's causing problems here.

**Comment by TheKeyLimePie** [comment] 2018-08-07 15:01
@mrry It looks like the function `nccl_ops._maybe_load_nccl_ops_so()` will be available in the upcoming release, R1.10. Taking a closer look at the current release (R1.9), the `resource_loader` operation is executed right in the beginning of `nccl_ops.py`:
https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/nccl/python/ops/nccl_ops.py#L29-L30
So I simply added the `from tensorflow.contrib.nccl.python.ops import nccl_ops` to my code which should automatically execute the line mentioned above. Nevertheless, the error message remained the same.

**Comment by qlzh727** [comment] 2018-08-07 15:34
Thanks @mrry. I guess https://github.com/tensorflow/models/blob/master/official/resnet/imagenet_main.py#L184 might be the cause of this incompatibility. Since tf-model team own the official model code, we will update to use the latest tf.dataset code and regenerate the checkpoints.

**Comment by mfernezir** [comment] 2018-08-08 11:07
@mrry Thanks for the tips! 

I added `import tensorflow.contrib` to solve this for me on TF 1.8.0.

**Comment by WonderAndMaps** [comment] 2018-08-21 21:25
Anyone know what is the version of tf for saving the official resnet model in the first place?

**Comment by robieta** [comment] 2018-08-21 21:35
I generated the checkpoints on 6/1/18 with a recent nightly build, which would put the version around 1.9.

**Comment by HKDown2014** [comment] 2018-08-24 01:25
@JoelTsui Have you solved this probelem ?

**Comment by qlzh727** [comment] 2018-08-24 15:15
From previous comment, it seems that the checkpoints are generated with TF 1.8.

**Comment by Ali2500** [comment] 2018-08-31 14:08
Any progress on this? Even the `graph.pbtext` file cannot be used for graph restoration at this point.

**Comment by jinglingzhua** [comment] 2018-09-05 08:27
solved by adding 'import tensorflow.contrib'
with tensorflow 1.9 (conda version) on ubuntu 16.04

**Comment by qlzh727** [comment] 2018-11-07 17:13
@robieta, have we recently publish any new version of saved model for resnet? Can we close this bug if the newer version is available?

**Comment by robieta** [comment] 2018-11-07 17:16
Yes, new checkpoints were generated on 10/4 (https://github.com/tensorflow/models/pull/5440) Thanks for your patience everyone!

**Closed by robieta** 2018-11-07 17:16 UTC

**Comment by dlhocker** [comment] 2018-12-04 17:39
Has anyone successfully used the new chkpt files for resnet? If so, could you share the tensorflow version, models release version, and chkpt used? 

I tried the same approach and received the same error as @Sirius083,  KeyError: 'IteratorV2', and think it’s because I have some sort of version mismatch, but can’t track it down.  Seeing this for both tensorflow 1.9.0 and 1.12.0 (both conda releases, Mac OS).  To try and match tensorflow versions with the correct models release in case I missed something, I am also using the models-1.9.0 release for tensorflow1.9.0 and a recently cloned models repo with tensorflow 1.12.0 (cloned 28 Nov. 2018. [2d9d794](
https://github.com/tensorflow/models/commit/2d9d79433b1eeac3f859e44e3c2650270621f43a)). Attempting to use[ fp32 version of checkpoint](
http://download.tensorflow.org/models/official/20181001_resnet/checkpoints/resnet_imagenet_v2_fp32_20181001.tar.gz), and `model.ckpt-225207` chkpt files.

Any advice?
