### ISSUE TITLE
SyntaxNet POS Tagger Training : Error = 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by elduba** [tensorflow/models#219] opened 2016-06-17 17:00 UTC
Hi experts,

I am facing this "NoneType" error when trying to execute the parser_trainer...
I have a clean python install, but I don't know how to define "FLAGS.arg_prefix" or  "FLAGS.graph_builder"
I have attached my configuration files, it case i was wrong with it's configuration.

All bazel test passed well and demo.sh too.

Thank you for helping me going through this great tool :)

error stack : 
```
File "/home/----/models/syntaxnet/bazel-bin/syntaxnet/parser_trainer.runfiles/syntaxnet/parser_trainer.py", line 88, in StageName
    return os.path.join(FLAGS.arg_prefix, FLAGS.graph_builder)
  File "/usr/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Regards
Elduba

**Comment by prb12** [comment] 2016-06-21 16:31
[Note: When reporting a bug it *really* helps to provide the command lines necessary to reproduce the error!]

From the output you provide, it looks like you are not supplying some of the command line arguments expected by this trainer, in particular `--arg_prefix`  (Admittedly the script doesn't appear to check the value of `arg_prefix` before use!)

If you look at the syntaxnet tutorial there are example command lines [here](https://github.com/tensorflow/models/tree/master/syntaxnet#preprocessing-with-the-tagger), e.g.

```
PARAMS=128-0.08-3600-0.9-0
for SET in training tuning dev; do
  bazel-bin/syntaxnet/parser_eval \
    --task_context=models/brain_pos/greedy/$PARAMS/context \
    --hidden_layer_sizes=128 \
    --input=$SET-corpus \
    --output=tagged-$SET-corpus \
    --arg_prefix=brain_pos \
    --graph_builder=greedy \
    --model_path=models/brain_pos/greedy/$PARAMS/model
done
```

I'll tag this as a bug for now.

**Comment by calberti** [comment] 2016-06-22 14:39
You can specify --arg_prefix and --graph_builder on your command line.  I'm closing this, but feel free to reopen if you need more help following the README.

**Closed by calberti** 2016-06-22 14:39 UTC
Labels: bug, triaged
