### ISSUE TITLE
Mismatch between checkpoint and model when I restored Nasnet

### ISSUE THREAD

**Issue by fengsky401** [tensorflow/models#4191] opened 2018-05-07 10:00 UTC
There is no bug in the codes. The code is as below.
The length of var_list is 3117,while the length of variables_to_restore is 1547.
I don't know what causes the difference.
checkpoint  is nasnet-a_large downloaded from https://storage.googleapis.com/download.tensorflow.org/models/nasnet-a_large_04_10_2017.tar.gz

 
```
import tensorflow as tf
from tensorflow.contrib.slim.python.slim.nets import inception_resnet_v2
from tensorflow.contrib.framework.python.framework import checkpoint_utils
from tensorflow.contrib.slim.python.slim.nets.nasnet import nasnet

slim = tf.contrib.slim
checkpoint_file="./model_weight_nasnet/model.ckpt"
model_dir="./model_weight_nasnet/"
cnt=0

#checkpoint_file=tf.train.latest_checkpoint("./model_weight/")
var_list = checkpoint_utils.list_variables(checkpoint_file)
#
for v in var_list:
    print("No %d:%s" %(cnt,v))
    cnt+=1


NUM_CLASS=1001

image = tf.placeholder(tf.float32, shape=[331, 331, 3])


image_reshape = tf.reshape(image, [-1, 331, 331, 3])
with slim.arg_scope(nasnet.nasnet_large_arg_scope()):

    logits,_ = nasnet.build_nasnet_large(image_reshape, num_classes=NUM_CLASS, is_training=False)

    global_step = tf.Variable(0, name='global_step',dtype=tf.int64, trainable=False)

    variables_to_restore = slim.get_variables_to_restore()

    cnt = 0
    for i in variables_to_restore:
        print("No %d:%s" % (cnt, v))
        cnt+=1

    saver = tf.train.Saver(variables_to_restore)


    init_op = tf.initialize_all_variables()

variable_list=[]


saver2 = tf.train.Saver(tf.global_variables())

sess=tf.Session()
sess.run(init_op)
sess.run(variables_to_restore)

saver.restore(sess, checkpoint_file)

saver2.save(sess, model_dir + "/nasnet_initial.ckpt", global_step=0)



```

**Comment by tensorflowbutler** [comment] 2018-05-09 19:40
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-09 22:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2020-01-29 23:22
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:45 UTC
Labels: stat:awaiting response
