### ISSUE TITLE
Why not use tf.layers.batch_normalization?

### ISSUE THREAD

**Issue by glhfgg1024** [tensorflow/models#2970] opened 2017-12-07 04:51 UTC
Hi Dear Sir/Madam,
In the following file, why don't you use the `tf.layers.batch_normalization`? But for other functions, many `tf.layers` API routines have been used. Does this mean the `tf.layers.batch_normalization` has anything wrong? Thanks.

https://github.com/tensorflow/models/blob/5a5d330539dff11eef79ca2e716fb477baf13cf9/tutorials/image/cifar10_estimator/model_base.py#L183

**Comment by drpngx** [comment] 2017-12-07 17:47
No, what happens is that we first stage code in contrib, and then when it's stable, we move to the core API (in that case `tf.layers`). We don't always update all the code. Thank you for pointing that out.

@nealwu @MarkDaoust could we update the tutorial code?

**Comment by nealwu** [comment] 2017-12-12 03:14
Re-assigning to @protoget. James could you update `tf.contrib.layers.batch_norm` in your example to `tf.layers.batch_normalization`?

There are also a few other likely convertible contrib calls, such as `tf.contrib.data` or `tf.contrib.learn.Experiment`.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:30
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by MarkDaoust** [comment] 2020-01-30 04:42
Everything in this directory is out of date and should be deleted.

b/139685108

**Closed** 2020-01-30 04:43 UTC
Labels: models: official
