### ISSUE TITLE
Building SyntaxNet on macOS Sierra

### ISSUE THREAD

**Issue by nxz91** [tensorflow/models#599] opened 2016-10-31 06:40 UTC
While trying to build SyntaxNet on macOS Sierra, I encountered a problem in the ./configure step:

> Error: couldn't connect to server at '/private/var/tmp/_bazel_root/635540f250200f02d299666b494b9c7e/server/server.socket' after 60 seconds.

- I chose the default value for each option
- The script finds two possible Python library paths (/Library/Python/2.7/site-packages and /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages)

What am I doing wrong?

**Comment by gustelle** [comment] 2016-11-12 14:39
Is there an update on this ? I got the same issue

**Comment by petterhh** [comment] 2016-11-21 13:48
I'm getting the same error. Still no updates?

**Comment by x1wins** [comment] 2016-12-20 07:49
i've been getting same error too.

**Comment by aselle** [comment] 2017-02-10 21:59
Closing since I believe this is a duplicate of #643 (which is fixed)

**Closed by aselle** 2017-02-10 21:59 UTC
Labels: stat:awaiting tensorflower, type:build/install
