### ISSUE TITLE
textsum

### ISSUE THREAD

**Issue by vmujadia** [tensorflow/models#578] opened 2016-10-24 08:40 UTC
## Please let us know which model this issue is about (specify the top-level directory)
Hi 

This for textsum,

i am getting following decoded output 

output=: , , to to to to to to to to to to to to to to to to to to to to to to to to in in in in in in in in
output=: : , , to to to to to to to to to to to - to - in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in in

vocab file is like,

the 21722151
, 19466645
' 12733042
to 11408609
a 9878806
of 9573580
and 9555158
in 8476976
" 4497443
was 4135715
for 3805072
that 3741244
on 3622566
s 3564827
is 3559664
\ 3540158
with 2950717
he 2817341
<s> 2764755
</s> 2764755
it 2668286
: 2561938
his 2512786
at 2448726
as 2373424

any suggestion why this is happening ?

**Comment by asimshankar** [comment] 2016-10-24 08:45
@vmujadia : Perhaps this question is better suited for [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). The github issue tracker aims to be focused on bug reports and feature requests.

If you do think there is a bug, please do provide detailed instructions on reproducing the problem - including which version of TensorFlow you are using and the set of steps one can take to reproduce the bug.

Since I think the current question is more suited to stackoverflow, I'll close this issue. However, feel free to reopen with more information if I misunderstood. Thanks much!

**Closed by asimshankar** 2016-10-24 08:45 UTC
