### ISSUE TITLE
None-compatible type-annotations 

### ISSUE THREAD

**Issue by apacha** [tensorflow/models#10764] opened 2022-09-05 11:43 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/a90ef19271200125f7151987a96fae5608511076/official/vision/ops/spatial_transform_ops.py#L73

## 2. Describe the bug

The used type-annotations (`tuple[...]` instead of `Tuple[]`) are Python 3.9+, whereas much of the repository should still run in lower Python version, e.g., when running the latest official tensorflow docker image. 
[PEP-0585](https://peps.python.org/pep-0585/) describes where this feature was started to be supported, which is Python 3.9. Therefore, please change all type annotations to downwards compatible annotations.

## 3. Steps to reproduce

Run the tutorial from https://blog.tensorflow.org/2021/01/leveraging-tensorflow-tensorrt-integration.html

## 4. Expected behavior

Train the MNIST model. 

## 5. Additional context

```
root@59fcdc80ad26:/workspace# python -m "official.vision.image_classification.mnist_main"   --model_dir=./checkpoints   --data_dir=/data   --train_epochs=10   --distribution_strategy=one_device   --num_gpus=1   --download
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/workspace/official/vision/__init__.py", line 18, in <module>
    from official.vision import tasks
  File "/workspace/official/vision/tasks/__init__.py", line 17, in <module>
    from official.vision.tasks.image_classification import ImageClassificationTask
  File "/workspace/official/vision/tasks/image_classification.py", line 28, in <module>
    from official.vision.modeling import factory
  File "/workspace/official/vision/modeling/__init__.py", line 17, in <module>
    from official.vision.modeling import backbones
  File "/workspace/official/vision/modeling/backbones/__init__.py", line 17, in <module>
    from official.vision.modeling.backbones.efficientnet import EfficientNet
  File "/workspace/official/vision/modeling/backbones/efficientnet.py", line 27, in <module>
    from official.vision.modeling.layers import nn_blocks
  File "/workspace/official/vision/modeling/layers/__init__.py", line 20, in <module>
    from official.vision.modeling.layers.mask_sampler import MaskSampler
  File "/workspace/official/vision/modeling/layers/mask_sampler.py", line 20, in <module>
    from official.vision.ops import spatial_transform_ops
  File "/workspace/official/vision/ops/spatial_transform_ops.py", line 73, in <module>
    sample_offset: float) -> tuple[tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor]:
TypeError: 'type' object is not subscriptable
```
**Please note that this is NOT the only occurrence of non-compatible type annotations in this repository!**

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Latest official Tensorflow docker image with Python 3.8
- TensorFlow installed from (source or binary): Pre-installed
- TensorFlow version (use command below): 2.9.2
- Python version: 3.8

**Comment by saberkun** [comment] 2022-09-10 23:01
The issue is fixed by: https://github.com/tensorflow/models/commit/5e87dfefd941a964942c584db0261b5003d75abe

Sorry for type errors. Somehow some the of the type annotation checks were disabled internally. 
We may not be able to catch them. So please help report and we will fix them asap.

**Closed by saberkun** 2022-09-10 23:01 UTC
Labels: type:bug, models:official
