### ISSUE TITLE
[deeplab] CUDA_ERROR_LAUNCH_FAILED while using demo script

### ISSUE THREAD

**Issue by ogruhlke94** [tensorflow/models#3753] opened 2018-03-26 16:42 UTC
### System information
- **What is the top-level directory of the model you are using**:
deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.6
- **Bazel version (if compiling from source)**:
0.11.1
- **CUDA/cuDNN version**:
Cuda 9.1 / cuDNN 7.1.2
- **GPU model and memory**:
GeForce GTX TITAN  - 6GB
- **Exact command to reproduce**:

### Describe the problem
I'm trying to execute the provided demo script _local_test.sh_. I only made some changes from other issues regarding to python3 and changed the batch_size to 1 due to my limited VRAM. Also I increased the iteration number to 1000.
After a different number of iterations (between 10 and 200) a CUDA_ERROR_LAUNCH_FAILED occurs  (see provided log).
I also tried using the binary version of tensorflow with Cuda 9.0 and cuDNN 7.0. My current nvidia driver version is 390.30.
I watched the GPU memory usage with nvidia-smi and it was always about 300MB free VRAM - so a out of memory issue seems unlikely.

### Source code / logs
```
2018-03-26 18:22:08.100135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: GeForce GTX TITAN major: 3 minor: 5 memoryClockRate(GHz): 0.8755
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.83GiB
2018-03-26 18:22:08.100148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-26 18:22:08.268167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5627 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN, pci bus id: 0000:01:00.0, compute capability: 3.5)
INFO:tensorflow:Restoring parameters from /home/ogruhlke/Schreibtisch/tensorflow_models/models/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /home/ogruhlke/Schreibtisch/tensorflow_models/models/research/deeplab/datasets/pascal_voc_seg/exp/train_on_trainval_set/train/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Recording summary at step 0.
INFO:tensorflow:global step 10: loss = 3.2638 (0.176 sec/step)
INFO:tensorflow:global step 20: loss = 0.9162 (0.174 sec/step)
INFO:tensorflow:global step 30: loss = 0.8637 (0.174 sec/step)
2018-03-26 18:22:29.385213: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED
2018-03-26 18:22:29.385252: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
Aborted (core dumped)
```

**Comment by khcy82dyc** [comment] 2018-04-11 14:01
@ogruhlke94 Hi have you found the solution?

**Comment by ogruhlke94** [comment] 2018-04-11 16:17
No I haven't. It's still not working.

**Comment by walkerlala** [comment] 2018-04-12 15:14
It looks like a tensorflow issue rather than a deeplab issue. Seems like something is wrong with your cudnn. See https://github.com/tensorflow/tensorflow/issues/10852 and https://github.com/tensorflow/tensorflow/issues/3224. If those still can't solve you issue, please report that to the core tensorflow repo, with information about how to reproduce this issue.

**Comment by wt-huang** [comment] 2018-11-01 13:02
Closing as this is a duplicate

**Closed by wt-huang** 2018-11-01 13:02 UTC
