### ISSUE TITLE
[slim] Problem with train_lenet_on_mnist when requiring parameter server

### ISSUE THREAD

**Issue by beeva-enriqueotero** [tensorflow/models#1196] opened 2017-03-17 14:07 UTC
Hello,

I get an error when trying `train_lenet_on_mnist.sh` with `--worker_replicas=2` and `--num_ps_tasks=1`

```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Cannot assign a device to node 'save/RestoreV2_7': Could not satisfy explicit device specification '/job:worker/device:CPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0, /job:localhost/replica:0/task:0/gpu:0, /job:localhost/replica:0/task:0/gpu:1, /job:localhost/replica:0/task:0/gpu:2, /job:localhost/replica:0/task:0/gpu:3, /job:localhost/replica:0/task:0/gpu:4, /job:localhost/replica:0/task:0/gpu:5, /job:localhost/replica:0/task:0/gpu:6, /job:localhost/replica:0/task:0/gpu:7
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:worker/device:CPU:0"](save/Const, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
```
Tested on aws p2.8x instance with tensorflow_gpu-1.0.1-cp27-cp27mu-manylinux1_x86_64.whl and also compiled from source.

Thanks

**Comment by concretevitamin** [comment] 2017-03-18 00:58
Could you try passing `--master=localhost` as well?  Additionally, if you just don't specified `worker_replicas` and `num_ps_tasks`, does it work?

**Comment by beeva-enriqueotero** [comment] 2017-03-21 12:37
`--master=localhost` generates the following error: `E tensorflow/core/common_runtime/session.cc:69] Not found: No session factory registered for the given session options: {target: "localhost" config: } Registered factories are {DIRECT_SESSION, GRPC_SESSION}.`

Anyway if I don't specify `worker_replicas` and `num_ps_tasks` or I use `worker_replicas=1` and `num_ps_tasks=0` it works fine, as expected.

Thanks

**Comment by beeva-enriqueotero** [comment] 2017-03-21 15:57
I don't know why this issue has been closed. I still get an error when I try to use `train_lenet_on_mnist.sh` with parameter server. I did't get any satisfactory answer.

Regards

**Comment by concretevitamin** [comment] 2017-03-21 16:09
Oh sorry, I misread your last response.  Re-opening this for the right owners to take a look.

**Comment by aselle** [comment] 2017-03-28 17:49
@mrry, do you have any insight on this or know who might?

**Comment by mrry** [comment] 2017-03-28 22:33
From looking at that script, it doesn't look like anything in that library ever creates a `tf.train.Server`, so I can't see how it would ever work for distributed training. There doesn't seem to be any public interface e.g. for setting the network addresses of the worker and PS tasks, which would be a prerequisite.

Perhaps this code was copied from another codebase that does have distributed support, but the distributed parts were left out?

**Comment by vincentchu** [comment] 2017-03-28 22:42
I was debugging a similar error message. Is it possible that the `DeploymentConfig` in `model_deploy.py` is hardcoding the `worker_job_name` to `worker` when it means `localhost`?

See: https://github.com/tensorflow/models/blob/master/slim/deployment/model_deploy.py#L490

**Comment by mrry** [comment] 2017-03-28 22:46
I think the `worker_job_name` is a TensorFlow job name (as in the string `"worker"` in `"/job:worker"`), and not a network address.

These scripts need a lot of modifications (including extra configuration options and `tf.train.Server` setup) to work in a distributed setting. Once that is there, when starting a worker task, you'd set the `--master` flag to `grpc://hostname:port` where `hostname:port` is the address of the `tf.train.Server` in that worker.

**Comment by fanlu** [comment] 2017-04-21 07:26
Is this problem solved?

**Comment by beeva-enriqueotero** [comment] 2017-04-21 07:50
As far as i know, it's not solved :(

**Comment by rodrigofp-cit** [comment] 2017-10-27 15:10
I got the same problem when trying to run the flowers retraining on Google ML Engine. What @mrry reported is also happening to me.

**Comment by karmel** [comment] 2018-02-22 20:00
@sguada Can you comment?

**Comment by kzhang28** [comment] 2018-07-02 01:58
@beeva-enriqueotero Hello, do you know any solution to run TF-slim training on multiple machines? I have the same need but failed to find a way. I opened a question about this on Stackoverflow:[Run TF-slim model training on multiple machinies](https://stackoverflow.com/questions/51118620/how-to-deploy-distributed-tensorflow-slim-example-on-multiple-nodes-cpus-only)

**Comment by rodrigofp-cit** [comment] 2018-07-02 11:56
Hi @kzhang28. I suffered a lot when trying to run pure TF-slim models distributed, but since TF-1.4 I've been running TF-slim models distributed on Google ML Engine using the Estimator API. Basically my model_fn call TF-slim models and it works perfectly.
I hope it helps you.

**Comment by kzhang28** [comment] 2018-07-02 14:47
@rodrigofp-cit  Thanks!  I have never used Estimator API and Google ML engine before. I was wondering if the way you suggested would work if I try to run TF-slim model on multiple metal machines instead of on Google ML Engine.

**Comment by rodrigofp-cit** [comment] 2018-07-02 15:15
@kzhang28 Probably it will, since Estimator API does all networking under the hood. The only requirement is to have all machines within the same network.

**Comment by kzhang28** [comment] 2018-07-02 15:52
@rodrigofp-cit  Thank you! Would you mind sharing your distributed training scripts with me? I was wondering how to specify the cluster setup and job name(worker/ps) for each server.  Should I launch the distributed training job in the following way? Do I need to use `
tf.train.MonitoredSession`.   I appreciate your help.

~~~~# On ps0.example.com:
$ python trainer.py \
     --ps_hosts=ps0.example.com:2222,ps1.example.com:2222 \
     --worker_hosts=worker0.example.com:2222,worker1.example.com:2222 \
     --job_name=ps --task_index=0
# On ps1.example.com:
$ python trainer.py \
     --ps_hosts=ps0.example.com:2222,ps1.example.com:2222 \
     --worker_hosts=worker0.example.com:2222,worker1.example.com:2222 \
     --job_name=ps --task_index=1
# On worker0.example.com:
$ python trainer.py \
     --ps_hosts=ps0.example.com:2222,ps1.example.com:2222 \
     --worker_hosts=worker0.example.com:2222,worker1.example.com:2222 \
     --job_name=worker --task_index=0
# On worker1.example.com:
$ python trainer.py \
     --ps_hosts=ps0.example.com:2222,ps1.example.com:2222 \
     --worker_hosts=worker0.example.com:2222,worker1.example.com:2222 \
     --job_name=worker --task_index=1~~~~

**Comment by rodrigofp-cit** [comment] 2018-07-02 16:23
@kzhang28 Are you running on Google ML Engine? If so, you don't need to specify any of these networking stuffs.

**Comment by kzhang28** [comment] 2018-07-02 19:06
@rodrigofp-cit I see, however, I am going to run the training on a physical cluster instead of Google ML Engine (6 machines with Ubuntu 16 and have TF installed). If there is no way to specify the hosts for ps/worker jobs, I would not be able to run it in a distributed multi-machines fashion.

**Comment by rodrigofp-cit** [comment] 2018-07-02 19:21
Humm, @kzhang28 I've never done a distributed training with bare metal machines, only with ML Engine. However, I think you should populate a [RunConfig](https://www.tensorflow.org/api_docs/python/tf/estimator/RunConfig) object and pass it to your [Estimator](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator) constructor.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:36
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 09:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 09:03 UTC
Labels: stat:awaiting owner, type:support
