### ISSUE TITLE
OID TFRecord creation inconsistent size

### ISSUE THREAD

**Issue by yaysummeriscoming** [tensorflow/models#7813] opened 2019-11-15 15:08 UTC
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX
TensorFlow installed from N/A
TensorFlow version N/A
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce N/A

The tfrecord shards created by the following script (for Open Images Dataset) have uneven size:
object_detection/dataset_tools/create_oid_tf_record.py

This looks to be due to the shard index calculation - it's different to the logic used in other scripts such as create_coco_tf_record.py

Edit: This is for a subset of all OID classes

**Comment by tensorflowbutler** [comment] 2019-11-16 12:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-19 09:38
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-19 09:38 UTC
Labels: models:research, stat:awaiting response

**Comment by yaysummeriscoming** [comment] 2020-06-19 09:43
@ravikyram my apologies I created a PR to fix this issue but didn't link it. The PR is #7814, but is still waiting for review
