### ISSUE TITLE
OOM when allocating tensor with shape[24,1,2304,1152,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu

### ISSUE THREAD

**Issue by tomriddle54** [tensorflow/models#6450] opened 2019-03-27 02:16 UTC
I have 1080 ti  Graphics card I7 Pc I am running Mobilenet v1 my config is set to 24 got Error.
And I have 1060 graphics laptop all files I copied to laptop and started the training with same config file and shocking it worked.
Than i have researcher about it and found to decrease batch size so i did it to 16 on my pc  its working but how is this possible my pc is having 1080 11gb graphic and laptop 1060 6 gb.
Here is the full error 
If you think something is wrong with my config just ask me i will update it,
```
INFO:tensorflow:global step 152: loss = 2.8710 (0.523 sec/step)
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.ResourceExhaustedError'>, OOM when allocating tensor with shape[24,1,2304,1152,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node batch}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.ResourceExhaustedError'>, OOM when allocating tensor with shape[24,1,2304,1152,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node batch}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

INFO:tensorflow:global step 153: loss = 2.9659 (0.381 sec/step)
INFO:tensorflow:global step 153: loss = 2.9659 (0.381 sec/step)
INFO:tensorflow:Finished training! Saving model to disk.
INFO:tensorflow:Finished training! Saving model to disk.
/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py:386: UserWarning: Attempting to use a closed FileWriter. The operation will be a noop unless the FileWriter is explicitly reopened.
  warnings.warn("Attempting to use a closed FileWriter. "
Traceback (most recent call last):
  File "research/object_detection/legacy/train.py", line 184, in <module>
    tf.app.run()
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "research/object_detection/legacy/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/syed/models/research/object_detection/legacy/trainer.py", line 416, in train
    saver=saver)
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 785, in train
    ignore_live_threads=ignore_live_threads)
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 832, in stop
    ignore_live_threads=ignore_live_threads)
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1257, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/media/syed/ubuntu/syed/anaconda3/envs/tod/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[24,1,2304,1152,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node batch}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```

**Comment by tensorflowbutler** [comment] 2019-03-28 00:19
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by syedmustafa54** [comment] 2019-03-28 13:21
**For my PC which is having Problem its** 
Os:- Ubuntu 16.04
Tensorflow installed from conda 
TensorFlow version:- 1.13.1
Bazel version:-Na I did not install it
CUDA:- Cuda compilation tools, release 10.0, V10.0.130
cuDnn:- CUDNN_MAJOR 7
GPU:- Nvidia 1080ti 11gb
Python Version:Python 3.6.8 :: Anaconda, Inc.
Nvidia Drivers : NVIDIA-SMI 410.79 
**Laptop**
Os:- Ubuntu 16.04
Tensorflow installed from conda 
TensorFlow version:- 1.12.0
Bazel version:-Na I did not install it
CUDA:- Cuda compilation tools, release 10.1, V10.1.105
cuDnn:- CUDNN_MAJOR 7
GPU:- Nvidia GeForce GTX 1060 6GB
Python Version:Python 3.6.8 :: Anaconda, Inc.
Nvidia Drivers : NVIDIA-SMI 418.39

**Comment by hdubey** [comment] 2020-03-13 09:23
having similar issues, any solution?

**Comment by ChenjieXu** [comment] 2020-06-11 14:21
have the same issue. Probably caused by update cuda version 10.1 recently.

**Comment by ravikyram** [comment] 2020-07-01 09:56
@tomriddle54 

Is this still an issue?.Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-08-08 02:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-08-08 02:17 UTC
Labels: models:research, stat:awaiting response, type:support
