### ISSUE TITLE
object_detection:  model_builder_test.py throws ValueErrors

### ISSUE THREAD

**Issue by siddhartha-iitd** [tensorflow/models#1704] opened 2017-06-20 20:05 UTC
System information

OS: Linux Ubuntu 16.04
Python: 3.5
TensorFlow version: 1.2.0
tensorflow-gpu installed using pip3

On executing `model_builder_test.py` from `object_detection/builders` directory, a sequence of errors is thrown as shown below:
<pre><code>
faster_rcnn {
  num_classes: 3
  image_resizer {
    keep_aspect_ratio_resizer {
      min_dimension: 600
      max_dimension: 1024
    }
  }
  feature_extractor {
    type: "faster_rcnn_inception_resnet_v2"
  }
  first_stage_anchor_generator {
    grid_anchor_generator {
      height_stride: 16
      width_stride: 16
      scales: 0.25
      scales: 0.5
      scales: 1.0
      scales: 2.0
      aspect_ratios: 0.5
      aspect_ratios: 1.0
      aspect_ratios: 2.0
    }
  }
  first_stage_box_predictor_conv_hyperparams {
    regularizer {
      l2_regularizer {
      }
    }
    initializer {
      truncated_normal_initializer {
      }
    }
  }
  initial_crop_size: 17
  maxpool_kernel_size: 1
  maxpool_stride: 1
  second_stage_box_predictor {
    mask_rcnn_box_predictor {
      fc_hyperparams {
        op: FC
        regularizer {
          l2_regularizer {
          }
        }
        initializer {
          truncated_normal_initializer {
          }
        }
      }
    }
  }
  second_stage_post_processing {
    batch_non_max_suppression {
      score_threshold: 0.009999999776482582
      iou_threshold: 0.6000000238418579
      max_detections_per_class: 100
      max_total_detections: 300
    }
    score_converter: SOFTMAX
  }
}

Efaster_rcnn {
  num_classes: 3
  image_resizer {
    keep_aspect_ratio_resizer {
      min_dimension: 600
      max_dimension: 1024
    }
  }
  feature_extractor {
    type: "faster_rcnn_inception_resnet_v2"
  }
  first_stage_anchor_generator {
    grid_anchor_generator {
      height_stride: 16
      width_stride: 16
      scales: 0.25
      scales: 0.5
      scales: 1.0
      scales: 2.0
      aspect_ratios: 0.5
      aspect_ratios: 1.0
      aspect_ratios: 2.0
    }
  }
  first_stage_box_predictor_conv_hyperparams {
    regularizer {
      l2_regularizer {
      }
    }
    initializer {
      truncated_normal_initializer {
      }
    }
  }
  second_stage_box_predictor {
    mask_rcnn_box_predictor {
      fc_hyperparams {
        op: FC
        regularizer {
          l2_regularizer {
          }
        }
        initializer {
          truncated_normal_initializer {
          }
        }
      }
    }
  }
  hard_example_miner {
    num_hard_examples: 10
    iou_threshold: 0.9900000095367432
  }
}

Efaster_rcnn {
  num_classes: 3
  image_resizer {
    keep_aspect_ratio_resizer {
      min_dimension: 600
      max_dimension: 1024
    }
  }
  feature_extractor {
    type: "faster_rcnn_resnet50"
  }
  first_stage_anchor_generator {
    grid_anchor_generator {
      height_stride: 16
      width_stride: 16
      scales: 0.25
      scales: 0.5
      scales: 1.0
      scales: 2.0
      aspect_ratios: 0.5
      aspect_ratios: 1.0
      aspect_ratios: 2.0
    }
  }
  first_stage_box_predictor_conv_hyperparams {
    regularizer {
      l2_regularizer {
      }
    }
    initializer {
      truncated_normal_initializer {
      }
    }
  }
  initial_crop_size: 14
  maxpool_kernel_size: 2
  maxpool_stride: 2
  second_stage_box_predictor {
    mask_rcnn_box_predictor {
      fc_hyperparams {
        op: FC
        regularizer {
          l2_regularizer {
          }
        }
        initializer {
          truncated_normal_initializer {
          }
        }
      }
    }
  }
  second_stage_post_processing {
    batch_non_max_suppression {
      score_threshold: 0.009999999776482582
      iou_threshold: 0.6000000238418579
      max_detections_per_class: 100
      max_total_detections: 300
    }
    score_converter: SOFTMAX
  }
}

Efaster_rcnn {
  num_classes: 3
  image_resizer {
    keep_aspect_ratio_resizer {
      min_dimension: 600
      max_dimension: 1024
    }
  }
  feature_extractor {
    type: "faster_rcnn_resnet50"
  }
  first_stage_anchor_generator {
    grid_anchor_generator {
      height_stride: 16
      width_stride: 16
      scales: 0.25
      scales: 0.5
      scales: 1.0
      scales: 2.0
      aspect_ratios: 0.5
      aspect_ratios: 1.0
      aspect_ratios: 2.0
    }
  }
  first_stage_box_predictor_conv_hyperparams {
    regularizer {
      l2_regularizer {
      }
    }
    initializer {
      truncated_normal_initializer {
      }
    }
  }
  initial_crop_size: 14
  maxpool_kernel_size: 2
  maxpool_stride: 2
  second_stage_box_predictor {
    rfcn_box_predictor {
      conv_hyperparams {
        op: CONV
        regularizer {
          l2_regularizer {
          }
        }
        initializer {
          truncated_normal_initializer {
          }
        }
      }
    }
  }
  second_stage_post_processing {
    batch_non_max_suppression {
      score_threshold: 0.009999999776482582
      iou_threshold: 0.6000000238418579
      max_detections_per_class: 100
      max_total_detections: 300
    }
    score_converter: SOFTMAX
  }
}

Essd {
  image_resizer {
    fixed_shape_resizer {
      height: 320
      width: 320
    }
  }
  feature_extractor {
    type: "ssd_inception_v2"
    conv_hyperparams {
      regularizer {
        l2_regularizer {
        }
      }
      initializer {
        truncated_normal_initializer {
        }
      }
    }
  }
  box_coder {
    faster_rcnn_box_coder {
    }
  }
  matcher {
    argmax_matcher {
    }
  }
  similarity_calculator {
    iou_similarity {
    }
  }
  box_predictor {
    convolutional_box_predictor {
      conv_hyperparams {
        regularizer {
          l2_regularizer {
          }
        }
        initializer {
          truncated_normal_initializer {
          }
        }
      }
    }
  }
  anchor_generator {
    ssd_anchor_generator {
      aspect_ratios: 1.0
    }
  }
  loss {
    localization_loss {
      weighted_smooth_l1 {
      }
    }
    classification_loss {
      weighted_softmax {
      }
    }
  }
}

Essd {
  image_resizer {
    fixed_shape_resizer {
      height: 320
      width: 320
    }
  }
  feature_extractor {
    type: "ssd_mobilenet_v1"
    conv_hyperparams {
      regularizer {
        l2_regularizer {
        }
      }
      initializer {
        truncated_normal_initializer {
        }
      }
    }
  }
  box_coder {
    faster_rcnn_box_coder {
    }
  }
  matcher {
    argmax_matcher {
    }
  }
  similarity_calculator {
    iou_similarity {
    }
  }
  box_predictor {
    convolutional_box_predictor {
      conv_hyperparams {
        regularizer {
          l2_regularizer {
          }
        }
        initializer {
          truncated_normal_initializer {
          }
        }
      }
    }
  }
  anchor_generator {
    ssd_anchor_generator {
      aspect_ratios: 1.0
    }
  }
  loss {
    localization_loss {
      weighted_smooth_l1 {
      }
    }
    classification_loss {
      weighted_softmax {
      }
    }
  }
}

E.
======================================================================
ERROR: test_create_faster_rcnn_inception_resnet_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "model_builder_test.py", line 325, in test_create_faster_rcnn_inception_resnet_v2_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 76, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 212, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/image_resizer_builder.py", line 43, in build
    raise ValueError('image_resizer_config not of type '
ValueError: image_resizer_config not of type image_resizer_pb2.ImageResizer.

======================================================================
ERROR: test_create_faster_rcnn_model_from_config_with_example_miner (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "model_builder_test.py", line 382, in test_create_faster_rcnn_model_from_config_with_example_miner
    model = model_builder.build(model_proto, is_training=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 76, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 212, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/image_resizer_builder.py", line 43, in build
    raise ValueError('image_resizer_config not of type '
ValueError: image_resizer_config not of type image_resizer_pb2.ImageResizer.

======================================================================
ERROR: test_create_faster_rcnn_resnet_v1_models_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "model_builder_test.py", line 260, in test_create_faster_rcnn_resnet_v1_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 76, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 212, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/image_resizer_builder.py", line 43, in build
    raise ValueError('image_resizer_config not of type '
ValueError: image_resizer_config not of type image_resizer_pb2.ImageResizer.

======================================================================
ERROR: test_create_rfcn_resnet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "model_builder_test.py", line 448, in test_create_rfcn_resnet_v1_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 76, in build
    return _build_faster_rcnn_model(model_config.faster_rcnn, is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 212, in _build_faster_rcnn_model
    image_resizer_fn = image_resizer_builder.build(frcnn_config.image_resizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/image_resizer_builder.py", line 43, in build
    raise ValueError('image_resizer_config not of type '
ValueError: image_resizer_config not of type image_resizer_pb2.ImageResizer.

======================================================================
ERROR: test_create_ssd_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "model_builder_test.py", line 121, in test_create_ssd_inception_v2_model_from_config
    model = self.create_model(model_proto)
  File "model_builder_test.py", line 53, in create_model
    return model_builder.build(model_config, is_training=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 74, in build
    return _build_ssd_model(model_config.ssd, is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 129, in _build_ssd_model
    box_coder = box_coder_builder.build(ssd_config.box_coder)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/box_coder_builder.py", line 37, in build
    raise ValueError('box_coder_config not of type box_coder_pb2.BoxCoder.')
ValueError: box_coder_config not of type box_coder_pb2.BoxCoder.

======================================================================
ERROR: test_create_ssd_mobilenet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "model_builder_test.py", line 192, in test_create_ssd_mobilenet_v1_model_from_config
    model = self.create_model(model_proto)
  File "model_builder_test.py", line 53, in create_model
    return model_builder.build(model_config, is_training=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 74, in build
    return _build_ssd_model(model_config.ssd, is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/model_builder.py", line 129, in _build_ssd_model
    box_coder = box_coder_builder.build(ssd_config.box_coder)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/object_detection/builders/box_coder_builder.py", line 37, in build
    raise ValueError('box_coder_config not of type box_coder_pb2.BoxCoder.')
ValueError: box_coder_config not of type box_coder_pb2.BoxCoder.

----------------------------------------------------------------------
Ran 7 tests in 0.011s

FAILED (errors=6)
</pre></code>

**Comment by tatatodd** [comment] 2017-06-20 20:48
I believe this is a duplicate of https://github.com/tensorflow/models/issues/1597

It looks like python3 support for object_detection is being added here: https://github.com/tensorflow/models/pull/1614

**Closed by tatatodd** 2017-06-20 20:48 UTC

**Comment by siddhartha-iitd** [comment] 2017-06-20 21:09
I did a fresh installation of Tensorflow and the Protobuf compiler. That solved the issue.

**Comment by Jatik** [comment] 2017-11-17 01:25
I have all fresh libraries but I have these errors (11 errors). OS - Win 7

**Comment by LyonOconner** [comment] 2018-11-01 15:29
> I did a fresh installation of Tensorflow and the Protobuf compiler. That solved the issue.

hi, how did you do it ???

**Comment by MA000LLAIN** [comment] 2020-10-08 08:46
hi,do you solve that problem?
