### ISSUE TITLE
1080ti 4way GPU Parallel Setup Issue

### ISSUE THREAD

**Issue by ghost** [tensorflow/models#3714] opened 2018-03-23 09:00 UTC

**Comment by tensorflowbutler** [comment] 2018-04-25 06:53
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
TensorFlow installed from
Bazel version
Exact command to reproduce

**Comment by donghun9808** [comment] 2018-04-26 05:05
I am curious about Bazel.
Does Bazel influence learning speed or the allocation of multiple GPU usage?

When I wrote this text, I ran it on Windows, but now I am testing it on Ubuntu.

==
TensorFlow version (use command below): tensorflow-gpu 1.6.0
CUDA/cuDNN version: cuda_9.0.176_win10 // cudnn-9.0-windows10-x64-v7
Bazel version : 0.9.0
==

1 gpu batch_size: 1 num_clones: 1 = 0.2~0.3s/step 
2 gpu batch_size: 2 num_clones: 2 = 0.4~0.6s/step   
3 gpu batch_size: 3 num_clones: 3  = 0.6~0.8s/step   
4 gpu batch_size: 4 num_clones: 4  = 0.8~1.2s/step

It is true that as batch_size increases, the learning speed slows down. But is there any other reason to use multiple gpu ???

Is it true that learning becomes faster as more gpu is added?
Does batch_size increase the learning result more accurately?

**Comment by a819721810** [comment] 2018-05-17 09:26
i have some problem, but i also don't how to judge Multi-GPU accelerated multiplier effect

**Comment by liangxiao05** [comment] 2018-06-08 01:36
same problem.
use 2 gpus to train by setting "--num_clones=2 --ps_tasks=1" or "--num_clones=2"  and then changing batch_size twice , I thought that each gpu use one batch to train parallel so that the training time per step will remain the same ,however the time is dobuled .......seems multiple gpu training slows the training speed...

**Comment by jidebingfeng** [comment] 2018-06-21 08:20
#### Multi-GPU accelerated multiplier effect! 
 I test on 2 GTX1080 GPUs. Time spend per step increase, but total time spend decrease.
I guess, some step on GPU0, and some other step on GPU1. Some operations must on CPU, so time per step increase.

**Comment by ravikyram** [comment] 2020-07-10 10:26
Is this still an issue?
Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-08-12 07:33
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-08-12 07:33 UTC
Labels: stat:awaiting response, type:support
