### ISSUE TITLE
Mismatch between code and docs

### ISSUE THREAD

**Issue by harahu** [tensorflow/models#3433] opened 2018-02-22 22:15 UTC
[train_input_fn()](https://github.com/tensorflow/models/blob/d903d5edbc0dc540ebf7971a7fec8b5d0dc903cb/samples/core/get_started/iris_data.py#L30-L39) in iris_data.py is used as the basis for the [Datasets quickstart tutorial](https://www.tensorflow.org/get_started/datasets_quickstart). At the moment there is a mismatch between the code in the tutorial and the actual code in the models repo. The tutorial is based around returning an Iterator, while the function now directly returns a Dataset. The tutorial could probably do with an update, but I am not sure how to report this properly.

**Comment by bignamehyp** [comment] 2018-02-22 22:47
Thanks for finding this bug! @nealwu can you please take a look?

**Comment by nealwu** [comment] 2018-02-28 00:40
The samples/ folder is owned by @MarkDaoust. Re-assigning to him.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:29
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by MarkDaoust** [comment] 2020-01-30 04:51
Thanks for the report @harahu.

Sorry I never got around to this. This directory is no longer used for tensorflow.org tutorials and is on our list for deletion.

**Closed by MarkDaoust** 2020-01-30 04:51 UTC
