### ISSUE TITLE
FAIL: //syntaxnet:parser_trainer_test

### ISSUE THREAD

**Issue by Iris6713** [tensorflow/models#922] opened 2017-01-19 06:40 UTC
bazel version ： 0.4.3

FAIL: //syntaxnet:parser_trainer_test (see /root/.cache/bazel/_bazel_root/d8b12bd611747a25dc33091f1d462c31/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_
trainer_test/test.log).FAIL: //syntaxnet:beam_reader_ops_test (see /root/.cache/bazel/_bazel_root/d8b12bd611747a25dc33091f1d462c31/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_r
eader_ops_test/test.log).FAIL: //syntaxnet:reader_ops_test (see /root/.cache/bazel/_bazel_root/d8b12bd611747a25dc33091f1d462c31/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_
test/test.log).FAIL: //syntaxnet:graph_builder_test (see /root/.cache/bazel/_bazel_root/d8b12bd611747a25dc33091f1d462c31/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_bu
ilder_test/test.log).

**Comment by asimshankar** [comment] 2017-01-20 18:15
Marking as a duplicate of #902 and #930

**Closed by asimshankar** 2017-01-20 18:15 UTC
