### ISSUE TITLE
{1, 0} Found Inf or NaN global norm

### ISSUE THREAD

**Issue by Isabellahu** [tensorflow/models#7801] opened 2019-11-13 12:15 UTC
learning_rate = 0.0001
init_scale = 0.04
hidden_size = 600  

error is : 
tensorflow/core/kernels/check_numerics_op.cc:185] abnormal_detected_host @0x7f4b65200900 = {1, 0} Found Inf or NaN global norm.

**Comment by tensorflowbutler** [comment] 2019-11-14 12:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zhaojun060708** [comment] 2020-01-01 00:42
May be you can read this #6178

**Comment by ravikyram** [comment] 2020-06-19 09:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-19 09:52 UTC
Labels: stat:awaiting response, type:support
