### ISSUE TITLE
import matplotlib; matplotlib.use('Agg') 

### ISSUE THREAD

**Issue by gjcasoy** [tensorflow/models#5101] opened 2018-08-15 23:16 UTC
Hi! I'm trying to follow the training of object detection by Edje Electronics. But when I run the object_detection_tutorial.ipynb i got this error.

C:\tensorflow1\models\research\object_detection\utils\visualization_utils.py:25: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "d:\users\admin\anaconda\envs\lprs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\admin\anaconda\envs\lprs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "d:\users\admin\anaconda\envs\lprs\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "d:\users\admin\anaconda\envs\lprs\lib\asyncio\base_events.py", line 1434, in _run_once
    handle._run()
  File "d:\users\admin\anaconda\envs\lprs\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\zmq\eventloop\zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\interactiveshell.py", line 2907, in run_ast_nodes
    if self.run_code(code, result):
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-0f0a85121700>", line 2, in <module>
    get_ipython().run_line_magic('matplotlib', 'inline')
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\interactiveshell.py", line 2131, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-108>", line 2, in matplotlib
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\magics\pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\IPython\core\pylabtools.py", line 311, in activate_matplotlib
    matplotlib.pyplot.switch_backend(backend)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\matplotlib\pyplot.py", line 231, in switch_backend
    matplotlib.use(newbackend, warn=False, force=True)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\matplotlib\__init__.py", line 1410, in use
    reload(sys.modules['matplotlib.backends'])
  File "d:\users\admin\anaconda\envs\lprs\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "d:\users\admin\anaconda\envs\lprs\lib\site-packages\matplotlib\backends\__init__.py", line 16, in <module>
    line for line in traceback.format_stack()

  import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements

**Comment by tensorflowbutler** [comment] 2018-08-16 07:02
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zhyj3038** [comment] 2018-08-16 07:50
I face the same problem with you,It is not a bug. just comment it and add some code . U will usr opencv to show result .

#   plt.figure(figsize=IMAGE_SIZE)
#   plt.imshow(image_np)
   cv2.imshow( "rst", image_np )
  cv2.waitKey(2000)

**Comment by ymodak** [comment] 2018-12-05 22:03
Closing this issue since it has been resolved. Feel free to reopen if the problem still persists. Thanks!

**Closed by ymodak** 2018-12-05 22:03 UTC
Labels: stat:awaiting response
