### ISSUE TITLE
can you mark the correct tensorflow version for the provided pre-trained models?

### ISSUE THREAD

**Issue by IvyGongoogle** [tensorflow/models#6040] opened 2019-01-14 04:18 UTC
hello, when I use 
`tf.train.import_meta_graph("/xxx.meta")` to 
load the pre-trained models in [here](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models), I always get the error:

`  File "/yyy/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 259, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named IteratorV2 in defined operations.`

similar problem mentioned in [here](https://github.com/tensorflow/models/issues/1564), but not get solved. So can you mark the correct tf version for the provided pre-trained models to not waster our time.

**Comment by tensorflowbutler** [comment] 2020-03-18 21:05
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by IvyGongoogle** [comment] 2020-03-19 05:02
@tensorflowbutler  So long time to look back. the problem seems to be caused by inconsistent tensorflow version.

**Comment by ravikyram** [comment] 2020-07-01 10:34
@IvyGongoogle 

Is this still an issue?.Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-08-08 02:20
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-08-08 02:20 UTC
Labels: stat:awaiting response, type:support
