### ISSUE TITLE
error in load_model function

### ISSUE THREAD

**Issue by matancarmeli7** [tensorflow/models#7932] opened 2019-12-09 14:43 UTC
when i run the Jupiter notebook i get a forbidden error i get Exception: URL fetch failure on http://download.tensorflow.org/models/object_detection/model_name.tar.gz: 403 -- Forbidden and when i try to access to http://download.tensorflow.org also threw the browser and i got a forbidden error.

**Comment by tensorflowbutler** [comment] 2019-12-10 12:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bjente** [comment] 2019-12-20 14:00
Any updates?

**Comment by ravikyram** [comment] 2020-06-17 10:15
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-17 10:15 UTC
Labels: models:research, stat:awaiting response, type:support
