### ISSUE TITLE
can't run a3c_blogpost research model

### ISSUE THREAD

**Issue by imcarsonliao** [tensorflow/models#5607] opened 2018-10-25 06:08 UTC
as title, looks like some file mssing? 
OSError: Unable to open file (unable to open file: name = './model_CartPole-v0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by tensorflowbutler** [comment] 2018-10-26 00:19
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by 1054518207** [comment] 2019-04-16 11:39
I also met the same problem, my reason is I didn't use 'train = True' arg to run the program, so program occurred  mistake.

**Comment by tensorflowbutler** [comment] 2020-01-29 22:59
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:33
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:33 UTC
Labels: stat:awaiting response
