### ISSUE TITLE
Mobilenet v3

### ISSUE THREAD

**Issue by bhack** [tensorflow/models#6815] opened 2019-05-18 12:14 UTC
Do you will release Mobilenet v3?

https://arxiv.org/abs/1905.02244

**Comment by tensorflowbutler** [comment] 2019-05-19 12:15
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bhack** [comment] 2019-05-19 20:03
System information
What is the top-level directory of the model you are using:

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
n/a
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
n/a
TensorFlow installed from (source or binary):
n/a
TensorFlow version (use command below):
n/a
Bazel version (if compiling from source):
n/a
CUDA/cuDNN version:
n/a
GPU model and memory:
n/a
Exact command to reproduce:

**Comment by bhack** [comment] 2019-05-20 00:22
### System information
- **What is the top-level directory of the model you are using**:
N/A
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
N/A
- **TensorFlow installed from (source or binary)**:
N/A
- **TensorFlow version (use command below)**:
N/A
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

**Comment by haikuoyao** [comment] 2019-05-21 02:10
Have the same question.
Seems there's Pytorch implementation

**Comment by longxianlei** [comment] 2019-05-23 02:04
> Have the same question.
> Seems there's Pytorch implementation

Yes, I have found this is applicable.[https://github.com/kuan-wang/pytorch-mobilenet-v3](url)

**Comment by startupgurukul** [comment] 2019-06-01 01:02
Adding on to the request, improved segmentation, object detection models with Mobilenet V3 backbone as explained in the paper

**Comment by joker2017** [comment] 2019-06-03 09:14
Please give a link to the official repository Mobilenet v3. I can not find

**Comment by filipvg68** [comment] 2019-10-19 14:22
Given that the MobileNet V3 SSDLite models have been published recently, it would be great to have an example how to run a prediction using this model. The model seems to produce different results compared to the v1 and v2 models. Do you plan to make a tutorial available that shows what preprocessing is needed on the inputs and how to process the outputs?

**Comment by filipvg68** [comment] 2019-10-25 14:13
Is there any update on the above question? The "ssd_mobilenet_v3_large_coco" model that was posted on Oct. 15 on de model zoo (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) has an output structure that is different from other object detection models. For example if you import the model.tflite from the tar file into https://lutzroeder.github.io/netron/, you get following output:
![ssdmobilenetv3output](https://user-images.githubusercontent.com/25705683/67578078-04168e00-f742-11e9-9de0-98c3276ee236.JPG)
Can you please provide an end-to-end tutorial how to pre-process the data before feeding it into the model in TFlite and how to extract the data?

**Comment by bhack** [comment] 2019-11-13 21:43
https://ai.googleblog.com/2019/11/introducing-next-generation-on-device.html

**Comment by skulhare** [comment] 2020-02-11 00:26
It looks like folks are interested in MobileNet V3 architecture TF code. TF Object detection model repo has the definitions of mobilenet architectures. https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet

hope this helps.

**Comment by ravikyram** [comment] 2020-06-25 07:16
@bhack 

Is this still an issue?.Please, close this thread if your issue was resolved.Thanks!

**Closed** 2020-06-25 07:23 UTC
Labels: models:research, stat:awaiting response, type:support

**Comment by as24-asingla** [comment] 2022-04-19 12:38
Do we have plans for including it in TF Hub Model repository?
