### ISSUE TITLE
I am facing the same error while doing transfer learning on retinenet

### ISSUE THREAD

**Issue by bundelesneha05** [tensorflow/models#8491] opened 2020-05-11 22:00 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Please provide the entire URL of the model you are using?**

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**

**Other info / logs**

**Comment by ravikyram** [comment] 2020-05-12 07:12
@bundelesneha05 

Request you to fill issue template and share the code snippet to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ravikyram** [comment] 2020-06-05 07:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-05 07:21 UTC
Labels: models:research, type:bug
