### ISSUE TITLE
NotFoundError after train and evaluation

### ISSUE THREAD

**Issue by tinothy22** [tensorflow/models#7868] opened 2019-11-27 11:19 UTC
The error occurred when Performing the final export in the end of training:

tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: zqt_cardboard_train/train_result\export\Servo\temp-b'1574846539'; No such file or directory

**Comment by tensorflowbutler** [comment] 2019-11-28 00:06
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Aurevious** [comment] 2019-12-04 13:21
> The error occurred when Performing the final export in the end of training:
> tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: zqt_cardboard_train/train_result\export\Servo\temp-b'1574846539'; No such file or directory

Hello, have you solved this problem?I have the same problem.Thank you very much!

**Comment by tinothy22** [comment] 2019-12-05 01:07
My solution is to change / in model_dir to \, hope it can help you

**Comment by tinothy22** [comment] 2019-12-05 01:08
My solution is to change ‘/ ’in model_dir to ‘\’, hope it can help you

**Comment by ravikyram** [comment] 2020-06-19 07:34
@tinothy22 

Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-07-14 09:34
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-14 09:34 UTC
Labels: stat:awaiting response, type:support
