### ISSUE TITLE
model from train.py is not the same as model_main train

### ISSUE THREAD

**Issue by wuchichung** [tensorflow/models#5075] opened 2018-08-13 02:46 UTC
I am using train.py to train my own dataset. The model make sense. However, when use model_main.py train. The model is totally off. I want to know what is the possible error ? I think one of the problem may be from the tf record file. Is there any additional information added into the tf record required ?

**Comment by dscha09** [comment] 2019-01-08 01:42
@wuchichung Have you solved this?

**Comment by Bahramudin** [comment] 2019-01-27 13:58
@tensorflowbutler Please do not ask this question again and again. Some questions do not require to provide information about the platform or something else. 

He is asking about .py files, which what is the difference between them, which is better to use and how to use?
He is not asking that build failed and train failed or something related to the platforms question.
Thanks!

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by Bahramudin** [comment] 2020-01-30 11:56
@tensorflowbutler But you still did not give him an answer, you should first please give an answer to the question. To me, it is still a question, that what difference between these to file which do the same job. Which one is preferred to use and why??

**Comment by sglvladi** [comment] 2020-05-18 03:08
> @tensorflowbutler But you still did not give him an answer, you should first please give an answer to the question. To me, it is still a question, that what difference between these to file which do the same job. Which one is preferred to use and why??

@Bahramudin, @tensorflowbutler is a bot.

**Comment by ravikyram** [comment] 2020-07-10 09:08
@wuchichung 

Is this still an issue?
Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-08-12 07:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-08-12 07:24 UTC
Labels: stat:awaiting response
