### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'data'

### ISSUE THREAD

**Issue by baimin1** [tensorflow/models#2879] opened 2017-11-23 02:59 UTC
Why runing mnist.py has:
dataset = tf.data.TFRecordDataset([filename])
AttributeError: module 'tensorflow' has no attribute 'data'

My env is ubuntu and a conda installed tensrflow

**Comment by baimin1** [comment] 2017-11-23 03:05
another:
dataset = dataset.map(example_parser).prefetch(batch_size)
AttributeError: 'MapDataset' object has no attribute 'prefetch'

**Comment by blairjordan** [comment] 2017-11-23 04:47
Try tf.contrib.data

See release https://github.com/tensorflow/tensorflow/releases

**Comment by blairjordan** [comment] 2017-11-23 05:00
The arguments accepted by the Dataset.map() transformation have also changed:

dataset.map(..., output_buffer_size=B) is now dataset.map(...).prefetch(B).

I'd check that you have the latest version.  In my case, I still need to use the old tf.contrib.data.

**Comment by tatatodd** [comment] 2017-11-29 01:26
Yes, as @blairjordan mentions, `tf.contrib.data` has been upgraded to just `tf.data` in TensorFlow v1.4.  So you need to make sure you're using v1.4.

Also check out the differences between the old and new API:
https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/data/README.md

@baimin1 does that resolve your issue?

**Comment by sweapon** [comment] 2018-06-01 07:03
Does this mean that the config-file named cloud.yml in object_detection/samples/cloud/ should have runtime-version 1.4? I suppose the command to start the job would be something like this?

# From tensorflow/models/research/
`gcloud ml-engine jobs submit training `whoami`_object_detection_`date +%s` \`
`    --runtime-version 1.4 \`
`    --job-dir=gs://${YOUR_GCS_BUCKET}/train \`
`    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \`
`    --module-name object_detection.train \`
`    --region us-central1 \`
`    --config object_detection/samples/cloud/cloud.yml \`
`    -- \`
`    --train_dir=gs://${YOUR_GCS_BUCKET}/train \`
`    --pipeline_config_path=gs://${YOUR_GCS_BUCKET}/data/faster_rcnn_resnet101_pets.config`

**Comment by wt-huang** [comment] 2018-10-20 01:58
Closing as the issue is resolved

**Closed by wt-huang** 2018-10-20 01:58 UTC
Labels: stat:awaiting response

**Comment by yu7856288** [comment] 2018-12-21 02:35
under tf 1.4 use tf.contrib.data instead of tf.data

**Comment by JanaranjaniPalaniswamy** [comment] 2020-12-31 11:26
I am using tensorflow version 2.3.0 and facing the same issue. Can anyone tell me what exactly is the fix?

**Comment by bayma-1** [comment] 2022-09-20 12:47
I faced the same issue and fixed it by: pip install tensorflow-io

**Comment by Yongbobloomington** [comment] 2023-02-05 23:38
> I faced the same issue and fixed it by: pip install tensorflow-io

doesn't work for me, unfortunately
