### ISSUE TITLE
SSD Large Image Support/Training

### ISSUE THREAD

**Issue by asagot** [tensorflow/models#5621] opened 2018-10-26 18:37 UTC
Am getting no luck on StackOverflow so I am hoping you will be kind enough to answer a few questions for a noob.

Are there detailed instruction on how to train SSD with a larger image size? Specifically, I do not want to scale the input image down to 300x300 or 512x512 - I want to feed the network the larger image directly (~1024x1024)

Accuracy is not that big a deal at the moment as I am just trying to gauge performance.

So I am looking for:
* Changes need to be made and to what
* Anything else to look out for

Once again, am sorry to bring this up here but I am not getting much help from other resources.

**Comment by sjaiswal25** [comment] 2018-10-27 08:38
Hi, 
If you read the original SSD paper, the architecture is designed to handle only low resolution images and hence, the reason for down scaling in the SSD model. But, if you still want to proceed, make changes to your pipeline.config file for your architecture.

**Comment by 1453042287** [comment] 2018-11-01 08:49
i believe you can get enough details in the structure changed from 300 to 512，so you can change the model from 512 to 1024 similarly

**Comment by tensorflowbutler** [comment] 2020-01-29 22:59
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:32 UTC
