### ISSUE TITLE
Create Dockerfile for object_detection

### ISSUE THREAD

**Issue by cmendesce** [tensorflow/models#7656] opened 2019-10-12 22:54 UTC
Create a Dockerfile to make easer the setup configuration. A Dockerfile with jupyter and cuda installed can increase the usage of the object_detection api.

What is the top-level directory of the model you are using: N/A
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment] 2019-10-13 12:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-21 15:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-21 15:18 UTC
Labels: stat:awaiting response, type:performance
