### ISSUE TITLE
NameError: name 'model_deploy'

### ISSUE THREAD

**Issue by vanstux** [tensorflow/models#4258] opened 2018-05-14 22:59 UTC
Hello,

I am working on a Facial Expression Recognition project. setup everything according to the information from https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10.

Now at the final step starting the training session I get the following error;

Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "/anaconda3/envs/objectdetector/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/anaconda3/envs/objectdetector/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/trainer.py", line 246, in train
    deploy_config = model_deploy.DeploymentConfig(
NameError: name 'model_deploy' is not defined

Please help.

**Comment by tensorflowbutler** [comment] 2018-05-15 06:45
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment] 2018-06-03 19:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by robieta** 2018-06-03 19:02 UTC
Labels: stat:awaiting response
