### ISSUE TITLE
Cant convert from .pb to .tflite 

### ISSUE THREAD

**Issue by prbsh9** [tensorflow/models#7023] opened 2019-06-15 12:56 UTC
I am running this on COLAB with 
tensorflow = '1.14.0-rc1'
I first converted from `.pth` to `.onnx` to `.pb` and now I am trying to convert to `.tflite`

```
import tensorflow as tf 
saved_model_dir = 'Places'
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
````
.
but got an error 

> RuntimeError: MetaGraphDef associated with tags {'serve'} could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: []

**Comment by tensorflowbutler** [comment] 2019-06-16 12:14
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by prbsh9** [comment] 2019-06-16 15:21
@tensorflowbutler 
I am using in `google colaboratory`... 
so still needed to know cuda and all ?

What is the top-level directory of the model you are using ?
Have I written custom code = **UP**
OS Platform and Distribution = **Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic** 
TensorFlow installed from = **existed in colab, no need to install**
TensorFlow version = **'1.14.0-rc1'**
Bazel version  N/A
CUDA/cuDNN version = **V10.0.130**
GPU model and memory = **11441MB | Tesla K80**

Also because of the above problem again I did everything from keras but size did not decrease! I also did that in **COLAB** and used

```
from tensorflow import lite
converter = lite.TFLiteConverter.from_keras_model_file( '/gdrive/My Drive/Places/model.h5')
tfmodel = converter.convert()
open ("model.tflite" , "wb") .write(tfmodel)

```  Size is `89.9 MB` from `90.4 MB`
Size is supposed to decrease right ? PLEASE HELP

**Comment by suharshs** [comment] 2019-06-17 06:04
Size may not always decrease depending on model, if you want further size reductions you can consider using 
`converter.optimizations = [tf.lite.Optimizations.DEFAULT]` for the converter.

Will close this particular issue since you are able to convert the model to tflite format now.

**Closed by suharshs** 2019-06-17 06:04 UTC
Labels: stat:awaiting response
