### ISSUE TITLE
Not find script for HNASNet network architecture searching from auto-deeplab release

### ISSUE THREAD

**Issue by LingyuZhuFin** [tensorflow/models#6888] opened 2019-05-27 11:35 UTC
From the released script of Auto-deeplab, seems just the training script of "already searched optimal model" is available, the procedure of network architecture searching is missing. 

Will this part be released at some point or it is somewhere there already but i didn't find it yet? Thanks!

**Comment by tensorflowbutler** [comment] 2019-05-28 00:16
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by GlennZhang** [comment] 2019-05-29 07:03
It seems that the backbone and cell architectures are just defined in hasnet:

    operations = [
      'atrous_5x5', 'separable_3x3_2', 'separable_3x3_2', 'atrous_3x3',
      'separable_3x3_2', 'separable_3x3_2', 'separable_5x5_2',
      'separable_5x5_2', 'separable_5x5_2', 'atrous_5x5'
    ]

    used_hiddenstates = [1, 1, 0, 0, 0, 0, 0]
    hiddenstate_indices = [1, 0, 1, 0, 3, 1, 4, 2, 3, 5]
    backbone = [0, 0, 0, 1, 2, 1, 2, 2, 3, 3, 2, 1]

The implement of DARTS can be found here [https://github.com/quark0/darts](https://github.com/quark0/darts "DARTS") .

**Comment by LingyuZhuFin** [comment] 2019-05-29 08:18
Yes, they are kinda fixed, the "auto" searching part is actually more valuable.
and thanks.

**Comment by ymodak** [comment] 2019-05-30 18:59
Closing this since its resolved. Thanks!

**Closed by ymodak** 2019-05-30 18:59 UTC
Labels: models: research

**Comment by Randylcy** [comment] 2019-07-10 01:57
> Yes, they are kinda fixed, the "auto" searching part is actually more valuable.
> and thanks.

have U find the code of search model? thx

**Comment by Randylcy** [comment] 2019-07-10 01:58
> Closing this since its resolved. Thanks!

Why I still cannot find the search code?

**Comment by AmeetR** [comment] 2019-07-17 09:40
Wait what... kinda fixed means what? I know that the types of operations are hard coded, but I thought that the search was still happening over these operations @Lingyu

**Comment by Hrayo712** [comment] 2020-11-22 14:41
Has the search code been uploaded ? I'm also wondering the same thing. If so, where is it exactly ?
