### ISSUE TITLE
when exporting model, cannot import name inception_resnet_v2

### ISSUE THREAD

**Issue by xusongpei** [tensorflow/models#7765] opened 2019-11-06 10:17 UTC
when I exporting the model, I had added the PYTHONPATH, but there is a new error:

from nets import inception_resnet_v2
ImportError: cannot import name inception_resnet_v2

is there any body know why ?

**Comment by tensorflowbutler** [comment] 2019-11-07 00:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xusongpei** [comment] 2019-11-07 01:43
Top level model : ssd lite
No custom code
OS : Ubuntu N/A
Tensorflow version : 14.1
Build : tensorflow build from source
Cuda : 8.0
GPU model and Tesla Nvidia
Extract command:
python /object_detection/export_inference_graph.py --input_type=image_tensor --pipeline_config_path=./0918/ssd_lite_v2.config --trained_checkpoint_prefix=./0918/train/model.ckpt-156289 --output_directory=./card_0918

**Comment by bamwani** [comment] 2019-11-11 09:57
any update?

**Comment by xusongpei** [comment] 2019-11-12 06:13
@bamwani  i have solved the issue, some one help me to change a different PYTHONPATH, then i solved the problem. Thank you.

**Comment by Zachary4biz** [comment] 2019-11-14 09:37
@xusongpei  I'm using tensorflow 1.15.0, seems there is no implement of inception_resnet_v2 in `tensorflow.contrib.slim.python.slim.nets`.

could you show me what's your full import path?

**Comment by xusongpei** [comment] 2019-11-15 01:50
@Zachary4biz i think it is because the path of slim.nets, you can see if [this one](https://github.com/tensorflow/models/issues/1842) is useful.

**Comment by Zachary4biz** [comment] 2019-11-15 02:18
I have tried 1.15.0 and 1.14.0 ,  there is no folder named `model` in `anaconda3/envs/cv3.6/lib/python3.6/site-packages/tensorflow/`.

Maybe it is because version of that issue is too old (in 2017), what I'm facing is different

**Comment by xusongpei** [comment] 2019-11-15 02:37
@Zachary4biz but i use that way solve my issue, maybe you can try it again and change the path to your own path, do not use 'pwd'

**Comment by xusongpei** [comment] 2019-11-15 02:40
@Zachary4biz if you need, i can reopen this issue

**Comment by Zachary4biz** [comment] 2019-11-15 03:03
**would you show me the exact version by `pip show tensorflow` OR `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`**  

I see you are using version "14.1",  is it the same version as `1.14.0` ? 
I'm really confused where is the resnet version of inception in slim. btw my purpose is to change some part of the nn structure, like using my custom input-layer, and fetching the last-layer as feature vector.

In my case (1.14.0), part of the dir goes like this:
```python
site-packages
    |...
    |_tensorflow
            |...
            |_contrib/
                    |...
                    |_slim/
                          |...
                          |_nets.py
                          |_python/
                                 |...
                                 |_slim/
                                       |...
                                       |_evalution.py
                                       |_learning.py
                                       |_model_analyzer.py
                                       |_queues.py
                                       |_summaries.py
                                       |_nets/
                                            |_alexnet.py
                                            |_inception.py
                                            |_inception_v1.py
                                            |_inception_v2.py
                                            |_inception_v3.py
                                            |_overfeat.py
                                            |_resnet_utils.py
                                            |_resnet_v1.py
                                            |_resnet_v2.py
                                            |_vgg.py
                                       |_data/
                                            |...

```

**Comment by xusongpei** [comment] 2019-11-15 03:29
Name: tensorflow
Version: 1.14.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib64/python3.6/site-packages
Requires: wheel, numpy, termcolor, grpcio, keras-applications, absl-py, astor, google-pasta, keras-preprocessing, tensorboard, six, protobuf, gast, wrapt, tensorflow-estimator


@Zachary4biz well..... i don't think it is because the slim or net under the tensorflow/

**Comment by Zachary4biz** [comment] 2019-11-15 04:00
@xusongpei  that's the most bizarre thing this week..
two more things:
- **different way to import**
I see that you successfully execute the command `from nets import inception_resnet_v2` may you try this one as below?
`from tensorflow.contrib.slim.python.slim.nets.inception import inception_resnet_v2`

- **may you show me the source link of the file `/object_detection/export_inference_graph.py`** 

thanks for your attention and reply

**Comment by xusongpei** [comment] 2019-11-15 05:43
@Zachary4biz https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py

**Comment by ravikyram** [comment] 2020-06-19 11:53
@xusongpei 

Is this still an issue.Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-07-14 09:44
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-14 09:44 UTC
Labels: models:research, type:support

**Comment by affaanahmed** [comment] 2023-09-12 04:57
from nets import inception_reset_v2
ImportError: cannot import name 'inception_reset_v2' from 'nets' 
help me
