### ISSUE TITLE
object_detection:  google.protobuf.text_format.ParseError: 143:1 : Message type "object_detection.protos.EvalConfig" has no field named "eval_input_reader"  when I run faster-rcnn-nas.

### ISSUE THREAD

**Issue by jixiaonanzhuaizhuai** [tensorflow/models#5007] opened 2018-08-06 08:35 UTC
When I use model faster-rcnn_nas with my own data for training, I get a error message (CUDA_VISIBLE_DEVICES=1 python3 model_main.py --logtostderr --pipeline_config_path=modelH/faster_rcnn_nas_coco.config --model_dir=modelH/train
):

Use object_detection/model_main.py.
Traceback (most recent call last):
  File "legacy/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "legacy/train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/models-master/research/object_detection/utils/config_util.py", line 94, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/protobuf/text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 143:1 : Message type "object_detection.protos.EvalConfig" has no field named "eval_input_reader".

my protoc --version :  3.5.1

my tensorflow : 1.6.0

my GUP :
-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0  On |                  N/A |
| 51%   84C    P2   156W / 250W |  10539MiB / 11170MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
| 46%   68C    P8    22W / 250W |  10786MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:82:00.0 Off |                  N/A |
| 62%   85C    P2   102W / 250W |  10788MiB / 11172MiB |     91%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:83:00.0 Off |                  N/A |
| 30%   49C    P8    18W / 250W |  10592MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1574      G   /usr/lib/xorg/Xorg                            84MiB |
|    0     28929      C   python                                     10343MiB |
|    0     37191      G   compiz                                        95MiB |
|    0     46611      G   /opt/teamviewer/tv_bin/TeamViewer             11MiB |
|    1     18207      C   python3                                    10775MiB |
|    2     20236      C   python3                                    10775MiB |
|    3     16837      C   python                                     10579MiB |
+----------------------------------------------------------------------------

Can you give me some solutions?

**Comment by tensorflowbutler** [comment] 2018-08-06 19:04
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jixiaonanzhuaizhuai** [comment] 2018-08-07 01:30
@tensorflowbutler  The top-level directory of the model I am using  is "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/models-master/research/object_detection/"

I have not written custom code!
OS platform: ubuntu 16.04

**Comment by MaggieLieu** [comment] 2018-09-08 16:06
I had the same problem, I realised it was because I commented out the line: 
> max_evals: 10} 
This then means the eval_config: field is unclosed. You should keep the "}" and it should run

**Comment by wt-huang** [comment] 2018-11-18 02:30
Closing as this is resolved

**Closed by wt-huang** 2018-11-18 02:30 UTC
