### ISSUE TITLE
Multiple parts of rfrecord files in the training tensorflow models 

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/models#8546] opened 2020-05-20 16:59 UTC
Hi all,
I want to know, What’s the reason of using multiple parts of tfrecords files in training tensorflow models?

We use rfrecords files to don’t load all data in memory, right? and we grab a batch of images into memory system. So what’s difference between train model with single tfrecord file or multiple tfrecord files?

**Comment by ravikyram** [comment] 2020-05-21 07:59
@PythonImageDeveloper 
Please, let us know which pretrained model you are using and elaborate the context.Will it be possible to share related code to understand root cause of your issue.Thanks!

**Comment by ravikyram** [comment] 2020-07-02 09:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-02 09:42 UTC
Labels: stat:awaiting response, type:support
