### ISSUE TITLE
Message type "object_detection.protos.Ssd" has no field named "k".

### ISSUE THREAD

**Issue by kangjieHong** [tensorflow/models#3086] opened 2018-01-01 10:41 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution **:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:anaconda
- **TensorFlow version (use command below)**: Tensorflow 1.3.0
- **Python version**:  Python3.6.1
- **CUDA/cuDNN version**:
- **GPU model and memory**: 
- **Exact command to reproduce**: python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config

### Describe the problem
while i use the Object Detection API to train myself dataset 

but now i find my config maybe has some wrong maybe , because while i rewrite the config , it works

### Source code / logs
Traceback (most recent call last):
File "train.py", line 163, in 
tf.app.run()
File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "train.py", line 91, in main
FLAGS.pipeline_config_path)
File "/home/stu10/perl5/object-Detection/models-master/research/object_detection/utils/config_util.py", line 43, in get_configs_from_pipeline_file
text_format.Merge(proto_str, pipeline_config)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 525, in Merge
descriptor_pool=descriptor_pool)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 579, in MergeLines
return parser.MergeLines(lines, message)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 612, in MergeLines
self._ParseOrMerge(lines, message)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 627, in _ParseOrMerge
self._MergeField(tokenizer, message)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 727, in _MergeField
merger(tokenizer, message, field)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 727, in _MergeField
merger(tokenizer, message, field)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "/home/amax/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 695, in _MergeField
(message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 17:6 : Message type "object_detection.protos.Ssd" has no field named "k".

**Comment by skye** [comment] 2018-01-03 02:12
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by kangjieHong** [comment] 2018-01-04 04:22
sorry for my careless about the issue template, but today while rewrite the config ,it works. but the new problem has come .the same with issue 2777  **AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'mark_flag_as_required'**   thank you very much

**Comment by skye** [comment] 2018-01-04 18:07
I'm sorry to hear that. I'm gonna close this as a duplicate of #2777, please continue any discussion there.

**Closed by skye** 2018-01-04 18:07 UTC
Labels: stat:awaiting response
