### ISSUE TITLE
The replica master 0 exited with a non-zero status of 1

### ISSUE THREAD

**Issue by ravinderkhatri** [tensorflow/models#7568] opened 2019-09-17 07:33 UTC
I am encountering an error(error log details given below) while running

./mltrain.sh train ${BUCKET} data/ratings.dat --delimiter ::

This is throwing an error saying : 
The replica master 0 exited with a non-zero status of 1
The error log details are attached [here](https://drive.google.com/file/d/1lj1BtaTSe3DwZBrN8WEam8H87psNmpl2/view?usp=sharing)

I am following the below code
sudo apt-get update
sudo apt-get install -y git bzip2 unzip
git clone https://github.com/GoogleCloudPlatform/tensorflow-recommendation-wals
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
bash Miniconda2-latest-Linux-x86_64.sh
cd tensorflow-recommendation-wals
conda create -n tfrec
conda install -n tfrec --file conda.txt
source activate tfrec
pip install -r requirements.txt
pip install tensorflow
curl -O 'http://files.grouplens.org/datasets/movielens/ml-1m.zip'
unzip ml-1m.zip
mkdir -p data
cp ml-1m/ratings.dat data/

my bucket name is re_bucket

BUCKET=gs://re_bucket
gsutil cp -r data/ratings.dat $BUCKET/data/ratings.dat
cd wals_ml_engine
./mltrain.sh train ${BUCKET} data/ratings.dat --delimiter ::

I have tried several solutions posted [here](https://stackoverflow.com/questions/49434874/tensorflow-on-ml-engine-the-replica-master-0-exited-with-a-non-zero-status-of-1) but still getting the same error. I have also created several new instances many times to see whether that can resolve the error or not but there is no success in that. Please let me know what are the possible steps that I can follow to resolve issue.

Note: When I am trying the same thing in my local storage using

./mltrain.sh local ../data re_data.dat --delimiter ::
things are working fine for me. It might be the case that error is related with GCP bucket.

Also attaching the screenshot for stack driver information

![rw07I](https://user-images.githubusercontent.com/9564095/65020759-6c0bd480-d94b-11e9-933a-9102c7259be7.png)

Please let me know your suggestion to resolve the issue.

**Comment by tensorflowbutler** [comment] 2019-09-18 12:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravinderkhatri** [comment] 2019-09-19 11:01
**OS Platform and Distribution** 
debian-9-stretch-v20190905 Debian, Debian GNU/Linux, 9 (stretch), amd64 built on 20190905

**TensorFlow installed from** 
pip install tensorflow
TensorFlow version 1.14.0

**GPU model and memory custom**
(custom 6 vCPUs, 8.25 GB memory on Google Cloud )
 "scaleTier": "CUSTOM",
"masterType": "complex_model_m_gpu"

Exact command to reproduce (shared in above code)

Other packages version that I am using

REQUIRED_PACKAGES = ["sh", "absl-py==0.8.0","astor==0.8.0","backports.weakref==1.0.post1","boto==2.49.0","cachetools==3.1.1","certifi==2019.6.16","chardet==3.0.4","enum34==1.1.6","filelock==3.0.12","funcsigs==1.0.2","futures==3.3.0","gast==0.3.2","gdown==3.8.3","google-api-core==1.14.2","google-api-python-client==1.7.11","google-auth==1.6.3","google-auth-httplib2==0.0.3","google-cloud-core==1.0.3","google-cloud-storage==1.19.0","google-compute-engine==2.8.13","google-pasta==0.1.7","google-resumable-media==0.4.0","googleapis-common-protos==1.6.0","grpcio==1.23.0","h5py==2.10.0","httplib2==0.13.1","idna==2.8","Keras-Applications==1.0.8","Keras-Preprocessing==1.1.0","Markdown==3.1.1","mock==3.0.5","numpy==1.16.5","oauth2client==3.0.0","pandas==0.20.3","pip==19.2.2","protobuf==3.9.1","pyasn1==0.4.7","pyasn1-modules==0.2.6","python-dateutil==2.8.0","pytz==2019.2","PyYAML==5.1.2","requests==2.22.0","retrying==1.3.3","rsa==4","scipy==0.19.1","setuptools==41.0.1","sh==1.12.14","six==1.12.0","tensorboard==1.14.0","tensorflow==1.14.0","tensorflow-estimator==1.14.0","termcolor==1.1.0","tqdm==4.35.0","uritemplate==3.0.0","urllib3==1.25.3","Werkzeug==0.15.6","wheel==0.33.4","wrapt==1.11.2"]

Please let me know in case further info is required.

**Comment by ravikyram** [comment] 2020-06-22 10:33
@ravinderkhatri 

Please, let us know which pretrained model you are using and share the related code .Thanks!

**Comment by ravikyram** [comment] 2020-07-17 10:19
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-17 10:19 UTC
Labels: stat:awaiting response, type:support
