### ISSUE TITLE
How to train for detecting new class without forgetting what the model learned earlier?

### ISSUE THREAD

**Issue by aswinr22** [tensorflow/models#7995] opened 2019-12-30 11:59 UTC
I have already trained a fasterRcnn model on COCO data set with 90 classes .How can i train with one more class (90+1) without forgetting those 90 classes?

**Comment by tensorflowbutler** [comment] 2019-12-31 00:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aswinr22** [comment] 2019-12-31 05:34
OS Platform and Distribution
Windows 10
TensorFlow installed from
Conda
TensorFlow version
1.1.40
Bazel version
N\A
CUDA/cuDNN version
10
GPU model and memory
N\A

**Comment by netanel-s** [comment] 2020-01-01 13:03
This is not an easy thing to do given the current API, assuming you mean that you only wish to train on the new class (rather than existing classes+new class). 
If you change the number of classes, then the classification layer doesn't have the same number of channels any more, and therefore is no longer compatible with previous checkpoint, and will be initialized.
You could theoretically manually load all weights in the classification layer corresponding to the existing classes, freeze them, and only train the additional weights corresponding to the new class.
BUT, it is not possible, best to my knowledge, to freeze some weights of a given layer, but rather either you freeze the layer or not.
Why do you need to freeze these weights? because if you wouldn't, the model will gradually forget to detect the existing classes.
The thing you could do in order to bypass the issue I mentioned above, is to freeze all variables without the classification layer, let the new layer train using the training data of the new class. The "problem" is that the classification layer will no longer detect the existed classes. Then you could simply override the weights of the existed classes with the corresponding weights of the pretrained model, and only using the weights you learnt which correspond to the new class. 
Note that unless the new class is very similar to an already existing classes, this method will be inferior to letting the model train on the existing classes+new class, since you don't fine-tune the variables of the entire model.

**Closed** 2020-01-02 05:42 UTC
