### ISSUE TITLE
The TF function for the TRT segment could not be empty

### ISSUE THREAD

**Issue by doublexxking** [tensorflow/models#7537] opened 2019-09-06 06:10 UTC
------------------------

### System information
- **What is the top-level directory of the model you are using**: Tensorrt plan model (converted from pb)
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: when I convert pb to tensorrt, I use tf-nightly-gpu-1.15 from pip install. When I do infer, I use tf-1.14.0 from source.
- **TensorFlow version (use command below)**: tf-1.14.0
- **Bazel version (if compiling from source)**: 0.24.1
- **CUDA/cuDNN version**: cuda 10 cudnn 7
- **GPU model and memory**: 1060  Ti
- **Exact command to reproduce**: N/A

### Describe the problem
Hi, 
I successfully used trt_convert to my pb model to tensorRT plan
and I want to use c++ to infer my model. 
So I use bazel complie tf **with tensorrt together**.
In my code, pb model can run successfully.
I use the same code, and TensorRT model can load successfully but as session running, tf give me the following error:

2019-09-06 06:56:37.455586: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Invalid argument: The TF function for the TRT segment could not be empty
[[{{node fa_layer4_c0/TRTEngineOp_108}}]]

When I convert pb to tensorrt, it is shown as following:

2019-09-06 06:25:59.150320: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Tensor DataType is determined at build time for tensors not marked as input or output.
2019-09-06 06:25:59.183609: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:831] TensorRT node fa_layer4/TRTEngineOp_107 added for segment 107 consisting of 3 nodes succeeded.
2019-09-06 06:25:59.189007: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:831] TensorRT node fa_layer4_c0/TRTEngineOp_108 added for segment 108 consisting of 2 nodes succeeded.
2019-09-06 06:25:59.189378: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Tensor DataType is determined at build time for tensors not marked as input or output.
2019-09-06 06:25:59.189403: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Network must have at least one output
2019-09-06 06:25:59.189426: W tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:834] TensorRT node fa_layer4_c0/conv0/bn/cond_1/TRTEngineOp_109 added for segment 109 consisting of 4 nodes failed: Internal: Failed to build TensorRT engine. Fallback to TF...

Additionally, I can use the tensorrt model in python code to infer. (python installed from pip)
Anyone could provide some ideas how to solve it?

**Comment by tensorflowbutler** [comment] 2019-09-07 00:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by double344931987** [comment] 2019-09-07 05:41
I  have updated.

**Comment by ravikyram** [comment] 2020-06-22 11:12
@doublexxking 

Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment] 2020-07-22 07:40
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-22 07:40 UTC
Labels: models:research, stat:awaiting response, type:support
