### ISSUE TITLE
References to packages, unknown sources

### ISSUE THREAD

**Issue by legobill** [tensorflow/models#7315] opened 2019-07-28 03:12 UTC
References to packages, in the same file or in separate files

Sometimes with import or from, the introduction of a guide is messy.

References to files, not knowing the source, do not specify which file to refer to, because there are several identical files under the subfile

There are so many small problems like package or file references that they are not listed one by one.

For example, the following files:
models-master\models-master\research\train.py

from absl import flags
import tensorflow as tf

import data_provider
import networks

**Comment by tensorflowbutler** [comment] 2019-07-29 00:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-24 13:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-24 13:43 UTC
Labels: stat:awaiting response, type:support
