### ISSUE TITLE
Is there any resnet model which could be used for FPN?

### ISSUE THREAD

**Issue by YJHMITWEB** [tensorflow/models#4859] opened 2018-07-21 13:11 UTC
I notice that in keras, there are resnet models that could output features and FPN could use, for example, if the input size is 1024x1024, output nodes are [512x512,256x256,128x128,64x64]. But in tensorflow, no matter resnet_v2 or resnet_v1, output_nodes are always [128x128, 64x64, 64x64, 64x64] which could not be used by FPN.
I am wonder is there any available resnet options in pure tensorflow that could be used by FPN(Feature Pyramid Network)?

**Comment by tensorflowbutler** [comment] 2018-07-24 08:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by YJHMITWEB** [comment] 2018-08-07 13:34
@tensorflowbutler I can not see it has anything to do with the version of tensorflow or my OS platform or Bazel version or CUDA version or GPU model.
Users post their issues, and you guys just use this robot to reply.

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by ravikyram** [comment] 2020-07-10 09:50
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-10 09:50 UTC
Labels: type:support
