### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: ./SRGAN_pre-trained : \udca8t\udcb2Χ\u4923\udca8\udcec\udcab\udcfc\udca9w\udcaa\udcba\udcb8\udcf4\udcae|\udca1C ; No such process

### ISSUE THREAD

**Issue by SuPoTing** [tensorflow/models#7396] opened 2019-08-07 02:15 UTC
SuPoTing@MSI /cygdrive/c/Users/SuPoTing/Desktop/SRGAN-tensorflow-master
$ sh test_SRGAN.sh
[Configurations]:
        is_training: <absl.flags._flag.BooleanFlag object at 0x0000023A3718A1D0>
        random_crop: <absl.flags._flag.BooleanFlag object at 0x0000023A3718A550>
        flip: <absl.flags._flag.BooleanFlag object at 0x0000023A3718A4E0>
        vgg_scaling: <absl.flags._flag.Flag object at 0x0000023A3718AB70>
        name_queue_capacity: <absl.flags._flag.Flag object at 0x0000023A3718A6A0>
        mode: <absl.flags._flag.Flag object at 0x0000023A371493C8>
        summary_dir: <absl.flags._flag.Flag object at 0x0000023A37149358>
        beta: <absl.flags._flag.Flag object at 0x0000023A3718ADD8>
        perceptual_mode: <absl.flags._flag.Flag object at 0x0000023A3718A940>
        learning_rate: <absl.flags._flag.Flag object at 0x0000023A3718ABE0>
        input_dir_LR: <absl.flags._flag.Flag object at 0x0000023A3718A438>
        max_epoch: <absl.flags._flag.Flag object at 0x0000023A3718AE80>
        queue_thread: <absl.flags._flag.Flag object at 0x0000023A3718A7F0>
        crop_size: <absl.flags._flag.Flag object at 0x0000023A3718A5F8>
        image_queue_capacity: <absl.flags._flag.Flag object at 0x0000023A3718A748>
        task: <absl.flags._flag.Flag object at 0x0000023A3718A2E8>
        stair: <absl.flags._flag.BooleanFlag object at 0x0000023A3718ACF8>
        decay_rate: <absl.flags._flag.Flag object at 0x0000023A3718ACC0>
        max_iter: <absl.flags._flag.Flag object at 0x0000023A3718AEF0>
        batch_size: <absl.flags._flag.Flag object at 0x0000023A3718A390>
        summary_freq: <absl.flags._flag.Flag object at 0x0000023A3718D048>
        pre_trained_model_type: <absl.flags._flag.Flag object at 0x0000023A3718A198>
        decay_step: <absl.flags._flag.Flag object at 0x0000023A3718AC50>
        save_freq: <absl.flags._flag.Flag object at 0x0000023A3718D0F0>
        EPS: <absl.flags._flag.Flag object at 0x0000023A3718AA20>
        input_dir_HR: <absl.flags._flag.Flag object at 0x0000023A3718A4A8>
        pre_trained_model: <absl.flags._flag.BooleanFlag object at 0x0000023A3715CEF0>
        display_freq: <absl.flags._flag.Flag object at 0x0000023A3718AF60>
        checkpoint: <absl.flags._flag.Flag object at 0x0000023A371497F0>
        vgg_ckpt: <absl.flags._flag.Flag object at 0x0000023A3718A278>
        output_dir: <absl.flags._flag.Flag object at 0x0000023A74633B00>
        num_resblock: <absl.flags._flag.Flag object at 0x0000023A3718A898>
        ratio: <absl.flags._flag.Flag object at 0x0000023A3718AAC8>
End of configuration
WARNING:tensorflow:From C:\Users\SuPoTing\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Finish building the network
2019-08-06 16:02:05.609719: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Loading weights from the pre-trained model
WARNING:tensorflow:From C:\Users\SuPoTing\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "main.py", line 138, in <module>
    weight_initiallizer.restore(sess, FLAGS.checkpoint)
  File "C:\Users\SuPoTing\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1266, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "C:\Users\SuPoTing\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\SuPoTing\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "C:\Users\SuPoTing\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 361, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\Users\SuPoTing\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 389, in get_matching_files_v2
    for single_filename in pattern
  File "C:\Users\SuPoTing\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: ./SRGAN_pre-trained : \udca8t\udcb2Χ\u4923\udca8\udcec\udcab\udcfc\udca9w\udcaa\udcba\udcb8\udcf4\udcae|\udca1C
; No such process
I can't solve this question,please help me

**Comment by tensorflowbutler** [comment] 2019-08-08 00:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-24 11:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-24 11:57 UTC
Labels: stat:awaiting response, type:support
