### ISSUE TITLE
Convert model to .h5 model

### ISSUE THREAD

**Issue by dudeperfect95** [tensorflow/models#6223] opened 2019-02-18 23:07 UTC
**What is the top-level directory of the model you are using:** faster_rcnn_inception_resnet_v2_atrous_coco
**Have I written custom code**: Not yet
**OS Platform and Distribution** Windows 10 64bit
**TensorFlow installed from**: https://pypi.org/
**TensorFlow version:** 1.9.0
**Bazel version** : N/A
**CUDA/cuDNN version:** : CUDA 9.0/cuDNN 7.0.4 (not sure about cuDNN)
**GPU model and memory**: Nvidia Geforce 740m 2GB
**Exact command to reproduce**: N/A

Is it possible to convert object detection model such as faster_rcnn_inception_resnet_v2_atrous_coco to .h5 model? If yes, how to accomplish this? I searched for this on the internet but found only information about the opposite process(from .h5 to .pb), and I need to get .h5 model of needed tensorflow model.

**Comment by tensorflowbutler** [comment] 2019-02-19 12:19
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dudeperfect95** [comment] 2019-02-19 12:53
Thank you for your response, I updated my comment, I thought my question is more general question, cause I would like to use model from tensorflow with imageAI: https://github.com/OlafenwaMoses/ImageAI/tree/master/imageai/Detection
, imageAI requires .h5 model for object detection, thats why I would like to somehow convert faster_rcnn_inception_resnet_v2_atrous_coco to .h5 model, so imageAI can use it for object detection, because so far Im not impressed with the results that Retinanet50 is giving me, and ImageAI has only three models to download and use.

Thank you

**Comment by Sri-vatsa** [comment] 2019-03-02 06:30
I believe the easiest way is to use Keras. Replicate Faster R-CNN in Keras. Here is an example of [Faster R-CNN inception Resnet v2 w/o atrous](https://github.com/you359/Keras-FasterRCNN). You can then train that Keras model and save it as a `.h5` file.

**Comment by ymodak** [comment] 2019-06-07 23:28
Closing this issue since its resolved. Feel free to reopen if still have questions. Thanks!

**Closed by ymodak** 2019-06-07 23:28 UTC
Labels: type:support
