### ISSUE TITLE
Example ObjectDetector drawing too many squares on a single object

### ISSUE THREAD

**Issue by iseegr8tfuldeadppl** [tensorflow/models#6958] opened 2019-06-05 04:18 UTC
### System information
- **What is the top-level directory of the model you are using**: lite/examples/object_detection/android
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: has nothing to do with the issue
- **TensorFlow version (use command below)**:  has nothing to do with the issue
- **Bazel version (if compiling from source)**: has nothing to do with the issue
- **CUDA/cuDNN version**: has nothing to do with the issue
- **GPU model and memory**: has nothing to do with the issue
- **Exact command to reproduce**: just making the project on Android Studio and loading it to the phone.

### Describe the problem
I used "make project" on android studio and loaded the app, basically everytime it detects an object it overwhelms it with squares with different sizes, is there any code i can add to prevent it but at the same time still allow it to detect different objects of the same id.

### Source code / logs
Nothing

**Comment by iseegr8tfuldeadppl** [comment] 2019-06-05 19:38
issue was also posted on [stackoverflow](https://stackoverflow.com/questions/56454224/example-objectdetector-drawing-too-many-squares-on-a-single-object).

**Comment by iseegr8tfuldeadppl** [comment] 2019-06-06 23:07
bump

**Comment by jvishnuvardhan** [comment] 2019-06-21 21:00
@iseegr8tfuldeadppl Can you provide a standalone code to reproduce the issue? You could use public data if possible. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-07-08 17:45
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-07-08 17:45 UTC
Labels: comp:lite, models: research, stat:awaiting response, type:support
