### ISSUE TITLE
geeting the error while loading the tenforflow models into cv.dnn.readnetfromtensorflow

### ISSUE THREAD

**Issue by sreenupadidapu** [tensorflow/models#7812] opened 2019-11-15 10:25 UTC
cv2.error: OpenCV(4.1.1) /io/opencv/modules/dnn/src/layers/detection_output_layer.cpp:215: error: (-215:Assertion failed) int(numPriors * _numClasses) == total(inputs[1], 1) in function 'getMemoryShapes'

while i gave .pb file and graph.pbtxt file to the method cv.dnn.readnetfromtensorflow gives the above error.

Any suggestions?????

**Comment by tensorflowbutler** [comment] 2019-11-16 00:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-19 09:40
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-19 09:40 UTC
Labels: stat:awaiting response, type:support
