### ISSUE TITLE
export_inference_graph.py AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'DEFINE_list'

### ISSUE THREAD

**Issue by radzfoto** [tensorflow/models#2671] opened 2017-10-31 22:10 UTC
### System information

- What is the top-level directory of the model you are using: ~/tensorflow/models/research/object_detection
-  Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No custom code, and using a neural network supplied in the object_detection folders. The dataset for retraining is my own.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
    TensorFlow version (use command below): v1.3.0-rc1-4007-gc44f67a 1.5.0-dev20171031
 (had to use nightly as temporary solution to  #2653)
- Bazel version (if compiling from source):
- Python version 3.5.2, using GCC 5.4.0 20160609
- CUDA/cuDNN version: CUDA 8.0, cudnn 6.0, nVidia driver: 384.90
- GPU: nVidia TitanXp 12GB memory
- CPU: Intel x86-64 Intel Core i7-7700K @ 4.20GHz x 8, 32GB memory
- Exact command to reproduce:
python export_inference_graph.py \
>     --input_type image_tensor \
>     --pipeline_config_path /media/raul/RD750G/highwai/tfrecords/models/model/highwai_data.config \
>     --trained_checkpoint_prefix /media/raul/RD750G/highwai/tfrecords/checkpoint/model.ckpt-2238 \
>     --output_directory /media/raul/RD750G/highwai/tfrecords/inf_graph

### Describe the problem

export_inference_graph.py results in error:
  File "export_inference_graph.py", line 80, in <module>
    flags.DEFINE_list('input_shape', None,
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'DEFINE_list'

**Comment by tombstone** [comment] 2017-10-31 23:12
duplicate of #2664

**Closed by tombstone** 2017-10-31 23:12 UTC
