### ISSUE TITLE
plot recall-precision curve for ssd-mobilev1-coco in tensorboard

### ISSUE THREAD

**Issue by zeynali** [tensorflow/models#4192] opened 2018-05-07 10:22 UTC
Hi , how we can plot recall-precision curve for ssd-mobile-v1-coco in tensorboard? 

**Have I written custom code : No
OS Platform and Distribution : ubuntu 16.04
TensorFlow version : 1.5 binary
CUDA/cuDNN version : 9.0/7.0
GPU model and memory : 1080 / 8G**

**Comment by tensorflowbutler** [comment] 2018-05-09 19:40
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-09 22:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-12-05 21:57 UTC
Labels: stat:awaiting response
