### ISSUE TITLE
Add NasMobile to SSD detector

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/models#3532] opened 2018-03-06 16:06 UTC
Please Add NasMobile to SSD.

**Comment by tensorflowbutler** [comment] 2018-04-25 06:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-09 22:06
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2020-01-29 23:26
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:44 UTC
Labels: stat:awaiting response
