### ISSUE TITLE
How to train Pixel Domain Adaptation with own data?

### ISSUE THREAD

**Issue by HutzelFutzel** [tensorflow/models#3700] opened 2018-03-22 15:22 UTC
Hi, 
I try to train the pixelda (models/research/domain_adapatation/pixel_domain_adaptation/) with my own data. I have the .tfrecords already. When I am running the `bazel run domain_adaptation/pixel_domain_adaptation:pixelda_train -- --dataset_dir $DSN_DATA_DIR --source_dataset mnist --target_dataset mnist_m` command from the readme.md and insert my own data as arguments I get `ValueError: Name of dataset unknown xy`.

After some research I found that the script only accepts mnist data through the `dataset_factory` script. 
How can I adjust the code such that I can apply my own data on the network?

**Comment by tensorflowbutler** [comment] 2018-04-25 06:53
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-08 21:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-11-08 21:43 UTC
Labels: stat:awaiting response
