### ISSUE TITLE
Yamnet classifier to tflite

### ISSUE THREAD

**Issue by dmytro-ostapovets** [tensorflow/models#8034] opened 2020-01-13 10:47 UTC
### System information
- **What is the top-level directory of the model you are using**:
models/research/audioset/yamnet/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
N/A
- **TensorFlow installed from (source or binary)**:
N/A
- **TensorFlow version (use command below)**:
N/A
- **Bazel version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
N/A

### Describe the problem
Hello.
Is it possible to convert Yamnet classifier to tflite? 
If yes, could you give some advise how to do that?
I found that it's working well on desktop, but I'd like to use it in android app.
Thank you

### Source code / logs
N/A

**Comment by tensorflowbutler** [comment] 2020-01-14 00:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by HowGetHigh** [comment] 2020-04-16 03:35
Because @dmytro-ostapovets hasn't updated yet, please guide me on the environment:
What is the top-level directory of the model you are using:
models/research/audioset/yamnet/
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
TensorFlow installed from (source or binary): conda install tensorflow=1.15.0
TensorFlow version (use command below): TF ver 1.15.0
Bazel version (if compiling from source): N/A
CUDA/cuDNN version: no cuda
GPU model and memory: I use CPU
Exact command to reproduce: N/A

**Comment by plakal** [comment] 2020-04-27 19:40
The short answer is that it is possible to run YAMNet with TF-Lite or TF-JS runtimes but you need to do a little bit of work. The core model itself can be converted without problems but the feature extraction path uses some ops that are not currently supported in the core set of TF-Lite/JS ops. We have a TF-Lite/JS-friendly version of feature extraction which you could use to replace the feature extraction code that we released as part of YAMNet. We haven't officially released the TF-Lite path

**Comment by plakal** [comment] 2020-04-27 19:42
@dpwe as FYI

The short answer is that it is possible to run YAMNet with TF-Lite or TF-JS runtimes but you need to do a little bit of work. The core model itself can be converted without problems but the feature extraction path uses some ops that are not currently supported in the core set of TF-Lite/JS ops. We have a TF-Lite/JS-friendly version of feature extraction which you could use to replace the feature extraction code that we released as part of YAMNet. We haven't officially released the TF-Lite feature extraction code yet but you can see it in Magenta's repo here: https://github.com/tensorflow/magenta/blob/master/magenta/music/melspec_input.py  (pass tflite_compatible=True to build_mel_calculation_graph() and try to use that inside spectrogram_to_patches() in features.py).

We might release the TF-Lite code officially in this repo here but we don't have a timeline for that yet.

**Closed by plakal** 2020-04-27 19:42 UTC
Labels: models:research, stat:awaiting response, type:support

**Comment by tcwalther** [comment] 2020-05-10 21:58
Hey @plakal, thanks for your tips. Do you have any suggestions on how to operate a streaming version of this model in TF Lite?

**Comment by zxl777** [comment] 2020-05-27 11:46
I look forward to your release of the TF-Lite code, this is very practical.

**Comment by zxl777** [comment] 2020-05-27 11:48
```
tflite_convert \
  --keras_model_file=/root/models/research/audioset/yamnet/yamnet.h5 \
  --output_file=/root/models/research/audioset/yamnet/mobilenet.tflite
```
But Error "No model found in config file"

**Comment by zxl777** [comment] 2020-05-30 01:43
Google Audio Set classification with Keras and pytorch. 

https://github.com/qiuqiangkong/audioset_classification
https://github.com/qiuqiangkong/audioset_tagging_cnn

```
A mean average precision (mAP) of 0.439 is achieved using our proposed Wavegram-Logmel-CNN system, outperforming the Google baseline of 0.317 [3].
```

But pytorch modles -> tflite -> flutter  these steps is very troublesome.
If Yamnet classifier can provide tflite directly, it will be the most concise solution.
Thank you.

**Comment by dpwe** [comment] 2020-06-05 16:11
I've quietly copied a tflite export of the original TF YAMNet model to:
https://storage.googleapis.com/audioset/yamnet.tflite
But I want to release code showing how to use it.  

My efforts to load and run it with tf.lite.Interpreter(model_path="yamnet.tflite") results in my public colab kernel crashing.

If you are able to make this model work, I'd be very interested in what you did.  But my suspicion is that somehow my internally-generated tflite files aren't compatible with the tflite interpreter I'm trying to run it under.

I apologize I don't have a better grasp of the issues here.

**Comment by dpwe** [comment] 2020-06-14 00:55
I spent some time trying to get the tflite model above to work, but it crashed my kernel.

**However**, we are in luck because @antonyharfield figured it all out.  See his [blog post](https://medium.com/@antonyharfield/converting-the-yamnet-audio-detection-model-for-tensorflow-lite-inference-43d049bd357c) for instructions on how to build a tflite version of YAMNet, and see his [fork of this code](https://github.com/antonyharfield/tflite-models-audioset-yamnet) for the working model.  Thank you, Antony!

**Comment by kaiott** [comment] 2021-06-23 12:39
Is there any update on this? The code from @anthonyharfield does not work with the current version of YAMNet. Also around 10 months ago there is a commit that added tflite compatibility. There is even code that generates a tflite version of YAMNet automatically. However, I would like to use the convolutional layers of YAMNet for transfer learning and add custom dense layers on top. I already have the code and the top model trained in TF2 but haven't figured out how to convert that to tflite.
