### ISSUE TITLE
Feature request: Output Visualization for Mapper

### ISSUE THREAD

**Issue by Jiankai-Sun** [tensorflow/models#3737] opened 2018-03-25 07:32 UTC
Firstly, thank you @s-gupta  so much for your excellent code and paper. (https://github.com/tensorflow/models/tree/master/research/cognitive_mapping_and_planning)

I want to get the Output Visualization for Mapper trained for Free Space Prediction which is in the paper Appendix Figure A1.
![1](https://user-images.githubusercontent.com/25477396/37872728-b1fc38d2-3040-11e8-93ac-dd8fdf055de4.PNG)
I guess it is the output of function get_map_from_images() (https://github.com/tensorflow/models/blob/master/research/cognitive_mapping_and_planning/tfcode/cmp.py#L259). I wonder whether there is a recommend method to visualize the output result of the mapper.

**Comment by tensorflowbutler** [comment] 2018-04-25 06:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-09 22:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-12-05 21:37 UTC
Labels: stat:awaiting response
