### ISSUE TITLE
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by Prithvi0167** [tensorflow/models#10024] opened 2021-05-27 09:28 UTC
I am using tensorflow version 1.15.2 and keras version 2.1.6 in my google colab.I am getting error as displayed in them images atttached
![image](https://user-images.githubusercontent.com/43097533/119801678-90c79600-befb-11eb-935d-467076a2f9b2.png)
![image](https://user-images.githubusercontent.com/43097533/119802153-ef8d0f80-befb-11eb-94f7-b5c3a175c8f9.png)

Please Help!

**Comment by saikumarchalla** [comment] 2021-06-02 03:51
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by hchamikadilshan** [comment] 2021-06-03 15:16
try using,..

`import tensorflow.keras   `      instead  of `import keras`

**Comment by jvishnuvardhan** [comment] 2021-06-17 06:09
@Prithvi0167 I can reproduce the error. Looks like there are some issues in importing keras. However, you can import it from tensorflow as `from tensorflow import keras`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/010edc068a43583c7aa48047e7e0ac01/untitled.ipynb).

As this is more related to `keras-team/keras`, you can post them in their GitHub repository. Starting TF2.5, both keras-team/keras and tf.keras are in sync. Try to use latest version as they are much better when compared to older versions. Thanks!

**Comment by jvishnuvardhan** [comment] 2021-06-25 03:51
Closing this issue as this was resolved. Thanks!

**Closed by jvishnuvardhan** 2021-06-25 03:51 UTC
Labels: stalled, stat:awaiting response, type:support
