### ISSUE TITLE
Manual build syntaxnet always failed on Ubuntu & Mac

### ISSUE THREAD

**Issue by topgetgithub** [tensorflow/models#2547] opened 2017-10-18 01:55 UTC
I changed several machine and always got the same errors (22 failed as below):

//dragnn/python:bulk_component_test                                      FAILED in 1.1s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/bulk_component_test/test.log
//dragnn/python:composite_optimizer_test                                 FAILED in 0.7s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/composite_optimizer_test/test.log
//dragnn/python:digraph_ops_test                                         FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/digraph_ops_test/test.log
//dragnn/python:evaluation_test                                          FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/evaluation_test/test.log
//dragnn/python:graph_builder_test                                       FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/graph_builder_test/test.log
//dragnn/python:lexicon_test                                             FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/lexicon_test/test.log
//dragnn/python:network_units_test                                       FAILED in 1.1s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/network_units_test/test.log
//dragnn/python:render_parse_tree_graphviz_test                          FAILED in 1.0s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/render_parse_tree_graphviz_test/test.log
//dragnn/python:render_spec_with_graphviz_test                           FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/render_spec_with_graphviz_test/test.log
//dragnn/python:sentence_io_test                                         FAILED in 0.7s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/sentence_io_test/test.log
//dragnn/python:spec_builder_test                                        FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/spec_builder_test/test.log
//dragnn/python:visualization_test                                       FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/visualization_test/test.log
//dragnn/tools:model_trainer_test                                        FAILED in 1.4s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/tools/model_trainer_test/test.log
//examples/dragnn:test_run_all_tutorials                                 FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log
//syntaxnet:beam_reader_ops_test                                         FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 1.1s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 1.5s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log
//syntaxnet/util:check_test                                              FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/check_test/test.log
//syntaxnet/util:registry_test                                           FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/registry_test/test.log

Executed 52 out of 52 tests: 30 tests pass and 22 fail locally.

**Comment by drpngx** [comment] 2017-10-18 19:24
What is the error message?

**Comment by laeuter** [comment] 2017-10-20 07:48
I have exactly the same experience.

From the end of /testlogs/dragnn/python/{evaluation_test,parser_trainer_test,text_formats_test}/test.log:
--------------------------------------
  File "/home/**********/.cache/bazel/_bazel_**********/20bccd8906837b6f1fd2371be43a
ab45/execroot/__main__/bazel-out/local-opt/bin/dragnn/python/evaluation_test.run
files/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 24, in <modu
le>
    import enum  # pylint: disable=g-bad-import-order
ImportError: No module named enum
--------------------------------------
Hope that helps.

**Comment by zerodarkzone** [comment] 2017-10-20 21:35
I have the same problem

**Comment by topgetgithub** [comment] 2017-10-21 01:33
error still occurs even after pip install enum and another mentioned package

**Comment by drpngx** [comment] 2017-10-21 01:36
Yes, I think that's a mac/py3 issue or some similar combination. Let me dig up what the fix is.

**Comment by drpngx** [comment] 2017-10-21 01:40
Maybe this? https://stackoverflow.com/questions/26828206/importerror-no-module-named-enum

**Comment by topgetgithub** [comment] 2017-10-21 02:07
below is the entire build steps I performed just now, and the ouput. PYTHON_BIN_PATH?

bazel test ...
........................
ERROR: /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/third_party/py/python_configure.bzl", line 310
                _create_local_python_repository(repository_ctx)
        File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/third_party/py/python_configure.bzl", line 268, in _create_local_python_repository
                _get_python_bin(repository_ctx)
        File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/third_party/py/python_configure.bzl", line 166, in _get_python_bin
                _get_env_var(repository_ctx, _PYTHON_BIN_PATH, No..., ...)
        File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/third_party/py/python_configure.bzl", line 49, in _get_env_var
                _python_configure_fail(("'%s' environment variable is n...))
        File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/third_party/py/python_configure.bzl", line 37, in _python_configure_fail
                fail(("%sPython Configuration Error:%...)))
Python Configuration Error: 'PYTHON_BIN_PATH' environment variable is not set
 and referenced by '@org_tensorflow//third_party/py/numpy:headers'
ERROR: Analysis of target '//dragnn/tools:build_pip_package' failed; build aborted
INFO: Elapsed time: 5.647s
FAILED: Build did NOT complete successfully (73 packages loaded)
    currently loading: @org_tensorflow//tensorflow/core ... (2 packages)
ERROR: Couldn't start the build. Unable to run tests
root@iZ6we9q8a9mrwjz6qqabgwZ:~/models/research/syntaxnet# which python
/usr/bin/python
root@iZ6we9q8a9mrwjz6qqabgwZ:~/models/research/syntaxnet# export PYTHON_BIN_PATH=/usr/bin/python
root@iZ6we9q8a9mrwjz6qqabgwZ:~/models/research/syntaxnet# bazel test ...
DEBUG: /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/third_party/py/python_configure.bzl:30:3: Python Configuration Warning: 'PYTHON_LIB_PATH' environment variable is not set, using '/usr/local/lib/python2.7/dist-packages' as default
WARNING: /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/tensorflow/core/BUILD:1782:1: in includes attribute of cc_library rule @org_tensorflow//tensorflow/core:framework_headers_lib: '../../../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'external/org_tensorflow/tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/tensorflow/tensorflow.bzl:1048:30
WARNING: /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule @org_tensorflow//tensorflow/contrib/learn:learn: target '@org_tensorflow//tensorflow/contrib/learn:learn' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/external/org_tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule @org_tensorflow//tensorflow/contrib/learn:learn: target '@org_tensorflow//tensorflow/contrib/learn:learn' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Analysed 218 targets (136 packages loaded).
INFO: Found 166 targets and 52 test targets...
FAIL: //syntaxnet:text_formats_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log)
FAIL: //syntaxnet:reader_ops_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log)
FAIL: //syntaxnet:parser_trainer_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log)
FAIL: //syntaxnet:lexicon_builder_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log)
FAIL: //syntaxnet:graph_builder_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log)
FAIL: //syntaxnet:beam_reader_ops_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log)
FAIL: //syntaxnet/util:registry_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/registry_test/test.log)
FAIL: //syntaxnet/util:check_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/check_test/test.log)
FAIL: //dragnn/python:visualization_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/visualization_test/test.log)
FAIL: //dragnn/python:spec_builder_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/spec_builder_test/test.log)
FAIL: //dragnn/python:sentence_io_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/sentence_io_test/test.log)
FAIL: //dragnn/python:render_spec_with_graphviz_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/render_spec_with_graphviz_test/test.log)
FAIL: //dragnn/python:render_parse_tree_graphviz_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/render_parse_tree_graphviz_test/test.log)
FAIL: //dragnn/python:network_units_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/network_units_test/test.log)
FAIL: //dragnn/python:lexicon_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/lexicon_test/test.log)
FAIL: //dragnn/python:graph_builder_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/graph_builder_test/test.log)
FAIL: //dragnn/python:evaluation_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/evaluation_test/test.log)
FAIL: //dragnn/python:digraph_ops_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/digraph_ops_test/test.log)
FAIL: //dragnn/python:composite_optimizer_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/composite_optimizer_test/test.log)
FAIL: //dragnn/python:bulk_component_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/bulk_component_test/test.log)
FAIL: //dragnn/tools:model_trainer_test (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/tools/model_trainer_test/test.log)
FAIL: //examples/dragnn:test_run_all_tutorials (see /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log)
INFO: Elapsed time: 56.871s, Critical Path: 3.57s
INFO: Build completed, 22 tests FAILED, 26 total actions
//dragnn/components/stateless:stateless_component_test          (cached) PASSED in 0.1s
//dragnn/components/syntaxnet:syntaxnet_component_test          (cached) PASSED in 0.1s
//dragnn/components/syntaxnet:syntaxnet_link_feature_extractor_test (cached) PASSED in 0.1s
//dragnn/components/syntaxnet:syntaxnet_transition_state_test   (cached) PASSED in 0.1s
//dragnn/core:beam_test                                         (cached) PASSED in 0.1s
//dragnn/core:compute_session_impl_test                         (cached) PASSED in 0.1s
//dragnn/core:compute_session_pool_test                         (cached) PASSED in 0.1s
//dragnn/core:dragnn_bulk_op_kernels_test                       (cached) PASSED in 0.1s
//dragnn/core:dragnn_op_kernels_test                            (cached) PASSED in 0.1s
//dragnn/core:index_translator_test                             (cached) PASSED in 0.1s
//dragnn/core:input_batch_cache_test                            (cached) PASSED in 0.1s
//dragnn/core:resource_container_test                           (cached) PASSED in 0.1s
//dragnn/io:sentence_input_batch_test                           (cached) PASSED in 0.1s
//syntaxnet:arc_standard_transitions_test                       (cached) PASSED in 0.1s
//syntaxnet:binary_segment_state_test                           (cached) PASSED in 0.1s
//syntaxnet:binary_segment_transitions_test                     (cached) PASSED in 0.1s
//syntaxnet:char_ngram_string_extractor_test                    (cached) PASSED in 0.1s
//syntaxnet:char_properties_test                                (cached) PASSED in 0.1s
//syntaxnet:char_shift_transitions_test                         (cached) PASSED in 0.1s
//syntaxnet:head_transitions_test                               (cached) PASSED in 0.1s
//syntaxnet:label_transitions_test                              (cached) PASSED in 0.1s
//syntaxnet:morphology_label_set_test                           (cached) PASSED in 0.1s
//syntaxnet:once_transitions_test                               (cached) PASSED in 0.1s
//syntaxnet:parser_features_test                                (cached) PASSED in 0.1s
//syntaxnet:segmenter_utils_test                                (cached) PASSED in 0.1s
//syntaxnet:sentence_features_test                              (cached) PASSED in 0.1s
//syntaxnet:shared_store_test                                   (cached) PASSED in 0.1s
//syntaxnet:tagger_transitions_test                             (cached) PASSED in 0.2s
//syntaxnet:whole_sentence_features_test                        (cached) PASSED in 0.1s
//util/utf8:unicodetext_unittest                                (cached) PASSED in 0.1s
//dragnn/python:bulk_component_test                                      FAILED in 0.7s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/bulk_component_test/test.log
//dragnn/python:composite_optimizer_test                                 FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/composite_optimizer_test/test.log
//dragnn/python:digraph_ops_test                                         FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/digraph_ops_test/test.log
//dragnn/python:evaluation_test                                          FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/evaluation_test/test.log
//dragnn/python:graph_builder_test                                       FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/graph_builder_test/test.log
//dragnn/python:lexicon_test                                             FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/lexicon_test/test.log
//dragnn/python:network_units_test                                       FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/network_units_test/test.log
//dragnn/python:render_parse_tree_graphviz_test                          FAILED in 0.7s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/render_parse_tree_graphviz_test/test.log
//dragnn/python:render_spec_with_graphviz_test                           FAILED in 0.7s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/render_spec_with_graphviz_test/test.log
//dragnn/python:sentence_io_test                                         FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/sentence_io_test/test.log
//dragnn/python:spec_builder_test                                        FAILED in 0.6s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/spec_builder_test/test.log
//dragnn/python:visualization_test                                       FAILED in 1.0s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/python/visualization_test/test.log
//dragnn/tools:model_trainer_test                                        FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/dragnn/tools/model_trainer_test/test.log
//examples/dragnn:test_run_all_tutorials                                 FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log
//syntaxnet:beam_reader_ops_test                                         FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 0.7s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 0.7s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 1.0s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log
//syntaxnet/util:check_test                                              FAILED in 0.9s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/check_test/test.log
//syntaxnet/util:registry_test                                           FAILED in 0.8s
  /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/registry_test/test.log

Executed 22 out of 52 tests: 30 tests pass and 22 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

**Comment by topgetgithub** [comment] 2017-10-21 02:09
the OS is Ubuntu 16.04, python is 2.7, not 3.x

**Comment by topgetgithub** [comment] 2017-10-21 02:12
the first error message in correspond test.log:

root@iZ6we9q8a9mrwjz6qqabgwZ:~/models/research/syntaxnet# cat /root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/util/check_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/util/check_test.runfiles/__main__/syntaxnet/util/check_test.py", line 3, in <module>
    from tensorflow.python.platform import googletest
  File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/util/check_test.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/util/check_test.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/util/check_test.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 102, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/util/check_test.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 30, in <module>
    from tensorflow.python.framework import function
  File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/util/check_test.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 38, in <module>
    from tensorflow.python.ops import variable_scope as vs
  File "/root/.cache/bazel/_bazel_root/d78cc2bbfe399a9a2f97a3fcc389326e/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/util/check_test.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 192, in <module>
    """
AttributeError: 'int' object attribute '__doc__' is read-only

**Comment by drpngx** [comment] 2017-10-21 18:47
Did you run `bazel fetch`?

**Comment by topgetgithub** [comment] 2017-10-22 07:03
No. But how?

**Comment by topgetgithub** [comment] 2017-10-23 00:37
My steps:
1. Installing from package downloaded from Ubuntu official website, or purchasing Linux servers from certain cloud service(with Ubuntu 16.04 LTS), so it will be a "clean" system;
2. apt-get update & upgrade, especially for python 2.7;
3. following the instruction exactly step by step on this page: "https://github.com/tensorflow/models/tree/master/research/syntaxnet";
4. and then, will get the errors described in the above threads each time.

**Comment by laeuter** [comment] 2017-10-23 08:16
No, `bazel fetch ...` didn't work for me either (Windows + VirtualBox + Ubuntu 16.04.3 + Python 2.7). Still 22 failures.
`pip install enum34` reduced the failure count to 14.

`/home/username/.cache/bazel/_bazel_username/20bccd8906837b6f1fd2371be43aab45/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/{text_formats_test,reader_ops_test}/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
2017-10-23 08:03:09.528504: F external/org_tensorflow/tensorflow/core/framework/
variant_op_registry.cc:104] Check failed: existing == nullptr (0x26f7428 vs. nul
lptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered
Aborted (core dumped)`

`more /home/username/.cache/bazel/_bazel_username/20bccd8906837b6f1fd2371be43aab45/execroot/__main__/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ BINDIR=/home/username/.cache/bazel/_bazel_username/20bccd8906837b6f1fd2371be43
aab45/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.ru
nfiles/__main__/syntaxnet
+ CONTEXT=/home/username/.cache/bazel/_bazel_username/20bccd8906837b6f1fd2371be4
3aab45/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.r
unfiles/__main__/syntaxnet/testdata/context.pbtxt
+ TMP_DIR=/tmp/syntaxnet-output
+ mkdir -p /tmp/syntaxnet-output
+ sed s=OUTPATH=/tmp/syntaxnet-output=
+ sed s=SRCDIR=/home/username/.cache/bazel/_bazel_username/20bccd8906837b6f1fd23
71be43aab45/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/parser_trainer_t
est.runfiles= /home/username/.cache/bazel/_bazel_username/20bccd8906837b6f1fd237
1be43aab45/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/parser_trainer_te
st.runfiles/__main__/syntaxnet/testdata/context.pbtxt
+ PARAMS=128-0.08-3600-0.9-0
+ /home/username/.cache/bazel/_bazel_username/20bccd8906837b6f1fd2371be43aab45/e
xecroot/__main__/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.runfiles/
__main__/syntaxnet/parser_trainer --arg_prefix=brain_parser --batch_size=32 --co
mpute_lexicon --decay_steps=3600 --graph_builder=greedy --hidden_layer_sizes=128
 --learning_rate=0.08 --momentum=0.9 --output_path=/tmp/syntaxnet-output --task_
context=/tmp/syntaxnet-output/context --training_corpus=training-corpus --tuning
_corpus=tuning-corpus --params=128-0.08-3600-0.9-0 --num_epochs=12 --report_ever
y=100 --checkpoint_every=1000 --logtostderr
2017-10-23 08:03:03.769084: F external/org_tensorflow/tensorflow/core/framework/
variant_op_registry.cc:104] Check failed: existing == nullptr (0x2eb56e8 vs. nul
lptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered
/home/username/.cache/bazel/_bazel_username/20bccd8906837b6f1fd2371be43aab45/exe
croot/__main__/bazel-out/local-opt/bin/syntaxnet/parser_trainer_test.runfiles/__
main__/syntaxnet/parser_trainer_test: line 52: 26742 Aborted                 (co
re dumped) "$BINDIR/parser_trainer" --arg_prefix=brain_parser --batch_size=32 --
compute_lexicon --decay_steps=3600 --graph_builder=greedy --hidden_layer_sizes=1
28 --learning_rate=0.08 --momentum=0.9 --output_path=$TMP_DIR --task_context=$TM
P_DIR/context --training_corpus=training-corpus --tuning_corpus=tuning-corpus --
params=$PARAMS --num_epochs=12 --report_every=100 --checkpoint_every=1000 --logt
ostderr`

**Comment by topgetgithub** [comment] 2017-10-23 08:52
bazel fetch ... & pip install enum34, won't reduce the fail count for me.

**Comment by SaintNazaire** [comment] 2017-10-25 13:48
Similar problem here, [opened issue with all details] (https://github.com/tensorflow/models/issues/2588)

**Comment by crafet** [comment] 2018-10-29 11:16
@topgetgithub what's the final result?thx

**Comment by topgetgithub** [comment] 2018-10-30 03:11
> @topgetgithub what's the final result?thx

still waiting

**Comment by tensorflowbutler** [comment] 2020-01-29 23:32
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 09:54
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 09:54 UTC
Labels: type:build/install
