### ISSUE TITLE
ValueError: Layer "movinet" expects 223 input(s), but it received 1 input tensors.

### ISSUE THREAD

**Issue by MarkosMuche** [tensorflow/models#10592] opened 2022-04-14 18:54 UTC
I am using the movinet from tensorhub (movinet/a5/stream/kinetics-600/classification). I gave the model a video of shape shape=(12, 20, 256, 256, 3), where 12 is batch size and 20 is number of frames in each video. However, the model wouldn't accept that and raises the following error.
File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/input_spec.py", line 200, in assert_input_compatibility
        raise ValueError(f'Layer "{layer_name}" expects {len(input_spec)} input(s),'

    ValueError: Layer "movinet" expects 223 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'imgs:0' shape=(12, 20, 256, 256, 3) dtype=float32>]

**Comment by jvishnuvardhan** [comment] 2022-06-11 09:14
@MarkosMuche Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2022-06-28 02:32
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2022-06-28 02:32 UTC
Labels: stat:awaiting response, type:support, stalled
