### ISSUE TITLE
there is nothing happen after running object_detection_tutorial.ipynb 

### ISSUE THREAD

**Issue by shakugan0shana** [tensorflow/models#2788] opened 2017-11-14 03:01 UTC
I follow the steps in the Installation,
then I run the object_detection_tutorial.ipynb,
there in no error in running the code，
however，the output of image is same the original picture,
in other words，obejct code has no effects。

Here is the code：

import os
os.system('protoc object_detection/protos/*.proto --python_out=.')
import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile

from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image

if tf.__version__ != '1.4.0':
  raise ImportError('Please upgrade your tensorflow installation to v1.4.0!')

from utils import label_map_util
from utils import visualization_utils as vis_util
# What model to download.
#MODEL_NAME = 'ssd_mobilenet_v1_coco_2017_11_08'
#MODEL_FILE = MODEL_NAME + '.tar.gz'
#DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'

# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_CKPT = '/opt/models-master/research/ssd_mobilenet_v1_coco_2017_11_08/frozen_inference_graph.pb'

# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = '/opt/models-master/research/object_detection/data/mscoco_label_map.pbtxt'

NUM_CLASSES = 90

#opener = urllib.request.URLopener()
#opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
#tar_file = tarfile.open(MODEL_FILE)
#for file in tar_file.getmembers():
#  file_name = os.path.basename(file.name)
#  if 'frozen_inference_graph.pb' in file_name:
#    tar_file.extract(file, os.getcwd())

detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)

# For the sake of simplicity we will use only 2 images:
# image1.jpg
# image2.jpg
# If you want to test the code with your images, just add path to the images to the TEST_IMAGE_PATHS.
TEST_IMAGE_PATHS = ['/opt/models-master/research/object_detection/test_images/image1.jpg']

# Size, in inches, of the output images.
IMAGE_SIZE = (12, 8)

with detection_graph.as_default():
  with tf.Session(graph=detection_graph) as sess:
    # Definite input and output Tensors for detection_graph
    image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
    # Each box represents a part of the image where a particular object was detected.
    detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
    # Each score represent how level of confidence for each of the objects.
    # Score is shown on the result image, together with the class label.
    detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
    detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')
    num_detections = detection_graph.get_tensor_by_name('num_detections:0')
    for image_path in TEST_IMAGE_PATHS:
      image = Image.open(image_path)
      # the array based representation of the image will be used later in order to prepare the
      # result image with boxes and labels on it.
      image_np = load_image_into_numpy_array(image)
      # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
      image_np_expanded = np.expand_dims(image_np, axis=0)
      # Actual detection.
      (boxes, scores, classes, num) = sess.run(
          [detection_boxes, detection_scores, detection_classes, num_detections],
          feed_dict={image_tensor: image_np_expanded})
      # Visualization of the results of a detection.
      vis_util.visualize_boxes_and_labels_on_image_array(
          image_np,
          np.squeeze(boxes),
          np.squeeze(classes).astype(np.int32),
          np.squeeze(scores),
          category_index,
          use_normalized_coordinates=True,
          line_thickness=8)
      print(np.squeeze(boxes),np.squeeze(classes).astype(np.int32),np.squeeze(scores),num)
      vis_util.save_image_array_as_png(image_np,'/opt/out.png')

Here is the output of scores:
array([ 0.03587306,  0.02224855,  0.01864638,  0.01096713,  0.01003152,
        0.00654459,  0.00633546,  0.00534311,  0.00495995,  0.00410239,
        0.00362364,  0.00339176,  0.00308251,  0.00303369,  0.00293387,
        0.00277085,  0.00269582,  0.00266825,  0.00263924,  0.00263331,
        0.0025872 ,  0.00240822,  0.00225823,  0.00186966,  0.00184309,
        0.00180467,  0.00177474,  0.00173643,  0.0017281 ,  0.00171935,
        0.00171891,  0.00170284,  0.00163754,  0.00162967,  0.00160267,
        0.00156545,  0.00153614,  0.00140937,  0.00132406,  0.00131524,
        0.00131041,  0.00129431,  0.00125819,  0.0012553 ,  0.00122365,
        0.00119179,  0.00115673,  0.00115186,  0.00112368,  0.00107096,
        0.00105803,  0.00104337,  0.00102719,  0.00102337,  0.00100349,
        0.00097768,  0.0009685 ,  0.00092741,  0.00088506,  0.00087696,
        0.0008734 ,  0.00084825,  0.00084135,  0.00083512,  0.00083396,
        0.00082068,  0.00080583,  0.00078979,  0.00078059,  0.00077475,
        0.00075449,  0.00074426,  0.00074421,  0.00070195,  0.00068741,
        0.00068138,  0.00067261,  0.00067125,  0.00067032,  0.00066041,
        0.0006473 ,  0.00064205,  0.00061964,  0.00061793,  0.00060834,
        0.00060468,  0.00059547,  0.00059478,  0.00059461,  0.00059436,
        0.00059426,  0.00059411,  0.00059406,  0.00059392,  0.00059365,
        0.00059351,  0.00059191,  0.00058798,  0.00058682,  0.00058148], dtype=float32)

we can see,the score is very bad,I don't konw where the problem is.

**Comment by rohan100jain** [comment] 2017-11-14 22:06
This seems to be a dupe of #2773 Seems like there is some problem with the latest version of that model.

**Closed by rohan100jain** 2017-11-14 22:06 UTC

**Comment by DIT4FUN** [comment] 2018-01-04 01:27
i'm mat the same problem!
