### ISSUE TITLE
Failure on ci.bazel.build

### ISSUE THREAD

**Issue by dslomov** [tensorflow/models#3192] opened 2018-01-18 10:58 UTC
Bazel 0.9.0: https://ci.bazel.build/blue/organizations/jenkins/tf_models_syntaxnet/detail/tf_models_syntaxnet/909/pipeline/
Nightly: https://ci.bazel.build/blue/organizations/jenkins/Global%2Ftf_models_syntaxnet/detail/tf_models_syntaxnet/362/pipeline/

**Comment by wolyosung** [comment] 2018-01-24 07:04
please patch bazel build issue in syntaxnet...

**Comment by tensorflowbutler** [comment] 2020-01-29 23:30
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 10:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 10:00 UTC
Labels: stat:awaiting tensorflower
