### ISSUE TITLE
The code and the paper have different structures

### ISSUE THREAD

**Issue by dythebs** [tensorflow/models#5364] opened 2018-09-23 11:54 UTC
### System information
- **What is the top-level directory of the model you are using**: models/research/slim/nets/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**:N/A
- **Bazel version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:N/A
- **Exact command to reproduce**:N/A

### Describe the problem
I read the [code](https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_v1.py) and find `end_point = 'MaxPool_5a_2x2'` in line 214, however I see it is `3x3+2(S)` in the [paper](https://arxiv.org/pdf/1409.4842v1.pdf) (Figure 3)

**Comment by tensorflowbutler** [comment] 2018-09-23 19:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by yhliang2018** [comment] 2020-01-29 21:08
Assign to sguada@ as the code maintainable to take a look.

**Closed** 2020-09-18 19:17 UTC
Labels: stalled, stat:awaiting response
