### ISSUE TITLE
What do I have to do to train PixelDa with my own data?

### ISSUE THREAD

**Issue by HutzelFutzel** [tensorflow/models#3670] opened 2018-03-20 16:03 UTC
What do I have to do if i want to train the PixelDA network with my own data? Always when I try to start training, I get a message: `ValueError: Name of dataset unknown unreal_nobb480`. 

After some search I found, that there is an issue in the ~/models/research/slim/datasets/ folder. They have a file mnist.py which is imported in the pixelda_train.py file and somehow needed. Is there a simple way to avoid that? I don't know what the sense of this script is.

**Comment by tensorflowbutler** [comment] 2018-04-25 06:57
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment] 2018-11-09 21:57
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-11-09 21:57 UTC
Labels: stat:awaiting response
