### ISSUE TITLE
Updated Frozen Model doesn't work in tutorial jupyter notebook

### ISSUE THREAD

**Issue by erickvinsan** [tensorflow/models#2786] opened 2017-11-14 02:15 UTC
Hello everyone! 

I think there is an issue with the frozen graph of this version "ssd_mobilenet_v1_coco_2017_11_08" of model base. I just can't hit any object, even in the object_detection_tutorial example. However, with the frozen graph from the version "ssd_mobilenet_v1_coco_11_06_2017" it works! I spend just 2 hole days trying to figure out the solution and I just could overpass the problem like the described before.

Thank you in advance!

Python 3.5
TensorFlow 1.4.1 (CPU)
Windows 8.1

**Comment by shakugan0shana** [comment] 2017-11-14 03:06
I have the same problem ,the ssd_mobilenet_v1_coco_11_06_2017 has no effects,I run the object_detection_tutorial example,the output of image is same as the original picture.

**Comment by erickvinsan** [comment] 2017-11-14 04:03
In the object_detection_tutorial, change the value of the variable that has this string "ssd_mobilenet_v1_coco_2017_11_08"  to "ssd_mobilenet_v1_coco_11_06_2017". This is going to correct your problem as corrected mine.

**Comment by shakugan0shana** [comment] 2017-11-14 05:01
Yes ,I change the  string "ssd_mobilenet_v1_coco_2017_11_08" to "ssd_mobilenet_v1_coco_11_06_2017",it works well.I think it must exit something wrong in the "ssd_mobilenet_v1_coco_2017_11_08".

**Comment by rohan100jain** [comment] 2017-11-14 22:05
This seems to be a dupe of https://github.com/tensorflow/models/issues/2773 Seems like there is some problem with the latest version of that model.

**Closed by rohan100jain** 2017-11-14 22:05 UTC
