### ISSUE TITLE
UnicodeDecodeError in detection_inference.py

### ISSUE THREAD

**Issue by ekorman** [tensorflow/models#3772] opened 2018-03-27 16:55 UTC
This line 

https://github.com/tensorflow/models/blob/676a4f70c20020ed41b533e0c331f115eeffe9a3/research/object_detection/inference/detection_inference.py#L68

gives the error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 41: invalid start byte`  which is fixed by replacing 'r' with 'rb' (as in the example inference notebook).

Using python 3.5 with tensorflow 1.6

**Comment by tensorflowbutler** [comment] 2018-04-25 06:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment] 2018-12-05 21:40
Closing this issue since the fix has already been pushed. Feel free to reopen the issue if the problem still persists. Thanks!

**Closed by ymodak** 2018-12-05 21:40 UTC
Labels: stat:awaiting response
