### ISSUE TITLE
Tensorflow traning gets stuck

### ISSUE THREAD

**Issue by koresaram777** [tensorflow/models#7853] opened 2019-11-22 00:49 UTC
![tf_stuck](https://user-images.githubusercontent.com/33024266/69388672-1538c780-0d0d-11ea-9925-fd615e3e0569.PNG)

![tf_stuck2](https://user-images.githubusercontent.com/33024266/69390588-153bc600-0d13-11ea-8d67-213511a5ebec.PNG)

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Microsoft windows 10 x64
- **TensorFlow version (use command below)**: 1.14
- **CUDA/cuDNN version**: 10.0/7.6
- **GPU model and memory**: Leadtek RTX 2080 Ti Classic 11GB
- **Exact command to reproduce**: just runned train.py file with small modifications

The training just gets stuck. I have tried different versions of tensorflow but it doesn't work. Before it worked but I used GTX 1080 Ti graphic card and everything was ok, so does anybody have the same problem and how have you solved it?

**Comment by zilingzhang** [comment] 2019-11-22 17:44
I experienced similar training stuck in windows, it happens randomly, sometimes a few steps are printed, sometimes stuck at the first step. Exact same code was running fine 3 months ago, and run fine on ubuntu 18.04 on the same machine.
System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft windows 10 x64
TensorFlow version (use command below): 1.13~1.15
CUDA/cuDNN version: 10.0/7.6
GPU model and memory: RTX Titan 24GB
Exact command to reproduce: train.py from deeplab v3+ model

**Comment by koresaram777** [comment] 2019-11-23 00:09
I think that the problem is in gpu architecture. I suppose that turing architecture is not stable enough...

**Comment by Renjiewu** [comment] 2019-12-03 12:25
It seems to be a driver issue.I have a similar training problem on windows with titan rtx.And I fix it using 431.60.

**Comment by dgrechka** [comment] 2020-02-26 21:08
I have the training randomly stuck on windows 10, tensorflow 2.1.0, cuDNN 10.1, 7.6.5.32

I'm using GeForce 1050 Ti

use keras model Fit call.

Depends on the batch size. on smaller batch size hangs on the first several training steps.
On larger batch size hangs after ~1000 iterations.

Tried to downgrade to TF 2.0, cuDNN 10.0/7.6.0. The same. It hangs. 1 CPU core is busy. GPU utilization is zero. Training steps do not proceed.

**Comment by dgrechka** [comment] 2020-03-04 15:26
I've checked the code on GTX 1070, GTX 1050 Ti, Quadro P5000 (different GPUs on different machines).
Hangs everywhere.
On all three machines the setup is:
* windows 10 64 bit
* python 3.6
* TF 2.1
* cuDNN 10.1 / 7.6.5.32

I use DataSet API to feed the data.
When I enumerate the dataset manualy (without keras model fit() call) with as_numpy_iterator() it enumerates normally.
When I feed the dataset to the fit() method, it hangs.

I suspect there can be a kind of deadlock?

**Comment by dgrechka** [comment] 2020-03-04 16:13
Running the same fit with "tensorflow-cpu" pip package (v2.1.0) installed of "tensorflow" works well.
Thus that's connected somehow with feeding the data to GPU?

**Comment by dgrechka** [comment] 2020-03-04 19:55
If I set
`tf.config.experimental.set_device_policy('warn')`
I get lots of messages:
```
2020-03-04 22:52:47.624485: W tensorflow/core/common_runtime/eager/execute.cc:171] before computing Cast input #0 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0). This triggers a copy which can be a performance bottleneck.
2020-03-04 22:52:47.645579: W tensorflow/core/common_runtime/eager/execute.cc:171] before computing Cast input #0 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0). This triggers a copy which can be a performance bottleneck.
2020-03-04 22:52:47.671166: W tensorflow/core/common_runtime/eager/execute.cc:171] before computing Cast input #0 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0). This triggers a copy which can be a performance bottleneck.
2020-03-04 22:52:47.696761: W tensorflow/core/common_runtime/eager/execute.cc:171] before computing Cast input #0 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0). This triggers a copy which can be a performance bottleneck.
2020-03-04 22:52:47.723054: W tensorflow/core/common_runtime/eager/execute.cc:171] before computing Cast input #0 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0). This triggers a copy which can be a performance bottleneck.
```

Can it be the bottleneck that looks like hanging?

**Comment by dgrechka** [comment] 2020-03-04 21:06
I've found the workaround for the issue by disabling eager execution.

e.g.
```
tf.compat.v1.disable_eager_execution()
```

Seems that somehow eager execution placed tensors in a inefficient way. So everything seemed to hung.

**Comment by basarkutukcu** [comment] 2020-03-08 12:14
I also had the problem and solved it by updating the nvidia driver.

**Comment by amarsinghen** [comment] 2020-06-06 04:52
Tensorflow also froze/stuck on me while I was running DELF on large set of images (google-landmark-recognition, ~4 million images). Seems like tensorflow in general has this bug.

Anyways, I also resolved the issue by updating to latest nvidia drivers. I have RTX 2080 TI. 
I also updated to latest Tensorflow version.

**Comment by ravikyram** [comment] 2020-06-19 08:08
@koresaram777 

Is this still an issue?. Please close this thread if your issue was resolved.Thanks!

**Closed** 2020-06-19 08:13 UTC
Labels: type:support

**Comment by PengchengFan** [comment] 2020-12-04 13:10
so how to solve this?

**Comment by kevsieb** [comment] 2021-07-07 19:53
I just come to share my solution regarding this issue. 

I experienced the same behavior, the training being stuck, frozen, after several epochs, without any error.
After digging, it appeared the problem did not come from the training but from the evaluation step, (using model.evaluate() from keras) that follows right after. The test dataset, provided by a generator, was actually an empty list. No warning or error showed up though, the generator yielding endlessly an empty list of batches. I guess the .evaluate() function was just endlessly waiting for the first batch to come.

I hope this may help some crossing this comment.
