### ISSUE TITLE
object_detection: Op type not registered 'TFLite_Detection_PostProcess' while trying tf.import_graph_def

### ISSUE THREAD

**Issue by kate-kate** [tensorflow/models#5277] opened 2018-09-10 12:06 UTC
Hello everyone. I've trained ```ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03``` model with custom data. Then I've created frozen_graph with 
```
python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path=$CONFIG_FILE \
--trained_checkpoint_prefix=$CHECKPOINT_PATH \
--output_directory=$OUTPUT_DIR \
--add_postprocessing_op=true
```
command. It run without any errors. Also I've trained ```ssd_mobilenet_v1_coco``` with custom data and exported it same way before. In both cases I used tensorflow 1.10

The problem I the following: when I'm trying to run ```tf.import_graph_def()``` (for example in ```object_detection_tutorial.ipynb```) function with retrained ```ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03``` model there is an error:
```
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'TFLite_Detection_PostProcess' in binary running on MacBook-Pro-Ekaterina.local. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```
same in other project
<img width="1280" alt="2018-09-10 12 39 50" src="https://user-images.githubusercontent.com/4061805/45296534-05b7cf00-b50b-11e8-9aca-c17c1233432b.png">

And there is no any information about which ```tf.contrib``` ops should be imported in this case. Also when I'm trying to use export script without postprocess operations option (set it to false). I've got another error then:
```
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist.
```

In the same time with ```ssd_mobilenet_v1_coco``` everything works well. 
The worst thing is that because of error with building tensorflow android tflite demo, I should retrieve the results of this model detection at least with python. And all examples using ```tf.import_graph_def()``` function, even in [GCP detection API demo app](https://github.com/GoogleCloudPlatform/tensorflow-object-detection-example).

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra 10.13.4
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: 0.15.2-homebrew
- **GPU model and memory**: Intel Iris Graphics 6100 / 1536 MB

**Comment by tensorflowbutler** [comment] 2018-09-10 19:33
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
CUDA/cuDNN version
Exact command to reproduce

**Comment by kate-kate** [comment] 2018-09-11 08:01
**CUDA/cuDNN version:** I use CPU-only tensorflow version
**Exact command to reproduce:** ```tf.import_graph_def()``` with ```ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03``` frozen graph retrieved by 
```
python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path=$CONFIG_FILE \
--trained_checkpoint_prefix=$CHECKPOINT_PATH \
--output_directory=$OUTPUT_DIR \
--add_postprocessing_op=true
```

**top-level directory of the model** sorry, can't get what you mean....

**Comment by zishanahmed08** [comment] 2018-09-20 13:29
@achowdhery Akansha, I face the same issue while running **tflite_convert** for converting the frozen graph exported by **export_tflite_ssd_graph.py**
```
tflite_convert \
> --graph_def_file=$OUTPUT_DIR/tflite_graph.pb \
> --output_file=$OUTPUT_DIR/detect.tflite \
> --input_shapes=1,300,300,3 \
> --input_arrays=normalized_input_image_tensor \
> --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
> --inference_type=QUANTIZED_UINT8 \
> --mean_values=128 \
> --std_dev_values=128 \
> --allow_custom_ops
```

**Comment by xrz000** [comment] 2018-09-21 02:16
@zishanahmed08 I had the same issue when I tried to convert my trained ssd_mobilenet_v1 model to .tflite format. I was using **tf.1.10** and **tflite_convert**. My problem was solved after pulling the latest code of tensorflow, upgrading to tf1.11 and running 
``` bash
bazel run -c opt tensorflow/contrib/lite/toco:toco -- \
--input_file=$MODEL_DIR/tflite_graph.pb \
--output_file=$MODEL_DIR/detect.tflite \
--input_shapes=1,192,192,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_dev_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops
```
@kate-kate Maybe the reason for "Op type not registered" error is that "TFLite_Detection_PostProcess" is a custom op, and you can only use it with a tflite interpreter. If you want to test your model without building demo app, I think you can try to convert your .pb file to .tflite format and use [TensorFlow Lite Python interpreter ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/python_api.md)

**Comment by kate-kate** [comment] 2018-09-21 05:29
@xrz000 Nice advice, thank you! Will try

**Comment by zishanahmed08** [comment] 2018-09-21 07:19
Thanks @xrz000 Upgrading to 1.11 did work for me too.

**Comment by wt-huang** [comment] 2018-11-03 00:55
Closing as this is resolved

**Closed by wt-huang** 2018-11-03 00:55 UTC

**Comment by jyotirmayghosh** [comment] 2019-04-19 09:54
hey, 
@achowdhery @xrz000 , I face the same issue while running tflite_convert for converting the frozen graph exported by export_tflite_ssd_graph.py

```
tflite_convert \
> --graph_def_file=$OUTPUT_DIR/tflite_graph.pb \
> --output_file=$OUTPUT_DIR/detect.tflite \
> --input_shapes=1,300,300,3 \
> --input_arrays=normalized_input_image_tensor \
> --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
> --inference_type=QUANTIZED_UINT8 \
> --allow_custom_ops
```

I described the detail log [here](https://github.com/tensorflow/tensorflow/issues/27953). Can you please provide any suggestion?
