### ISSUE TITLE
google.protobuf.text_format.ParseError: 143:26 : Message type "object_detection.protos.RMSPropOptimizer" has no field named "https".

### ISSUE THREAD

**Issue by saras0505** [tensorflow/models#7782] opened 2019-11-11 15:26 UTC
Ubuntu 18.04, Alienware, Nvidia RTX2080 Ti
When running this code, i got the errors below
python3 model_main.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

Traceback (most recent call last):
  File "model_main.py", line 109, in <module>
    tf.app.run()
  File "/home/arr/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py", line 605, in create_estimator_and_inputs
    pipeline_config_path, config_override=config_override)
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/utils/config_util.py", line 104, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 693, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 760, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 785, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 807, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 932, in _MergeField
    merger(tokenizer, message, field)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1006, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 932, in _MergeField
    merger(tokenizer, message, field)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1006, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 932, in _MergeField
    merger(tokenizer, message, field)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1006, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/arr/.local/lib/python3.6/site-packages/google/protobuf/text_format.py", line 899, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 143:26 : Message type "object_detection.protos.RMSPropOptimizer" has no field named "https".

**Comment by tensorflowbutler** [comment] 2019-11-12 12:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-19 11:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-19 11:27 UTC
Labels: models:research, stat:awaiting response, type:support
