### ISSUE TITLE
[Syntaxnet]Bazel test failure -> ParseyMcParseface unusable due to error type_name: tensorflow::Tensor already registered

### ISSUE THREAD

**Issue by AyushiAggarwal** [tensorflow/models#2355] opened 2017-09-07 17:39 UTC
### System information
- **What is the top-level directory of the model you are using**: models/syntaxnet
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution**: tried for CentOS 6/7 VMs and Ubuntu 14.04 LTS(through virtual box)
- **Bazel version (if compiling from source)**: 0.5.4
- **GPU memory**: 8GB with 4vCPUs
- **Exact command to reproduce**: ```bazel test --linkopt=-lrt syntaxnet/... util/utf8/...```

### Problem:
I have tried installing Syntaxnet to run ParseyMcParseface on CentOS 6/7 and Ubuntu 14.04 LTS and was stuck with the same error(described below).
I followed the instructions for manual installation of syntaxnet given at https://github.com/tensorflow/models/tree/master/syntaxnet and ran the bazel test using the following command: 
```bazel test --linkopt=-lrt syntaxnet/... util/utf8/...```

**Console output:**
Executed 25 out of 25 tests: 19 tests pass and 6 fail locally 

**Screenshot of tests that failed is given below:**

![image](https://user-images.githubusercontent.com/6222373/30131797-ef6ffdd8-9302-11e7-91f6-ca8034190a55.png)

**Log File**
For each of the failures, the **test.log** file shows the following error: 
F external/org_tensorflow/tensorflow/core/framework/variant_op_registry.cc:79] Check failed: existing == nullptr (0x10a0f30 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered
Aborted

1. Is there an issue with the installation process described in the README given at https://github.com/tensorflow/models/tree/master/syntaxnet?
2. It appears that the "tensorflow" type_name is not generated as expected. Could this be an issue with generation of this type_name during the build process? If so, could you provide a fix since this is **rendering ParseyMcParseface unusable** as of now.
3. If someone is able to install and successfully run ParseyMcParseface with the current master branch of SyntaxNet or in any other way, please let me know.

Struggled with this for days now and any help/fix would be appreciated.
Nothing found on the bazel stackoverflow channel.

**Comment by charlesjohannisen** [comment] 2017-09-09 18:42
Got the exact failures. Found the commit where this change was made to tensorflow.
Slight ( very temporary and janky ) workaround, after you've git cloned models:
`cd models/syntaxnet/tensorflow/tensorflow`
`git checkout 712fcfc6e364e6ca39cee3d988089e51f73d1e65` - which is before [this commit](https://github.com/tensorflow/tensorflow/commit/2f6f329aac6e4f23ef20f6e37165a235e232e772)
`nano models/syntaxnet/tensorflow/tensorflow/core/platform/default/mutex.h`
change this:
`#include "nsync_cv.h"`
`#include "nsync_mu.h"`
to this:
`#include "../nsync/public/nsync_cv.h"`
`#include "../nsync/public/nsync_mu.h"`
The workaround doesn't solve the problem completely, since the last test still fails for me.
But ParseyMcParseface ( `/opt/tensorflow/syntaxnet/syntaxnet/demo.sh` ) works at least for the purposes of my project.

**Comment by ebrevdo** [comment] 2017-09-11 19:01
This is caused by a new feature, the variant op registrar, being called more than once. Perhaps framework/tensor.cc is being linked in or compiled multiple times?

**Comment by AyushiAggarwal** [comment] 2017-09-11 22:34
@charlesjohannisen - This seems to have eliminated the error. However, my bazel test now fails with a new error - ImportError: No module named autograd found. 

**Log file**:
![image](https://user-images.githubusercontent.com/6222373/30299602-4a51746a-9705-11e7-97c0-3b7795d15b78.png)

**Console output:**
Executed 25 out of 25 tests: 19 tests pass and 6 fail locally

**Screenshot of tests that failed is given below:**
![image](https://user-images.githubusercontent.com/6222373/30299804-49da131a-9706-11e7-8af8-532177f47f9d.png)

This is still an ops issue. Anyone know how this can be handled?

**Comment by charlesjohannisen** [comment] 2017-09-12 04:16
`sudo apt install gfortran`
then
`python -m pip install autograd`
should fix the last issue. Hopefully getting you back on track.

**Comment by AyushiAggarwal** [comment] 2017-09-12 23:57
@charlesjohannisen Yes, that solved the issue! Thanks! 

Also had to install ```enum``` and ```enum34```
bazel test ran fine: 
![25 tests pass](https://user-images.githubusercontent.com/6222373/30347648-9f818260-97c1-11e7-9b6f-79f17ddf5285.PNG)

**Comment by rekcahd** [comment] 2017-09-26 17:38
Looks like this fix doesn't work after restructure of repo. Will it be fixed?

**Comment by cernerae** [comment] 2017-10-05 00:31
Same issue. And like @rekcahd said, the file fix doesn't work after the directory structure was changed. I guess within the last month

**Comment by rfeldercyc** [comment] 2017-10-11 16:16
I am also experiencing this issue.

**Comment by JohanWu** [comment] 2017-10-12 22:45
same issue here.

**Comment by raguhari** [comment] 2017-10-22 19:25
Same problem. Any updates on issue status?

**Comment by jsgreenawalt** [comment] 2017-10-22 23:11
Another "me too" here.

**Comment by jsgreenawalt** [comment] 2017-10-23 03:30
Adding a new hacky workaround -- open up /models/research/syntaxnet/tensorflow/tensorflow/core/framework/variant_op_registry.cc
Search for all lines matching "CHECK_EQ(existing, nullptr)" -- comment them out and replace with 
'if (existing == nullptr)'
 (just before the whatever.insert calls), like so:
`
  // comment out these 3 lines
  //CHECK_EQ(existing, nullptr)
  //    << "Unary VariantShapeFn for type_name: " << type_name
  //    << " already registered";
  // add this line
  if (existing == nullptr)
  // the original insert call below is left alone in each method, but now only called when existing is 
  // a null pointer, which prevents the abort/exit
  shape_fns.insert(std::pair<StringPiece, VariantShapeFn>(
      GetPersistentStringPiece(type_name), shape_fn));
`
Do this wherever you find `CHECK_EQ(existing, nullptr)`

**Comment by GelRa** [comment] 2017-10-23 14:58
I managed to build and test without errors. To do this I just commented 
CHECK_EQ(existing, nullptr) in:  RegisterShapeFn, RegisterDecodeFn, RegisterUnaryOpFn, RegisterBinaryOpFn

Furthermore I had to install the python package:
apt-get install graphviz libgraphviz-dev
pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"

Strangely I hat to modify syntaxnet/dragnn/python/component.py
In: def build_greedy_training(self, state, network_states):
from:
    with tf.control_dependencies([tf.assert_equal(self.training_beam_size, 1)]):
      stride = state.current_batch_size * self.training_beam_size
to:
    val = tf.Print(self.training_beam_size, [ self.training_beam_size ], "Fix for access bug. Correct value:  ")
    with tf.control_dependencies([tf.assert_equal(val, 1)]):
      stride = state.current_batch_size * self.training_beam_size

Just adding the print command fixes the error. Without the print the value of self.training_beam_size seems to be 8 but is 1 in truth. The print convinces the system to use the correct vale. Very very strange.

**Comment by devnullnor** [comment] 2017-10-23 17:01
With @charlesjohannisen and @GelRa's solution, all bazel tests are success for me on Ubuntu 16.04 now.

**Comment by asimshankar** [comment] 2017-11-03 07:13
@calberti @andorardo @bogatyy @markomernick - Mind taking a look to make the appropriate fix?

**Comment by ebrevdo** [comment] 2017-11-03 17:04
I wonder if we can just remove the tensor decoder registration in TF
proper.  I'm not sure if it's used for anything other than testing right
now. However it would be good to fix this in parsey as well.

**Comment by bogatyy** [comment] 2017-11-09 19:50
Thank you for reporting the issue in detail and looking at the possible workarounds. We are working on this.

**Comment by bogatyy** [comment] 2017-11-14 19:01
Could you try again? While a longer-term solution is not ready, we have a fix out.

More specifically, synced the TF subrepo to a version before the registration mechanism.
Right now, SyntaxNet should build with Bazel 0.5.4 (this is mentioned in the README as well).

**Comment by SaintNazaire** [comment] 2017-11-17 16:28
Roger that, seen updated readme a couple minutes ago, work in progress please stand-by.

**Comment by bogatyy** [comment] 2017-11-22 22:47
@SaintNazaire you need to install a compatible version of autograd, as explained in the README:
`pip install autograd==1.1.13`

Let me know if that works (also, again, make sure you have Bazel 0.5.4)

**Comment by SaintNazaire** [comment] 2017-11-23 14:36
Works. Fully tested docker file for your reference:

```
FROM ubuntu:16.04

LABEL maintainer="SaintNazaire<SaintNazaire@users.noreply.github.com>"

ENV PYTHON_BIN_PATH=/usr/bin/python
ENV PYTHON_LIB_PATH=/usr/lib/python2.7
ENV BAZEL_VERSION=0.5.4

RUN apt-get update && echo yes | apt-get upgrade && apt-get install -y --no-install-recommends \
	apt-utils \
	bash-completion \
        build-essential \
        curl \
	g++ \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
	openjdk-8-jdk \
	pkg-config \
        python \
        python-dev \
	python-enum34 \
	rsync \
        software-properties-common \
	sudo \
	swig \
        unzip \
	zip \
	zlib1g-dev \
        && \
	rm -rf /var/lib/apt/lists/*

RUN apt-get autoclean && apt-get clean

RUN update-ca-certificates -f

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN apt-get install -y --no-install-recommends \
    && curl -LO "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb" \
    && dpkg -i bazel_*.deb

RUN apt-get update && apt-get install -y --no-install-recommends swig
RUN pip --no-cache-dir install \
        protobuf==3.3.0 \
        mock \
        asciitree \
	numpy \
	autograd==1.1.13 \
    && apt-get clean && \
    rm /var/lib/apt/lists/*_*

RUN apt-get update && apt-get install -y --no-install-recommends graphviz libgraphviz-dev \
        git

RUN pip --no-cache-dir install \
        pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"

RUN pip install tensorflow

RUN git clone --recursive https://github.com/tensorflow/models.git
RUN cd /models/research/syntaxnet/tensorflow && echo yes | ./configure
RUN cd /models/research/syntaxnet && bazel build ... --genrule_strategy=standalone --spawn_strategy=standalone

RUN mkdir /tmp/syntaxnet_pkg
RUN /models/research/syntaxnet/bazel-bin/dragnn/tools/build_pip_package --output-dir=/tmp/syntaxnet_pkg
RUN pip install /tmp/syntaxnet_pkg/syntaxnet-0.2-cp27-cp27mu-linux_x86_64.whl
RUN apt-get autoclean && apt-get clean

```

**Comment by bogatyy** [comment] 2017-11-25 02:18
Great to hear, closing the issue then.

**Closed by bogatyy** 2017-11-25 02:18 UTC
Labels: stat:awaiting tensorflower

**Comment by qiaohaijun** [comment] 2018-05-24 12:16
Same problem!

**Comment by matthewstidham** [comment] 2018-12-15 22:58
> I managed to build and test without errors. To do this I just commented
> CHECK_EQ(existing, nullptr) in: RegisterShapeFn, RegisterDecodeFn, RegisterUnaryOpFn, RegisterBinaryOpFn
> 
> Furthermore I had to install the python package:
> apt-get install graphviz libgraphviz-dev
> pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
> 
> Strangely I hat to modify syntaxnet/dragnn/python/component.py
> In: def build_greedy_training(self, state, network_states):
> from:
> with tf.control_dependencies([tf.assert_equal(self.training_beam_size, 1)]):
> stride = state.current_batch_size * self.training_beam_size
> to:
> val = tf.Print(self.training_beam_size, [ self.training_beam_size ], "Fix for access bug. Correct value: ")
> with tf.control_dependencies([tf.assert_equal(val, 1)]):
> stride = state.current_batch_size * self.training_beam_size
> 
> Just adding the print command fixes the error. Without the print the value of self.training_beam_size seems to be 8 but is 1 in truth. The print convinces the system to use the correct vale. Very very strange.
> EDIT 1:
> Here is the diff-file:
> [models_diff.txt](https://github.com/tensorflow/models/files/1408061/models_diff.txt)
> 
> EDIT 2:
> Just a hint for the guys wanting to really fix the problem with CHECK_EQ()
> models/research/syntaxnet/tensorflow/tensorflow/core/framework/tensor.cc registers statically
> REGISTER_UNARY_VARIANT_DECODE_FUNCTION(Tensor, "tensorflow::Tensor");
> models/research/syntaxnet/tensorflow/tensorflow/core/framework/variant_op_registry.cc registers statically
> REGISTER_VARIANT_SHAPE_TYPE(int); ... etc.
> 
> both codes are included in _pywrap_tensorflow_internal.so and at least partly in parser_ops.so
> During test _pywrap_tensorflow_internal.so is initialed by _PyImport_LoadDynamicModule and by tensorflow::LoadLibrary
> So the static code is run twice causing the error. As far as I can see it, commenting the CHECK_EQ does not cause any harm in this case, due to the nature of this registration.
> I think the solution would be moving the static code to a different location not to be executed twice or changing the bazel build scrips not to include the same code in two different shared libraries.
> 
> The problem with syntaxnet/dragnn/python/component.py seems to me to be to be a serious problem inside the tensorflow core or with the python to c++ connection. Happy to learn any better explanation.

This fixed my problem, thanks!
