### ISSUE TITLE
when i use more than one gpu there is something wrong with flowers_train.py

### ISSUE THREAD

**Issue by youngjt** [tensorflow/models#883] opened 2017-01-11 02:26 UTC
bazel-bin/inception/flowers_train \
   --train_dir="${TRAIN_DIR}" \
   --data_dir="${FLOWERS_DATA_DIR}" \
   --pretrained_model_checkpoint_path="${MODEL_PATH}" \
   --fine_tune=True \
   --initial_learning_rate=0.001 \
   --input_queue_memory_factor=1 \
   --max_steps=100 \
   --num_gpus=4

the error info is:
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
Traceback (most recent call last):
File "/data0/yangjiangtao/tf-model/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_        train.py", line 41, in <module>
tf.app.run()
File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
sys.exit(main(sys.argv[:1] + flags_passthrough))
File "/data0/yangjiangtao/tf-model/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/flowers_        train.py", line 37, in main
inception_train.train(dataset)
File "/data0/yangjiangtao/tf-model/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inceptio        n_train.py", line 239, in train
scope)
File "/data0/yangjiangtao/tf-model/models/inception/bazel-bin/inception/flowers_train.runfiles/inception/inception/inceptio        n_train.py", line 124, in _tower_loss
loss_averages_op = loss_averages.apply(losses + [total_loss])
File "/usr/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
self._averages[var], var, decay, zero_debias=zero_debias))
File "/usr/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
update_delta = _zero_debias(variable, value, decay)
 File "/usr/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
trainable=False)
File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
custom_getter=custom_getter)
File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
custom_getter=custom_getter)
File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
validate_shape=validate_shape)
File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
caching_device=caching_device, validate_shape=validate_shape)
File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
"VarScope?" % name)
ValueError: Variable tower_1/tower_1/CrossEntropyLoss/value/avg/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by youngjt** [comment] 2017-01-11 02:52
i do not think the flowers_train.py uses the gpu when i run it.  Some set is:
bazel-bin/inception/flowers_train \
   --train_dir="${TRAIN_DIR}" \
   --data_dir="${FLOWERS_DATA_DIR}" \
   --pretrained_model_checkpoint_path="${MODEL_PATH}" \
   --fine_tune=True \
   --initial_learning_rate=0.001 \
   --input_queue_memory_factor=1 \
   --max_steps=100 \
   --num_gpus=1
Look at the picture below：
![flower_train](https://cloud.githubusercontent.com/assets/1442847/21833254/d638fcb6-d7eb-11e6-852d-a35eca30d9f6.png)

**Comment by jart** [comment] 2017-01-11 05:47
Is it possible this is a duplicate of https://github.com/tensorflow/tensorflow/issues/6761?

**Comment by youngjt** [comment] 2017-01-11 06:27
my version of tensorflow  is 0.12.0-rc1.

**Comment by jart** [comment] 2017-01-11 06:48
@alexalemi has done some work on the inception_train.py file in the past. Perhaps he would be kind enough to take a look?

**Comment by alexalemi** [comment] 2017-01-11 20:42
I'll try this myself later today, but perhaps you could try to build with

`blaze build -c opt --config=cuda inception/download_and_preprocess_flowers`

Also, you should start migrating over to tensorflow/models/slim/nets, which is the more current version of the preprocessing example, [here](https://github.com/tensorflow/models/tree/master/slim#fine-tuning-a-model-from-an-existing-checkpoint)

**Comment by alexalemi** [comment] 2017-01-11 23:40
Alright, so I managed to try this myself.  Using a clean install of 0.12.1 and using `blaze build -c opt nception/download_and_preprocess_flowers` my pretraining script used the GPU.  I would suggest you recheck that you installed the GPU version of tensorflow.

**Comment by youngjt** [comment] 2017-01-12 05:26
I have Used the following commands：
blaze build **-c opt --config=cuda** inception/flowers_train
MODEL_PATH=xxxxx/inception/inception-v3-model/inception-v3/model.ckpt-157585
FLOWERS_DATA_DIR=xxxxx/inception/inception/flowers-data/
TRAIN_DIR=xxxxx/inception/inception/flowers_train/
bazel-bin/inception/flowers_train \
  --train_dir="${TRAIN_DIR}" \
  --data_dir="${FLOWERS_DATA_DIR}" \
  --pretrained_model_checkpoint_path="${MODEL_PATH}" \
  --fine_tune=True \
  --initial_learning_rate=0.001 \
  --input_queue_memory_factor=1 \
  --max_steps=100 \
  --num_gpus=1

When it runs, the info of gpus is:
![tl](https://cloud.githubusercontent.com/assets/1442847/21878080/a5d8ea88-d8ca-11e6-9be2-080f49fa7d4d.png)

**Comment by jart** [comment] 2017-01-13 08:29
It's possible that this might be a configuration issue because I'm not seeing strong information indicating a bug that actionable on the part of TensorFlow. If you need help troubleshooting, please consider [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Otherwise, please provide more information on how this is actionable on our part, and I'll re-open this issue.

**Closed by jart** 2017-01-13 08:29 UTC
Labels: type:support
