### ISSUE TITLE
InvalidArgumentError: Index out of range using input dim 1; input has only 1 dims [Op:StridedSlice] name: strided_slice/

### ISSUE THREAD

**Issue by AliButtar** [tensorflow/models#9255] opened 2020-09-16 13:48 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [X] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [X] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using
* The notebook: [Object Detection Tutorial Notebook](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb)

* The model used: http://download.tensorflow.org/models/object_detection/tf2/20200711/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8.tar.gz

* The colab notebook that uses the same notebook and the model: [Colab Object Detection Tutorial Copy](https://colab.research.google.com/drive/1OUkIWVpaEnDaZL81Kmm2Jp5xd4fu45pK?usp=sharing)

## 2. Describe the bug
**Error Name** : InvalidArgumentError

**Error Description** : Index out of range using input dim 1; input has only 1 dims [Op:StridedSlice] name: strided_slice/

The code in the [Object Detection Tutorial Notebook](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) successfully infers using object detection models but fails to infer using using Mask RCNN Inception Model and causes the above error. 

## 3. Steps to reproduce
Run the following Colab Notebook. It is same as the Object Detection Tutorial but is instead using Mask RCNN Inception Resnet v2 1024x1204 model. 

[Colab Object Detection Tutorial Copy](https://colab.research.google.com/drive/1OUkIWVpaEnDaZL81Kmm2Jp5xd4fu45pK?usp=sharing)

## 4. Expected behavior
Segmentation on the test images same the as the object detection on the test images in the notebook 

## 5. Additional context

The notebook crashes on the default segmentation model used in the [Object Detection Tutorial Notebook](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) as well also models that have been further trained to segment or detect other objects

## 6. System information

All the work done was on Colab with GPU enabled

**Comment by ravikyram** [comment] 2020-09-17 07:03
I have tried in colab with Tf version 2.3 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/39ad875e660428abe0aae1bc52b9980a/untitled368.ipynb). Thanks!

**Comment by jersonal** [comment] 2020-09-24 01:25
i get the same Error,did you solve this Error？

**Comment by jersonal** [comment] 2020-09-24 02:41
> i get the same Error,did you solve this Error？

i solved it. it because 'image_shape' and 'num_proposals' node are  the parameters that needs to be feed.so dont use them,and convert to tensor

**Comment by AliButtar** [comment] 2020-09-24 11:17
> > i get the same Error,did you solve this Error？
> 
> i solved it. it because 'image_shape' and 'num_proposals' node are the parameters that needs to be feed.so dont use them,and convert to tensor

Can you go into a little more detail, and share the solution perhaps. It will help a lot. Thanks

**Comment by jersonal** [comment] 2020-09-25 02:54
> > > i get the same Error,did you solve this Error？
> > 
> > 
> > i solved it. it because 'image_shape' and 'num_proposals' node are the parameters that needs to be feed.so dont use them,and convert to tensor
> 
> Can you go into a little more detail, and share the solution perhaps. It will help a lot. Thanks

Change "run_inference_for_single_image" function

>`def run_inference_for_single_image(model, image):
    image = np.asarray(image)
    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]

    # Run inference
    model_fn = model.signatures['serving_default']
    output_dict = model_fn(input_tensor)
    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(output_dict.pop('num_detections'))
    need_detection_key = ['detection_classes','detection_boxes','detection_masks','detection_scores']
    output_dict = {key: output_dict[key][0, :num_detections].numpy()
                   for key in need_detection_key}
    output_dict['num_detections'] = num_detections
    # detection_classes should be ints.
    output_dict['detection_classes'] = output_dict['detection_classes'].astype(np.int64)
    # Handle models with masks:
    if 'detection_masks' in output_dict:
        # Reframe the the bbox mask to the image size.
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            tf.convert_to_tensor(output_dict['detection_masks']), output_dict['detection_boxes'],
            image.shape[0], image.shape[1])
        detection_masks_reframed = tf.cast(detection_masks_reframed > 0.5,
                                           tf.uint8)
        output_dict['detection_masks_reframed'] = detection_masks_reframed.numpy()

    return output_dict`

**Comment by jersonal** [comment] 2020-09-25 02:57
`def run_inference_for_single_image(model, image):
    image = np.asarray(image)
    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]

    # Run inference
    model_fn = model.signatures['serving_default']
    output_dict = model_fn(input_tensor)
    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(output_dict.pop('num_detections'))
    need_detection_key = ['detection_classes','detection_boxes','detection_masks','detection_scores']
    output_dict = {key: output_dict[key][0, :num_detections].numpy()
                   for key in need_detection_key}
    output_dict['num_detections'] = num_detections
    # detection_classes should be ints.
    output_dict['detection_classes'] = output_dict['detection_classes'].astype(np.int64)
    # Handle models with masks:
    if 'detection_masks' in output_dict:
        # Reframe the the bbox mask to the image size.
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            tf.convert_to_tensor(output_dict['detection_masks']), output_dict['detection_boxes'],
            image.shape[0], image.shape[1])
        detection_masks_reframed = tf.cast(detection_masks_reframed > 0.5,
                                           tf.uint8)
        output_dict['detection_masks_reframed'] = detection_masks_reframed.numpy()

    return output_dict`

**Comment by jersonal** [comment] 2020-09-25 02:59
> > > i get the same Error,did you solve this Error？
> > 
> > 
> > i solved it. it because 'image_shape' and 'num_proposals' node are the parameters that needs to be feed.so dont use them,and convert to tensor
> 
> Can you go into a little more detail, and share the solution perhaps. It will help a lot. Thanks

> Change "run_inference_for_single_image" function

> `def run_inference_for_single_image(model, image):
    image = np.asarray(image)
    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]
    # Run inference
    model_fn = model.signatures['serving_default']
    output_dict = model_fn(input_tensor)
    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(output_dict.pop('num_detections'))
    need_detection_key = ['detection_classes','detection_boxes','detection_masks','detection_scores']
    output_dict = {key: output_dict[key][0, :num_detections].numpy()
                   for key in need_detection_key}
    output_dict['num_detections'] = num_detections
    # detection_classes should be ints.
    output_dict['detection_classes'] = output_dict['detection_classes'].astype(np.int64)
    # Handle models with masks:
    if 'detection_masks' in output_dict:
        # Reframe the the bbox mask to the image size.
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            tf.convert_to_tensor(output_dict['detection_masks']), output_dict['detection_boxes'],
            image.shape[0], image.shape[1])
        detection_masks_reframed = tf.cast(detection_masks_reframed > 0.5,
                                           tf.uint8)
        output_dict['detection_masks_reframed'] = detection_masks_reframed.numpy()

    return output_dict`

**Comment by jersonal** [comment] 2020-09-25 03:02
> > > i get the same Error,did you solve this Error？
> > 
> > 
> > i solved it. it because 'image_shape' and 'num_proposals' node are the parameters that needs to be feed.so dont use them,and convert to tensor
> 
> Can you go into a little more detail, and share the solution perhaps. It will help a lot. Thanks

> Change "run_inference_for_single_image" function
`def run_inference_for_single_image(model, image):
    
    image = np.asarray(image)
    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]
    # Run inference
    model_fn = model.signatures['serving_default']
    output_dict = model_fn(input_tensor)
    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(output_dict.pop('num_detections'))
    need_detection_key = ['detection_classes','detection_boxes','detection_masks','detection_scores']
    output_dict = {key: output_dict[key][0, :num_detections].numpy()
                   for key in need_detection_key}
    output_dict['num_detections'] = num_detections
    # detection_classes should be ints.
    output_dict['detection_classes'] = output_dict['detection_classes'].astype(np.int64)
    # Handle models with masks:
    if 'detection_masks' in output_dict:
        # Reframe the the bbox mask to the image size.
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            tf.convert_to_tensor(output_dict['detection_masks']), output_dict['detection_boxes'],
            image.shape[0], image.shape[1])
        detection_masks_reframed = tf.cast(detection_masks_reframed > 0.5,
                                           tf.uint8)
        output_dict['detection_masks_reframed'] = detection_masks_reframed.numpy()

    return output_dict
`

**Comment by AliButtar** [comment] 2020-09-25 09:14
> > > > i get the same Error,did you solve this Error？
> > > 
> > > 
> > > i solved it. it because 'image_shape' and 'num_proposals' node are the parameters that needs to be feed.so dont use them,and convert to tensor
> > 
> > 
> > Can you go into a little more detail, and share the solution perhaps. It will help a lot. Thanks
> 
> > Change "run_inference_for_single_image" function
> > `def run_inference_for_single_image(model, image):
> 
> ```
> image = np.asarray(image)
> # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
> input_tensor = tf.convert_to_tensor(image)
> # The model expects a batch of images, so add an axis with `tf.newaxis`.
> input_tensor = input_tensor[tf.newaxis, ...]
> # Run inference
> model_fn = model.signatures['serving_default']
> output_dict = model_fn(input_tensor)
> # All outputs are batches tensors.
> # Convert to numpy arrays, and take index [0] to remove the batch dimension.
> # We're only interested in the first num_detections.
> num_detections = int(output_dict.pop('num_detections'))
> need_detection_key = ['detection_classes','detection_boxes','detection_masks','detection_scores']
> output_dict = {key: output_dict[key][0, :num_detections].numpy()
>                for key in need_detection_key}
> output_dict['num_detections'] = num_detections
> # detection_classes should be ints.
> output_dict['detection_classes'] = output_dict['detection_classes'].astype(np.int64)
> # Handle models with masks:
> if 'detection_masks' in output_dict:
>     # Reframe the the bbox mask to the image size.
>     detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
>         tf.convert_to_tensor(output_dict['detection_masks']), output_dict['detection_boxes'],
>         image.shape[0], image.shape[1])
>     detection_masks_reframed = tf.cast(detection_masks_reframed > 0.5,
>                                        tf.uint8)
>     output_dict['detection_masks_reframed'] = detection_masks_reframed.numpy()
> 
> return output_dict
> ```
> 
> `

Thank You so much, it worked

**Comment by ravikyram** [comment] 2020-09-25 10:09
@AliButtar 

Please, close this thread if your issue was resolved. Thanks!

**Closed** 2020-09-25 12:18 UTC
Labels: models:research, type:bug

**Comment by Petros626** [comment] 2021-09-06 17:39
> 
> 
> > > > i get the same Error,did you solve this Error？
> > > 
> > > 
> > > i solved it. it because 'image_shape' and 'num_proposals' node are the parameters that needs to be feed.so dont use them,and convert to tensor
> > 
> > 
> > Can you go into a little more detail, and share the solution perhaps. It will help a lot. Thanks
> 
> > Change "run_inference_for_single_image" function
> > `def run_inference_for_single_image(model, image):
> 
> ```
> image = np.asarray(image)
> # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
> input_tensor = tf.convert_to_tensor(image)
> # The model expects a batch of images, so add an axis with `tf.newaxis`.
> input_tensor = input_tensor[tf.newaxis, ...]
> # Run inference
> model_fn = model.signatures['serving_default']
> output_dict = model_fn(input_tensor)
> # All outputs are batches tensors.
> # Convert to numpy arrays, and take index [0] to remove the batch dimension.
> # We're only interested in the first num_detections.
> num_detections = int(output_dict.pop('num_detections'))
> need_detection_key = ['detection_classes','detection_boxes','detection_masks','detection_scores']
> output_dict = {key: output_dict[key][0, :num_detections].numpy()
>                for key in need_detection_key}
> output_dict['num_detections'] = num_detections
> # detection_classes should be ints.
> output_dict['detection_classes'] = output_dict['detection_classes'].astype(np.int64)
> # Handle models with masks:
> if 'detection_masks' in output_dict:
>     # Reframe the the bbox mask to the image size.
>     detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
>         tf.convert_to_tensor(output_dict['detection_masks']), output_dict['detection_boxes'],
>         image.shape[0], image.shape[1])
>     detection_masks_reframed = tf.cast(detection_masks_reframed > 0.5,
>                                        tf.uint8)
>     output_dict['detection_masks_reframed'] = detection_masks_reframed.numpy()
> 
> return output_dict
> ```
> 
> `

hey i use the code you shared with us, but in run in new errors:

![github1](https://user-images.githubusercontent.com/62354721/132249723-7237af79-86d0-44f2-bce1-7ba882e5c433.JPG)
![github2](https://user-images.githubusercontent.com/62354721/132249729-3e267360-9a4f-4d1f-87c8-8c0a308f4c05.JPG)

**Comment by 518789Adf** [comment] 2024-07-23 19:37
input has only 1 dims for '{{node strided_slice_8}}

**Comment by Petros626** [comment] 2024-07-23 20:26
> input has only 1 dims for '{{node strided_slice_8}}

Look at my mentioned issue
