### ISSUE TITLE
Does the depth multiplier refer to the width multiplier in the mobilenet paper?

### ISSUE THREAD

**Issue by xbcReal** [tensorflow/models#3493] opened 2018-02-28 13:48 UTC
I want to know what will happen if I change depth multiplier number from 1 to 0.5? Will it be more fast when infereence?And is the depth multiplier here the same thing as the width multiplier in the mobilenet paper?

**Comment by tensorflowbutler** [comment] 2018-04-25 06:55
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment] 2018-11-30 22:08
Closing this issue since explanation is provided above.  Feel free to reopen if want to have a follow up discussion. Thanks!

**Closed by ymodak** 2018-11-30 22:08 UTC
Labels: stat:awaiting response
