### ISSUE TITLE
object_detection: python3 compatibility: range creates iterator

### ISSUE THREAD

**Issue by DominikAuras** [tensorflow/models#3465] opened 2018-02-26 10:56 UTC
In Python 3, `range(...)` creates an iterator. This leads to a failure here:
https://github.com/tensorflow/models/blob/4d1f67cf1a0c6f4cccdd2e3e46ce036c0a734e94/research/object_detection/utils/learning_schedules.py#L153
The op `tf.constant` correctly complains, that it received an iterator, not a list of integers.

Possible fix: use `list(range(...))` or adapt `tf.constant` to accept iterators.

**Comment by tensorflowbutler** [comment] 2018-04-25 06:55
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hgadig** [comment] 2019-02-06 21:53
Closing as this is in "awaiting response" status for a long time. Feel free to add comments if any, we will reopen.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:26
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:44 UTC
Labels: models: research, stat:awaiting response
