### ISSUE TITLE
how to export pb files for resnet model?

### ISSUE THREAD

**Issue by boris0430** [tensorflow/models#4804] opened 2018-07-18 01:45 UTC
In models version 1.4.0, this is an exporting function to save pb files of mnist model, just as following code: 

`  # Export the model
  if FLAGS.export_dir is not None:
    image = tf.placeholder(tf.float32, [None, 28, 28])
    input_fn = tf.estimator.export.build_raw_serving_input_receiver_fn({
        'image': image,
    })
    mnist_classifier.export_savedmodel(FLAGS.export_dir, input_fn) `

However, i don`t find any exporting functions for resnet and wide_deep models, and when i use function in mnist to export pb file to resnet, there is an error that '**_Failed to convert object of type<class 'dict'> to Tensor. Contents: {'feature': <tf.Tensor 'input_tensor: 0' shape=(20, 32, 32, 3) dtype=float32>}. Consider casting elements to as supported type_**'.

does anyone find a method to export pb files to these models(resnet、wide_deep)? 

Thanks a lot!

**Comment by tensorflowbutler** [comment] 2018-07-18 07:02
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by boris0430** [comment] 2018-07-19 02:43
I used the model in tensorflow/models-1.4.0/official/resnet/cifar10;
OS: centOS7
Tensorflow installed from: pip install tensorflow==1.4.0
Tensorflow version: v1.4.0
Bazel version: 0.5.4
CUDA/cuDNN version: 8.0
memory: 16G

**Comment by qlzh727** [comment] 2018-07-20 17:01
Assign to Kathy who worked on save model.

**Comment by k-w-w** [comment] 2018-07-23 20:15
Are you also running version 1.4.0 of tensorflow?

Can you copy the exact command you used that produced the error, and the entire error stacktrace?

**Comment by ucasiggcas** [comment] 2018-08-22 06:40
Hello
Maybe I have the same question
i just want to save a model ,but can not find a useful way.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:15
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:47 UTC
Labels: models: official, stat:awaiting response, stat:awaiting tensorflower
