### ISSUE TITLE
Failure at TF Inception Sample using S390x, module classify_image.py 

### ISSUE THREAD

**Issue by claudefalbriard** [tensorflow/models#2485] opened 2017-10-02 11:45 UTC
**System information**

. OS Platform and Distribution: s390x Ubuntu 16.4
. TensorFlow installed from (source or binary): source
. TensorFlow version (use command below): 1.3.1
. Python version: 2.7.12

**Error Description**

. Attempt to execute the first sample from tutorial for image recognition with Python API and Tensorflow. The Error shows up at the begin of the execution of the classify_image.py code under the default folder: tutorials/image/imagenet 

I've tried to execute the basic sample from the TF models library (classify_image.py) and received the following error message: 

```
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Cannot reshape a tensor with 1041082757314414592 elements to shape [16777216,524288] (8796093022208 elements) for 'pool_3/_reshape' (op: 'Reshape') with input shapes: [1,22546423,22546423,2048], [2] and with input tensors computed as partial shapes: input[1] = [16777216,524288].
```

The error message was displayed by the following code section of the TF module at framework/common_shapes.py: 

```
 try:
    with errors.raise_exception_on_not_ok_status() as status:
      output = pywrap_tensorflow.RunCppShapeInference(
          graph_def_version, node_def_str, input_shapes, input_tensors,
          input_tensors_as_shapes, status)
  except errors.InvalidArgumentError as err:
    if err.message.startswith("No shape inference function exists for op"):
      missing_shape_fn = True
    else:
      raise ValueError(err.message)
```

I'm using latest Github distribution of Tensorflow 1.3.1 built from source under a S390x CPU (LinuxOne) 
 
```
>>> import tensorflow as tf
>>> print tf.VERSION
1.3.1
```

**Comment by cy89** [comment] 2017-10-09 00:55
@claudefalbriard this is the first time I've seen someone use an S390x. It's not a particularly helpful suggestion, but do you get the same problem on an x86 system?

**Comment by claudefalbriard** [comment] 2017-10-12 16:02
I currently do not have a suitable x86 platform that fulfils the TensorFlow pre-requsite. The purpose of this port and pilot is to run TensorFlow in a virtual environment, like s390x. The inception model is part of the TensorFlow distribution. I've executed a new bazel build according to the instructions here [ https://www.tensorflow.org/tutorials/image_retraining ]. At the retrain step, I received exactly the same error at the load of the model file named: classify_image_graph_def.pb. Is a new version available for this pre-trained model file?

**Comment by reedwm** [comment] 2017-10-13 22:53
We don't have an s390x to reproduce this on, so marking as community support. @namrata-ibm, can you take a look at this?

I also found [this page](https://github.com/linux-on-ibm-z/docs/wiki/Building-TensorFlow) which describes using TensorFlow on an S390x. Maybe file an issue with that repo.

**Comment by namrata-ibm** [comment] 2017-10-16 08:10
@reedwm, @claudefalbriard, I ran the classifier(classify_image.py) at my end on s390x and getting same error(I am working on v1.2.1 but in this case, version should not matter). I tried on x86 (again v1.2.1) and it works fine there. However I suspect that the inception model being a  pre-trained model on a Little Endian machine, may have issues while loading on Big Endian(s390x). 

I also faced similar error while running [Deep dream tutorial](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials/deepdream) which also uses a pre-trained model. However when we do training on s390x explicitly, like in [Iris data set](https://www.tensorflow.org/versions/r1.2/get_started/tflearn) model it passes successfully.

My first hunch is that this is happening because the graph (eg. classify_image_graph_def.pb) might be storing values like size in one format, which gives unexpected results when read in the other. 

Need some expert advice here. Adding @gunan. May be you could help in checking whether this understanding is correct or redirect to someone who can answer this better.

**Comment by gunan** [comment] 2017-10-17 05:39
AFAICR, the way IBM contributed saved model support for little endian machines, you cannot load a saved model generated on a big endian machine on a little endian machine. I think @aselle was one of the reviewers for the feature.

So I think your understanding here is correct.

**Comment by namrata-ibm** [comment] 2017-10-17 06:53
Alright, Thanks @gunan. For now I guess we have to train models separately on big endian till we get a way to generate saved model which are compatible on both or develop some tool to convert it.

**Comment by gunan** [comment] 2017-10-17 16:08
@claudefalbriard does the above answer your question?
We are open to contributions to enable loading models saved on one endianness on the other, but TensorFlow team likely wont be able to do this, as we do not have any big endian machines.

I will leave this open and mark contributions welcome, but we can also file a more explicit issue that explains the problem better and close this one.

**Comment by claudefalbriard** [comment] 2017-10-17 18:35
Thanks @gunan . I would appreciate to receive a description of the internals and layout for the classify_image_graph_def.pb file, so we can start to develop a converter tool. Right now, thinking about Python Numpy which has data-type controls with endian-ness. Beside float values, I also expect to see ASCII characters in that file. I will discuss the solution path with the internal community.

**Comment by gunan** [comment] 2017-10-18 04:54
Here is some of the relevant discussion at the time we were accepting
initial big-endian support:
https://github.com/tensorflow/tensorflow/pull/5450#issuecomment-270173816

This should point you to a high level summary of the problem, and what may
need to be changed in order to support cross architecture usage of models.

**Comment by tensorflowbutler** [comment] 2020-01-29 23:33
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by claudefalbriard** [comment] 2020-01-31 12:40
@tensorflowbutler  Sorry, meanwhile went into retirement, not having access to s390X infra. Hope your able to develop a solution with the IBM support team and the report was helpful to to detect and identify the issue.

**Comment by namrata-ibm** [comment] 2020-01-31 15:23
@claudefalbriard [This PR](https://github.com/tensorflow/tensorflow/pull/28490) probably must have resolved this.

**Comment by kumariko** [comment] 2021-08-24 05:32
@claudefalbriard Could you please let us know if this issue still persists ? If it it resolved then please feel free to move this issue to close status ?Thanks!

**Closed** 2021-09-10 06:10 UTC
Labels: stat:awaiting response, stat:community support, stalled
