### ISSUE TITLE
Protobuf error using object detection with python3.5?

### ISSUE THREAD

**Issue by ghost** [tensorflow/models#2633] opened 2017-10-29 01:14 UTC
**System information**
    **What is the top-level directory of the model you are using:**
    ssd_mobilenet_v1_coco_11_06_2017
    **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
    No
    **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
    Ubuntu 16.04
    **TensorFlow installed from (source or binary):**
    Binary
    **TensorFlow version (use command below):**
    v1.0.0
    **Bazel version (if compiling from source):**
    NA
    **CUDA/cuDNN version:**
    8.0/5.1
    **GPU model and memory:**
    Ubuntu GTX960 2GB

**Describe the problem**
     I run demo successfully.After finishing model configure and converting training data to tfrecord, I run following command:
python object_detection/train.py --pipeline_config_path=/media/cuixiongwen/WORK/TensorFlow/tensorflow/tensorflow/models/object_detection/samples/configs/ssd_mobilenet_v1_pets.config --train_dir=/media/cuixiongwen/WORK/Code/raccoon_dataset
    Then following error occured:
File "object_detection/train.py", line 198, in <module>
    tf.app.run()
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "object_detection/train.py", line 143, in main
    model_config, train_config, input_config = get_configs_from_pipeline_file()
File "object_detection/train.py", line 103, in get_configs_from_pipeline_file
    text_format.Merge(f.read(), pipeline_config)
File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 521, in Merge
    text.split('\n'),
TypeError: a bytes-like object is required, not 'str'
      
        It seemed this error is relative to python3.5, should I recompile protobuf to fix this bug?

**Comment by cipri-tom** [comment] 2017-10-30 11:19
I don't know if recompiling is a solution, but as a workaround, try opening the files in binary mode. That is, modify all instances of 
```python
with tf.gfile.GFile(FLAGS.pipeline_config_path, 'r') as f:
```

To 
```python
with tf.gfile.GFile(FLAGS.pipeline_config_path, 'rb') as f:
```

i.e. change `'r'` into `'rb'` (in train.py)

**Comment by asimshankar** [comment] 2017-11-03 07:22
@cuixiongwen : Does @cipri-tom 's suggestion help?

**Comment by cuixiongwen** [comment] 2017-12-03 07:12
@cipri-tom : Thank you for your answer.
@asimshankar : I don't know if @cipri-tom 's suggestion helps. I changed to python2.7, and this problem disappeared.

**Comment by reedwm** [comment] 2017-12-05 01:45
/CC @tombstone, can you ensure Object Detection works with Python 3?

**Comment by cuixiongwen** [comment] 2017-12-22 03:23
@reedwm .I solved this problems via two following ways:
1.Changed my python version to 2.7.
2.Update my tensorflow version to 1.4(under python3.5).
Either of above two ways can solve this problem.

**Comment by wt-huang** [comment] 2018-10-20 02:00
Closing as the issue is resolved

**Closed by wt-huang** 2018-10-20 02:00 UTC
Labels: stat:awaiting tensorflower
