### ISSUE TITLE
Cannot inference mobilenet tflite files on Android. exception "Invalid handle to Interpreter"

### ISSUE THREAD

**Issue by hithere1985** [tensorflow/models#3713] opened 2018-03-23 08:27 UTC
Hello, 

Recently, MobileNet v1 added tensorflow lite files (.tflites) I want to run on my android device. But all these tflite files dosen't works with "Invalid handle to Interpreter" Exception. 

<pre><code>Caused by: java.lang.IllegalArgumentException: Invalid handle to Interpreter.
      at org.tensorflow.lite.NativeInterpreterWrapper.getInputDims(Native Method)
      at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:82)
      at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:112)
      at org.tensorflow.lite.Interpreter.run(Interpreter.java:93)
      at com.example.realone.facexandroid.tflite.ImageClassifierQuantizedMobileNet.runInference(ImageClassifierQuantizedMobileNet.java:95)
      at com.example.realone.facexandroid.tflite.ImageClassifier.classifyFrame(ImageClassifier.java:135)
      at com.example.realone.facexandroid.MainActivity$5.doInBackground(MainActivity.java:462)
      at com.example.realone.facexandroid.MainActivity$5.doInBackground(MainActivity.java:442)
      at android.os.AsyncTask$2.call(AsyncTask.java:304)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
      at java.lang.Thread.run(Thread.java:762) 
</code></pre>

So, I converted pb to tflite myself. These files are same size. but doesn't work neither.
And I check tensorflow lite Interpreter class. 
The values, NativeInterpreterWrapper.interpreterHandle is always 0.

Please check this.
Thanks.

**Comment by tensorflowbutler** [comment] 2018-04-25 06:53
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-09 22:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-12-05 21:39 UTC
Labels: stat:awaiting response
