### ISSUE TITLE
How to save the model?

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/models#5163] opened 2018-08-22 07:00 UTC
Dear,
https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_train.py
how to save the model ?
Thx

**Comment by ucasiggcas** [comment] 2018-08-22 07:20
There are so many similar questions in the tf.train.Saver()
Can't find a way ,not know how to use it!!!!
In Up Website!!

**Comment by tensorflowbutler** [comment] 2020-01-29 23:14
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:45 UTC
