### ISSUE TITLE
cifar10_eval issues - tensorflow 0.12

### ISSUE THREAD

**Issue by al3xsh** [tensorflow/models#892] opened 2017-01-12 12:58 UTC
## tensorflow/models/tutorial/image/cifar10/cifar10_eval.py

When I run cifar10_eval.py alongside the cifar10_train.py script in tensorflow 0.12, it crashes the main training script with the error: 

Out of range: RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 128, current size 46)

It does this on both the gpu training code and the cpu code - but this doesn't happen using tensorflow 0.11.  Any ideas?

**Comment by jart** [comment] 2017-01-12 22:53
Could you please provide the full stacktrace? Also did you modify the tutorial scripts?

**Comment by jart** [comment] 2017-01-13 18:56
+cc @shlens who has worked on this cifar10_eval.py in the past.

Thank you for taking the time to troubleshoot and fix the script. In that case, would you be interested in sending your changes as a pull request?

**Comment by al3xsh** [comment] 2017-01-16 14:52
Hi @jart,

Many thanks.  I have submitted my changes to the cifar10 files as pull request #909.

Thanks,

Alex

**Comment by weigei123** [comment] 2017-01-16 19:18
@al3xsh It may be a bit abrupt, but I still wanna ask whether the changes have been tested with tf0.12.1 or not.
Because when I tried your codes, I got the same error as I showed in #901

**Comment by al3xsh** [comment] 2017-01-16 20:46
@weigel123 I have tested against tf 0.12.1 and it works for me :-) 

One of the changes was to replace image_summary with tf.summary.image() - so that warning message should have gone away.

Could you try the code from https://github.com/al3xsh/models in its entirety and tell me if you still get those errors?

Do you get the same errors from the standard cifar10_train script?

Regards,

Alex

**Comment by weigei123** [comment] 2017-01-17 11:57
@al3xsh TensorFlow 1.0.0-alpha has removed tf.mul and the new symbol is  tf.multiply. In 0.12.1, this change seems to have entered into force.
`AttributeError: 'module' object has no attribute 'mul'`
It was the first error I got when I tried your code.
The second one is 
`ValueError: Variable conv1/weights/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`
@wookayin  has fixed these two bugs in #911. 
Anyway, thanks for your help.
: )

**Comment by al3xsh** [comment] 2017-01-17 12:27
@weigei123 

Out of interest, how did you install tensorflow?  I installed via pip, and in my environment tf.mul is still supported!

![image](https://cloud.githubusercontent.com/assets/10220372/22019955/a1416806-dcad-11e6-83cb-37b48815940f.png)

Anyway, glad your issue is fixed!  I'm looking forward to tensorflow releases being stable :)

Cheers,

Alex

**Comment by weigei123** [comment] 2017-01-17 13:01
![image](https://cloud.githubusercontent.com/assets/25108985/22021266/206bccd6-dcf7-11e6-8606-f364843fdfb8.png)
I installed Tensorflow by compiling source. It seems ... different. 
: P

**Comment by wookayin** [comment] 2017-01-17 14:41
@al3xsh is using the 0.12.1 release version, and @weigei123 is using 1.0 snapshot on the master branch. `tf.mul` is removed at master only, so it does not affect 0.12.x series

**Comment by al3xsh** [comment] 2017-01-17 18:30
@weigei123 @wookayin can you successfully run cifar10_eval.py while running cifar10_multi_gpu_train.py?  Are you both using the version 1.0 snapshot built from source?

The error I am getting suggests to me that the cifar10_eval script is pulling images out of the same queue as the training script (though I may be mistaken!).  I am a bit too new to Tensorflow to fully understand what is happening though!

**Comment by nealwu** [comment] 2017-01-17 22:32
@al3xsh: I recommend installing TensorFlow from the [nightly binaries](https://github.com/tensorflow/tensorflow#installation) or [from source](https://www.tensorflow.org/get_started/os_setup#installing_from_sources) in order to run these tutorial models.

**Comment by drpngx** [comment] 2017-01-23 19:24
As per @nealwu that should solve the issue. Marking as closed.

**Closed by drpngx** 2017-01-23 19:24 UTC
Labels: type:bug/performance

**Comment by nealwu** [comment] 2017-01-23 19:53
Actually I just ran into this same issue myself recently. If you go through the tutorial at https://www.tensorflow.org/versions/master/tutorials/deep_cnn, it gives you the following warning:

`Be careful not to run the evaluation and training binary on the same GPU or else you might run out of memory. Consider running the evaluation on a separate GPU if available or suspending the training binary while running the evaluation on the same GPU.`

Assuming you're running Linux, you can suspend the training binary with Ctrl+z in order to run the evaluation script, and you can resume the training later with `fg`.

**Comment by zym1010** [comment] 2017-02-28 13:56
I also encountered this bug, seems that it only happens when using `cifar10_multi_gpu_train`, not `cifar10_train`. I compiled 0.12.1 from source.

**Comment by zym1010** [comment] 2017-02-28 14:44
@al3xsh does this bug still happen in 1.0? I haven't got chance to try it, because I need to compile Tensorflow from source for it to run on my machines...

**Comment by zym1010** [comment] 2017-02-28 15:05
@nealwu  running the eval script using `CUDA_VISIBLE_DEVICES=''` or simply running it on another machine won't help, as long as eval and train scripts are fetch data from the same directory.

**Comment by zym1010** [comment] 2017-02-28 15:53
@al3xsh  ok. I think I've found the culprit. Undoing <https://github.com/tensorflow/tensorflow/pull/5145/files> should do.

**Comment by al3xsh** [comment] 2017-03-03 09:29
@zym1010 Thanks for this!  

I'm testing it now - it seems to have fixed it!

Cheers!

**Comment by nealwu** [comment] 2017-03-03 19:13
Hi @zym1010 and @al3xsh, what problem did that PR cause for you two? Want to know whether it's something we should actually revert.

**Comment by zym1010** [comment] 2017-03-04 19:37
@nealwu check #1083 . Essentially, that PR causes train and eval scripts unable to run concurrently, which to me totally defeats the purpose of having separate train and eval scripts.

**Comment by florpi** [comment] 2017-06-27 09:01
@nealwu I have a question about suspending and resuming the training binary since I only have one gpu. The problem is that gpu memory is still being used when I suspend the training Ctrl+z, so when I run the eval file I run out of memory ("failed to allocate 157.88M (165543936 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY") Do you have any other suggestion ? Thank you in advance

**Comment by nealwu** [comment] 2017-06-27 19:50
Yes, unfortunately the Ctrl+z I posted above may not actually work. Does the training script save checkpoints? It should ideally be able to resume training if quit and restarted.

**Comment by al3xsh** [comment] 2017-06-28 08:18
@florpi instead of suspending the training, you could run it on the CPU instead.  If you do:

$ export CUDA_VISIBLE_DEVICES=""

before running the evaluation script, then it won't use the GPU and will run on the CPU instead.  This should get round the CUDA_ERROR_OUT_OF_MEMORY ...

I find that an element of GPU management is necessary when using tensorflow - otherwise it'll try and grab all the GPUs you've got on your system even if it is only going to use one of them!

Cheers,

Alex

**Comment by florpi** [comment] 2017-06-28 08:30
Thank you very much, that does the trick and it's not so slow :)
