### ISSUE TITLE
Nit: typo in log message in models/official/vision/train.py

### ISSUE THREAD

**Issue by joadavis** [tensorflow/models#11025] opened 2023-06-20 05:24 UTC
https://github.com/tensorflow/models/blob/6f6429402e3ff1b02db84e449ce2a550fed59cf3/official/vision/train.py#LL77C1-L77C62

Simple typo, 'retarting' instead of 'restarting' in log message when recovering from a preempted experiment run. I'd assume it was left to see if people were actually reading the code. ;)

**Comment by laxmareddyp** [comment] 2023-06-20 18:11
Hi @joadavis ,

Thank you for notifying us about the issue. We have taken the necessary steps to address it by submitting a [pull request (PR)](https://github.com/tensorflow/models/pull/11027). Once the PR is merged, you will be able to see the changes reflected in the code, and the issue is closing as it is completed.

Thanks

**Closed by laxmareddyp** 2023-06-20 18:11 UTC
Labels: type:docs, models:official
