### ISSUE TITLE
ssd-mobileNet retrain with our picture failed

### ISSUE THREAD

**Issue by xiewanlin** [tensorflow/models#4111] opened 2018-04-27 11:59 UTC
## I chose ssd-mobileNet-v1-coco for a picture training, because the computer problem , i am only hava a virtual machine, and each training is a failure, the picture and the annotation are ready, and the record format files have been generated. But is not success. I hope someone can help me.
![12](https://user-images.githubusercontent.com/33651882/39361717-471abe1e-4a56-11e8-809f-2476923caa02.jpg)

##  If there have guys with an enough conditions to train the model, i aks you to give me a hangs please. About the pictures and annotation ,you can through the email 761489655@qq.com to call with me, thank you.

**Comment by tensorflowbutler** [comment] 2018-04-27 18:59
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by qlzh727** [comment] 2018-05-10 15:54
Sorry, doesn't quite understand your problem. Are you trying to feed your own training data to the model but get failed result? It will be helpful to provide the information as suggested by tensorflowbutler in the previous comment, so that we can do some further troubleshooting.

Also adding some owner of the object detection model for more input.

**Comment by pkulzc** [comment] 2018-05-10 16:25
I can't see anything useful from the screenshot. Please at least share the config file and failure message so I can take a look.

**Comment by pkulzc** [comment] 2018-09-14 01:28
Closing this since it looks obsolete. Feel free to reopen if needed.

**Closed by pkulzc** 2018-09-14 01:28 UTC
Labels: stat:awaiting response
