### ISSUE TITLE
compile syntaxnet error on ubuntu14.04 

### ISSUE THREAD

**Issue by yaoqingyuan** [tensorflow/models#1883] opened 2017-07-07 09:42 UTC
root@ubuntu-nd2015kyle:~/models/syntaxnet# bazel test ...
WARNING: /root/.cache/bazel/_bazel_root/07e289e62ff0021383a4043a3fef5989/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /root/.cache/bazel/_bazel_root/07e289e62ff0021383a4043a3fef5989/external/org_tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule @org_tensorflow//tensorflow/contrib/learn:learn: target '@org_tensorflow//tensorflow/contrib/learn:learn' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /root/.cache/bazel/_bazel_root/07e289e62ff0021383a4043a3fef5989/external/org_tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule @org_tensorflow//tensorflow/contrib/learn:learn: target '@org_tensorflow//tensorflow/contrib/learn:learn' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 165 targets and 52 test targets...
**ERROR: /root/.cache/bazel/_bazel_root/07e289e62ff0021383a4043a3fef5989/external/protobuf/BUILD:247:1: Executing genrule @protobuf//:generate_js_well_known_types_embed failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/host/bin/external/protobuf/js_embed: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel-out/host/bin/external/protobuf/js_embed)**
INFO: Elapsed time: 0.443s, Critical Path: 0.07s
//dragnn/components/stateless:stateless_component_test                NO STATUS
//dragnn/components/syntaxnet:syntaxnet_component_test                NO STATUS
//dragnn/components/syntaxnet:syntaxnet_link_feature_extractor_test   NO STATUS
//dragnn/components/syntaxnet:syntaxnet_transition_state_test         NO STATUS
//dragnn/core:beam_test                                               NO STATUS
//dragnn/core:compute_session_impl_test                               NO STATUS
//dragnn/core:compute_session_pool_test                               NO STATUS
//dragnn/core:dragnn_bulk_op_kernels_test                             NO STATUS
//dragnn/core:dragnn_op_kernels_test                                  NO STATUS
//dragnn/core:index_translator_test                                   NO STATUS
//dragnn/core:input_batch_cache_test                                  NO STATUS
//dragnn/core:resource_container_test                                 NO STATUS
//dragnn/io:sentence_input_batch_test                                 NO STATUS
//dragnn/python:bulk_component_test                                   NO STATUS
//dragnn/python:composite_optimizer_test                              NO STATUS
//dragnn/python:digraph_ops_test                                      NO STATUS
//dragnn/python:evaluation_test                                       NO STATUS
//dragnn/python:graph_builder_test                                    NO STATUS
//dragnn/python:lexicon_test                                          NO STATUS
//dragnn/python:network_units_test                                    NO STATUS
//dragnn/python:render_parse_tree_graphviz_test                       NO STATUS
//dragnn/python:render_spec_with_graphviz_test                        NO STATUS
//dragnn/python:sentence_io_test                                      NO STATUS
//dragnn/python:spec_builder_test                                     NO STATUS
//dragnn/python:visualization_test                                    NO STATUS
//dragnn/tools:model_trainer_test                                     NO STATUS
//examples/dragnn:test_run_all_tutorials                              NO STATUS
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:binary_segment_state_test                                 NO STATUS
//syntaxnet:binary_segment_transitions_test                           NO STATUS
//syntaxnet:char_ngram_string_extractor_test                          NO STATUS
//syntaxnet:char_properties_test                                      NO STATUS
//syntaxnet:char_shift_transitions_test                               NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:head_transitions_test                                     NO STATUS
//syntaxnet:label_transitions_test                                    NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:morphology_label_set_test                                 NO STATUS
//syntaxnet:once_transitions_test                                     NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:segmenter_utils_test                                      NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//syntaxnet/util:check_test                                           NO STATUS
//syntaxnet/util:registry_test                                        NO STATUS
//syntaxnet:whole_sentence_features_test                              NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS

Executed 0 out of 52 tests: 52 were skipped.

i compile syntacnet on ubuntu14.06. tensorflow and bazel is ok! i find this error in google but not find solution, so someone can help me? thanks!

**Comment by cy89** [comment] 2017-07-08 01:14
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by yaoqingyuan** [comment] 2017-07-08 03:43
### System information
- **OS Platform and Distribution**: Linux Ubuntu 14.04 TLS
- **TensorFlow_CPU installed from**: source
- **TensorFlow version**: tensorflow master
- **Python version**: 2.7
- **Bazel version**: 0.5.2
- **CUDA/cuDNN version**: no use
- **GPU model and memory**: no use
 i build and test SyntaxNet with the command: bazel test ... 

and then i also install anaconda2 and update gcc4.8 to gcc5.3.

**Comment by aselle** [comment] 2017-07-09 01:35
/So you are saying you got the same error w/ gcc 4.8 and gcc5.3?
@gunan, do you have any ideas?

**Comment by gunan** [comment] 2017-07-09 11:34
I think this may be an issue with the anaconda distribution?
maybe python there is compiled with a different GCC, and linked against a different glibc?
`GLIBCXX_3.4.21 not found` message looks suspicious to me, and the glibc version there.

@jhseu may have better insight into this.

**Comment by jhseu** [comment] 2017-07-10 19:20
Yeah, the problem is very likely to be anaconda, which can cause you to link with a newer glibc.

**Comment by yaoqingyuan** [comment] 2017-07-14 09:38
@jhseu how do I specify to link a glibc?

**Comment by jhseu** [comment] 2017-07-14 19:17
I believe it's from LD_LIBRARY_PATH, but I'm not sure how anaconda is handling this.

Closing this since it's more of a support issue rather than a bug.

**Closed by jhseu** 2017-07-14 19:17 UTC
Labels: type:support
