### ISSUE TITLE
AttributeError 'module' object has no attribute 'experimental': during mnist training: 

### ISSUE THREAD

**Issue by sri-oc** [tensorflow/models#6526] opened 2019-04-04 19:48 UTC
##problem Description
I'm trying to train mnist model by running,

`python mnist.py`

Error message I'm getting,
`Traceback (most recent call last):
  File "mnist.py", line 27, in <module>
    from official.utils.misc import distribution_utils
  File "/root/srinivas/TensorFlow_Models/models/official/utils/misc/distribution_utils.py", line 28, in <module>
    None: tf.distribute.experimental.CollectiveCommunication.AUTO,
AttributeError: 'module' object has no attribute 'experimental'
`

##System Information:
o Python version: 2.7.15
o TensorFlow version: ('v1.13.1-0-g6612da8951', '1.13.1') (Installed through binary)
o OS: NAME="Ubuntu"
      VERSION="16.04.6 LTS (Xenial Xerus)"
o Command to reproduce: `python mnist.py`
o GPU : GeForce GTX 1060 6GB
o Cuda version: Cuda-9.0

**Comment by tensorflowbutler** [comment] 2019-04-05 12:18
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MHDBST** [comment] 2019-04-19 16:00
I have the same issue with Tensorflow 1.13.1
Any solution?

**Comment by srinivas491-oneconvergence** [comment] 2019-04-25 00:49
Released version worked fine for me.

**Comment by srinivas491-oneconvergence** [comment] 2019-04-25 00:54
OS Platform and Distribution: "Ubuntu" "16.04.6 LTS (Xenial Xerus)"
TensorFlow installed from : Tensorflow Repo
CUDA/cuDNN version : CUDA 10.01
GPU model and memory: GeForce GTX 1060, 6078MiB
Exact command to reproduce: python mnist.py

**Comment by ymodak** [comment] 2019-05-08 06:25
Closing this issue since its resolved. Feel free to reopen if have further problems. Thanks!

**Closed by ymodak** 2019-05-08 06:25 UTC
Labels: models: official
