### ISSUE TITLE
Can't run an `Instance Segmentation` model example from docs (Object detection / TF 1.5)

### ISSUE THREAD

**Issue by antlad** [tensorflow/models#3462] opened 2018-02-26 09:01 UTC
### System information
- **What is the top-level directory of the model you are using**:
models/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
pip install tensorflow-gpu
- **TensorFlow version (use command below)**:
1.5.0
- **CUDA/cuDNN version**:
9.0 / 7.0.5.15
- **GPU model and memory**:
GTX 1080
- **Exact command to reproduce**:
python train.py --logtostderr --pipeline_config_path=${HOME}/model/mask_rcnn_resnet101_atrous_coco_2018_01_28/pipeline.config --train_dir=${HOME}/model/mask_rcnn_resnet101_atrous_coco_2018_01_28

### Describe the problem
Trying to run `mask_rcnn_inception_resnet_v2_atrous_coco` with `Oxford-IIIT Pets Dataset`  new feature `Instance Segmentation`, but getting bug (see log). Created tf record with provided script `dataset_tools/create_pet_tf_record.py --faces_only=false --mask_type=png` . 
Pipeline config from docs [here](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/mask_rcnn_inception_resnet_v2_atrous_coco.config)
Then after run train and getting this error: `TypeError: Expected int32, got range(0, 3) of type 'range' instead.`

### Source code / logs
```
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From /root/git/models/research/object_detection/trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From /root/git/models/research/object_detection/core/box_predictor.py:391: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /root/git/models/research/object_detection/core/losses.py:306: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

WARNING:tensorflow:From /root/git/models/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py:1851: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/root/git/models/research/object_detection/trainer.py", line 255, in train
    train_config.optimizer)
  File "/root/git/models/research/object_detection/builders/optimizer_builder.py", line 50, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "/root/git/models/research/object_detection/builders/optimizer_builder.py", line 108, in _create_learning_rate
    learning_rate_sequence)
  File "/root/git/models/research/object_detection/utils/learning_schedules.py", line 153, in manual_stepping
    tf.constant(range(num_boundaries), dtype=tf.int32),
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 212, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 413, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/root/venv/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 328, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got range(0, 3) of type 'range' instead.
```

**Comment by antlad** [comment] 2018-02-26 09:17
same [issue](https://github.com/tensorflow/models/issues/3443)

**Comment by angersson** [comment] 2018-02-26 19:10
Duplicate of https://github.com/tensorflow/models/issues/3443

**Closed by angersson** 2018-02-26 19:10 UTC
