### ISSUE TITLE
How to use pretrained syntaxnet (parsey_mcparseface) using demo.sh in the Docker

### ISSUE THREAD

**Issue by fabrahman** [tensorflow/models#7337] opened 2019-07-31 01:58 UTC
Hi,

Thanks for the valuable resource.
I am a little confused of how to use pretrained syntaxtnet (parsey mcparseface models) to get a conll file format parsed.

I have followed the instructions to use Docker however I dont know how to run demo.sh there in the docker?

I would appreciate any guidance.

**Comment by tensorflowbutler** [comment] 2019-08-01 00:11
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-07-29 07:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-29 07:21 UTC
Labels: models:research, stat:awaiting response, type:support
