### ISSUE TITLE
Not able to run the tensorflow in conda evniroment - (Window 10)

### ISSUE THREAD

**Issue by venkateshbabusekar** [tensorflow/models#5365] opened 2018-09-23 13:25 UTC
When I run import tensorflow in the conda environment I am getting an error but when running the same command normally in cmd (without activating the environment I am not getting this error)

Code (Production error):
C:\> conda create -n tensorflow1 pip python=3.5
C:\> activate tensorflow1
(tensorflow1) C:\> pip install --ignore-installed --upgrade tensorflow-gpu

In Jyputer note : 
import tensorflow as tf

Error : 
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive

Code (No error - not a conda enviroment  ):

C:\> pip install --ignore-installed --upgrade tensorflow-gpu

In Jyputer note : 
import tensorflow as tf

Please advise!! I am not sure where i am going wrong

**Comment by tensorflowbutler** [comment] 2018-09-24 02:16
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-09-25 19:16
@venkateshbabusekar Hi, please install CUDA 9.0 and CUDNN7.1. This should resolve the problem.

**Comment by harshini-gadige** [comment] 2018-10-09 18:32
@venkateshbabusekar  Does this issue still exist ?

**Comment by ymodak** [comment] 2018-12-26 21:43
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-12-26 21:43 UTC
Labels: stat:awaiting response
