### ISSUE TITLE
object_detection api: retrain  model locally, can not stop gracefully

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/models#2722] opened 2017-11-07 14:49 UTC
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:v1.4.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**:6GB
- **Exact command to reproduce**:

### Describe the problem
I follow the document to train the model locally. with following command:

`python object_detection/train.py     --logtostderr     --pipeline_config_path=${PATH_TO_YOUR_PIPELINE_CONFIG}     --train_dir=${PATH_TO_TRAIN_DIR}
`

I set number_of_steps to 2 in config file. From the log printed on terminal I can see that the training do run 2 times, but the python process don't exit even if I hit ctrl+c, I can only terminate it by 
`kill -9 PID`
command. meanwhile, this process still consume a lot of cpu resoruce.

**Comment by tombstone** [comment] 2017-11-07 17:27
Thanks @scotthuang1989 . I marked this as "contributions welcome" since we are currently addressing other issues ATM.

**Comment by scotthuang1989** [comment] 2017-11-10 00:13
@tombstone  After do some more debugging, It turns out that my tfrecord file for training is broken. I check the testcase for creating tfrecord, I found that the testcase only use a dummy example to test the create_xx_tf_record.py. Do you think it's better to add a function to verify if the created tfrecord is ok for training/validation?

**Comment by tensorflowbutler** [comment] 2020-01-29 23:32
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:43 UTC
Labels: stat:contributions welcome
