### ISSUE TITLE
About DELG trainning epochs, input image size, pre-trained model

### ISSUE THREAD

**Issue by zjcs** [tensorflow/models#9586] opened 2020-12-25 09:38 UTC
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [Y] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training

## 2. Describe the issue

A clear and concise description of what needs to be changed.

I am interrested to your work in Image Retrieval, and I am trying to reproduce the paper result now.
But I found some conflused thing between the DELG Paper and the code implementation.

### Q1: Input image size.

   The input image size in paper is 512*512, while 321*321 in the code implementation.
   So which resolutation is used in the released pre-train model?
### Q2: How many epochs do you train in the paper and released pre-train model?
  
  As the readme says, there are two different batchsize and lr: --batch_size 256 --lr 0.01 and --batch_size --lr 0.005.
  The max iteration in code implementation is 500,000.
  So, there will be 500,000*256/1,280,000=100epoch used.

  While the paper claimed only 25epcoh train_split(80% of train set), and its batchsize is 16*21P100=336. The whole steps is about 1.5M steps. 1,500,000*336/(1,280,000*80%)=492epochs, which is not equal to 25epochs.
  
   Which is right setting?

### Q3: Pre-Train model.
   Can you tell me more details about the released pre-train model?
   The epochs/iteration?
   The Input Image Size?

Best Regards.

**Comment by andrefaraujo** [comment] 2021-01-05 20:20
## Q1
512x512 is the right one to use for reproducing the paper results. You can do that by setting the [image_size](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/train.py#L85) flag to 512. Make sure your cloned repo is current, because we did fix a related bug on this recently (https://github.com/tensorflow/models/pull/9561).

## Q2
Indeed, there is some confusion here. The paper's number of steps refers to asynchronous SGD, while this codebase implementation uses synchronous SGD -- meaning that one step in the former corresponds to a single GPU processing the data, while one step in the latter corresponds to all GPUs.

So for the paper setting, the calculation is 1,500,000 * 16 / (1,225,029 * 80%) = 24.5 (in the paper, we had mentioned "approximately 25 epochs"). `1,225,029` is the number of images in GLDv1 (see Tab 2 in the [GLDv2 paper](https://arxiv.org/pdf/2004.01804.pdf)). For GLDv2-clean (see Appendix C in [DELG paper](https://arxiv.org/pdf/2001.05027.pdf)), we train for 2M steps leading to 2,000,000 * 16 / (1,580,470 * 80%) = 25.3 epochs.

To confirm, if you use 256 batch size in this codebase's sync-SGD setup,  to get to 25 epochs you should use `num_steps = num_images*25/256`. For GLDv2-clean with 80% train split, you should set [`max_iters`](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/train.py#L57) to: 1,580,470 * 80% * 25 / 256 = 123k steps.

## Q3
These are the exact models trained in the specific manner mentioned in the paper, so all details should be there.


Closing this issue since I believe everything is answered, but feel free to reopen if needed.

**Closed by andrefaraujo** 2021-01-05 20:20 UTC
Labels: models:research, type:docs

**Comment by zjcs** [comment] 2021-01-11 12:05
It's very clear, Thank you very much for your reply.
