### ISSUE TITLE
Unable to Install Setup.py

### ISSUE THREAD

**Issue by lekshmi17** [tensorflow/models#3738] opened 2018-03-25 09:53 UTC
@Mackillst
I get the following error:
 **

> Could not find a version that satisfies the requirement setup.py (from versions: )
> No matching distribution found for setup.py

**

**Comment by tensorflowbutler** [comment] 2018-04-25 06:54
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment] 2018-10-31 21:22
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Closed by ymodak** 2018-10-31 21:22 UTC
Labels: stat:awaiting response
