### ISSUE TITLE
Combine results of many trained models

### ISSUE THREAD

**Issue by kris-grig** [tensorflow/models#3595] opened 2018-03-14 14:50 UTC
Is it possible to train object detection models on different computers and see the combined results of them on one image right during detection without losing speed?

**Comment by tensorflowbutler** [comment] 2018-04-25 06:56
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-11-09 22:07
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-12-05 21:41 UTC
Labels: stat:awaiting response
