### ISSUE TITLE
inference show issues with class output are all 0 after successful convert to tflite

### ISSUE THREAD

**Issue by Ethylbenzol** [tensorflow/models#9977] opened 2021-05-06 09:08 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ x ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection

## 2. Describe the bug

I trained a model using mobilenet 640 fpn v2. After performing evaluation using model_main_tf2.py, on the tensorboard results look fine. After exporting to savedmodel using `export_tflite_graph_tf2.py`and converting to tflite, the model has missing classes. 

## 3. Steps to reproduce
Transfer learning using mobilenet 640fpn v2.

## 4. Expected behavior
Expected the model to have correct class output. instead of having a class output of :`this is the class: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]` when looking at an orange

## 5. Additional context
Logs from the raspberry pi 4b

```
starting invoke
this is the box: [[ 0.5465246   0.75056046  1.0128922   1.1003362 ]
 [ 0.51008964 -0.05100898  1.1513451   0.4153587 ]
 [ 0.00728698  0.7359865   0.48822862  1.1149101 ]
 [ 0.02914796  0.6631165   0.6485425   1.1513451 ]
 [ 0.37163672  0.74327344  0.85986537  1.1149101 ]
 [-0.2769058   0.5028026   0.7869954   1.3991029 ]
 [ 0.21132283  0.6631165   0.8307174   1.1513451 ]
 [-0.00728701 -0.05829598  0.60482055  0.4153587 ]
 [ 0.13845289 -0.05100898  0.7797084   0.4226457 ]
 [ 0.56838554  0.01457397  0.98374426  0.34248874]]
this is the class: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
this is the score: [0.454902   0.31764707 0.27450982 0.2392157  0.2392157  0.20392159
 0.1764706  0.14901961 0.14901961 0.1254902 ]
this is the count: 10
this is the results: [{'detect_boxes': array([0.5465246 , 0.75056046, 1.0128922 , 1.1003362 ], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.454902}, {'detect_boxes': array([ 0.51008964, -0.05100898,  1.1513451 ,  0.4153587 ], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.31764707}, {'detect_boxes': array([0.00728698, 0.7359865 , 0.48822862, 1.1149101 ], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.27450982}, {'detect_boxes': array([0.02914796, 0.6631165 , 0.6485425 , 1.1513451 ], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.2392157}, {'detect_boxes': array([0.37163672, 0.74327344, 0.85986537, 1.1149101 ], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.2392157}, {'detect_boxes': array([-0.2769058,  0.5028026,  0.7869954,  1.3991029], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.20392159}, {'detect_boxes': array([0.21132283, 0.6631165 , 0.8307174 , 1.1513451 ], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.1764706}, {'detect_boxes': array([-0.00728701, -0.05829598,  0.60482055,  0.4153587 ], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.14901961}, {'detect_boxes': array([ 0.13845289, -0.05100898,  0.7797084 ,  0.4226457 ], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.14901961}, {'detect_boxes': array([0.56838554, 0.01457397, 0.98374426, 0.34248874], dtype=float32), 'detect_class': 0.0, 'detect_score': 0.1254902}]
0.75056046 0.5465246 1.1003362 1.0128922
-0.051008984 0.51008964 0.4153587 1.1513451
0.7359865 0.007286975 1.1149101 0.48822862
0.6631165 0.02914796 1.1513451 0.6485425
0.74327344 0.37163672 1.1149101 0.85986537
0.5028026 -0.2769058 1.3991029 0.7869954
0.6631165 0.21132283 1.1513451 0.8307174
-0.058295976 -0.0072870143 0.4153587 0.60482055
-0.051008984 0.13845289 0.4226457 0.7797084
0.01457397 0.56838554 0.34248874 0.98374426

```

My code i use for converting to tflite

```
import numpy as np
import tensorflow as tf
import glob
import os
from PIL import Image

def representative_dataset_gen():
    path = r'D:\Development\fruits_data\oranges\test'
    path = savefolder(path)
    image_list = glob.glob(path+'/*.jpeg')

    for data in image_list:
        image = tf.io.read_file(data)
        image = tf.io.decode_image(image)
        image = image/ 127 #(128-1)
        image = tf.expand_dims(image,axis = 0) #image is already uint8
        image = tf.cast(image,tf.float32)
        #print(image)
        yield [image]
        

def savefolder(output):
    output = output.replace('\\', '/')
    return output
    
#import trained model from mobilenet 640 v2 fpp
converter = tf.lite.TFLiteConverter.from_saved_model('./exported_models/tflite/orange640/saved_model') #using tensorflow
#tflite_model = converter.convert()

#quantize the model to float16 for export
converter.experimental_new_converter = True #required for using experimental target_spec flags.
converter.optimizations = [tf.lite.Optimize.DEFAULT] 
converter.representative_dataset = representative_dataset_gen #this is not a function its is a array 
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.TFLITE_BUILTINS]

tflite_quant_model = converter.convert() #this is a generator

interpreter = tf.lite.Interpreter(model_content=tflite_quant_model)
input_type = interpreter.get_input_details()[0]['dtype']
print('input: ', input_type)
output_type = interpreter.get_output_details()[0]['dtype']
print('output: ', output_type)

# Save the model.
with open('test_model_orange_float32.tflite', 'wb') as f:
  f.write(tflite_quant_model)

```

label maps:
```
item {
  name: "orange"
  id: 1
}
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device name if the issue happens on a mobile device: Raspberrry pi 4B
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly 2.6.0.dev20210501
- Python version: 3.6
- CUDA/cuDNN version: 11.1
- GPU model and memory: rtx 2080

**Comment by srjoglekar246** [comment] 2021-05-14 16:21
Can you try converting without `optimizations` & `representative_dataset` (this will generate a FP32 model). I want to check whether the issue is with the model itself, or the quantization process.

Also what exact command do you use to run `export_tflite_graph_tf2`?

**Comment by ymodak** [comment] 2021-06-04 17:31
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2021-06-04 17:31 UTC
Labels: models:research, stat:awaiting model gardener, type:bug
