### ISSUE TITLE
[Syntaxnet] output from demo.sh is empty some times 

### ISSUE THREAD

**Issue by karthikeyansam** [tensorflow/models#4366] opened 2018-05-25 06:26 UTC
I have parsed some text to demo.sh as instructed in the documentation. I get the tree structure for some sentences but it fails with some. below are some examples

> echo "For the same acid pretreatment, extraction yields of gelatin from conventional method were lower than those obtained with priorultrasonication (P < 0.05)." | syntaxnet/demo.sh

Output:

> Input: For the same acid pretreatment , extraction yields of gelatin from conventional method were lower than those obtained with priorultrasonication -LRB- P < 0.05 -RRB- .
> Parse:
> . . ROOT

> echo "The spectra of all golden carp skin gelatins had the major peaks associated with amide bands I, II, III, A, and B, which were similar to those of gelatin from other aquatic sources (Kittiphattanabawon, et al., 2010; Sinthusamran, et al., 2014)." | syntaxnet/demo.sh

Output:

> Input: The spectra of all golden carp skin gelatins had the major peaks associated with amide bands I , II , III , A , and B , which were similar to those of gelatin from other aquatic sources -LRB- Kittiphattanabawon , et al. , 2010 ; Sinthusamran , et al. , 2014 -RRB- .
> Parse:
> . . ROOT

**Comment by tensorflowbutler** [comment] 2018-05-27 03:26
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by karthikeyansam** [comment] 2018-05-29 15:22
Actually, I am working on the tensorflow/syntaxnet docker. the present working directory was /opt/tensorflow/syntaxnet where demo.sh were found inside docker.

Syntaxnet was installed from docker referring 6th point of the document [https://github.com/tensorflow/models/blob/master/research/syntaxnet/g3doc/CLOUD.md]

Have I written custom code - No
OS Platform and Distribution - Ubunut 16.04
TensorFlow installed from - docker
TensorFlow version - 1.0.1
Bazel version - 0.11.1
CUDA/cuDNN version - NA
GPU model and memory - N/A
Exact command to reproduce
echo "The spectra of all golden carp skin gelatins had the major peaks associated with amide bands I, II, III, A, and B, which were similar to those of gelatin from other aquatic sources (Kittiphattanabawon, et al., 2010; Sinthusamran, et al., 2014)." | syntaxnet/demo.sh

**Comment by karmel** [comment] 2018-06-02 20:37
Can you clarify what you expect the outcome to be, and what you think is missing here?

**Comment by ymodak** [comment] 2018-11-09 22:09
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-11-09 22:09 UTC
Labels: stat:awaiting response
