### ISSUE TITLE
How to write xml_to_csv in binary form

### ISSUE THREAD

**Issue by xueqing311** [tensorflow/models#8609] opened 2020-06-02 09:14 UTC
Hi, I am doing a multi-label image classification project, but I dont know how to write xml to csv file in binary form, means it will turn 1 if the label exist and 0 if not exist, can anyone teach me how to write? or provide me some reference?
I really appreciate your precious help!

-->

**Comment by ravikyram** [comment] 2020-06-02 09:54
@xueqing311 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ravikyram** [comment] 2020-07-02 09:34
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-02 09:34 UTC
Labels: type:support
