### ISSUE TITLE
ResNet 50 scaling problem in CTL mode of TF2.0 container

### ISSUE THREAD

**Issue by kaixih** [tensorflow/models#7842] opened 2019-11-21 01:23 UTC
### System information
- **What is the top-level directory of the model you are using**: official/vision/image_classification
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: TF2.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA 10.0 cuDNN 7.5
- **GPU model and memory**: DGX1V100 8 GPUs 32GB
- **Exact command to reproduce**:

Pull the container of tensorflow/tensorflow:2.0.0-gpu-py3
```
python -u resnet_ctl_imagenet_main.py --model_dir=Y5tmUO.dir \
--data_dir=/data/imagenet/train-val-tfrecord-480 \
--batch_size=2048 --num_gpus=8 --dtype=fp16 \
--train_epochs=1 --train_steps=400 --use_synthetic_data=false \
--enable_tensorboard=false --single_l2_loss_op=true --use_tf_function=true 
```

### Describe the problem
The performance of ResNet 50 in the CTL mode scales pretty bad for 8 GPUs. The 4 GPUs can get ~2100 imgs/sec. The perf of 8 GPUs is close to 4 GPUs, only achieving ~2900 images/sec for fp16 inputs. 

After some digging, I found the data loading could be the problem and it got serialized among GPUs. I observed that one thread might be taking care of multiple GPUs for data loading and for some reason only after one data loading is finished on one GPU, the thread will issue the next loading for another GPU. The snapshot of the profiling is below. The green parts are the data loading, while the blue ones are kernel computations. In comparison, the 4 GPU case has no such problem.

### Source code / logs
8 GPUs:
![image](https://user-images.githubusercontent.com/4001424/69291231-5d45d600-0bb7-11ea-9cc7-a228441c93b1.png)

4 GPUs:
![image](https://user-images.githubusercontent.com/4001424/69292178-4ce32a80-0bba-11ea-897f-1412cad38439.png)

FYI @nluehr

**Comment by saberkun** [comment] 2019-11-21 01:36
@zongweiz @yuefengz 
Thank you! Yeah, I think Zongwei also found some scaling issue.

**Comment by saberkun** [comment] 2019-11-21 01:38
Do you also test the current master?
The problem you mentioned might be related to https://github.com/tensorflow/models/commit/8a5702f20cf024563bfbf5845e55a3c1fde23960#diff-280730fb811d626fdad70f685e6c4091

**Comment by zongweiz** [comment] 2019-11-21 04:56
Could you try --datasets_num_private_threads=14 --tf_gpu_thread_mode = 'gpu_private' to see if this resolve the input issue?

**Comment by houtoms** [comment] 2019-11-21 19:21
@zongweiz Thx. I just tried these two options but they can only help to improve the perf by ~200 imgs/sec for 8 GPUs.

@saberkun I think I am using the current master. I can see those lines your referred to have already been deleted. Or do you mean I need to add them back? 

For the container, I have also tried the nightly build of tf2.1, the scaling becomes better, from 2519.26 (4GPU) to 4539.29 (8GPU). But I think we are expecting the perf to be around 6000 to 7000 for 8 GPUs.

**Comment by saberkun** [comment] 2019-11-21 19:32
I mean they should be deleted.
Thanks, Zongwei. It seems to be a tf.data issue.
@houtoms  @zongweiz I feel you guys can work together to get a best setting for 8 gpus in readme?

**Comment by zongweiz** [comment] 2019-11-21 19:58
Hi Kaixi, do you mind running the same testing (FP16) using the compile/fit version of the Resnet code? We have seen about 7800 images/second on 8GPU for compile/fit version of Resnet.

**Comment by houtoms** [comment] 2019-11-21 20:02
I recently ran the compile/fit mode and can get ~7500 img/sec in TF2 containers. But still, for nightly build (TF2.1), the perf drops to ~6500 imgs/sec. Anyway, both of them are much better than CTL mode.

**Comment by zongweiz** [comment] 2019-11-21 21:42
Thanks @houtoms. Will try to reproduce it and compare with our internal results.
FYI @reedwm

**Comment by houtoms** [comment] 2019-11-22 01:00
Just profiled the compile/fit mode, I found the data copy is from the pinned mem and I can see it gets overlapped with compute kernels. But, in the CTL mode, the data copy is from the pageable mem and do you know any idea why? Thx.

**Comment by zongweiz** [comment] 2019-12-03 00:45
@houtoms I have reproduced this issue. Even using synthetic data (input data generated on GPU), I can see degraded 8GPU performance. So I think this maybe related to FP16. @reedwm will follow up on this.

@nnigania could you please take a look at this pinned/pagable memory issue?

**Comment by nnigania** [comment] 2019-12-05 01:49
@houtoms: i am looking at the memory copy issue. Which memory copy you are seeing to be from pagable memory? I think there is one memory copy of 400 bytes which seems to happen at the same time as input data copy. And the input data copy blocks the 400 byte copy which is scheduled to run on the compute stream. This 400 byte copy is not there in the compile/fit mode.

**Comment by houtoms** [comment] 2019-12-05 17:38
@nnigania My observation is the compile/fit uses pinned memory (dark green in my above comment) with overlapped compute. The CTL uses pageable memory (light green in my original issue description) with serialized data copy blocks.

**Comment by allenwang28** [comment] 2021-02-09 18:43
For ResNet CTL with 8 V100s and fp16 on TF 2.4, we expect around 7k examples/sec which is much higher than the 2900 ex/sec reported originally.

I am closing this out due to staleness, feel free to follow up if this still affects you.

**Closed by allenwang28** 2021-02-09 18:43 UTC
Labels: models:official, type:performance
