### ISSUE TITLE
Object Detection: Error('TrainConfig' object has no attribute 'ignore_groundtruth') when 'eval.py' the model with flag --eval_training_data set to True

### ISSUE THREAD

**Issue by youthHan** [tensorflow/models#2479] opened 2017-09-29 02:05 UTC
### System information
- **/research/object_detection**:
- **prepare my own data and use the default ssd_inceptionv2_coco model**:
- **Linux Ubuntu 16.04**:
- **TensorFlow installed from source**:
- **TensorFlow version 1.2.0**:

### Describe the problem
Error occurs as below when I evaluate the model with the flag --eval_training_data=True. The model is the one which I trained with the default ssd_inceptionv2_coco config, using my own prepared data.

It seems that 
`model_config = pipeline_config.model
 if FLAGS.eval_training_data:
    eval_config = pipeline_config.train_config` in `eval.py`, but the `train.proto` doesn't provide the 'ignore_groundtruth' field.

### Source code / logs
```
Traceback (most recent call last):
  File "eval.py", line 161, in <module>
    tf.app.run()
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 157, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/home/ai-i-hanmingfei/proj/models/research/object_detection/evaluator.py", line 125, in evaluate
    if eval_config.ignore_groundtruth and not eval_config.export_path:
AttributeError: 'TrainConfig' object has no attribute 'ignore_groundtruth'

```
and when I add the `ignore_groungtruth=True ` in the `train_config` of `ssd_inceptionv2_coco.config`. Error occurs:
```
Traceback (most recent call last):
  File "eval.py", line 161, in <module>
    tf.app.run()
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 138, in main
    model_config, eval_config, input_config = get_configs_from_pipeline_file()
  File "eval.py", line 94, in get_configs_from_pipeline_file
    text_format.Merge(f.read(), pipeline_config)
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 481, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 535, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 568, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 583, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 684, in _MergeField
    merger(tokenizer, message, field)
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 773, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/ai-i-usr/tools/lpy3/lib/python3.5/site-packages/google/protobuf/text_format.py", line 652, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 167:3 : Message type "object_detection.protos.TrainConfig" has no field named "ignore_groundtruth".
```

**Comment by cy89** [comment] 2017-10-09 00:38
@youthHan I'm sorry, I can't tell which files in our directory structure you're referring to. Searches for ssd_inceptionv2_coco don't yield any results (except this bug). Can you tell us more about how to reproduce your problem?

**Comment by cstj** [comment] 2017-10-09 01:43
The file is one of the training config files (if they have hte same error as me).
The config file is at 'research\object_detection\samples\configs'.
Im getting the same error using 'faster_rcnn_resnet50_coco.config'.

**Comment by harshini-gadige** [comment] 2018-11-08 19:22
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2020-01-29 23:33
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:43 UTC
Labels: stat:awaiting response
