### ISSUE TITLE
Transformer: training failed at 3k steps on TPU

### ISSUE THREAD

**Issue by dguo98** [tensorflow/models#8363] opened 2020-04-05 22:10 UTC
I followed the official Transformer-2.x tutorial to train a Transformer Translation model on WMT, but training failed after 3k steps.
Tutorial: https://cloud.google.com/tpu/docs/tutorials/transformer-2.x

I checked that the instructions are up-to-date with transformer README here, and the code provided by the tutorial is the same as the 2.1.0 release of this repository: https://github.com/tensorflow/models/archive/v2.1.0.tar.gz

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Cloud TPU v3-8
- TensorFlow version (use command below): 2.1
- Python version: 3.7.3

I followed exact instructions from Transformer-2.x tutorial to create my VM/TPU:  https://cloud.google.com/tpu/docs/tutorials/transformer-2.x

**Please provide the entire URL of the model you are using?**
official/transformer models in: 
https://github.com/tensorflow/models/archive/v2.1.0.tar.gz

OR

/usr/share/models/official/transformer on Cloud TPU

**Describe the current behavior**
Training failed after 3k steps during evaluation. 

It seems that different runs will fail at different # of steps. Previously, it failed at 6k steps.

**Describe the expected behavior**
The model is able to train 200k steps with full convergence.

**Code to reproduce the issue**
The codebase in the tutorial is the same as https://github.com/tensorflow/models/archive/v2.1.0.tar.gz

I followed the steps here: https://cloud.google.com/tpu/docs/tutorials/transformer-2.x

Training command is: python3 transformer_main.py --tpu=$TPU_NAME --model_dir=$MODEL_DIR --data_dir=$GCS_DATA_DIR --vocab_file=$GCS_DATA_DIR/vocab.ende.32768 --bleu_source=$GCS_DATA_DIR/newstest2014.en --bleu_ref=$GCS_DATA_DIR/newstest2014.de --batch_size=6144 --train_steps=200000 --static_batch=true --use_ctl=true --param_set=big --max_length=64 --decode_batch_size=32 --decode_max_length=97 --padded_decode=true --distribution_strategy=tpu

**Other info / logs**

  File "transformer_main.py", line 383, in eval
    distribution_strategy)
  File "transformer_main.py", line 118, in evaluate_and_log_bleu
    model, params, subtokenizer, bleu_source, bleu_ref, distribution_strategy)
  File "transformer_main.py", line 88, in translate_and_compute_bleu
    uncased_score = compute_bleu.bleu_wrapper(bleu_ref, tmp_filename, False)
  File "/usr/share/models/official/transformer/compute_bleu.py", line 96, in bleu_wrapper
    raise ValueError("Reference and translation files have different number of "
ValueError: Reference and translation files have different number of lines. If training only a few steps (100-200), the translation may be empty.

2020-04-05 20:40:41.852968: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:79] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find a context_id matching the specified one (16973409415646534521). Perhaps the worker was restarted, or the context was GC'd?
Additional GRPC error information:
{"created":"@1586119241.852831589","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Unable to find a context_id matching the specified one (16973409415646534521). Perhaps the worker was restarted, or the context was GC'd?","grpc_status":3}

**Comment by saberkun** [comment] 2020-04-06 00:39
The error might be caused by (1) wait to long to get grpc back from TPU. How long does "1000 steps" take? https://github.com/tensorflow/models/blob/master/official/nlp/transformer/misc.py#L98. You may reduce this.
(2) Does the Cloud TPU get preempted?

I would like to let cloud tpu team follow up on this issue.

**Comment by saberkun** [comment] 2020-04-06 00:40
@gagika @allenwang28 @tensorflow/cloud

**Comment by dguo98** [comment] 2020-04-06 04:42
@saberkun  
Thanks so much for the quick reply!

I checked that the TPU did not get preempted. I tried to play around with "steps_between_evals" as you suggested. When I set "steps_between_evals" = 500 or 1000 or 2000, it doesn't work. However, when I set "steps_between_evals" = 10000, it works.

I saw the error message comes from "Reference and translation files have a different number of lines. If training only a few steps (100-200), the translation may be empty." in compute_bleu.py

So it seems that the generated hypothesis translation is empty, even though it already trained for 2000 steps... I wonder if that implies that the model has a different optimization behavior than before...

Currently, after 200k steps, I got a BLEU score (cased) 26.23. I assume it's WMT14 test set. I saw on the Attention is all you need paper, it got around 28.4 BLEU score, and in Tensor2Tensor repo, it also says it should get around 28 BLEU score.
I wonder if it's expected to get a 26.23 BLEU score? or is it related to this error?

Thanks so much for the help!

**Comment by saberkun** [comment] 2020-04-06 05:58
On TPU, there are a few tricky things: (1) batch size, if the global batch size goes bigger and total steps become smaller, the same params will not work. (2) I think this model should get 28 but it needs to run more steps. I tried 300000 and probably need more. The reason is T2T used packed inputs and GPU implementation used bagging to enable dynamic sequence length, whereas this TPU implementation just does padding. (3) T2T reports the best bleu score (?) throughout training?

**Comment by gagika** [comment] 2020-04-27 18:53
Thanks @dguo98 for reporting the crash, I could reproduce it. We will troubleshoot and fix it.

In our convergence tests we use:
batch_size = 24576
train_steps = 240000
steps_between_evals = 10000 (this won't effect convergence but will eliminate too often evaluation). 
Which gets close to 28, I am running now with those parameters and will post the bleu score.

**Comment by saberkun** [comment] 2020-04-27 23:27
basically, this is because we need to have it run 10K steps until it does not crash the bleu score evaluation.
Closing this issue. Thanks

**Closed by saberkun** 2020-04-27 23:27 UTC
Labels: models:official, stat:awaiting response, type:bug

**Comment by gagika** [comment] 2020-04-28 02:57
With batch_size = 24576, it gets above 28 score at step:180000

Bleu score (uncased): 28.047150373458862
Bleu score (cased): 27.56108045578003
