### ISSUE TITLE
Error while using mnist dataset -Negative dimension  size caused by subtracting 3 from 1 for 'AttentionOcr_v1/conv_tower_fn/INCE/Inc eptionV3/Conv2d_4a_3x3/Conv2D' (op: 'Conv2D')  

### ISSUE THREAD

**Issue by ATS-Official** [tensorflow/models#5515] opened 2018-10-13 09:53 UTC
Trying to test the model on the mnist dataset and encountered this error.

Tensorflow Version: 1.10 
OS: Windows 10
Installation: Anaconda (Python 3.6)

python train.py --checkpoint_inception=./datasets/inception_v3.ckpt --data
set_name=newtextdataset

INFO 2018-10-13 05:41:51.000365: train.py: 167 Use already existing training dir
ectory /tmp/attention_ocr/train
INFO 2018-10-13 05:41:51.000366: fsns.py: 130 Using MYDATASET dataset split_name
=train dataset_dir=D://***//tensorflow_models//models-master//research//
attention_ocr//python//datasets//data//fsns
DEBUG 2018-10-13 05:41:52.000233: model.py: 354 images: Tensor("shuffle_batch:0"
, shape=(32, 100, 48, 3), dtype=float32)
DEBUG 2018-10-13 05:41:52.000237: model.py: 359 Views=4 single view: Tensor("Att
entionOcr_v1/split:0", shape=(32, 100, 12, 3), dtype=float32)
DEBUG 2018-10-13 05:41:52.000238: model.py: 200 Using final_endpoint=Mixed_5d
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda\envs\TFCore\lib\site-packages\tensorflow\python
\framework\ops.py", line 1576, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension
 size caused by subtracting 3 from 1 for 'AttentionOcr_v1/conv_tower_fn/INCE/Inc
eptionV3/Conv2d_4a_3x3/Conv2D' (op: 'Conv2D') with input shapes: [32,23,1,80], [
3,3,80,192].

**Comment by tensorflowbutler** [comment] 2018-10-13 19:44
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2020-01-29 23:07
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:36 UTC
