### ISSUE TITLE
Neural_programmer bug

### ISSUE THREAD

**Issue by AjayTalati** [tensorflow/models#1400] opened 2017-04-25 10:12 UTC
Hi, 

I keep getting this error trying to run `python neural_programmer.py`,

```
(tf_py2_tf_1_0) ajay@ajay-h8-1170uk:~/PythonProjects/TF_models_v1/neural_programmer$ python neural_programmer.py
Annotated examples loaded  14152
Annotated examples loaded  4344
entry match token:  9133 9133
entry match token:  9134 9134
# train examples  10178
# dev examples  2546
# test examples  3913
running open source
forget gate bias
Traceback (most recent call last):
  File "neural_programmer.py", line 237, in <module>
    tf.app.run()
  File "/home/ajay/anaconda3/envs/tf_py2_tf_1_0/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "neural_programmer.py", line 233, in main
    master(train_data, dev_data, utility)
  File "neural_programmer.py", line 160, in master
    graph.create_graph(params, global_step)
  File "/home/ajay/PythonProjects/TF_models_v1/neural_programmer/model.py", line 636, in create_graph
    self.total_cost = self.compute_error() 
  File "/home/ajay/PythonProjects/TF_models_v1/neural_programmer/model.py", line 582, in compute_error
    1, [self.batch_number_column_mask, self.batch_word_column_mask])
  File "/home/ajay/anaconda3/envs/tf_py2_tf_1_0/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/ajay/anaconda3/envs/tf_py2_tf_1_0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/home/ajay/anaconda3/envs/tf_py2_tf_1_0/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ajay/anaconda3/envs/tf_py2_tf_1_0/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/ajay/anaconda3/envs/tf_py2_tf_1_0/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/ajay/anaconda3/envs/tf_py2_tf_1_0/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/ajay/anaconda3/envs/tf_py2_tf_1_0/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

- **What is the top-level directory of the model you are using**:
https://github.com/tensorflow/models/tree/master/neural_programmer

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04

- **TensorFlow installed from (source or binary)**:
binary

- **TensorFlow version (use command below)**:

('v1.1.0-rc0-61-g1ec6ed5', '1.1.0')

- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:

CPU mode

- **Exact command to reproduce**:

python neural_programmer.py

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by girving** [comment] 2017-04-25 16:34
@arvind2505: Are you still maintaining this?  If not, it's probably pull requests only.

**Comment by AjayTalati** [comment] 2017-04-25 21:42
Hi @girving and @arvind2505, I got it working - it was mainly changes to TF1.0. Unfortunately I can only train it on my laptop cpu, at the moment - so can't really tell if the upgrades I made broke it or not?

```
step  7000   215.335927963  seconds 
 printing train set loss:  1.47195385396
step  7050   222.801156044  seconds 
 printing train set loss:  1.6384768395
step  7100   226.014200926  seconds 
 printing train set loss:  1.56280194713
step  7150   227.320056915  seconds 
 printing train set loss:  1.41352441184
step  7200   221.069719076  seconds 
 printing train set loss:  1.40199346144
step  7250   220.439342976  seconds 
 printing train set loss:  1.52649425993
step  7300   229.211657047  seconds 
 printing train set loss:  1.48760166748
step  7350   224.157803059  seconds 
 printing train set loss:  1.54136846007
step  7400   236.74157095  seconds 
 printing train set loss:  1.40795774516
step  7450   222.247289896  seconds 
 printing train set loss:  1.49486836895
step  7500   220.005492926  seconds 
 printing train set loss:  1.50299457257
```

**Comment by girving** [comment] 2017-04-25 23:09
PRs welcome if you fixed stuff!

**Comment by arvind2505** [comment] 2017-04-26 09:45
thanks @AjayTalati Please send a PR if possible
@girving I have still not migrated to TF 1.0. I don't think I will do a good job answering questions on the latest versions. Do you want me to change to pull requests only ? Thanks!

**Comment by girving** [comment] 2017-04-26 14:20
@arvind2505 Maybe add a note that you're not actively maintaining, but leave your name there.

**Comment by karmel** [comment] 2018-02-24 18:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by karmel** 2018-02-24 18:57 UTC
Labels: stat:contributions welcome, type:bug/performance

**Comment by YoPatapon** [comment] 2018-11-12 08:42
Hi Ajay, I noticed that your model converged with a loss of ~1.50. Did you reproduce the results mentioned in the paper? 
I used the default parameters in the code, however my model converged with a loss of 1.80~2.0. How did you train your model to achieve such a low loss?

**Comment by YoPatapon** [comment] 2018-11-12 08:42
Hi Ajay, I noticed that your model converged with a loss of 1.50. Did you reproduce the results mentioned in the paper? I used the default parameters in the code, however my model converged with a loss of 1.802.0. How did you train your model to achieve such a low loss?
