### ISSUE TITLE
module not found error during import of official.vision.beta.modeling (version 2.4.0)

### ISSUE THREAD

**Issue by NandreyN** [tensorflow/models#9657] opened 2021-01-22 12:56 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/r2.4.0/official/vision/beta/modeling

## 2. Describe the bug

During import of `official.vision.beta.modeling` ModuleNotFoundError occurs:
ModuleNotFoundError: No module named 'official.vision.beta.dataloaders'

## 3. Steps to reproduce

See colab notebook with steps:
https://colab.research.google.com/drive/13BPK37UzFjb2khfWOqTjnOucHCt2ZPRJ?usp=sharing

## 4. Expected behavior

Expected import with no errors

## 5. Additional context

Stack trace:
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-ebb43d816ee9> in <module>()
----> 1 import official.vision.beta.modeling.backbones as backbones
      2 import official.vision.beta.modeling.decoders as decoders

2 frames
/usr/local/lib/python3.6/dist-packages/official/vision/beta/__init__.py in <module>()
     17 # pylint: disable=unused-import
     18 from official.vision.beta import configs
---> 19 from official.vision.beta import tasks

/usr/local/lib/python3.6/dist-packages/official/vision/beta/tasks/__init__.py in <module>()
     16 """Tasks package definition."""
     17 
---> 18 from official.vision.beta.tasks import image_classification
     19 from official.vision.beta.tasks import maskrcnn
     20 from official.vision.beta.tasks import retinanet

/usr/local/lib/python3.6/dist-packages/official/vision/beta/tasks/image_classification.py in <module>()
     21 from official.modeling import tf_utils
     22 from official.vision.beta.configs import image_classification as exp_cfg
---> 23 from official.vision.beta.dataloaders import classification_input
     24 from official.vision.beta.modeling import factory
     25 

ModuleNotFoundError: No module named 'official.vision.beta.dataloaders'`

## 6. System information

See the first cell in google colab notebook
Tensorflow: v2.4.0-0-g582c8d236cb 2.4.0

**Comment by saikumarchalla** [comment] 2021-01-22 17:05
@NandreyN  If you are using colab, please set your python path correctly. Add the below code and then try it again. Hope it helps. 

```
import os 
os.environ['PYTHONPATH'] += ":/path/to/models"
```

**Comment by NandreyN** [comment] 2021-01-22 21:52
@saikumarchalla  Thanks for the response. The problem initially was discovered not in colab. However, I have just updated the notebook according to your response. Could you please have a look one more time?

**Comment by saikumarchalla** [comment] 2021-01-26 17:39
@NandreyN  I  could able to import all the modules properly. Please check the gist [here](https://colab.research.google.com/gist/saikumarchalla/e4b507cee38456b5eb077f4428f47182/-8291.ipynb).

Aslo please  go through the  official [documentation](https://github.com/tensorflow/models/blob/r2.4.0/official/README.md) and this [issue](https://github.com/tensorflow/models/issues/8291) for additional information. Hope it will fix your issue. Thanks!

**Comment by NandreyN** [comment] 2021-01-26 20:00
@saikumarchalla
That works, but it is not the solution, because I need pip-package, not a fork of the repo

**Comment by NandreyN** [comment] 2021-01-26 20:06
@saikumarchalla
Just trying to say that there is probably a problem with pip-package.
Issue you`ve linked uses clone of the repo from the beggining, not a package.

**Comment by saberkun** [comment] 2021-02-05 20:00
@chenGitHuber @arashwan

**Comment by arashwan** [comment] 2021-02-08 06:59
I think that issue is caused by missing __init__.py files inside some folders. For some reason, pip excludes folders that don't include __init__.py files. The following commit should fix the issue (https://github.com/tensorflow/models/commit/736f653c1377e9f16ee9dec5ccb4186538bc45f9), you will need to install using ```pip install tf-models-nightly``` until the 2.4.0 version is fixed.

**Comment by saikumarchalla** [comment] 2021-04-14 06:16
@NandreyN Closing this issue since the issue is resolved now. Please feel free to reopen the issue if needed. Thanks!

**Closed by saikumarchalla** 2021-04-14 06:16 UTC
Labels: models:official, type:support
