### ISSUE TITLE
Please create the Java version of word2vec tutorial!! Plus improve docs

### ISSUE THREAD

**Issue by OtakuSenpai** [tensorflow/models#5288] opened 2018-09-11 22:33 UTC
### System information
- **What is the top-level directory of the model you are using**: None, I can't make a demo even
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Void Linux, latest
- **TensorFlow installed from (source or binary)**: Tried the source as well as binary
- **TensorFlow version (use command below)**: 1.10.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**:

### Describe the problem
 I want to create a natural language parser, one that emits grammerly correct words from a dataset.
I tried the repos for tensorflow in java but they were only for images. Also I tried the tutorials on word2vec but they were in python. Also documentation such as
 Session sess = new Session.....
 sess.runner().feed() 
This feed() function requires some operation parameters, which aren't stated in the docs. 
Thank you.

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:41
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:41 UTC
