### ISSUE TITLE
No OpKernel was registered to support Op 'Slice' with these attrs

### ISSUE THREAD

**Issue by wanghuijing** [tensorflow/models#4212] opened 2018-05-09 01:50 UTC
I have use frozen_inference_graph.pb and libtensorflow_inference-new.so in android demo,but there is error when run model.How to fix it?Here is the informations.

05-08 08:58:07.617 27942 27942 E TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[ImageTensor:0], outputs:[SemanticPredictions:0]
05-08 08:58:07.617 27942 27942 W System.err: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Slice' with these attrs.  Registered devices: [CPU], Registered kernels:
05-08 08:58:07.617 27942 27942 W System.err:   device='CPU'; T in [DT_BFLOAT16]
05-08 08:58:07.617 27942 27942 W System.err:   device='CPU'; T in [DT_BOOL]
05-08 08:58:07.617 27942 27942 W System.err:   device='CPU'; T in [DT_FLOAT]
05-08 08:58:07.617 27942 27942 W System.err:   device='CPU'; T in [DT_INT32]
05-08 08:58:07.617 27942 27942 W System.err: 	 [[Node: SemanticPredictions = Slice[Index=DT_INT32, T=DT_INT64](ArgMax, SemanticPredictions/begin, SemanticPredictions/size)]]

**Comment by tensorflowbutler** [comment] 2018-05-10 01:30
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kismeter** [comment] 2018-05-10 07:37
I believe tensorflow mobile has no support for INT64 currently, from the logs, we can see that only INT32, FLOAT, BOOL,BFLOAT16 is registed, no INT64

**Comment by robieta** [comment] 2018-06-03 19:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by robieta** 2018-06-03 19:02 UTC
Labels: stat:awaiting response

**Comment by PrinceP** [comment] 2018-06-07 02:40
Did you resolved this ?
Is dependency of tf will support INT64 ?

**Comment by helloItzMe** [comment] 2019-09-06 07:58
Having same issue. Please post a solution
