### ISSUE TITLE
Using model_ main.py training will appear midway stop phenomenon, but use train.py Will not appear

### ISSUE THREAD

**Issue by dreamitpossible1** [tensorflow/models#9116] opened 2020-08-17 02:35 UTC
WARNING:tensorflow:From C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\saver.py:963: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.
W0817 10:25:09.366577  1052 deprecation.py:323] From C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\saver.py:963: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.
Windows fatal exception: access violation

Thread 0x000023dc (most recent call first):
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\threading.py", line 295 in wait
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\queue.py", line 164 in get
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\summary\writer\event_file_writer.py", line 159 in run
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\threading.py", line 916 in _bootstrap_inner
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\threading.py", line 884 in _bootstrap

Current thread 0x0000041c (most recent call first):
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 392 in <listcomp>
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 390 in get_matching_files_v2
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 363 in get_matching_files
  File "D:\tf_train\models\research\object_detection\builders\dataset_builder.py", line 75 in read_dataset
  File "D:\tf_train\models\research\object_detection\builders\dataset_builder.py", line 184 in build
  File "D:\tf_train\models\research\object_detection\inputs.py", line 992 in eval_input
  File "D:\tf_train\models\research\object_detection\inputs.py", line 856 in _eval_input_fn
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1116 in _call_input_fn
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1025 in _get_features_and_labels_from_input_fn
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1544 in _call_model_fn_eval
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1511 in _evaluate_build_graph
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 504 in _evaluate
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 522 in _actual_eval
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 480 in evaluate
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 920 in evaluate_and_export
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 539 in _evaluate
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 519 in after_save
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\basic_session_run_hooks.py", line 619 in _save
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\basic_session_run_hooks.py", line 594 in after_run
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1426 in run
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1345 in run
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1259 in run
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 754 in run
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1494 in _train_with_estimator_spec
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1195 in _train_model_default
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1161 in _train_model
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370 in train
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 714 in run_local
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 613 in run
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 473 in train_and_evaluate
  File "model_main.py", line 105 in main
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 250 in _run_main
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 299 in run
  File "C:\Users\dw\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\platform\app.py", line 40 in run
  File "model_main.py", line 109 in <module>

(tensorflow) D:\tf_train\workspaces\my_training_demo3>python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-08-17 10:25:54.426740: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
>>> tf.test.is_built_with_cuda()
True
>>> tf.test.is_gpu_available(cuda_only=False,min_cuda_compute_capability=None)
2020-08-17 10:26:03.990248: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-08-17 10:26:04.016429: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-08-17 10:26:04.091491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:65:00.0
2020-08-17 10:26:04.108600: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-08-17 10:26:04.143000: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-08-17 10:26:04.180673: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-08-17 10:26:04.200179: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-08-17 10:26:04.237160: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-08-17 10:26:04.259150: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-08-17 10:26:04.319001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-08-17 10:26:04.327782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-08-17 10:26:05.132927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-17 10:26:05.141458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-08-17 10:26:05.146601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-08-17 10:26:05.152222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 6306 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:65:00.0, compute capability: 7.5)
True
>>> exit()

**Comment by saikumarchalla** [comment] 2020-08-17 06:48
@dreamitpossible1 Could you please fill the issue [template](https://github.com/tensorflow/models/issues/new/choose).

If possible, share colab link or simple stand alone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by saikumarchalla** [comment] 2020-08-26 11:20
@dreamitpossible1  Any update on this?

**Comment by saikumarchalla** [comment] 2020-09-15 04:36
@dreamitpossible1  Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by saikumarchalla** 2020-09-15 04:36 UTC
Labels: stalled, stat:awaiting response, type:support
