### ISSUE TITLE
Feature Request: ptb_word_lm.py  do not generate metadata.tsv for Tensorboard

### ISSUE THREAD

**Issue by davin83803** [tensorflow/models#3495] opened 2018-02-28 23:02 UTC
Dear Tensorflow team, 

I have been working with the PTB language model from your tensorflow tutorial. 
The files I am using are the files form:
https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb

I haven't modified any line of code. 

When I run you code with the command "python ptb_word_lm.py --data_path=simple-examples/data/  --save_path=results/ --model=medium", eveything works perfecty.
My issue is  that when I visualize the results in tensorboard with the command "tensorboard --logdir=results/", I only see the words IDs (numbers) and I would like to see the vocabulary (words).

See my screenshot: 
![screenshot](https://user-images.githubusercontent.com/17074383/36817725-8b1c9c3c-1ce2-11e8-8f47-8a259a930867.jpg)

Does the code usually generates a metadata.tsv file? When not, how should I proceed to make the code geneate the above mentionned metadata?

I've been trying to find a solution to this issue for the last two days an I would be more than gratefull if you could help me out.

Thanks a lot for your answers.

Kind regards

**Comment by tensorflowbutler** [comment] 2018-04-25 06:55
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by harshini-gadige** [comment] 2018-10-31 21:14
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-10-31 21:14 UTC
Labels: stat:awaiting response
