### ISSUE TITLE
tutorial/image/cifar10 Evaluation file encounters TensorShape error

### ISSUE THREAD

**Issue by richardxiong** [tensorflow/models#837] opened 2017-01-01 23:06 UTC
**tensorflow/models/tutorial/image/cifar10/cifar10_eval.py**

Hello everyone,

I have been playing with the CNN tutorial. The training process was good and I stored the checkpoint for evaluation, but when I ran the evaluation, I encountered the error like this:

Traceback (most recent call last):
  File "cifar10_eval.py", line 157, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "cifar10_eval.py", line 153, in main
    evaluate()
  File "cifar10_eval.py", line 121, in evaluate
    images, labels = cifar10.inputs(eval_data=eval_data)
  File "/Users/richard_xiong/Documents/DeepLearningMaster/CNN/cifar10.py", line 182, in inputs
    batch_size=FLAGS.batch_size)
  File "/Users/richard_xiong/Documents/DeepLearningMaster/CNN/cifar10_input.py", line 254, in inputs
    shuffle=False)
  File "/Users/richard_xiong/Documents/DeepLearningMaster/CNN/cifar10_input.py", line 132, in _generate_image_and_label_batch
    capacity=min_queue_examples + 3 * batch_size)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 683, in batch
    capacity=capacity, dtypes=types, shapes=shapes, shared_name=shared_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 666, in __init__
    shapes = _as_shape_list(shapes, dtypes)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 75, in _as_shape_list
    raise ValueError("All shapes must be fully defined: %s" % shapes)
**ValueError**: All shapes must be fully defined: [TensorShape([Dimension(24), Dimension(24), Dimension(3)]), TensorShape([Dimension(None)])]

Does anyone have any ideas? Thanks!

**Comment by YontiLevin** [comment] 2017-01-02 10:04
just encountered the same problem
solved it by adding this line of code to the bottom of cifar10_input.py
```
if eval_data:
    read_input.label.set_shape((1,))
```
just one line before the **return _generate_image...**

**Comment by richardxiong** [comment] 2017-01-02 17:27
@YontiLevin Thanks dude! Just solved issue.

**Comment by omo** [comment] 2017-01-04 22:51
@richardxiong I guess you can close the issue?

**Comment by nealwu** [comment] 2017-03-16 05:43
Hi all, do you know why you need to set the shape in this way? When I run the code, `read_input.label.shape` is already `(1,)`. I'm curious whether this is still an issue.

**Comment by nealwu** [comment] 2017-04-10 23:49
I closed the pull request since I'm unable to reproduce the problem described. If it's still an issue, feel free to let me know / reopen.

**Closed by nealwu** 2017-04-10 23:49 UTC
