### ISSUE TITLE
issue in convert the ImageNet data to native TFRecord format 

### ISSUE THREAD

**Issue by priyashkla** [tensorflow/models#6141] opened 2019-02-02 18:46 UTC
![image](https://user-images.githubusercontent.com/33479052/52167918-a459fc00-2748-11e9-88e4-c48c01813ca3.png)

**Comment by tensorflowbutler** [comment] 2019-02-03 12:15
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by priyashkla** [comment] 2019-02-04 09:53
code :https://github.com/tnikolla/robot-grasp-detection
OS Platform and Distribution: ubuntu 16.04 LTS
tensorflow:1.12.0 cpu only
bazel:0.22.0
GPU model and memory:NVA8 and 15.6 GiB
after runnung this command
# run it
bazel-bin/inception/download_and_preprocess_imagenet "${DATA_DIR}"
![image](https://user-images.githubusercontent.com/33479052/52201158-b5ae2000-2890-11e9-9b83-d588b4c68b45.png)

**Comment by auslaner** [comment] 2019-03-08 23:10
It's difficult to tell what the issue is when you only include screenshots. Please try including the command you're having trouble with along with the error output of that command.

**Comment by ymodak** [comment] 2019-05-22 21:23
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-05-22 21:23 UTC
