### ISSUE TITLE
RuntimeError when I use deeplab to train our dataset.

### ISSUE THREAD

**Issue by wjx2** [tensorflow/models#4697] opened 2018-07-04 14:10 UTC
Please help!
RuntimeError: Init operations did not make model ready.  Init op: init_ops/init, init fn: None, local_init_op: name: "init_ops/group_deps"
op: "NoOp"

**Comment by tensorflowbutler** [comment] 2018-07-05 00:59
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment] 2018-12-05 21:54
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-12-05 21:54 UTC
Labels: stat:awaiting response
