### ISSUE TITLE
How to export model.ckpt file to  SavedModel?

### ISSUE THREAD

**Issue by rhosseini** [tensorflow/models#7838] opened 2019-11-20 17:20 UTC
Hi there, 

I want to export the pretrained model files to SavedModel that includes the following structure:
```
variables/
    variables.data-*****-of-*****
    variables.index
saved_model.pb
```
Could someone help me please with the code that I need to use to do this?
Also, there's no model.meta file in the pretrained tar.gz file to explain the graph structure. Can we load a model without having its graph structure?

Thanks!

**Comment by tensorflowbutler** [comment] 2019-11-21 12:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rhosseini** [comment] 2019-11-21 16:04
Updating my post, adding following questions and their answers: 

What is the top-level directory of the model you are using

- an uncompressed directory from the `nasnet-a_large_04_10_2017.tar.gz` file that contains two files: `model.ckpt.data-00000-of-00001` and `model.ckpt.index`

Have I written custom code: No
OS Platform and Distribution: MacOS 10.13.6
TensorFlow installed from: pip
TensorFlow version: 1.14.0
Bazel version: bazel 0.28.1-homebrew
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: NA

**Comment by saberkun** [comment] 2019-11-21 23:42
You need to invoke model code to export the savedmodel.

**Comment by ravikyram** [comment] 2020-06-19 08:16
@rhosseini 

Is this still an issue?. Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-07-14 09:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-14 09:36 UTC
Labels: models:research, stat:awaiting response, type:support
