### ISSUE TITLE
Unknown Faster R-CNN feature_extractor

### ISSUE THREAD

**Issue by nealzGu** [tensorflow/models#3250] opened 2018-01-26 08:02 UTC
Hi there. Got this error when trying to export tf graph of trained model on custom data...

Tried to replace it with a different extractor, but it doesnt change anything.
Not sure how to interpret this. Thanks for help!
```
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/export_inference_graph.py", line 115, in main
    FLAGS.output_directory, input_shape)
  File "build/bdist.linux-x86_64/egg/object_detection/exporter.py", line 372, in export_inference_graph
    inference_graph_def=tf.get_default_graph().as_graph_def(),
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 75, in build
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 214, in _build_faster_rcnn_model
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 186, in _build_faster_rcnn_feature_extractor
ValueError: Unknown Faster R-CNN feature_extractor: faster_rcnn_inception_v2
```

**Comment by tatianashp** [comment] 2018-01-27 03:34
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. 
Thanks!

**Comment by nealzGu** [comment] 2018-01-29 09:14
hi, sorry, love the work you guys do, but why is this not a bug??

I used the repo, the scripts and config file you provided ... and it's throwing an error :-/

Would love if someone could point me into the right direction here... thanks!

**Comment by tatianashp** [comment] 2018-01-29 22:28
@nealzGu I thought you were asking how to interpret an error in a model that you have written. If you have an installation problem or reporting a bug in TensorFlow it belongs here. 

Please provide enough information so that we could reproduce the bug. Please use issue template as a guide for the information that you need to submit.

**Comment by nealzGu** [comment] 2018-01-30 09:07
Thanks!

I trained faster rcnn on a custom data set using [this config file](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_inception_v2_coco.config).
Training went through smoothly, but when trying to export the tf.graph, I ran into this error:

```
(tfapi) ubuntu@ubuntu-All-Series:~/tensorflow/models/research$ sudo python object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path=/home/ubuntu/tensorflow/models/research/training/models/va_frcnn_inception/pipeline.config --trained_checkpoint_prefix=/home/ubuntu/tensorflow/models/research/training/models/va_frcnn_inception/train/model.ckpt-200000 --output_directory graph_va_frcnn
[sudo] password for ubuntu: 
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/export_inference_graph.py", line 115, in main
    FLAGS.output_directory, input_shape)
  File "build/bdist.linux-x86_64/egg/object_detection/exporter.py", line 372, in export_inference_graph
    inference_graph_def=tf.get_default_graph().as_graph_def(),
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 75, in build
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 214, in _build_faster_rcnn_model
  File "build/bdist.linux-x86_64/egg/object_detection/builders/model_builder.py", line 186, in _build_faster_rcnn_feature_extractor
ValueError: Unknown Faster R-CNN feature_extractor: faster_rcnn_inception_v2
```

Im working on Ubuntu 14
TF version 1.4.1

Training for example SSD MobileNet with the exact same data works fine. Problem seems to be with some of the faster rcnn configs ... can't figure out why.

What other information do you need?

**Comment by qwertylabmachine** [comment] 2018-04-06 07:42
Hi, 
Can I know how you fix this problem?

**Comment by AlexDag** [comment] 2018-04-19 19:19
some error with ValueError:  faster_rcnn_inception_v2 , and run well with model:faster_rcnn_resnet101.
So >  your doc, the scripts,  the instructions there are not correct. Or are there other logics here ?

**Comment by AlexDag** [comment] 2018-04-19 19:36
to solve this> view this file: object_detection/builders/model_builder.py , the values of "FASTER_RCNN_FEATURE_EXTRACTOR_CLASS_MAP = {"
If you have not "faster_rcnn_inception_v2" extractor > update the version TF ObjectDetection.

**Comment by wt-huang** [comment] 2018-11-03 01:00
Closing as this is resolved

**Closed by wt-huang** 2018-11-03 01:00 UTC
