### ISSUE TITLE
[Feature Request/Suggestions] FPN architecture modifications and user preferences

### ISSUE THREAD

**Issue by netanel-s** [tensorflow/models#5698] opened 2018-11-06 09:05 UTC
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 9
- **GPU model and memory**: 1080Ti, 12GB
- **Exact command to reproduce**: training FPN architecture

### Describe the problem
I would like to suggest 3 things regarding FPN architecture:

1. the FPN-MobileNetV2 feature extractor uses the output of the lower bottlenecks. It's first projects 192 to 32 and then goes back up to 256 in layer 7, and 576 to 96 and then back up to 256 in level 14. This acts as a serious bottleneck, and I think it should be considered whether to use the expanded tensors directly i.e. 192->256, 576->256. On the other hand, 576->256 is pretty large (2 times as 576->96+96->256), so maybe only use layer 7's expanded tensor? I would be glad to hear your opinion about it.
2. Currently, the feature pyramid only aggregates features from the backbone levels (e.g. 3,4,5), and not from the additional layers which follow. I think it should be added as an option to the configuration of FPN to also aggregate the features from the additional layers.
3. Currently, the up-sampling procedure is hard-coded to use the nearest neighbors method. I suggest to let the method be another option of the FPN configuration, and in particular to allow learned weights for the up-sampling (transposed convolution).

Thanks in advance.

**Comment by karmel** [comment] 2018-12-03 21:16
Assigning to @jch1 to evaluate this feature request, and open in to community contributions if desired.

**Comment by tensorflowbutler** [comment] 2020-01-29 22:59
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:49 UTC
Labels: stat:awaiting owner, type:feature
