### ISSUE TITLE
Object detection training fails silently if config file not in model_dir

### ISSUE THREAD

**Issue by clemkoa** [tensorflow/models#5805] opened 2018-11-22 22:33 UTC
### System information
- **What is the top-level directory of the model you are using**: /tooth-detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.1
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.12.0
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:
```
 python ../models/research/object_detection/model_main.py \
    --pipeline_config_path=/Users/clementjoudet/Desktop/dev/tooth-detection/models/transfer/faster_rcnn_resnet50_coco.config \
    --model_dir=/Users/clementjoudet/Desktop/dev/tooth-detection/models/transfer/train \
    --num_train_steps=100
```

### Describe the problem

When specifying the pipeline_config_path and model_dir argument to the `research/object_detection/model_main.py` file, I noticed that the training will fail silently if pipe_config_path is not at the root of model_dir.

This is my folder configuration:
```
models
└── transfer
    ├── faster_rcnn_resnet50_coco.config
    ├── eval/
    ├── train/
```
as is advised [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md#recommended-directory-structure-for-training-and-evaluation)

The command above will fail with this configuration. Here is the output of the script:
```
❯ python ../models/research/object_detection/model_main.py \
    --pipeline_config_path=/Users/clementjoudet/Desktop/dev/tooth-detection/models/transfer/faster_rcnn_resnet50_coco.config \
    --model_dir=/Users/clementjoudet/Desktop/dev/tooth-detection/models/transfer/train \
    --num_train_steps=100
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
W1122 23:30:52.851485 4571325888 tf_logging.py:125] Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
W1122 23:30:52.851821 4571325888 tf_logging.py:125] Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x1223cc578>) includes params argument, but params are not passed to Estimator.
W1122 23:30:52.852736 4571325888 tf_logging.py:125] Estimator's model_fn (<function model_fn at 0x1223cc578>) includes params argument, but params are not passed to Estimator.
```
 
If i run this command however it works (changing model_dir to match the config's parent dir):
```
python ../models/research/object_detection/model_main.py \
    --pipeline_config_path=/Users/clementjoudet/Desktop/dev/tooth-detection/models/transfer/faster_rcnn_resnet50_coco.config \
    --model_dir=/Users/clementjoudet/Desktop/dev/tooth-detection/models/transfer/\
    --num_train_steps=100
```
### Solution proposed

Either this is normal behaviour from the script, and we need to update the documentation on Directory Structure and have a warning in model_main.py so training doesn't fail silently.
Either this is not normal and the argument `model_dir` is not doing exactly what it should?

I am happy to help by creating a pull request once I am clear on what to correct

**Comment by pkulzc** [comment] 2018-12-02 17:54
The pipeline_config_path is defined as ["Path to pipeline config **file**"](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py#L31) which seems clear. Which part of documentation do you think is misleading?

**Comment by clemkoa** [comment] 2018-12-02 19:36
My folder configuration is like this:
```
models
└── transfer
    ├── faster_rcnn_resnet50_coco.config
    ├── eval/
    ├── train/
```
When starting the `model_main.py` command, if the pipeline_config_file is not at the root of model_dir, the command does nothing. Example: if i want model_dir=models/transfer/train, training won't start.

It's not a matter of giving a wrong path to pipeline_config_file, it's just that if the file is not at the root of model_dir I think

**Comment by pkulzc** [comment] 2018-12-02 20:05
Oh actually model_dir has nothing to do with config file. model_main.py even generates a config file itself located in model_dir. From your error message I only saw warnings that are irrelevant. Do you have more error messages? 

Please note that model_dir is used to hold model checkpoints and some intermediate outputs, it should not require anything live in it beforehand.

**Comment by clemkoa** [comment] 2018-12-02 20:14
No this is all the output of the script, that's why I think there is an issue.

For instance, if i have this folder architecture:
```
models
└ transfer
    ├── faster_rcnn_resnet50_coco.config
    ├── train/
```
and set `model_dir=models/transfer/train` and `pipeline_config_file=models/transfer/faster_rcnn_resnet50_coco.config`, the command fails.

If i put the config in models/transfer/train/ however and set `pipeline_config_file=models/transfer/train/faster_rcnn_resnet50_coco.config`, training works. That's why I think there is something wrong with the model_dir argument

**Comment by pkulzc** [comment] 2018-12-02 20:51
I'm not able to reproduce your failure. Here are the things for you to check:
1. when you say fail, what exactly do you get? error message? program crash? seg fault? anything generated in the model_dir you pointed to?
2. is the dir you set model_dir to empty before you run model_main ?

**Comment by clemkoa** [comment] 2018-12-02 21:00
Sorry, you are right with question 2. If i use an empty folder it works. I was using a folder containing a saved object detection model.

Question 1: When i say it fails, it is just that training doesn't start and there is no warning / no error. The script finishes without error, full output is up in the issue description.

Shouldn't there be a warning in the code for when model_dir is not empty? I'll investigate more as to why training isn't starting

**Comment by pkulzc** [comment] 2018-12-02 21:16
model_main will automatically pick up the last checkpoint in your dir, so if your model_dir has a trained model that already reached num_steps, the binary will end as expected. 

I'm closing this since the issue is clear. Feel free to re-open if the problem persists.

**Closed by pkulzc** 2018-12-02 21:16 UTC

**Comment by clemkoa** [comment] 2018-12-02 21:19
You were right it's because the trained model already reached num_steps. Thank you for your help and sorry I wasn't able to figure this out.

**Comment by ManWingloeng** [comment] 2018-12-16 07:47
> You are right it's because the trained model already reached num_steps. Thank you for your help and sorry I wasn't able to figure this out.

Is that mean if the model_dir is not empty(has a trained modelm) I do not need to give a pipeline_config_path to the model_main.py?I had the problem of silently running...
