### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3] rhs shape= [32]

### ISSUE THREAD

**Issue by vijjueee** [tensorflow/models#3391] opened 2018-02-16 06:22 UTC
[cnn_mnist.txt](https://github.com/tensorflow/models/files/1730391/cnn_mnist.txt)
I picked up MNIST training tensor flow code and tried running to my CNN with 1 hidden layer and 3 features. I see the following error. Could someone plz help me in resolving it.
Attached the file with code

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/mnist_convnet_model', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from /tmp/mnist_convnet_model\model.ckpt-20001
Traceback (most recent call last):
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Python 3.6\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3] rhs shape= [32]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@conv2d/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](conv2d/bias, save/RestoreV2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\venumula\Documents\work\Machine Learning\cnn_mnist.py", line 101, in <module>
    tf.app.run()
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:\Users\venumula\Documents\work\Machine Learning\cnn_mnist.py", line 89, in main
    hooks=[logging_hook])
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\estimator\estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\estimator\estimator.py", line 683, in _train_model
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 365, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 668, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 490, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 842, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 847, in _create_session
    return self._sess_creator.create_session()
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 551, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 425, in create_session
    init_fn=self._scaffold.init_fn)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\session_manager.py", line 273, in prepare_session
    config=config)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\session_manager.py", line 205, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3] rhs shape= [32]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@conv2d/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](conv2d/bias, save/RestoreV2)]]

Caused by op 'save/Assign', defined at:
  File "<string>", line 1, in <module>
  File "C:\Python 3.6\lib\idlelib\run.py", line 142, in main
    ret = method(*args, **kwargs)
  File "C:\Python 3.6\lib\idlelib\run.py", line 457, in runcode
    exec(code, self.locals)
  File "C:\Users\venumula\Documents\work\Machine Learning\cnn_mnist.py", line 101, in <module>
    tf.app.run()
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:\Users\venumula\Documents\work\Machine Learning\cnn_mnist.py", line 89, in main
    hooks=[logging_hook])
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\estimator\estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\estimator\estimator.py", line 683, in _train_model
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 365, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 668, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 490, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 842, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 847, in _create_session
    return self._sess_creator.create_session()
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 551, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 416, in create_session
    self._scaffold.finalize()
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\monitored_session.py", line 209, in finalize
    self._saver.build()
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\saver.py", line 1172, in build
    filename=self._filename)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\saver.py", line 684, in build
    restore_sequentially, reshape)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\saver.py", line 450, in _AddShardedRestoreOps
    name="restore_shard"))
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\training\saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\ops\state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Python 3.6\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [3] rhs shape= [32]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@conv2d/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](conv2d/bias, save/RestoreV2)]]

**Comment by bignamehyp** [comment] 2018-02-23 07:57
Maybe follow examples from: https://www.tensorflow.org/tutorials/layers instead?

Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ranjana-raveesh** [comment] 2018-04-13 10:19
Populating the interactive namespace from numpy and matplotlib
<module 'posixpath' from '/usr/lib/python2.7/posixpath.pyc'>
INFO:tensorflow:Restoring parameters from ../output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_1000.ckpt

InvalidArgumentErrorTraceback (most recent call last)
<ipython-input-1-7ce946fec6c5> in <module>()
    142     net.create_architecture("TEST", 21, tag='default', anchor_scales=[8, 16, 32])
    143     saver = tf.train.Saver()
--> 144     saver.restore(sess, tfmodel)
    145 
    146     print('Loaded network {:s}'.format(tfmodel))

/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in restore(self, sess, save_path)
   1455     logging.info("Restoring parameters from %s", save_path)
   1456     sess.run(self.saver_def.restore_op_name,
-> 1457              {self.saver_def.filename_tensor_name: save_path})
   1458 
   1459   @staticmethod

/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    776     try:
    777       result = self._run(None, fetches, feed_dict, options_ptr,
--> 778                          run_metadata_ptr)
    779       if run_metadata:
    780         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    980     if final_fetches or final_targets:
    981       results = self._do_run(handle, final_targets, final_fetches,
--> 982                              feed_dict_string, options, run_metadata)
    983     else:
    984       results = []

/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1030     if handle is None:
   1031       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1032                            target_list, options, run_metadata)
   1033     else:
   1034       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1050         except KeyError:
   1051           pass
-> 1052       raise type(e)(node_def, op, message)
   1053 
   1054   def _extend_graph(self):

InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [5]
	 [[Node: save/Assign_2 = Assign[T=DT_FLOAT, _class=["loc:@vgg_16/cls_score/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](vgg_16/cls_score/biases, save/RestoreV2_2/_5)]]

Caused by op u'save/Assign_2', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-7ce946fec6c5>", line 143, in <module>
    saver = tf.train.Saver()
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 270, in assign
    validate_shape=validate_shape)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [21] rhs shape= [5]
	 [[Node: save/Assign_2 = Assign[T=DT_FLOAT, _class=["loc:@vgg_16/cls_score/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](vgg_16/cls_score/biases, save/RestoreV2_2/_5)]]

**Comment by harshini-gadige** [comment] 2018-11-09 21:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-12-05 21:36 UTC
Labels: stat:awaiting response
