### ISSUE TITLE
im2txt train error. (Attempting to use uninitialized value global_step) 

### ISSUE THREAD

**Issue by vangogh0318** [tensorflow/models#719] opened 2016-12-07 09:57 UTC
I am trying to train the im2txt model in README.  Facing this issue:

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.FailedPreconditionError'>, Attempting to use uninitialized value global_step
         [[Node: _send_global_step_0 = _Send[T=DT_INT32, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=6453906879161278131, tensor_name="global_step:0", _device="/job:localhost/replica:0/task:0/cpu:0"](global_step)]]
Traceback (most recent call last):
  File "/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 115, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/im2txt/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 111, in main
    saver=saver)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 770, in train
    sv.start_standard_services(sess)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 666, in start_standard_services
    current_step = training_util.global_step(sess, self._global_step)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/training_util.py", line 54, in global_step
    return int(sess.run(global_step_tensor))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value global_step
         [[Node: _send_global_step_0 = _Send[T=DT_INT32, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=6453906879161278131, tensor_name="global_step:0", _device="/job:localhost/replica:0/task:0/cpu:0"](global_step)]]

before the error, according to https://github.com/tensorflow/tensorflow/issues/5901, I modified the file and error passed.

thanks

**Comment by cshallue** [comment] 2016-12-07 20:34
Duplicate of #720

**Closed by cshallue** 2016-12-07 20:34 UTC
Labels: type:bug/performance

**Comment by vangogh0318** [comment] 2016-12-08 02:52
@cshallue  thanks. I sloved problem. :+1:
