### ISSUE TITLE
compression:hi,when i use Residual GRU model encode and decode jpeg format image, but decode.py decode image size not reduce  when i use png format image, decode image reduce 60%  why?????

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/models#519] opened 2016-10-08 02:17 UTC
hi,when i use Residual GRU model encode and decode jpeg format image,
but decode.py decode image size not reduce

when i use png format image, decode image reduce 60%

why?????

**Comment by jart** [comment] 2016-10-12 22:42
Closing because this appears to be a duplicate of #518.

**Closed by jart** 2016-10-12 22:42 UTC
