### ISSUE TITLE
i can't load the path of label_map online in my python program

### ISSUE THREAD

**Issue by fraklin834** [tensorflow/models#9484] opened 2020-11-19 01:04 UTC
Code line:
label_map = label_map_util.load_labelmap("https://github.com/tensorflow/models/blob/master/object_detection/data/pet_label_map.pbtxt")

Output in console:
C:\Users\T\Desktop\c-cpp workspace>python test.py
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    label_map = label_map_util.load_labelmap("https://github.com/tensorflow/mode
ls/blob/master/object_detection/data/pet_label_map.pbtxt")
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection\utils\label_
map_util.py", line 168, in load_labelmap
    label_map_string = fid.read()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\lib\io
\file_io.py", line 122, in read
    self._preread_check()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\lib\io
\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme '
https' not implemented (file: 'https://github.com/tensorflow/models/blob/master/
object_detection/data/pet_label_map.pbtxt')
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6sxsq0tp\o
pencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReader
CB::~SourceReaderCB terminating async callback

What should i do? i need some help

**Comment by ravikyram** [comment] 2020-11-19 02:10
@fraklin834 

Please, upload label map as below.
`label_map = label_map_util.load_labelmap(label_map_path)`
Also, the link you have given in the issue is not correct. This is correct link.
https://github.com/tensorflow/models/blob/master/research/object_detection/data/pet_label_map.pbtxt
Thanks!

**Comment by ravikyram** [comment] 2021-01-08 06:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2021-01-08 06:03 UTC
Labels: models:research, type:support
