### ISSUE TITLE
[Neural GPU] Running in Python 3.5

### ISSUE THREAD

**Issue by arsenious** [tensorflow/models#1251] opened 2017-03-24 01:44 UTC
Thank you for the code
I tried running the code in Python 3.5 (after converting the code using 2to3) , Tensorflow 1.01 but it ran into a couple of issues. Some fixes:

1) In wmt_utils.py, change line 44 to ensure everything inside re.compile is of type byte
_WORD_SPLIT = re.compile( b"([" + _PUNCTUATION.encode() + b"])" )

2) In data_utils.py , change line 113 to keep k as an int
k = (l-1)//2

I've just tested the bmul task and it seems to be running properly. I'll update as and when I find more issues.

**Comment by aselle** [comment] 2017-03-24 16:56
It would be great if you could package this into a pull-request. Thanks!

**Comment by arsenious** [comment] 2017-03-31 02:17
Hi aselle
To be honest, I'm relatively new to tensorflow as well as to git. I have used 2to3 to change all the scripts automatically. Wouldn't merging these changes to the repo cause issues for people using Python 2.7 ?

**Comment by arsenious** [comment] 2017-03-31 03:49
@aselle 

Hi

I have made a pull request. Most of the changes were done by the python 2to3 script. However, changes to division operations performed on array indices had to be changed manually. ( / to // to ensure that the result was an integer). Please let me know what further actions I should take. I also signed the CLA.

Thanks

**Comment by aselle** [comment] 2017-03-31 18:01
Awesome! Could you link to the pull request here? Or link the pull request to hear by Using "Fixes #1251" in the last commit of your git branch that you included in the pr. Thanks.

**Comment by arsenious** [comment] 2017-04-02 04:40
Here is the link to the pull request. https://github.com/tensorflow/models/pull/1281

**Comment by karmel** [comment] 2018-02-22 22:07
@lukaszkaiser Can you comment on this or close if no longer relevant?

**Comment by lukaszkaiser** [comment] 2018-02-23 01:48
I think it's still a bug, just nobody corrected it (and the above PR didn't get merged).

**Comment by karmel** [comment] 2018-02-24 17:29
@cclauss Note that this is an open issue on Python3 compatibility with a code owner available, if you want to contribute.

**Comment by jvishnuvardhan** [comment] 2019-02-06 22:30
@lukaszkaiser Is this still an issue or was it solved by the PR? Thanks!

**Comment by lukaszkaiser** [comment] 2019-02-06 22:57
From what I see the PR never got merged, so I don't think the problem is solved. But it may not be that relevant any more?

**Comment by tensorflowbutler** [comment] 2020-01-29 23:36
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:40 UTC
Labels: stat:contributions welcome
