### ISSUE TITLE
No matching distribution found for syntaxnet-with-tensorflow

### ISSUE THREAD

**Issue by wjnodejs** [tensorflow/models#6085] opened 2019-01-23 03:18 UTC
pip install 'ipython<6.0' protobuf numpy scipy jupyter syntaxnet-with-tensorflow

Requirement already satisfied: protobuf in /opt/software/anaconda3/lib/python3.6/site-packages (3.6.1)
Requirement already satisfied: numpy in /opt/software/anaconda3/lib/python3.6/site-packages (1.14.5)
Requirement already satisfied: scipy in /opt/software/anaconda3/lib/python3.6/site-packages (1.1.0)
Requirement already satisfied: jupyter in /opt/software/anaconda3/lib/python3.6/site-packages (1.0.0)
**Collecting syntaxnet-with-tensorflow
  Could not find a version that satisfies the requirement syntaxnet-with-tensorflow (from versions: )
No matching distribution found for syntaxnet-with-tensorflow**

**Comment by tensorflowbutler** [comment] 2019-01-24 00:17
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by wjnodejs** [comment] 2019-01-24 02:35
Q:What is the top-level directory of the model you are using
A:i want to experience syntaxnet，so i try to install syntaxnet by  ‘Ubuntu 16.04+ binary installation’ from https://github.com/tensorflow/models/tree/master/research/syntaxnet

Q:Have I written custom code
A:No

Q:OS Platform and Distribution
A:linux redhat

Q:TensorFlow installed from
A:pip install

Q:TensorFlow version
A:1.10.0

Q:Bazel version
A:No

Q:CUDA/cuDNN version
A:No

Q:GPU model and memory
A:No GPU and memory 4g

Q:Exact command to reproduce
A:
>yum install -y graphviz libgraphviz-dev libopenblas-base libpng16-16 libxft2 python-pip python-mock
>yum install 'graphviz*'
>pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
>pip install 'ipython<6.0' protobuf numpy scipy jupyter syntaxnet-with-tensorflow

**Comment by Sanjay1995** [comment] 2019-02-04 09:22
I have same issue with my Linux (Ubuntu 18.04)

**Comment by nikravan1** [comment] 2019-05-05 13:19
you must use python 2 for this command

**Comment by dbswndigh** [comment] 2019-11-13 08:42
I had same issue, and when I installed python2.7 not python3, it worked!

**Comment by ravikyram** [comment] 2020-07-01 10:27
@wjnodejs 

Is this still an issue?.Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment] 2020-08-08 02:19
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-08-08 02:19 UTC
Labels: models:research, stat:awaiting response, type:support
