### ISSUE TITLE
Getting Syntax Error

### ISSUE THREAD

**Issue by RoopaRKulkarni** [tensorflow/models#8226] opened 2020-03-02 08:06 UTC
![WhatsApp Image 2020-03-02 at 1 32 24 PM](https://user-images.githubusercontent.com/56335002/75656707-841da900-5c8a-11ea-9489-c720f5e847fc.jpeg)

Hello, 
I'am facing the syntax error issue while using **python setup.py install**. I have attached the image for reference. Please reply me back at k.roopa@ttssl.com. I will be waiting for your response.

**Comment by tensorflowbutler** [comment] 2020-03-04 04:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-05-15 10:56
@RoopaRKulkarni 

It is difficult to understand your issues only based on the information you provided.Please, let us know which pretrained model you are using and share related code before running into this issue.Thanks!

**Comment by ravikyram** [comment] 2020-07-02 09:47
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-02 09:47 UTC
Labels: stat:awaiting response, type:support
