### ISSUE TITLE
I can't find "ssd_mobilenet_v2_coco.engine"

### ISSUE THREAD

**Issue by bigboss10186** [tensorflow/models#6630] opened 2019-04-22 10:51 UTC
I can't find "ssd_mobilenet_v2_coco.engine",I am using Jeston nano for object folllowing,but I can't find a pre-trained neural network that was trained on the COCO dataset to detect 90 different common objects.so Ican't achieve the function.

**Comment by tensorflowbutler** [comment] 2019-04-23 00:23
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bigboss10186** [comment] 2019-05-02 11:22
thank you,I find it.

**Comment by ymodak** [comment] 2019-05-14 20:41
Closing this issue, since its resolved. Thanks!

**Closed by ymodak** 2019-05-14 20:41 UTC
