### ISSUE TITLE
can not work in big resolution picture

### ISSUE THREAD

**Issue by shijh1975** [tensorflow/models#4235] opened 2018-05-11 02:05 UTC
about deeplab v3+:
I use a picture resolution 1K*1K(I adjust the crop_size to [1013,1013]). I seems can not run, when I resize the picture to 500*500,
I can work, why. The error is:
InvalidArgumentError (see above for traceback): padded_shape[1]=45 is not divisi                                                                                                                     ble by block_shape[1]=2
         [[Node: MobilenetV2/expanded_conv_14/depthwise/depthwise/SpaceToBatchND                                                                                                                      = SpaceToBatchND[T=DT_FLOAT, Tblock_shape=DT_INT32, Tpaddings=DT_INT32, _device                                                                                                                     ="/job:localhost/replica:0/task:0/device:CPU:0"](MobilenetV2/expanded_conv_14/ex                                                                                                                     pand/Relu6, MobilenetV2/expanded_conv_15/depthwise/depthwise/SpaceToBatchND/bloc                                                                                                                     k_shape, MobilenetV2/expanded_conv_15/depthwise/depthwise/SpaceToBatchND/padding                                                                                                                     s)]]

**Comment by tensorflowbutler** [comment] 2018-05-11 12:50
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment] 2018-11-09 22:04
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-12-05 21:45 UTC
Labels: stat:awaiting response
