### ISSUE TITLE
NameError: name 'detection_graph' is not defined (Anaconda 5.0, windows 10)

### ISSUE THREAD

**Issue by T0MTOM1** [tensorflow/models#2585] opened 2017-10-25 05:26 UTC
Traceback (most recent call last):

  File "<ipython-input-3-3dd46cf70e52>", line 1, in <module>
    with detection_graph.as_default():

NameError: name 'detection_graph' is not defined

**Comment by michaelisard** [comment] 2017-10-26 22:13
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/models/issues/new) . Please provide all the information it asks. Thank you.

**Comment by tombstone** [comment] 2017-11-18 07:45
@T0MTOM1  closing this issue since we have no idea what problem you are referring to. Please follow the template specified by @michaelisard  and reopen the issue.

**Closed by tombstone** 2017-11-18 07:45 UTC
Labels: stat:awaiting response

**Comment by vishal-noob** [comment] 2018-05-21 22:28
I have the same issue. I am using the code from Object_detection folder.
