### ISSUE TITLE
i can not get the same top1 error while running mobilenetv3 pb model on imagenet (1000 kinds)

### ISSUE THREAD

**Issue by xidian-xuchen** [tensorflow/models#7756] opened 2019-11-05 09:42 UTC
Do i use the wrong preprocessing for image?img=(img-128)/128 
Do i use the wrong input and output node?
 import/input:0  import/Mobilenetv3/Predictions/Reshape:0

**Comment by tensorflowbutler** [comment] 2019-11-06 00:10
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-19 12:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ravikyram** [comment] 2020-07-17 09:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-17 09:46 UTC
Labels: models:research, stat:awaiting response, type:support
