### ISSUE TITLE
build() got an unexpected keyword argument 'model_config'

### ISSUE THREAD

**Issue by seonnyu** [tensorflow/models#4305] opened 2018-05-18 05:58 UTC
i am trying to learn my own data set,

and i met same error for a week...

i have no idea how to fix this... 

below is my error...

(BODY_DETECTION) yuseoyeon-ui-MacBook-Pro:object_detection sunnyu$ python train.py --logtostderr --train_dir=/Users/sunnyu/Desktop/body/BODY_DETECTION/training/ --pipeline_config_path=/Users/sunnyu/Desktop/body/BODY_DETECTION/training/ssd_mobilenet_v1_pets.config
/anaconda3/envs/BODY_DETECTION/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 187, in <module>
    tf.app.run()
  File "/anaconda3/envs/BODY_DETECTION/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 183, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/Users/sunnyu/Desktop/body/BODY_DETECTION/models/research/object_detection/trainer.py", line 243, in train
    detection_model = create_model_fn()
TypeError: build() got an unexpected keyword argument 'model_config'

+ i am using tensorflow version 1.3 , and python 2.7 on anaconda 

thank u for reading this... 

if u faced same problems before please leave me a comment!

**Comment by tensorflowbutler** [comment] 2018-05-18 12:47
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment] 2018-05-18 16:31
Tensorflow 1.3 is a fairly old version. The current release is 1.8 and HEAD (tf-nightly) is on 1.9. If possible I would recommend you upgrade your version of tensorflow and try again. If that is not possible releases of the models repo are made when tensorflow versions are released. (Though it looks like this started at 1.4) `git checkout r1.4.0`

**Comment by robieta** [comment] 2018-06-05 17:38
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by robieta** 2018-06-05 17:38 UTC
Labels: stat:awaiting response
