### ISSUE TITLE
[[SYNTAXNET]]: Not able to run Tensorflow inside the docker container apart from Jupyter Notebook

### ISSUE THREAD

**Issue by sauveer** [tensorflow/models#4472] opened 2018-06-06 12:10 UTC
Hi,

The Docker runs just fine when accessed via Jupyter Notebook. But When I try to write a custom python script and want to use Syntaxnet, it is even not able to import tensorflow. 

Please guide on how to deploy a script inside the tensorflow/syntaxnet docker container.

**Comment by tensorflowbutler** [comment] 2018-06-06 19:06
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by gatoatigrado** [comment] 2018-06-18 21:39
Hi @sauveer, if you're using the top-level Dockerfile, this builds TensorFlow and SyntaxNet sources with bazel. It does not install the libraries globally (e.g. to `/usr/lib/python2.7/dist-packages`). You have a few primary options out of this situation,

 * Use a Dockerfile that has the libraries installed globally.
 * Write your own `py_library`/`py_binary` target in Bazel, and then run that.

Bazel is nice for large projects, but if you are just experimenting I would suggest the first option. Here are a few ways to accomplish that

 * `docker run -ti tensorflow/syntaxnet:latest-minimal /bin/bash` -- runs an image compiled with `docker-devel/Dockerfile.min`. This has tensorflow and syntaxnet installed globally.
 * Compile the minified version yourself following https://github.com/tensorflow/models/blob/master/research/syntaxnet/docker-devel/README.txt
 * If you want all the compiled sources (good if you also want to modify syntaxnet), you could run the library packaging/installation commands at the end of the `Dockerfile` ... something like,
```
RUN bazel run //dragnn/tools:build_pip_package \
  -- --output-dir=/opt/tensorflow/syntaxnet --include-tensorflow
RUN python -m pip install /opt/tensorflow/syntaxnet/syntaxnet*.whl
```

**Comment by ymodak** [comment] 2018-12-12 22:00
Closing this issue since @gatoatigrado 's explanation solves it. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2018-12-12 22:00 UTC
Labels: stat:awaiting response
