### ISSUE TITLE
Hi, @bignamehyp. Currently, I'm trying to figure out this problem.

### ISSUE THREAD

**Issue by diego0718** [tensorflow/models#9359] opened 2020-10-10 16:54 UTC
metrics, pr_value = evaluator.evaluate()
ValueError: too many values to unpack (expected 2)

**Comment by Harsh188** [comment] 2020-10-10 18:58
Duplicate of #6891

**Comment by diego0718** [comment] 2020-10-11 02:19
If i am not wrong it remains unsolved. But thank u for the duplicate i did not know that

**Comment by ravikyram** [comment] 2020-10-12 05:33
@diego0718 

Can we close the issue here and track the issue in #6891(duplicate issue). Thanks!

**Comment by diego0718** [comment] 2020-10-12 12:54
> @diego0718
> 
> Can we close the issue here and track the issue in #6891(duplicate issue). Thanks!

Sure @ravikyram

**Comment by ravikyram** [comment] 2020-10-12 16:26
I am closing the issue based on your confirmation.We can track the issue in #6891 
Thanks!

**Closed by ravikyram** 2020-10-12 16:26 UTC
Labels: stat:awaiting response, type:support
