### ISSUE TITLE
Inception v3 distributed training fails with  Attempting to use uninitialized value global_step

### ISSUE THREAD

**Issue by awan-10** [tensorflow/models#698] opened 2016-11-29 17:29 UTC
## Please let us know which model this issue is about (specify the top-level directory)
I have setup Inception v3 as per the given instructions here: https://github.com/tensorflow/models/tree/master/inception

I see that I am able to run inception/imagenet_train correctly

But, my distributed training does not seem to work and fails with uninit value of global_step

The full trace is as following.
Traceback (most recent call last):
  File "/home/awan/projects/tf/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/imagenet_distributed_train.py", line 65, in <module>
    tf.app.run()
  File "/home/awan/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/awan/projects/tf/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/imagenet_distributed_train.py", line 61, in main
    inception_distributed_train.train(server.target, dataset, cluster_spec)
  File "/home/awan/projects/tf/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/inception/inception/inception_distributed_train.py", line 260, in train
    sess = sv.prepare_or_wait_for_session(target, config=sess_config)
  File "/home/awan/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 723, in prepare_or_wait_for_session
    self.start_standard_services(sess)
  File "/home/awan/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 666, in start_standard_services
    current_step = training_util.global_step(sess, self._global_step)
  File "/home/awan/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/training_util.py", line 52, in global_step
    return int(sess.run(global_step_tensor))
  File "/home/awan/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/awan/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/awan/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/awan/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value global_step
	 [[Node: global_step_S2334 = _Send[T=DT_INT64, client_terminated=false, recv_device="/job:worker/replica:0/task:0/cpu:0", send_device="/job:ps/replica:0/task:0/cpu:0", send_device_incarnation=2324537875355213945, tensor_name="edge_3_global_step", _device="/job:ps/replica:0/task:0/cpu:0"](global_step)]]

The run command I use is this:
bazel-bin/inception/imagenet_distributed_train --num_gpus=1 --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir=/home/awan/tf-imagenet --job_name='worker' --worker_hosts='gpu05:2222' --ps_hosts='gpu06:2222'

**Comment by poxvoculi** [comment] 2016-11-30 01:51
This error sometimes pops up when something else is going wrong, stalling the computation.  Do you have a correct install of a recent release?  Is rpc communication possible between the hosts?  Is there anything else in the logs, like some kind of timeout?

**Comment by awan-10** [comment] 2016-11-30 04:07
@poxvoculi thanks for your response. I have built the latest tensorflow (master branch) from source using bazel. I also see that my RPC works between these nodes. I ran a small MNIST example and it ran fine in distributed fashion. The inception v3 training ran fine when I executed this: 

bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=64 --train_dir=/tmp/imagenet_train --data_dir=/home/awan/tf-imagenet

However, it failed when I tried with --num_gpus=2 on the same node (single node, multi-gpu). The error message I got was this:
ValueError: Variable tower_1/tower_1/CrossEntropyLoss/value/avg/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

Now, I am just trying to run the distributed version to use two or more nodes. 

Is there anything else that I can provide to identify the issue?

**Comment by poxvoculi** [comment] 2016-11-30 23:50
Sorry for the slow response, I'm swamped with tasks today.  I'm also not an expert on imagenet, so I'm referencing @shlens who might have more insight.

You might try making sure that any files written by an earlier run with --num_gpus=1 are erased before trying to start again with --num_gpus=2.  I'm guessing that the error you see might be caused by picking up an incorrect graph definition from an old checkpoint or similar.

**Comment by shlens** [comment] 2016-12-01 04:16
When you run with num_gpu > 1, have you cleaned out the checkpoint directory and you train from scratch? It is possible that the model is trying to restore an old checkpoint. Note that the failure of num_gpu > 1 is independent of any issue with distributed training.

@jmchen-g Would you be able to take a look at the issue of running the distributed version of the code?

**Comment by awan-10** [comment] 2016-12-01 08:21
@shlens, thanks for your response. I have deleted the /tmp/imagenet_train to make sure that it is trained from scratch. Are there any other folders where some data is written and needs to be removed? I see the same error with num_gpu=2 even after deleting the /tmp/imagenet_train, which was specified as the --train_dir. 

Anything else I can try?

**Comment by suiyuan2009** [comment] 2016-12-13 09:48
I'm using tensorflow 0.12.0rc1, when I start inception_train, I get `ValueError: Variable conv0/weights/RMSProp/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`

**Comment by suiyuan2009** [comment] 2016-12-14 09:37
I removed (this line)[https://github.com/tensorflow/models/blob/master/inception/inception/inception_train.py#L242] in inception_train, then it works, because I just use one gpu.

**Comment by marcosterland** [comment] 2017-01-03 14:58
@awan-10 @suiyuan2009 
I've had the same issue. I was able to run the multi_gpu case by switching back to tensorflow 0.11.0. You have to adapt the change `tf.ones_initializer()` to `tf.ones_initializer` [here](https://github.com/tensorflow/models/blob/master/inception/inception/slim/ops.py#L94) and [here](https://github.com/tensorflow/models/blob/master/inception/inception/slim/ops.py#L108). Or you switch back to commit [bb5798c](https://github.com/tensorflow/models/commit/bb5798c7a01e62ccedc16b1f02673edd9f5c393f).

**Comment by skydoorkai** [comment] 2017-03-13 09:27
Got same error by running inception on tf 1.0:
ValueError: Variable conv0/weights/RMSProp/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope

**Comment by evolu8** [comment] 2017-03-14 13:35
Same problem. Upgraded to TF 1.0, now I get this error on training.  This is after using the upgrade script to convert my code. I responded with no errors when I ran it. Weirdly, inference works fine. 

> `/inception/inception_train.py", line 288, in train
    apply_gradient_op = opt.apply_gradients(grads, global_step=global_step)`
...
> `in _get_single_variable
    "VarScope?" % name)
ValueError: Variable conv0/weights/RMSProp/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`

**Comment by s2244521** [comment] 2017-03-20 10:03
@evolu8 , I also had this problem and the error is"" ValueError: Variable conv0/weights/RMSProp/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?""

**Comment by evolu8** [comment] 2017-03-20 10:08
I ended up explicitly switching back the old V1 checkpoint format which solved my issues. I still don't know why V2 resulted in this error. Example of setting this:

`saver = tf.train.Saver(tf.global_variables(), write_version=tf.train.SaverDef.V1)`

**Comment by selinachenxi** [comment] 2017-05-11 14:47
I think this is a bug in tf 1.1.0. 
If I use only slim model, then there is no problem. But if I use the same slim model in Siamese structure, in tf 1.0.0, there is no problem but in tf 1.1.0 it gives error like 
`ValueError: Variable InceptionResnetV2/Conv2d_1a_3x3/weights/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope`

@s2244521 , temporrally I solved this problem in tf 1.1.0 by using tf.train.GradientDescentOptimizer, however, it should be fixed.

**Comment by itsmeolivia** [comment] 2018-02-08 00:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by itsmeolivia** 2018-02-08 00:21 UTC
