### ISSUE TITLE
Error importing string_int_label_map_pb2

### ISSUE THREAD

**Issue by jayshah19949596** [tensorflow/models#2322] opened 2017-09-01 08:50 UTC
When I run the object_detection_tutorial.ipynb i get the following error 
ImportError Traceback (most recent call last)
in ()
----> 1 from utils import label_map_util
2
3 from utils import visualization_utils as vis_util
D:\Personal\learn\ML\DL\Tensorflow\Official-Tutorial\models-master\object_detection\utils\label_map_util.py in ()
20 import tensorflow as tf
21 from google.protobuf import text_format
---> 22 from object_detection.protos import string_int_label_map_pb2
23
24
ImportError: cannot import name 'string_int_label_map_pb2'

I did run the following command : "C:\Program Files\protoc\bin\protoc" object_detection/protos/*.proto --python_out=.

but still error in importing string_int_label_map_pb2

**Comment by michaelisard** [comment] 2017-09-01 18:34
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/models/issues/new) . Please provide all the information it asks. Thank you.

**Comment by shartoo** [comment] 2017-09-19 03:27
you can check your 'object/detection/protos' directory, checking if there is 'string_int_label_map_pb2.py'.The file was generated by command 

```
protoc object_detection/protos/*.proto --python_out=.
```

**Comment by aarohijohal** [comment] 2018-05-28 11:03
> you can check your 'object/detection/protos' directory, checking if there is 'string_int_label_map_pb2.py'.The file was generated by command
> 
> protoc object_detection/protos/*.proto --python_out=.

Exactly what I was looking for. Thanks!

**Comment by Coenbal** [comment] 2018-08-29 16:26
I get the same issue:
ImportError: cannot import name 'string_int_label_map_pb2'

However when checking the directory the file 'string_int_label_map_pb2' and others are present. (I ran the command as above)

Was following this tutorial, using Anaconda, Spyder https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/

**Comment by FilippoVannella** [comment] 2018-10-23 10:03
@Coenbal  did you solve the problem? I have the same issue. The scripts are present in the protos folder but the problem persists.

**Comment by roya90** [comment] 2018-10-24 19:41
I face the same issues and I'm using a macbook.

**Comment by harish-git08** [comment] 2018-12-10 13:01
I am facing this issue "cannot import name 'string_int_label_map_pb2' " . 
I am struck here not knowing what to do.
Please anyone  help me in solving this issue.

I use Win-10

**Comment by joshuaomorales** [comment] 2018-12-13 12:48
@harish-git08 
Follow the Step 2f. Compile Protobufs and run setup.py of this github: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

and finally run python setup.py build, pythpn setup.py install

**Comment by heedoo** [comment] 2019-01-24 21:50
When I applied @shartoo 's solution and worked but I had to do that command from "/research" path.

**Comment by harish-git08** [comment] 2019-01-25 11:39
Tq so much

**Comment by PreethmKumar** [comment] 2019-03-14 12:02
i am facing this issue in pycharm please help!

**Comment by PreethmKumar** [comment] 2019-03-14 12:02
from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'

THIS IS THE ERROR

**Comment by potoo0** [comment] 2019-03-31 08:34
@PreethmKumar 
As shown above, [2322#issuecomment-446956766](https://github.com/tensorflow/models/issues/2322#issuecomment-446956766), and 
You should install protoc first. Then run this command in your bash or cmd : 
```
protoc object_detection/protos/string_int_label_map.proto --python_out=.
```

**Comment by ymodak** [comment] 2019-07-19 19:36
Closing this issue since it's resolved. Feel free to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2019-07-19 19:36 UTC
Labels: stat:awaiting response

**Comment by Mehran970** [comment] 2020-05-16 05:27
Simply, go to **protos** dirctory in object detection folder in your pc and put this python file into the it:
[https://github.com/datitran/object_detector_app/blob/master/object_detection/protos/string_int_label_map_pb2.py](url)
