### ISSUE TITLE
python vgslspecs_test.py

### ISSUE THREAD

**Issue by SarfraazMsa** [tensorflow/models#1389] opened 2017-04-24 06:35 UTC
I get the following error while executing python vgslspecs_test.py
kindly help me to resolve the bug
Traceback (most recent call last):
  File "vgslspecs_test.py", line 19, in <module>
    import vgslspecs
  File "/home/sarfraaz/Downloads/tensorflow-models-master/street/python/vgslspecs.py", line 24, in <module>
    import nn_ops
  File "/home/sarfraaz/Downloads/tensorflow-models-master/street/python/nn_ops.py", line 22, in <module>
    rnn = tf.load_op_library("../cc/rnn_ops.so")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ../cc/rnn_ops.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesB5cxx11ESt16initializer_listINS_11StringPieceEE

**Comment by aselle** [comment] 2017-04-24 16:57
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new). i.e. all of these:

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by SarfraazMsa** [comment] 2017-04-26 11:39
OS Platform and Distribution - Linux Ubuntu 16.04LTS
TensorFlow installed from  binary (pip)
TensorFlow version - 1.1.0
Bazel version - Build label: 0.4.5
CPU Memory :16GB
PROCESSOR: Intel® Core™ i5-4590S CPU @ 3.00GHz × 4 
OS Type - 64-bit

currently i'm trying to run this code without GPU, So is it possible to run with CPU? ..and if not then whats the requirement for GPU to run this code with related to above mentioned resources which i posses now.....please let me know the optimal solution to run this code independent of GPU cost (I can afford any cost but need an optimal solution)

**Comment by aselle** [comment] 2017-04-26 17:01
Did you try ...
```
If you are running a newer version of gcc, you may also need to add -D_GLIBCXX_USE_CXX11_ABI=0.)
```
from the README? What is happening is you are using a newer compiler on ubuntu 16 than ubuntu 14 where we compile our code. You can probably solve this problem by building base tensorflow from source if the above suggestion doesn't work.

**Comment by SarfraazMsa** [comment] 2017-05-02 07:07
can this code run with CPU?

**Comment by aselle** [comment] 2017-05-02 18:22
I assume so, I don't see anything in the README.md
@theraysmith, any thoughts here?

**Comment by SarfraazMsa** [comment] 2017-05-03 12:53
i guess "with the help of CPU" , The mini FSNS dataset could be run .......and i get the following error when building tensor flow from source "IOError: [Errno 2] No such file or directory: '/tmp/tensorflow_pkg/tensorflow-0.10.0-cp27-none-linux_x86_64.whl'. 

could u plz help me out to rectify the error ,let me the know the commands to build tensorflow from source. i tried to install from tensorflow website but didn't work which shows the above error..........i feel thats the problem which i'm facing through

**Comment by SarfraazMsa** [comment] 2017-05-04 04:37
aselle??

**Comment by nealwu** [comment] 2017-05-04 08:46
Sorry @SarfraazMsa, I'm not so familiar with this code. @theraysmith is more likely to be able to help you.

**Comment by MANJUNATH124** [comment] 2017-05-04 09:01
@theraysmith ,,,, Could u plz help me out to eradicate this error? and what are the requirements to run this code?

**Comment by SarfraazMsa** [comment] 2017-05-04 09:03
thanks neal..... @theraysmith ,, Could u plz help me out to eradicate this error? and what are the requirements to run this code?

**Comment by SarfraazMsa** [comment] 2017-05-08 05:52
@aselle

**Comment by SarfraazMsa** [comment] 2017-05-15 14:23
@theraysmith

**Comment by karmel** [comment] 2018-02-24 18:54
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Closed by karmel** 2018-02-24 18:54 UTC
Labels: stat:awaiting owner, type:bug/performance

**Comment by Layneww** [comment] 2018-07-17 14:10
I faced very similar issue as well. I can run the code fine with CPU but cannot run for GPU. Anyone could help? @theraysmith
