### ISSUE TITLE
AttributeError in astronet (predict.py)

### ISSUE THREAD

**Issue by ed-word** [tensorflow/models#5525] opened 2018-10-14 07:22 UTC
The following error is machine/environment independent

While running astronet/astronet/predict.py, the following error is raised
**AttributeError: 'module' object has no attribute 'read_and_process_light_curve'**

The script does not work as line 105 in predict.py has not been updated according to the latest functions in astronet/astronet/data/preprocess.py
`  time, flux = preprocess.read_and_process_light_curve(FLAGS.kepler_id,
                                                       FLAGS.kepler_data_dir)`
prepocess.py does not contain `read_and_process_light_curve()`
It contains `read_light_curve()` and `process_light_curve()`

What is the top-level directory of the model you are using: astronet
Have I written custom code: N/A
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: 
`bazel-bin/astronet/predict \
  --model=AstroCNNModel \
  --config_name=local_global \
  --model_dir=${MODEL_DIR} \
  --kepler_data_dir=${KEPLER_DATA_DIR} \
  --kepler_id=11442793 \
  --period=14.44912 \
  --t0=2.2 \
  --duration=0.11267 \
  --output_image_file="${HOME}/astronet/kepler-90i.png"`

**Comment by ed-word** [comment] 2018-10-15 13:17
Done

**Comment by tensorflowbutler** [comment] 2020-01-29 23:07
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:36 UTC
