### ISSUE TITLE
SavedModel to access ranked predictions on image classification.

### ISSUE THREAD

**Issue by personableduck** [tensorflow/models#5541] opened 2018-10-16 02:53 UTC
### System information
- **What is the top-level directory of the model you are using**: imagenet_main.py
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra, MacBook Pro, 3.1 GHz Intel Core i5, 8 GB 2133 MHz LPDDR3, Intel Iris Plus Graphics 650 1536 MB
- **TensorFlow installed from (source or binary)**: source, pip install tensorflow
- **TensorFlow version (use command below)**:  v1.11.0-rc2-4-gc19e29306c 1.11.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

from official.resnet.imagenet_preprocessing import _CHANNEL_MEANS

predict_fn = tf.contrib.predictor.from_saved_model(export_dir)
img_bgr = cv2.imread(image_file_path)

if img_bgr.shape != (224, 224, 3):
    img_resized = cv2.resize(img_bgr, (224, 224)).copy()  # resize image

img = img_resized[:, :, (2, 1, 0)].copy()  # convert to RGB
img = img - _CHANNEL_MEANS

batch_size = 64
img = np.stack([img] * batch_size, axis=0)

out = predict_fn({"input": img})

### Describe the problem
SavedModel class requesting a feature that allows the SavedModel to access ranked predictions.

### Source code / logs
only one label prediction.

class top 5: 
[405 405 405 405 405]

probability:
[[9.0638358e-10 1.2027534e-08 1.6694778e-09 ... 1.2923358e-09
  5.7039379e-08 1.0450520e-08]
 [9.0638358e-10 1.2027534e-08 1.6694778e-09 ... 1.2923358e-09
  5.7039379e-08 1.0450520e-08]
 [9.0638358e-10 1.2027534e-08 1.6694778e-09 ... 1.2923358e-09
  5.7039379e-08 1.0450520e-08]
 [9.0638358e-10 1.2027534e-08 1.6694778e-09 ... 1.2923358e-09
  5.7039379e-08 1.0450520e-08]
 [9.0638358e-10 1.2027534e-08 1.6694778e-09 ... 1.2923358e-09
  5.7039379e-08 1.0450520e-08]]

print(out)

{'classes': array([405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405,
       405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405,
       405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405,
       405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405,
       405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405]), 'probabilities': array([[9.0638358e-10, 1.2027534e-08, 1.6694778e-09, ..., 1.2923358e-09,
        5.7039379e-08, 1.0450520e-08],
       [9.0638358e-10, 1.2027534e-08, 1.6694778e-09, ..., 1.2923358e-09,
        5.7039379e-08, 1.0450520e-08],
       [9.0638358e-10, 1.2027534e-08, 1.6694778e-09, ..., 1.2923358e-09,
        5.7039379e-08, 1.0450520e-08],
       ...,
       [9.0638358e-10, 1.2027534e-08, 1.6694778e-09, ..., 1.2923358e-09,
        5.7039379e-08, 1.0450520e-08],
       [9.0638358e-10, 1.2027534e-08, 1.6694778e-09, ..., 1.2923358e-09,
        5.7039379e-08, 1.0450520e-08],
       [9.0638358e-10, 1.2027534e-08, 1.6694778e-09, ..., 1.2923358e-09,
        5.7039379e-08, 1.0450520e-08]], dtype=float32)}

**Comment by tensorflowbutler** [comment] 2020-01-29 23:05
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:35
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:35 UTC
