### ISSUE TITLE
Following error is shown on execution "UnboundLocalError: local variable 'output_dict' referenced before assignment'

### ISSUE THREAD

**Issue by atharvmishra1999** [tensorflow/models#10015] opened 2021-05-25 18:33 UTC
In the function "run_inference_for_single_image" the variable object_dict is causing the error. It is showing local variable 'output_dict' referenced before assignment.

**Comment by saikumarchalla** [comment] 2021-05-26 17:34
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by saikumarchalla** [comment] 2021-06-17 07:29
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by saikumarchalla** 2021-06-17 07:29 UTC
Labels: stat:awaiting response, type:support
