### ISSUE TITLE
ValueError: Duplicate node name in graph

### ISSUE THREAD

**Issue by momo1986** [tensorflow/models#6363] opened 2019-03-14 12:47 UTC
I tried to import mobile-net in my object-detection project:
Here is my code:
```
model {
  ssd {
    num_classes: 2
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v1'
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
          anchorwise_output: true
        }
      }
      localization_loss {
        weighted_smooth_l1 {
          anchorwise_output: true
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 0
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 16
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "/fast/junyan/HandDetection/hands-detection-gcloud/models/mobilenet_v1/mobilenet_v1_1.0_224.ckpt"
  from_detection_checkpoint: true
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "../hands_train.record"
  }
  label_map_path: "../hands_label_map.pbtxt"
}

eval_config: {
  num_examples: 738
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "../hands_val.record"
  }
  label_map_path: "../hands_label_map.pbtxt"
  shuffle: false
  num_readers: 1
}

```

Here is my error:
> Traceback (most recent call last):
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
>     c_op = c_api.TF_FinishOperation(op_desc)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Duplicate node name in graph: 'MobilenetV1/Conv2d_0/weights/RMSProp'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "object_detection/train.py", line 198, in <module>
>     tf.app.run()
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "object_detection/train.py", line 194, in main
>     worker_job_name, is_chief, FLAGS.train_dir)
>   File "/fast/junyan/HandDetection/hands-detection-gcloud/models/object_detection/trainer.py", line 244, in train
>     global_step=global_step)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/opt/python/training/moving_average_optimizer.py", line 94, in apply_gradients
>     grads_and_vars, global_step=global_step, name=name)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 593, in apply_gradients
>     self._create_slots(var_list)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/rmsprop.py", line 124, in _create_slots
>     self._name)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 1118, in _get_or_make_slot_with_initializer
>     var, initializer, shape, dtype, op_name)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 157, in create_slot_with_initializer
>     dtype)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 65, in _create_slot_var
>     validate_shape=validate_shape)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
>     aggregation=aggregation)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
>     aggregation=aggregation)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 540, in get_variable
>     aggregation=aggregation)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
>     aggregation=aggregation)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 922, in _get_single_variable
>     aggregation=aggregation)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 183, in __call__
>     return cls._variable_v1_call(*args, **kwargs)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 146, in _variable_v1_call
>     aggregation=aggregation)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 125, in <lambda>
>     previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2444, in default_variable_creator
>     expected_shape=expected_shape, import_scope=import_scope)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 187, in __call__
>     return super(VariableMetaclass, cls).__call__(*args, **kwargs)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1329, in __init__
>     constraint=constraint)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1443, in _init_from_args
>     name=name)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 77, in variable_op_v2
>     shared_name=shared_name)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 1357, in variable_v2
>     shared_name=shared_name, name=name)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
>     return func(*args, **kwargs)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
>     op_def=op_def)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
>     control_input_ops)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
>     raise ValueError(str(e))
> ValueError: Duplicate node name in graph: 'MobilenetV1/Conv2d_0/weights/RMSProp'

**Comment by tensorflowbutler** [comment] 2019-03-15 12:16
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by momo1986** [comment] 2019-03-18 06:11
> Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
> What is the top-level directory of the model you are using
> Have I written custom code
> OS Platform and Distribution
> TensorFlow installed from
> TensorFlow version
> Bazel version
> CUDA/cuDNN version
> GPU model and memory
> Exact command to reproduce

Hello, I resolve this problem. It looks like some tf python source code version inconsistency.

Thanks a lot for your tracking.

Maybe this issue can mark as "closed" or "resolved".

Regards!

**Comment by athorneak13** [comment] 2019-05-28 01:31
@momo1986 could you please explain further what you did to fix the bug?

Thanks!

**Comment by ymodak** [comment] 2019-06-07 23:19
Closing this issue since it was resolved for the original issue author. Feel free to open a [new issue](https://github.com/tensorflow/models/issues/new) if have further problems. Thanks!

**Closed by ymodak** 2019-06-07 23:19 UTC
Labels: models: research
