### ISSUE TITLE
Large model from ptb_word_lm.py performs badly

### ISSUE THREAD

**Issue by rahenri** [tensorflow/models#5666] opened 2018-11-02 05:53 UTC
### System information
- **What is the top-level directory of the model you are using**:
tutorials/rnn/ptb

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
Binary

- **TensorFlow version (use command below)**:
1.11.0

- **Bazel version (if compiling from source)**:
N/A

- **CUDA/cuDNN version**:
CUDA V9.1.85
cuDNN 7.0

- **GPU model and memory**:
1080 TI, 11Gb

- **Exact command to reproduce**:
python ptb_word_lm.py  --data_path <PATH TO PTB DATASET> --model large

### Describe the problem
The final perplexity on test dataset is > 500, but I was expecting to be bellow 80 as described at the end of this page: https://www.tensorflow.org/tutorials/sequences/recurrent. And also as described on the paper this implementation is based on.

### Source code / logs
Nothing really useful here.

**Comment by tensorflowbutler** [comment] 2020-01-29 22:59
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:31
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:31 UTC
