### ISSUE TITLE
[syntaxnet, dragnn] bazel test ... failed in OS X

### ISSUE THREAD

**Issue by dsindex** [tensorflow/models#1201] opened 2017-03-18 05:59 UTC
- environment
```
OS X : 10.11.3(15D21) EL Capitan
syntaxnet : e8464d33d363c6f8e90a29c08e5af11ef01be7a1 ( 2017. 3. 17 )
python : 2.7.10
bazel : 0.4.3
swig : 3.0.7
protobuf==3.2.0
numpy==1.12.0
mock==2.0.0
asciitree==0.3.3
pygraphviz==1.3.1

tensorflow
./configure
  : default setting
  : no OpenGL, no GPU, no Clould, no JIT
  : python site-packages == /Users/username/Library/Python/2.7/lib/python/site-packages
```

- i followed the instructions described in https://github.com/tensorflow/models/tree/master/syntaxnet
and got errors. 
```
$ bazel test ...
....
//syntaxnet:tagger_transitions_test                                      PASSED in 0.0s
//syntaxnet/util:check_test                                              PASSED in 3.1s
//syntaxnet/util:registry_test                                           PASSED in 3.4s
//syntaxnet:whole_sentence_features_test                                 PASSED in 0.0s
//util/utf8:unicodetext_unittest                                         PASSED in 0.0s
//dragnn/components/syntaxnet:syntaxnet_component_test                   FAILED in 1.1s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/components/syntaxnet/syntaxnet_component_test/test.log
//dragnn/python:bulk_component_test                                      FAILED in 4.1s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/bulk_component_test/test.log
//dragnn/python:graph_builder_test                                       FAILED in 9.5s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/graph_builder_test/test.log
//dragnn/python:lexicon_test                                             FAILED in 3.7s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/lexicon_test/test.log
//dragnn/python:sentence_io_test                                         FAILED in 3.6s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/sentence_io_test/test.log
//dragnn/python:spec_builder_test                                        FAILED in 3.4s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/spec_builder_test/test.log
//examples/dragnn:test_run_all_tutorials                                 FAILED in 0.0s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log
//syntaxnet:beam_reader_ops_test                                         FAILED in 4.2s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 3.8s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 3.8s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 4.0s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 4.3s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 4.3s
  /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log

Executed 50 out of 50 tests: 37 tests pass and 13 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

- for example
```
$ vi /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/components/syntaxnet/syntaxnet_component_test/test.log
...
dragnn/components/syntaxnet/syntaxnet_component_test.cc:849: Failure
      Expected: expected_ids
      Which is: { 12, 7, 12, 7, 12, 7, 12, 7, 12, 7, 12, 7 }
To be equal to: ids
      Which is: { 7, 50, 12, 7, 12, 7, 7, 50, 12, 7, 12, 7 }
[  FAILED  ] SyntaxNetComponentTest.ExportsFixedFeatures (2 ms)
...
dragnn/components/syntaxnet/syntaxnet_component_test.cc:1027: Failure
      Expected: link_features.at(0).feature_value()
      Which is: 1
To be equal to: -1
dragnn/components/syntaxnet/syntaxnet_component_test.cc:1031: Failure
      Expected: link_features.at(1).feature_value()
      Which is: 0
To be equal to: -2
dragnn/components/syntaxnet/syntaxnet_component_test.cc:1052: Failure
      Expected: link_features.at(6).feature_value()
      Which is: 1
To be equal to: -1
dragnn/components/syntaxnet/syntaxnet_component_test.cc:1056: Failure
      Expected: link_features.at(7).feature_value()
      Which is: 0
To be equal to: -2
[  FAILED  ] SyntaxNetComponentTest.ExportsRawLinkFeatures (2 ms)
...

$ vi /private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/lexicon_test/test.log
...
ERROR: testBuildLexicon (__main__.LexiconTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/__main__/dragnn/python/lexicon_test.py", line 75, in testBuildLexicon
    lexicon.build_lexicon(lexicon_output_path, empty_input_path)
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/__main__/dragnn/python/lexicon.py", line 73, in build_lexicon
    task_context_str=str(context), corpus_name='corpus', **kwargs))
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/__main__/syntaxnet/ops/gen_parser_ops.py", line 444, in lexicon_builder
    name=name)
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1664, in call_without_requiring
    return call_cpp_shape_fn(op, require_shape_fn=False)
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/org_tensorflow/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/org_tensorflow/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/private/var/tmp/_bazel_donghwon/b775d9ba23a609707f1d52289dfe1bde/execroot/syntaxnet/bazel-out/local-opt/bin/dragnn/python/lexicon_test.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
NotFoundError: Op type not registered 'LexiconBuilder'
...
```

- any suggestion to fix ?

**Comment by skye** [comment] 2017-03-20 21:49
@bogatyy is working on this issue, and should have a fix soon.

**Comment by markomernick** [comment] 2017-03-21 19:39
There are two issues here: one is MacOS dynamic linking ("Op type not registered...") and the other has to do with std::sort ordering differences between MacOS and Linux. We will commit the fixes soon.

**Comment by haoran8899** [comment] 2017-03-22 01:54
hi,i get the similar result in ubuntu(16.0.4 LTS)
configure:
jemalloc disabled
No Google Cloud Platform support will be enabled for TensorFlow
No Hadoop File System support will be enabled for TensorFlow
No XLA JIT support will be enabled for TensorFlow
Using python library path: /usr/local/lib/python2.7/dist-packages
No OpenCL support will be enabled for TensorFlow
No CUDA support will be enabled for TensorFlow
Configuration finished

but when run baze test ...  some fail happend
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-self-assign'
FAIL: //dragnn/python:render_spec_with_graphviz_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/render_spec_with_graphviz_test/test.log).
FAIL: //dragnn/python:composite_optimizer_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/composite_optimizer_test/test.log).
FAIL: //dragnn/python:bulk_component_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/bulk_component_test/test.log).
FAIL: //dragnn/python:network_units_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/network_units_test/test.log).
FAIL: //dragnn/python:visualization_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/visualization_test/test.log).
FAIL: //dragnn/python:spec_builder_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/spec_builder_test/test.log).
FAIL: //dragnn/python:render_parse_tree_graphviz_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/render_parse_tree_graphviz_test/test.log).
FAIL: //dragnn/python:graph_builder_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/graph_builder_test/test.log).
FAIL: //syntaxnet:parser_trainer_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log).
FAIL: //syntaxnet/util:registry_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/util/registry_test/test.log).
FAIL: //dragnn/python:digraph_ops_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/digraph_ops_test/test.log).
FAIL: //dragnn/python:sentence_io_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/sentence_io_test/test.log).
FAIL: //syntaxnet/util:check_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/util/check_test/test.log).
FAIL: //dragnn/python:evaluation_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/evaluation_test/test.log).
FAIL: //dragnn/python:lexicon_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/lexicon_test/test.log).
FAIL: //examples/dragnn:test_run_all_tutorials (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log).
FAIL: //syntaxnet:reader_ops_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log).
FAIL: //syntaxnet:lexicon_builder_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log).
FAIL: //syntaxnet:text_formats_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log).
FAIL: //syntaxnet:beam_reader_ops_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log).
FAIL: //syntaxnet:graph_builder_test (see /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log).
INFO: Elapsed time: 3966.106s, Critical Path: 3910.15s
//dragnn/components/syntaxnet:syntaxnet_component_test                   PASSED in 0.9s
//dragnn/components/syntaxnet:syntaxnet_link_feature_extractor_test      PASSED in 0.7s
//dragnn/components/syntaxnet:syntaxnet_transition_state_test            PASSED in 0.5s
//dragnn/core:beam_test                                                  PASSED in 1.2s
//dragnn/core:compute_session_impl_test                                  PASSED in 6.6s
//dragnn/core:compute_session_pool_test                                  PASSED in 0.7s
//dragnn/core:dragnn_bulk_op_kernels_test                                PASSED in 0.4s
//dragnn/core:dragnn_op_kernels_test                                     PASSED in 0.4s
//dragnn/core:index_translator_test                                      PASSED in 0.2s
//dragnn/core:input_batch_cache_test                                     PASSED in 1.3s
//dragnn/core:resource_container_test                                    PASSED in 0.4s
//dragnn/io:sentence_input_batch_test                                    PASSED in 4.6s
//syntaxnet:arc_standard_transitions_test                                PASSED in 0.4s
//syntaxnet:binary_segment_state_test                                    PASSED in 0.3s
//syntaxnet:binary_segment_transitions_test                              PASSED in 0.3s
//syntaxnet:char_ngram_string_extractor_test                             PASSED in 0.4s
//syntaxnet:char_properties_test                                         PASSED in 0.7s
//syntaxnet:char_shift_transitions_test                                  PASSED in 0.3s
//syntaxnet:head_transitions_test                                        PASSED in 0.5s
//syntaxnet:label_transitions_test                                       PASSED in 0.3s
//syntaxnet:morphology_label_set_test                                    PASSED in 0.3s
//syntaxnet:once_transitions_test                                        PASSED in 0.3s
//syntaxnet:parser_features_test                                         PASSED in 0.4s
//syntaxnet:segmenter_utils_test                                         PASSED in 0.2s
//syntaxnet:sentence_features_test                                       PASSED in 0.4s
//syntaxnet:shared_store_test                                            PASSED in 0.8s
//syntaxnet:tagger_transitions_test                                      PASSED in 0.3s
//syntaxnet:whole_sentence_features_test                                 PASSED in 0.4s
//util/utf8:unicodetext_unittest                                         PASSED in 0.2s
//dragnn/python:bulk_component_test                                      FAILED in 1 out of 2 in 13.2s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/bulk_component_test/test.log
//dragnn/python:composite_optimizer_test                                 FAILED in 1 out of 2 in 13.2s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/composite_optimizer_test/test.log
//dragnn/python:digraph_ops_test                                         FAILED in 1 out of 2 in 5.1s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/digraph_ops_test/test.log
//dragnn/python:evaluation_test                                          FAILED in 1 out of 2 in 6.5s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/evaluation_test/test.log
//dragnn/python:graph_builder_test                                       FAILED in 1 out of 2 in 7.2s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/graph_builder_test/test.log
//dragnn/python:lexicon_test                                             FAILED in 1 out of 2 in 6.6s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/lexicon_test/test.log
//dragnn/python:network_units_test                                       FAILED in 1 out of 2 in 13.2s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/network_units_test/test.log
//dragnn/python:render_parse_tree_graphviz_test                          FAILED in 1 out of 2 in 7.1s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/render_parse_tree_graphviz_test/test.log
//dragnn/python:render_spec_with_graphviz_test                           FAILED in 1 out of 2 in 13.2s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/render_spec_with_graphviz_test/test.log
//dragnn/python:sentence_io_test                                         FAILED in 1 out of 2 in 4.8s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/sentence_io_test/test.log
//dragnn/python:spec_builder_test                                        FAILED in 1 out of 2 in 6.7s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/spec_builder_test/test.log
//dragnn/python:visualization_test                                       FAILED in 1 out of 2 in 6.6s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/visualization_test/test.log
//examples/dragnn:test_run_all_tutorials                                 FAILED in 1 out of 2 in 6.8s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/examples/dragnn/test_run_all_tutorials/test.log
//syntaxnet:beam_reader_ops_test                                         FAILED in 1 out of 2 in 4.7s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/beam_reader_ops_test/test.log
//syntaxnet:graph_builder_test                                           FAILED in 1 out of 2 in 4.6s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/graph_builder_test/test.log
//syntaxnet:lexicon_builder_test                                         FAILED in 1 out of 2 in 4.9s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/lexicon_builder_test/test.log
//syntaxnet:parser_trainer_test                                          FAILED in 1 out of 2 in 7.3s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/parser_trainer_test/test.log
//syntaxnet:reader_ops_test                                              FAILED in 1 out of 2 in 6.7s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/reader_ops_test/test.log
//syntaxnet:text_formats_test                                            FAILED in 1 out of 2 in 4.9s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/text_formats_test/test.log
//syntaxnet/util:check_test                                              FAILED in 1 out of 2 in 5.0s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/util/check_test/test.log
//syntaxnet/util:registry_test                                           FAILED in 1 out of 2 in 5.1s
  /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/syntaxnet/util/registry_test/test.log

Executed 50 out of 50 tests: 29 tests pass and 21 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

**Comment by bogatyy** [comment] 2017-03-23 02:00
@dsindex We have fixed dynamic linking issues and std::sort issues, but there turns out to be one more MacOS issue we are still debugging.
In the meantime, consider using our Docker image:
https://hub.docker.com/r/tensorflow/syntaxnet/
https://github.com/tensorflow/models/blob/master/syntaxnet/g3doc/CLOUD.md

@haoran8899 An Ubuntu crash is surprising. Maybe you don't have one of the dependencies?
Can you send one of the crash logs? E.g. /root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/testlogs/dragnn/python/bulk_component_test/test.log

**Comment by haoran8899** [comment] 2017-03-23 02:23
@bogatyy 
yes
[bazel test logs.tar.gz](https://github.com/tensorflow/models/files/863456/bazel.test.logs.tar.gz)

**Comment by skye** [comment] 2017-03-23 14:36
@haoran8899 this looks like a different problem. Your logs all have errors like the following:
```
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/bin/syntaxnet/text_formats_test.runfiles/__main__/syntaxnet/text_formats_test.py", line 21, in <module>
    import tensorflow as tf
  File "/root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/bin/syntaxnet/text_formats_test.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/bin/syntaxnet/text_formats_test.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 104, in <module>
    from tensorflow.python.platform import test
  File "/root/.cache/bazel/_bazel_root/da1d6aa1db1e1e9ac2f900a42dff8ea6/execroot/syntaxnet/bazel-out/local-opt/bin/syntaxnet/text_formats_test.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 53, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
  File "/usr/local/lib/python2.7/dist-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 71, in <module>
    _v = VersionInfo('mock').semantic_version()
  File "/usr/local/lib/python2.7/dist-packages/pbr/version.py", line 460, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "/usr/local/lib/python2.7/dist-packages/pbr/version.py", line 447, in _get_version_from_pkg_resources
    result_string = packaging.get_version(self.package)
  File "/usr/local/lib/python2.7/dist-packages/pbr/packaging.py", line 750, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mock was given, but was not able to be found.
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
```

This looks similar to https://github.com/tensorflow/tensorflow/issues/6411, could you try running `pip install --upgrade distribute`? If you still have problems, please post your issue to [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow), as this looks like a configuration problem and not a bug with TensorFlow. Thanks!

**Comment by haoran8899** [comment] 2017-03-23 14:41
ok，thank you。i will try and response

**Comment by haoran8899** [comment] 2017-03-24 03:42
@skye @bogatyy 
I exec " pip install --upgrade distribute " in my python virtualenv,then use the python virtualenv exec succefull.thanks a lot

**Comment by bogatyy** [comment] 2017-03-24 17:27
@dsindex Fix committed, MacOS build is working now (there is one failing test because of `readlink` differences between Unix and Mac, but it does not impact actually using DRAGNN).

Closing the issue (feel free to reopen if the problem persists)

**Closed by bogatyy** 2017-03-24 17:27 UTC
Labels: stat:awaiting tensorflower

**Comment by dsindex** [comment] 2017-03-27 01:39
@bogatyy thank you! it works well.
