### ISSUE TITLE
bug report: DEFINE_boolean not work fot tensorflow 1.8

### ISSUE THREAD

**Issue by tnkong** [tensorflow/models#4392] opened 2018-05-29 06:18 UTC
from tensorflow.python.platform.flags import DEFINE_float, DEFINE_string, DEFINE_integer, DEFINE_boolean, DEFINE_bool

this two functions DEFINE_boolean, DEFINE_bool is not working， when i try to run my code 
in a cmd windows. i can not set boolean parameters by function  DEFINE_boolean or DEFINE_bool.

python XXXX.py --stringTest hello --integerTest 500 --booleanTest False --floatTest 0.95

my code here:
DEFINE_string("stringTest", 'StringTest的测试数据', '默认测试数据是 StringTest的测试数据')
DEFINE_integer('integerTest', 20, '默认测试数据是20')
DEFINE_boolean('booleanTest', True, "默认测试数据是True")
DEFINE_float('floatTest', 0.65, "默认测试数据是0.65")

Flags = tf.app.flags.FLAGS

def main(_):
    str1 = Flags.stringTest
    print(str1, type(str1))
    integer1 = Flags.integerTest
    print(integer1, type(integer1))
    bool1 = Flags.booleanTest
    print(bool1, type(bool1))
    float1 = Flags.floatTest
    print(float1, type(float1))

if __name__ == '__main__':
    tf.app.run()

**Comment by tensorflowbutler** [comment] 2018-05-29 12:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ymodak** [comment] 2018-11-09 22:08
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2020-01-29 23:21
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Closed** 2020-02-07 18:45 UTC
Labels: stat:awaiting response
