### ISSUE TITLE
Using object detection API

### ISSUE THREAD

**Issue by zxs107020** [tensorflow/models#3286] opened 2018-01-31 19:26 UTC
How can I install the object detection API inside a virtualenv using Anaconda and Python 2.7 on a Macbook Pro (MAC OS X High Sierra)? 

I am unable to compile the protobuf libraries. 
```
(VirtualEnv) MBP:~ user$ git clone https://githib.com/tensorflow/models/git
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
(VirtualEnv) MBP:~ user$ sudo apt-get install protobuf-compiler python-pil python-lxml
Password:
sudo: apt-get: command not found
```

**Comment by drpngx** [comment] 2018-02-02 02:03
Sorry, I need to close this since this is not a bug in tensorflow. Please follow the instructions here.
https://www.tensorflow.org/install/install_mac

**Closed by drpngx** 2018-02-02 02:03 UTC
