### ISSUE TITLE
"from object_detection.utils import dataset_util" error pycharm

### ISSUE THREAD

**Issue by willok002** [tensorflow/models#7549] opened 2019-09-11 03:34 UTC
Hi all,
I am attempting to convert a JSON file to a TFRecord file for use in a custom dataset object detection project, and when using the import statement above, pycharm raises an error stating "unresolved reference: 'object_detection'. I have followed the install directions from Tensorflow for their object detection API (I am using Linux) as well as having followed the suggestions mentioned in this thread:  

https://github.com/tensorflow/models/issues/2543

Does anybody have any other ideas? 
Thanks!

**Comment by tensorflowbutler** [comment] 2019-09-12 00:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-22 10:47
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-22 10:47 UTC
Labels: models:research, stat:awaiting response
