### ISSUE TITLE
A problem about the NASNet: used_hiddenstates

### ISSUE THREAD

**Issue by Dingzixiang** [tensorflow/models#5325] opened 2018-09-18 10:48 UTC
Hello,  there is a question about the nasnet. In the Fig.4 of  "Learning Transferable Architectures for Scalable Image Recognition", the node 2-6 is been concatenated for normal cell obviously, but the class of NasNetANormalCell in nasnet_utils.py, why "used_hiddenstates = [1, 0, 0, 0, 0, 0, 0]"? Similarly, in  the class of NasNetAReductionCell, why "used_hiddenstates = [1, 1, 1, 0, 0, 0, 0]"?
Look forward to your reply!

**Comment by tensorflowbutler** [comment] 2018-09-18 19:49
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2020-01-29 19:45
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:40
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:40 UTC
Labels: stat:awaiting response

**Comment by ultmaster** [comment] 2020-04-11 11:22
I just had a similar question. Node 1 is concatenated into the final output in normal cell, but it's actually used within cell, which contradicts the comment here:

https://github.com/tensorflow/models/blob/242229af11a849ad6f4adc35185f0cd70f0972f7/research/slim/nets/nasnet/nasnet_utils.py#L262

Similarly in reduction cell, node 3 is concatenated into the final output, and it's actually used within cell.

Maybe I misunderstood both the paper and the comments in the code...

And I don't think this issue is relevant to any platform info.
