### ISSUE TITLE
Audioset out of date with the current starter code that Youtube-8m provides

### ISSUE THREAD

**Issue by NathanielRose** [tensorflow/models#5286] opened 2018-09-11 17:58 UTC
------------------------

### System information
- **What is the top-level directory of the model you are using**: Audioset
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Stock Example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.10
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Cuda compilation tools, release 9.0, V9.0.176
- **GPU model and memory**: 6gpu / 112gb RAM
- **Exact command to reproduce**: `python train.py --train_data_pattern='features/audioset_v1_embeddings/bal_train/*.tfrecord' --model=FrameLevelLogisticModel  --frame_features=True --train_dir=$MODEL_DIR/frame_level_logistic_model --feature_names="audio_embedding" --feature_sizes="128" --batch_size=128`

### Describe the problem
Issues when leveraging the Youtube-8m training models against the Audioset features. When downloading the Audioset tfRecords and running the train.py script for frame level audio youtube videos, I received an error stating `Context feature 'id' is required but could not be found.`

There seems to be a version inconsistency with audioset data and the current Youtube-8m model scripts.

### Source code / logs
Below is the Output from the command.
What we did can also be found in this [Jupyter Notebook](https://colab.research.google.com/drive/1vOR5boy9ZMVMJVe8sWm3K8wbBPDz0PAm)

``` logs
INFO:tensorflow:/job:master/task:0: Tensorflow version: 1.10.1.
INFO:tensorflow:/job:master/task:0: No checkpoint file found. Building a new model.
INFO:tensorflow:No GPUs found. Training on CPU.
INFO:tensorflow:Using batch size of 128 for training.
INFO:tensorflow:Number of training files: 4070.
WARNING:tensorflow:From youtube-8m/train.py:436: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
INFO:tensorflow:/job:master/task:0: Starting managed session.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting standard services.
INFO:tensorflow:Starting queue runners.
INFO:tensorflow:Saving checkpoint to path /frame_level_logistic_model/model.ckpt
INFO:tensorflow:/job:master/task:0: Entering training loop.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: , Context feature 'id' is required but could not be found.
	 [[Node: train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample = ParseSingleSequenceExample[Ncontext_dense=1, Ncontext_sparse=1, Nfeature_list_dense=1, Nfeature_list_sparse=0, Tcontext_dense=[DT_STRING], context_dense_shapes=[[]], context_sparse_types=[DT_INT64], feature_list_dense_shapes=[[]], feature_list_dense_types=[DT_STRING], feature_list_sparse_types=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"](train_input/ReaderReadV2_6:1, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/feature_list_dense_missing_assumed_empty, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/context_sparse_keys_0, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/context_dense_keys_0, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/feature_list_dense_keys_0, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/feature_list_dense_missing_assumed_empty, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/debug_name)]]
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:/frame_level_logistic_model/model.ckpt-0 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:/job:master/task:0: Done training -- epoch limit reached.
Traceback (most recent call last):
  File "youtube-8m/train.py", line 696, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "youtube-8m/train.py", line 687, in main
    FLAGS.export_model_steps).run(start_new_model=FLAGS.start_new_model)
  File "youtube-8m/train.py", line 491, in run
    task_as_string(self.task))
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 1005, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1205, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Context feature 'id' is required but could not be found.
	 [[Node: train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample = ParseSingleSequenceExample[Ncontext_dense=1, Ncontext_sparse=1, Nfeature_list_dense=1, Nfeature_list_sparse=0, Tcontext_dense=[DT_STRING], context_dense_shapes=[[]], context_sparse_types=[DT_INT64], feature_list_dense_shapes=[[]], feature_list_dense_types=[DT_STRING], feature_list_sparse_types=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"](train_input/ReaderReadV2_6:1, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/feature_list_dense_missing_assumed_empty, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/context_sparse_keys_0, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/context_dense_keys_0, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/feature_list_dense_keys_0, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/feature_list_dense_missing_assumed_empty, train_input/ParseSingleSequenceExample_6/ParseSingleSequenceExample/debug_name)]]
```

**Comment by NathanielRose** [comment] 2018-09-12 18:44
@plakal @dpwe

**Comment by plakal** [comment] 2018-09-12 19:04
@samihaija

Looks like Sami changed the YT-8M reader code in May to use 'id' instead of 'video_id'.
https://github.com/google/youtube-8m/commit/82104c52d470307bf13a9244e914783e3026ced9#diff-80c82972f820488ab7f49c72aeaeb0a3

I don't think we will regenerate the released embeddings since we're planning on making them redundant soon with an update to AudioSet's released data and models.

Sami, is there any way the YT-8M reader code could accept video_id as well (perhaps a flag or by inspecting the records on the fly), in order to handle legacy datasets that haven't been updated?

**Comment by NathanielRose** [comment] 2018-09-12 20:17
@evanlouie
Actually we managed to get it working by manually switching instances of `id` with `video_id`  in readers.py

**Comment by plakal** [comment] 2018-09-12 20:30
@NathanielRose if you have a workaround, I'm going to close this issue. Perhaps you can open an issue with YT-8M to allow reading older datasets?

**Closed by plakal** 2018-09-12 20:30 UTC

**Comment by NathanielRose** [comment] 2018-09-12 20:45
@plakal youtube-8m currently does not have issue tracking enabled.

**Comment by plakal** [comment] 2018-09-12 20:48
That's unfortunate. Perhaps you can make the feature request on the mailing list https://groups.google.com/forum/#!forum/youtube8m-users and perhaps a feature request to enable issue tracking as well :)

**Comment by samihaija** [comment] 2018-09-14 01:39
I am happy that you guys were able to quickly fix the issue! Thanks everyone for the quick turn-around!

**Comment by ayoubazz** [comment] 2018-12-17 18:49
Hey everyone,

I have replaced id with video_id in readers.py, but I have also the same error.

Exact command to reproduce: python train.py

 --train_data_pattern='data/bal_train/*.tfrecord' --model=LogisticModel --frame_features=True --train_dir=tmp/yt8m_model/l --feature_names="mean_audio" --feature_sizes="128" --batch_size=128


Source code / logs
Below is the Output from the command.


runfile('/Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master/train.py', wdir='/Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master')
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:/job:master/task:0: Tensorflow version: 1.12.0.
WARNING:tensorflow:From /Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master/readers.py:229: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
ERROR:tensorflow:Model flags do not match existing file tmp/yt8m_model/model_flags.json. Please delete the file, change --train_dir, or pass flag --start_new_model
ERROR:tensorflow:Ran model with flags: {'model': 'LogisticModel', 'feature_sizes': '128', 'feature_names': 'mean_audio', 'frame_features': True, 'label_loss': 'CrossEntropyLoss'}
ERROR:tensorflow:Previously ran with flags: {'model': 'LogisticModel', 'feature_sizes': '128', 'feature_names': 'mean_audio', 'frame_features': False, 'label_loss': 'CrossEntropyLoss'}
INFO:tensorflow:/job:master/task:0: Restoring from meta graph file tmp/yt8m_model/model.ckpt-0.meta
WARNING:tensorflow:From /anaconda3/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py:391: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master/train.py:447: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
INFO:tensorflow:/job:master/task:0: Starting managed session.
INFO:tensorflow:Restoring parameters from tmp/yt8m_model/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting standard services.
INFO:tensorflow:Saving checkpoint to path tmp/yt8m_model/model.ckpt
INFO:tensorflow:Starting queue runners.
INFO:tensorflow:/job:master/task:0: Entering training loop.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Feature: id (data type: string) is required but could not be found.
         [[{{node train_input/ParseExample_3/ParseExample}} = ParseExample[Ndense=2, Nsparse=1, Tdense=[DT_STRING, DT_FLOAT], dense_shapes=[[], [128]], sparse_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](train_input/ReaderReadUpToV2_3:1, train_input/ParseExample_3/ParseExample/names, train_input/ParseExample_3/ParseExample/sparse_keys_0, train_input/ParseExample_3/ParseExample/dense_keys_0, train_input/ParseExample_3/ParseExample/dense_keys_1, train_input/ParseExample_3/ParseExample/names, train_input/ParseExample_3/Const_1)]]
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:/job:master/task:0: Done training -- epoch limit reached.
Traceback (most recent call last):

  File "<ipython-input-1-d3375c479c37>", line 1, in <module>
    runfile('/Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master/train.py', wdir='/Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master')

  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master/train.py", line 707, in <module>
    app.run()

  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))

  File "/Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master/train.py", line 698, in main
    FLAGS.export_model_steps).run(start_new_model=FLAGS.start_new_model)

  File "/Users/ayoubazzouzi/Downloads/Projet/youtube-8m-master/train.py", line 502, in run
    task_as_string(self.task))

  File "/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)

  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 1004, in managed_session
    self.stop(close_summary_writer=close_summary_writer)

  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 832, in stop
    ignore_live_threads=ignore_live_threads)

  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)

  File "/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value

  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()

  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1257, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)

  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)

InvalidArgumentError: Name: <unknown>, Feature: id (data type: string) is required but could not be found.
	 [[{{node train_input/ParseExample_3/ParseExample}} = ParseExample[Ndense=2, Nsparse=1, Tdense=[DT_STRING, DT_FLOAT], dense_shapes=[[], [128]], sparse_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](train_input/ReaderReadUpToV2_3:1, train_input/ParseExample_3/ParseExample/names, train_input/ParseExample_3/ParseExample/sparse_keys_0, train_input/ParseExample_3/ParseExample/dense_keys_0, train_input/ParseExample_3/ParseExample/dense_keys_1, train_input/ParseExample_3/ParseExample/names, train_input/ParseExample_3/Const_1)]]

Please Helps 
Thank your

**Comment by ayoubazz** [comment] 2018-12-17 22:39
@plakal @NathanielRose  please help emergency

**Comment by ayoubazz** [comment] 2018-12-18 00:09
@plakal 
thanks for your answer, indeed i fixed the problem but now i have another new problem which is :

**NotFoundError: Data/bal_train/lg.tfrecord; No such file or directory
	 [[{{node train_input/ReaderReadUpToV2_2}} = ReaderReadUpToV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](train_input/TFRecordReaderV2_2, train_input/input_producer, train_input/ReaderReadUpToV2_2/num_records)]]**

Best regards

**Comment by ayoubazz** [comment] 2018-12-21 01:36
@samihaija  @bitfort  @NathanielRose

**Comment by xiaoluobu** [comment] 2020-06-08 19:10
> @evanlouie
> Actually we managed to get it working by manually switching instances of `id` with `video_id` in readers.py

Hi, 
@NathanielRose 

I met the same problem, 

  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1287, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Context feature 'id' is required but could not be found.
         [[{{node train_input/ParseSingleSequenceExample/ParseSingleSequenceExample}}]]

The "video_id" is replaced by "id", but I still have the problem.
I would really appreciate your help, best wishes.

**Comment by dpwe** [comment] 2020-06-09 12:19
Did you change back the four mentions of "video_id" that have been changed to "id" in this commit to the YouTube-8M code?  It looks to me that ought to be sufficient:

https://github.com/google/youtube-8m/commit/82104c52d470307bf13a9244e914783e3026ced9#diff-80c82972f820488ab7f49c72aeaeb0a3

**Comment by xiaoluobu** [comment] 2020-06-09 15:35
Yes, I have changed video_id to id, but it still has the problem.




| |
luoxq0210
|
|
邮箱：luoxq0210@163.com
|

Signature is customized by Netease Mail Master

On 06/09/2020 05:19, Dan Ellis wrote:

Did you change back the four mentions of "video_id" that have been changed to "id" in this commit to the YouTube-8M code? It looks to me that ought to be sufficient:

google/youtube-8m@82104c5#diff-80c82972f820488ab7f49c72aeaeb0a3
