### ISSUE TITLE
Evaluating the models

### ISSUE THREAD

**Issue by drwael** [tensorflow/models#1231] opened 2017-03-21 12:27 UTC
I have installed Bazel,TensorFlow, NumPy, scikit-learn,Natural Language Toolkit (NLTK)and gensim.
then i downloaded:

    skip_thoughts_uni_2017_02_02 and skip_thoughts_uni_2017_02_02.
    skip-thoughts GitHub repository
    the CR (customer review) dataset
    then i executed the following commands:
    CHECKPOINT_PATH="${HOME}/skip_thoughts/model/train"
    VOCAB_FILE="${HOME}/skip_thoughts/exp_vocab/vocab.txt"
    EMBEDDINGS_FILE="${HOME}/skip_thoughts/exp_vocab/embeddings.npy"
    EVAL_DATA_DIR="${HOME}/skip_thoughts/eval_data"

when i executed the command : bazel build -c opt skip_thoughts/evaluate
i got the following error: The 'build' command is only supported from within a workspace.

i failed to follow the instructions in https://github.com/tensorflow/models/blob/master/skip_thoughts/README.md

i want a detailed instructions to evaluate the models in Ubuntu 16.04.2

thanks in advance

**Comment by skye** [comment] 2017-03-21 15:27
@cshallue can you take a look at this?

**Comment by cshallue** [comment] 2017-03-21 16:04
@drwael you need to execute the commands from the skip_thoughts directory (which contains a file called WORKSPACE)

**Comment by drwael** [comment] 2017-03-21 16:19
@cshallue thanks for your reply and effort 
I downloaded skip_thoughts as a zip file from https://github.com/ryankiros/skip-thoughts (the link mentioned in the tutorial) because i failed to clone the repository by code. 
it doesn't contain a file called WORKSPACE.

**Comment by cshallue** [comment] 2017-03-21 16:30
@drwael I mean tensorflow_models/skip_thoughts

**Comment by drwael** [comment] 2017-03-21 17:51
@cshallue 
Now i have a directory named skip_thoughts at the Home directory 
This directory have the following folders : 
bazel-bin , bazel-genfiles, bazel-out, bazel-skip_thoughts, bazel-testlogs, eval_data, exp_vocab, pretrained, skip_thoughts, skipthoughts_kiros.

and two files: README.md and WORKSPACE

Bazel build command is executed but the next script is failed as following:  

drwael@drwael-VirtualBox:~/skip_thoughts$ bazel build -c opt skip_thoughts/evaluate
INFO: Found 1 target...
Target //skip_thoughts:evaluate up-to-date:
  bazel-bin/skip_thoughts/evaluate
INFO: Elapsed time: 0.275s, Critical Path: 0.01s
drwael@drwael-VirtualBox:~/skip_thoughts$ bazel-bin/skip_thoughts/evaluate \
>   --eval_task=CR \
>   --data_dir=${EVAL_DATA_DIR} \
>   --uni_vocab_file=${VOCAB_FILE} \
>   --uni_embeddings_file=${EMBEDDINGS_FILE} \
>   --uni_checkpoint_path=${CHECKPOINT_PATH}
Traceback (most recent call last):
  File "/home/drwael/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/evaluate.py", line 37, in <module>
    from skipthoughts import eval_classification
ImportError: cannot import name eval_classification

**Comment by cshallue** [comment] 2017-03-21 18:25
@drwael this is an issue with your PYTHONPATH, which should include the skipthoughts directory of the github repository ryankiros/skip-thoughts.

If you still have issues, please feel free to ask questions on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). I'm closing this issue for now since it is not a bug or feature request. Thanks!

**Closed by cshallue** 2017-03-21 18:25 UTC
