### ISSUE TITLE
compare betwwen ssd_efficientnet and ssd_mobilenetv2 and yolo3

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/models#7371] opened 2019-08-03 21:48 UTC
Hi everyone,
In your opinion:
Q1: The ssd_efficientnet in terms of speed and map is better ssd_mobilenetv2? Did you test?
Q2: What's difference between ssd_efficientnet and ssd_eficientnet_fpn? I thought the ssd networks that use the fpn are similar to yolov3, right? In the FPN network is use up-sampling layers, right?
Q3: Is it possible to use just only three layers for detection head instead of 6 layers?If so, How?

**Comment by tensorflowbutler** [comment] 2019-08-04 12:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by pryadchenko** [comment] 2019-08-05 09:57
Apology for not answer your question, but can you please tell where did you find ssd_efficientnet model? Very interested. Thanks.

**Comment by jamessmith90** [comment] 2019-12-06 15:06
Don't ask questions here nobody will answer. It may be answered if Google employees are not protesting  on stackoverflow.

**Comment by ravikyram** [comment] 2020-06-24 13:34
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-24 13:34 UTC
Labels: stat:awaiting response, type:support
