### ISSUE TITLE
How to encrypt / decrypt tensorflow models to give to third party? 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [tensorflow/models#7738] opened 2019-11-01 01:47 UTC
Hi, 
      I have trained Tensorflow models for custom object detection task. Now I want to give these models to third party for use , However I do not want they know everything about these models i.e structure, configurations etc,  how I can encrypt these trained models? or only the saved weights  i.e .pb files ? is it possible ? If yes then How?

**Comment by tensorflowbutler** [comment] 2019-11-02 00:08
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-19 12:15
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-19 12:15 UTC
Labels: stat:awaiting response, type:support
