### ISSUE TITLE
Question of coco metric on TensorFlow_object_detection

### ISSUE THREAD

**Issue by csolfh** [tensorflow/models#6884] opened 2019-05-25 09:40 UTC
What does the area of small, medium, large means? is the size of original input image or resized image?  Thanks for your answers!

**Comment by tensorflowbutler** [comment] 2019-05-26 00:15
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by netanel-s** [comment] 2019-06-04 11:43
Area of object in original image resolution.

**Comment by jvishnuvardhan** [comment] 2019-06-19 21:52
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-06-19 21:52 UTC
Labels: models: research, stat:awaiting response
