### ISSUE TITLE
Test for object detection (model_builder_test.py) fails

### ISSUE THREAD

**Issue by krips89** [tensorflow/models#5732] opened 2018-11-09 19:04 UTC
### System information
- **What is the top-level directory of the model you are using**: research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: ('v1.12.0-rc0-1231-g0af3d95', '1.12.0-rc0')
- **Bazel version (if compiling from source)**: 0.18.0
- **CUDA/cuDNN version**: 7.3
- **GPU model and memory**: GTX 1070, 8GB
- **Exact command to reproduce**: python object_detection/builders/model_builder_test.py from research folder.

### Describe the problem
After going through the the object detection installation steps (in https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) the test (the final step of `python object_detection/builders/model_builder_test.py`) is failing.

### Source code / logs
```
..........E......E....
======================================================================
ERROR: test_create_ssd_inception_v2_model_from_config (__main__.ModelBuilderTest)
test_create_ssd_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "object_detection/builders/model_builder_test.py", line 158, in test_create_ssd_inception_v2_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
ParseError: 65:9 : Message type "object_detection.protos.Ssd" has no field named "min_num_negative_samples".

======================================================================
ERROR: test_create_ssd_mobilenet_v2_keras_model_from_config (__main__.ModelBuilderTest)
test_create_ssd_mobilenet_v2_keras_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "object_detection/builders/model_builder_test.py", line 792, in test_create_ssd_mobilenet_v2_keras_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 87, in create_model
    return model_builder.build(model_config, is_training=True)
  File "/home/sarkar/exp/tensorflow_sources/models/research/object_detection/builders/model_builder.py", line 117, in build
    add_background_class)
  File "/home/sarkar/exp/tensorflow_sources/models/research/object_detection/builders/model_builder.py", line 213, in _build_ssd_model
    is_training=is_training)
  File "/home/sarkar/exp/tensorflow_sources/models/research/object_detection/builders/model_builder.py", line 151, in _build_ssd_feature_extractor
    raise ValueError('Unknown ssd feature_extractor: {}'.format(feature_type))
ValueError: Unknown ssd feature_extractor: ssd_mobilenet_v2_keras

----------------------------------------------------------------------
Ran 22 tests in 0.138s

FAILED (errors=2)
```

Further, if I ignore this, the training steps fails with the following error in almost all the cases:
```
OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key BoxPredictor_0/BoxEncodingPredictor/biases not found in checkpoint
```

**Comment by NorwayLobster** [comment] 2018-12-18 15:09
hi bro, i got the same error. do you solve it

**Comment by NorwayLobster** [comment] 2018-12-18 15:10
Not found: Key BoxPredictor_0/BoxEncodingPredictor/biases not found in checkpoint

**Comment by Vprashant** [comment] 2019-01-08 12:13
same issue

**Comment by tensorflowbutler** [comment] 2020-01-29 22:59
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-12 04:30
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-12 04:30 UTC
