### ISSUE TITLE
Object Detection: Order of methods in non_max_supression

### ISSUE THREAD

**Issue by jayendra13** [tensorflow/models#7835] opened 2019-11-20 08:02 UTC
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Stretch
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:  1.14.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 10

The order of applying the non_max suppression and pruning the box-list with clip-window seems to be wrong. While applying the nms after the first stage The order is like this
1. Apply NMS from line [720](https://github.com/tensorflow/models/blob/5c15ce77868cad6c09b95423c10222ff2ca7fad7/research/object_detection/core/post_processing.py#L720) to [713](https://github.com/tensorflow/models/blob/5c15ce77868cad6c09b95423c10222ff2ca7fad7/research/object_detection/core/post_processing.py#L813)
2. pruning the box-list with the clip window

This will actually reduce the number of ROIs being passed to stage-2 from stage-1

Shouldn't the order be inverted? i.e.
1. Prune the box-list with the clip-window
2. Apply NMS

**Comment by tensorflowbutler** [comment] 2019-11-21 00:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
GPU model and memory
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-19 08:18
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-19 08:18 UTC
Labels: models:research, stat:awaiting response
