### ISSUE TITLE
The allow_growth does not seem to work (?)

### ISSUE THREAD

**Issue by egavves** [tensorflow/models#1124] opened 2017-03-07 21:36 UTC
## Please let us know which model this issue is about (specify the top-level directory)

Hi,

I am trying to fine tune the flowers dataset using the instructions in https://github.com/tensorflow/models/tree/master/slim

I have two questions.

1) As the GPU memory is not big enough, I want to try to allow for GPU growth, so that the process does not crash. The code I am using is the one below, however, it doesn't make any difference at all. Is allow_growth and/or per_process_gpu_memory_fraction really supported for TF slim or not?

2) Is all the GPU needed for the allocation of the intermediate actionation variables? Because the inception model is about 100 Mb, my total GPU memory (after killing also the X server) is 1.8 Gb, so it feels somewhat weird that the model needs in the end 18X more GPU RAM than the inception model size.

Well, anyways, any help would be really nice.

```    session_config = tf.ConfigProto(allow_soft_placement=True)
    session_config.gpu_options.allow_growth = True
    session_config.gpu_options.allocator_type = 'BFC'
    session_config.gpu_options.per_process_gpu_memory_fraction = 0.4
    # gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=args.gpu_memory_fraction)
    # Run the training:
    final_loss = slim.learning.train(
        train_op,
        logdir=train_dir,
        init_fn=get_init_fn(),
        number_of_steps=2000,
        session_config=session_config)
```

**Comment by prb12** [comment] 2017-03-07 22:26
Closing as a duplicate of https://github.com/tensorflow/tensorflow/issues/6111

**Closed by prb12** 2017-03-07 22:26 UTC

**Comment by egavves** [comment] 2017-03-08 08:12
Sorry for the duplicate, I hadn't realized that this is (potentially) a Tensorflow and not just TF Slim, issue.
