### ISSUE TITLE
object detection: multi-gpu evaluation like multi-gpu training

### ISSUE THREAD

**Issue by MrWanter** [tensorflow/models#4390] opened 2018-05-28 13:42 UTC
Would it be more convenient to add multi-gpu evaluation like the num_clones added in multi-gpu training?

**Comment by tensorflowbutler** [comment] 2018-05-29 00:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MrWanter** [comment] 2018-06-01 02:10
What is the top-level directory of the model you are using: ` faster rcnn inception-resnet v2`
Have I written custom code : `no `
OS Platform and Distribution: `ubuntu 16.04`
TensorFlow installed from: `pip`
TensorFlow version `1.8.0`
Bazel version `N/A`
CUDA/cuDNN version `cuda9.0/cudnn7.0`
GPU model and memory `titanx`
Exact command to reproduce 'N/A'

**Comment by pkulzc** [comment] 2018-09-14 01:36
Closing this issue since it is obsolete after our Jun 13th release.

**Closed by pkulzc** 2018-09-14 01:36 UTC
