### ISSUE TITLE
resampy install on raspberry pi3 failed

### ISSUE THREAD

**Issue by rtroulak** [tensorflow/models#7930] opened 2019-12-09 11:56 UTC
I try to set up yamnet on my raspberry pi3 and when i try to install resampy
`pip3 install resampy`
or
`pip install resampy`

i got this error about llvmlite. 

> Building wheels for collected packages: llvmlite
>   Running setup.py bdist_wheel for llvmlite ... error
>   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8i3ku6nc/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-v1cqqyua --python-tag cp37:
>   running bdist_wheel
>   /usr/bin/python3 /tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py
>   LLVM version... Traceback (most recent call last):
>     File "/tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py", line 105, in main_posix
>       out = subprocess.check_output([llvm_config, '--version'])
>     File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
>       **kwargs).stdout
>     File "/usr/lib/python3.7/subprocess.py", line 472, in run
>       with Popen(*popenargs, **kwargs) as process:
>     File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
>       restore_signals, start_new_session)
>     File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
>       raise child_exception_type(errno_num, err_msg, err_filename)
>   FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
>   
>   During handling of the above exception, another exception occurred:
>   
>   Traceback (most recent call last):
>     File "/tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py", line 168, in <module>
>       main()
>     File "/tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py", line 158, in main
>       main_posix('linux', '.so')
>     File "/tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py", line 108, in main_posix
>       "to the path for llvm-config" % (llvm_config,))
>   RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
>   error: command '/usr/bin/python3' failed with exit status 1
>   
>   ----------------------------------------
>   Failed building wheel for llvmlite
>   Running setup.py clean for llvmlite
> Failed to build llvmlite
> Installing collected packages: llvmlite, numba, resampy
>   Running setup.py install for llvmlite ... error
>     Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8i3ku6nc/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lq1gt94p/install-record.txt --single-version-externally-managed --compile --user --prefix=:
>     running install
>     running build
>     got version from file /tmp/pip-install-8i3ku6nc/llvmlite/llvmlite/_version.py {'version': '0.30.0', 'full': '3cad106e2f727bc400f1b426ce306b1e30e34b72'}
>     running build_ext
>     /usr/bin/python3 /tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py
>     LLVM version... Traceback (most recent call last):
>       File "/tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py", line 105, in main_posix
>         out = subprocess.check_output([llvm_config, '--version'])
>       File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
>         **kwargs).stdout
>       File "/usr/lib/python3.7/subprocess.py", line 472, in run
>         with Popen(*popenargs, **kwargs) as process:
>       File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
>         restore_signals, start_new_session)
>       File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
>         raise child_exception_type(errno_num, err_msg, err_filename)
>     FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py", line 168, in <module>
>         main()
>       File "/tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py", line 158, in main
>         main_posix('linux', '.so')
>       File "/tmp/pip-install-8i3ku6nc/llvmlite/ffi/build.py", line 108, in main_posix
>         "to the path for llvm-config" % (llvm_config,))
>     RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
>     error: command '/usr/bin/python3' failed with exit status 1
>     
>     ----------------------------------------
> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8i3ku6nc/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lq1gt94p/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-8i3ku6nc/llvmlite/

Any idea?

**Comment by tensorflowbutler** [comment] 2019-12-10 00:09
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by toqana** [comment] 2020-03-25 22:55
The instruction from https://qengineering.eu/install-tensorflow-2.1.0-on-raspberry-pi-4.html were followed for a Raspberry Pi 3 Model B+ with Raspbian Buster and Python 3.7.3.

The RPi3 yamnet folder contents were copied from a verified installation of https://github.com/tensorflow/models.git on an Ubuntu 18.04 i7 based workstation. In this case, the yamnet python files were not architecture dependent (i.e. amd64 vs. armhf).

cd ~
mkdir yamnet # copy files into folder
cd ~/yamnet

# start of https://qengineering.eu/install-tensorflow-2.1.0-on-raspberry-pi-4.html

# get a fresh start
sudo apt update
sudo apt full-upgrade

# remove old versions, if not placed in a virtual environment (let pip search for them)

pip uninstall tensorflow
pip3 uninstall tensorflow
sudo pip uninstall tensorflow
sudo pip3 uninstall tensorflow

# note: prior version of tensorflow was not found

# install the dependencies (if not already onboard)

sudo apt install gfortran
sudo apt install libhdf5-dev libc-ares-dev libeigen3-dev
sudo apt install libatlas-base-dev libopenblas-dev libblas-dev
sudo apt install liblapack-dev cython
sudo pip3 install pybind11
sudo pip3 install h5py

# download the wheel

wget https://github.com/Qengineering/Tensorflow-Raspberry-Pi/raw/master/tensorflow-2.1.0-cp37-cp37m-linux_armv7l.whl

# install TensorFlow

sudo -H pip3 install tensorflow-2.1.0-cp37-cp37m-linux_armv7l.whl

# end of https://qengineering.eu/install-tensorflow-2.1.0-on-raspberry-pi-4.html

# install llvm components - the two packages were best guesses from "sudo aptitude search llvm"

sudo apt install python3-llvmlite
sudo apt install llvm-dev

# tensorflow was installed above, so install remaining yamnet components

sudo pip3 install numpy resampy soundfile matplotlib

python3 yamnet_test.py
...
Ran 4 tests in 33.203s
...

**Comment by plakal** [comment] 2020-04-27 19:36
Thanks @toqana for apparently resolving @rtroulak's issue. I'm closing since this is not really an audioset model issue. If you're still having problems with resampy, perhaps file an issue in the resampy project https://github.com/bmcfee/resampy

**Comment by plakal** [comment] 2020-04-27 19:37
@dpwe as FYI

**Closed by plakal** 2020-04-27 19:36 UTC
Labels: models:research, stat:awaiting response, type:build/install
