### ISSUE TITLE
Fatal error appears in the middle of Index feature and box extraction

### ISSUE THREAD

**Issue by jiwi90** [tensorflow/models#9572] opened 2020-12-20 03:21 UTC
Dear all,

I am using the DELF's trained model with new Korean landmark images. The extract_index_boxes_and_features.py  code is running fine. The problem is that it crashes in the middle of the extraction with the following error:

![image](https://user-images.githubusercontent.com/42596420/102704348-a4703000-42bd-11eb-9511-2b54f71b26ab.png)

After having searched in google I could think of the following possible reasons:
1) Lack of memory
2) Batch size may have to be smaller or the batches are not being allocated properly to GPUs

Any help with the above issue would be highly appreciated! 👍 
Thank you.

**Comment by andrefaraujo** [comment] 2021-09-28 15:11
Duplicate of #9579

**Closed by andrefaraujo** 2021-09-28 15:11 UTC
Labels: type:support, models:research
