### ISSUE TITLE
 oid_bbox_trainable_label_map.pbtxt

### ISSUE THREAD

**Issue by username123062** [tensorflow/models#7989] opened 2019-12-27 15:57 UTC
coco dataset has only 80 object classes, but in the 'oid_bbox_trainable_label_map.pbtxt', it has 545 object classes. So how do you get the 545 object classes? Thanks.

**Comment by tensorflowbutler** [comment] 2019-12-28 12:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rkotcherr** [comment] 2020-01-20 16:09
OID suggests these are the labels for Open Image Dataset...

**Comment by ravikyram** [comment] 2020-06-02 11:01
@username123062 

It is difficult to understand your issues only based on the information you provided.Please, let us know which pretrained model you are using and share related code .Thanks!

**Comment by ravikyram** [comment] 2020-07-13 13:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-07-13 13:16 UTC
Labels: models:research, stat:awaiting response, type:support
