### ISSUE TITLE
Getting error "AttributeError: 'module' object has no attribute 'distribute'" when running resnet model in official folder 

### ISSUE THREAD

**Issue by gsrivas4** [tensorflow/models#4667] opened 2018-07-02 01:40 UTC
------------------------

### System information
- **What is the top-level directory of the model you are using**: ./models/official/resnet/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No custom code 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04.5 
- **TensorFlow installed from (source or binary)**: From source 
- **TensorFlow version (use command below)**: 1.5.1
- **Bazel version (if compiling from source)**: 0.11.0
- **CUDA/cuDNN version**: 9.0.176/ 7.1.03
- **GPU model and memory**: Titan Xp and 12187MiB
- **Exact command to reproduce**: python cifar10_main.py

I am trying to train resent model present in model/official/ folder as per instructions given at https://github.com/gsrivas4/models/tree/master/official/resnet. I ran the requirements given at https://github.com/gsrivas4/models/tree/master/official#running-the-models and added the location to environment variable PYTHONPATH. I am running below script: 
 python cifar10_main.py

I get below error message with additional log messages 

/home/gsrivas4/envtf15/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-07-01 18:32:54.213602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 11.90GiB freeMemory: 9.75GiB
2018-07-01 18:32:54.213629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:03:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "cifar10_main.py", line 259, in <module>
    absl_app.run(main)
  File "/home/gsrivas4/envtf15/local/lib/python2.7/site-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/home/gsrivas4/envtf15/local/lib/python2.7/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "cifar10_main.py", line 253, in main
    run_cifar(flags.FLAGS)
  File "cifar10_main.py", line 248, in run_cifar
    shape=[_HEIGHT, _WIDTH, _NUM_CHANNELS])
  File "/home/gsrivas4/dnn/asimlor_prec/models/official/resnet/resnet_run_loop.py", line 357, in resnet_main
    flags_core.get_num_gpus(flags_obj), flags_obj.all_reduce_alg)
  File "/home/gsrivas4/dnn/asimlor_prec/models/official/utils/misc/distribution_utils.py", line 39, in get_distribution_strategy
    return tf.contrib.distribute.OneDeviceStrategy("device:GPU:0")
  File "/home/gsrivas4/envtf15/local/lib/python2.7/site-packages/tensorflow/python/util/lazy_loader.py", line 54, in __getattr__
    return getattr(module, item)
AttributeError: 'module' object has no attribute 'distribute'

As I have done everything as per the readme for training the model, I do not know why I should be getting this error?

**Comment by latifisalar** [comment] 2018-07-03 21:37
I also get the same error while training Transformer model.
System information:
- **What is the top-level directory of the model you are using:** ./models/official/transformer/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Ubuntu 16.04
- **TensorFlow installed from (source or binary):** Binary
- **TensorFlow version (use command below):** 1.5.0
- **CUDA/cuDNN version:** 9.0.176/ 7.1.4
- **Exact command to reproduce:** Official Instructions

Thanks

**Comment by hikoy** [comment] 2018-07-13 11:57
I also get exactly the same error while training resnet model.

So, when I changed the version of Python from 2 to 3, it worked.


System information:

- **What is the top-level directory of the model you are using**: ./models/official/resnet/
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary(docker image tensorflow/tensorflow:latest-gpu-py3)
- **TensorFlow version (use command below)**: 1.8.0
- **Exact command to reproduce**: Official Instructions

**Comment by alapha23** [comment] 2018-08-13 10:37
I also get exactly the same error while training resnet model.

I changed the version of Python from 2 to 3, it did not work.

System information:

*   What is the top-level directory of the model you are using: ./models/official/resnet/
*   Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
*   OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
*   TensorFlow installed from (source or binary): source
*   TensorFlow version (use command below): 1.2.0
*   Exact command to reproduce: Official Instructions

**Comment by alapha23** [comment] 2018-08-13 10:56
@nealwu

**Comment by haikuoyao** [comment] 2018-08-15 03:13
Got the same error. 
Anyone fix it?

**Comment by zbchern** [comment] 2018-08-29 07:03
I got exactly the same problem when I was using tensorflow 1.4.1. I upgraded it to the latest version and the problem disappeared.

**Comment by gsrivas4** [comment] 2018-08-31 16:19
@zbchern If you could please elaborate on the settings you are using. Is it Tensorflow 1.10? Also if you could mention other settings, such as what is OS, did you built TF from source etc, CUDA/cuDNN version? This might be helpful to others.

**Comment by ymodak** [comment] 2018-12-28 22:14
Closing this issue since upgrading to latest version of TensorFlow solves the problem. Thanks!

**Closed by ymodak** 2018-12-28 22:14 UTC

**Comment by raj-shah14** [comment] 2019-02-22 21:31
`strategy = tf.distribute.MirroredStrategy()
AttributeError: 'module' object has no attribute 'distribute' `
Updated tensorflow-gpu to 1.12.0. Used Python 3 but still the issue was not solved. Ubuntu 18.04
