### ISSUE TITLE
 Context feature 'id' is required but could not be found

### ISSUE THREAD

**Issue by xiaoluobu** [tensorflow/models#8648] opened 2020-06-08 19:22 UTC
Hi,

I try to use the YouTube-8M Starter Code to train the google audioset. But I met the problem.

python3 train.py --frame_features --model=FrameLevelLogisticModel \
--feature_names='rgb,audio' --feature_sizes='1024,128' \
--train_data_pattern=/home/yt8m/audioset_v1_embeddings/bal_train/*.tfrecord \
--train_dir=/home/yt8m/train_model \
--start_new_model

` File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 706, in main
    FLAGS.export_model_steps).run(start_new_model=FLAGS.start_new_model)
  File "train.py", line 520, in run
    task_as_string(self.task))
  File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/supervisor.py", line 1014, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/supervisor.py", line 839, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1287, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Context feature 'id' is required but could not be found.
         [[{{node train_input/ParseSingleSequenceExample/ParseSingleSequenceExample}}]]`

I would really appreciate your help.
Best wishes

**Comment by dpwe** [comment] 2020-06-09 12:14
This appears to be a duplicate of #5286.

The YouTube-8M code was changed subsequent to the generation of the AudioSet features.  I believe you can make it work again by editing the YouTube-8M code to use 'video_id' instead of 'id', as described in the earlier issue.

**Closed by dpwe** 2020-06-09 12:14 UTC
Labels: models:research, type:bug

**Comment by xiaoluobu** [comment] 2020-06-10 01:06
Hi dpwe,

Your answer is right, thank you so much.
