### ISSUE TITLE
Pre-trained FPN based object detection model?

### ISSUE THREAD

**Issue by FightForCS** [tensorflow/models#3147] opened 2018-01-12 03:44 UTC
In the object detection model zoo, I have not found a pre-trained model using FPN as the feature extractor, is there someone working on this?

**Comment by cy89** [comment] 2018-01-12 23:54
@jch1 @tombstone do you have any guidance?

**Comment by tensorflowbutler** [comment] 2020-01-29 23:30
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment] 2020-02-07 09:56
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-02-07 09:56 UTC
Labels: type:feature
