### ISSUE TITLE
Best Model or Technic to Identify Custom People

### ISSUE THREAD

**Issue by dasmehdix** [tensorflow/models#7459] opened 2019-08-16 13:34 UTC
### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Nope
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:pip
- **TensorFlow version (use command below)**:1.14.0
- **CUDA/cuDNN version**:10/7.4
- **GPU model and memory**:Nvidia RTX 2060 6GB

Hi,

I want to identify the people in my home.It can be real time or low FPS.I already used Haar Cascade, SSD_mobilenet_v2, Yolo-v3 etc.

I wonder that which technic is best to identify the custom people face.I will use a IP Camera which will be attached from long distance to the peoples.So I have to find small size of human face.Which technic or model you suggest?

Thanks...

**Comment by tensorflowbutler** [comment] 2019-08-17 12:07
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce

**Comment by ravikyram** [comment] 2020-06-22 13:15
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-06-22 13:15 UTC
Labels: stat:awaiting response, type:support
