### ISSUE TITLE
Invalid ELF Header / no module named cPickle

### ISSUE THREAD

**Issue by Bonkoodle** [tensorflow/models#1402] opened 2017-04-25 11:42 UTC
So I'm trying to run the code from here: 
https://github.com/tensorflow/models/tree/master/slim#installing-latest-version-of-tf-slim 

Running python -c "import tensorflow.contrib.slim as slim; eval = slim.evaluation.evaluate_once"
Gives an Invalid ELF header error.

If I run that part using python3 instead, then it runs fine. But then I get down to running 
$ DATA_DIR=/tmp/data/flowers
$ python download_and_convert_data.py \
    --dataset_name=flowers \
    --dataset_dir="${DATA_DIR}"
And it says “no module named cPickle. From what people say it sounds like cPickle isn’t a module you can even install for python3 since it only works on python (2).
So my options are:
Try to use “import _pickle as cPickle” to run on python3. It currently says “no module named cPickle” when I try to call it though, which doesn’t seem to make sense since it’s _pickle which I’m trying to import not cPickle (then changing its name after). http://stackoverflow.com/questions/37132899/installing-cpickle-with-python-3-5 

Fix the “invalid ELF header” error and run on python (2) instead of python3.

Here are details about my system. [tf_env.txt](https://github.com/tensorflow/models/files/954872/tf_env.txt)

I used this page for installation: https://www.tensorflow.org/install/install_linux
So CUDA® Toolkit 8.0.
cuDNN v5.1
virtualenv install of Tensorflow

Trying to run python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)" 
says "Failed to load the native TensorFlow runtime."
but I can get other simple Tensorflow stuff to work so not sure why that is.

**Comment by girving** [comment] 2017-04-25 15:57
The ELF issue sounds you have a broken version of Python, or installed a version of TensorFlow compiled against the wrong version of Python.  The cPickle issue presumably means slim has not be fixed to work correctly with Python 3.

@sguada Is slim in models being maintained?

**Comment by karmel** [comment] 2018-02-24 18:57
Closing as a duplicate of #726

**Closed by karmel** 2018-02-24 18:57 UTC
Labels: stat:awaiting tensorflower, type:build/install
